// Original short affirmations — written for this app, not quoted from any external source.
// Words wrapped in **double asterisks** get the rough hand-marker highlight in the UI.
export const BUILT_IN_THOUGHTS: string[] = [
  "**Progress** hides inside repetition. Show up again today.",
  "You don't need to feel ready. You just need to **begin**.",
  "Every chapter you revise is a future point on the **exam**.",
  "Small **consistent** effort beats occasional intensity.",
  "The version of you that clears NEET is built today, **one hour at a time**.",
  "Difficult topics feel that way right up until they don't.",
  "You're not behind. You're exactly where your **effort** has taken you — keep adding to it.",
  "**Rest** is part of the plan, not a break from it.",
  "One **focused** hour is worth more than three distracted ones.",
  "Your future self is counting on the version of you sitting here **right now**.",
  "Doubt is just tiredness talking. **Keep going**.",
  "The syllabus doesn't care how you feel about it — but your **discipline** does.",
  "You've already survived every hard day so far. That's a good **track record**.",
  "**Understanding** beats memorizing, but showing up beats both.",
  "Nobody sees the quiet hours. That's exactly why they **matter**.",
  "A slow chapter finished is better than a fast chapter **half-done**.",
  "Comparison steals focus. Your only competition is **yesterday's you**.",
  "The white coat is built from ordinary Tuesdays like **this one**.",
  "You don't have to feel motivated. You just have to **open the book**.",
  "Confusion is the first step before clarity — **stay in the process**.",
  "Every mock test, good or bad, is data. **Use it**, don't fear it.",
  "The goal isn't a perfect day. It's a day that **moves you forward**.",
  "You are allowed to be a beginner at something you'll one day **master**.",
  "Struggling with a topic means you're finally at the edge of your ability — that's where **growth** happens.",
  "Today's revision is tomorrow's **recall**.",
  "**Discipline** is choosing what you want most over what you want now.",
  "You don't need more time. You need one more **focused hour**, right now.",
  "The exam rewards **preparation**, not panic.",
  "Every mistake corrected today is a mark saved **tomorrow**.",
  "Keep your promises to yourself — that's where real **confidence** comes from.",

  // Imported general motivational/science/perseverance quotes (attributions intentionally omitted)
 "**Imagination** is more **important** than knowledge.",
  "Your **work** is going to fill a large part of **your life**, and the only way to be truly satisfied is to do what you believe is great work.",
  "It’s fine to celebrate **success** but it is more **important** to heed the lessons of failure.",
  "**Science** is a way of **thinking** much more than it is a body of knowledge.",
  "Any sufficiently advanced **technology** is indistinguishable from magic.",
  "The **important** thing is not to stop **questioning**. Curiosity has its own reason for existing.",
  "**Success** usually comes to those who are too busy to be looking for it.",
  "If you can’t explain it simply, you don’t understand it well enough.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "The **science** of today is the **technology** of tomorrow.",
  "The good thing about **science** is that it’s true whether or not you **believe** in it.",
  "Code is like humor. When you have to explain it, it’s bad.",
  "**Innovation** distinguishes between a leader and a follower.",
  "Logic will get you from A to B. **Imagination** will take you everywhere.",
  "The human brain has 100 billion neurons, but the network of connections is what matters.",
  "Everybody in this country should learn to program a computer because it teaches you how to think.",
  "First, solve the **problem**. Then, write the code.",
  "Any fool can write code that a computer can understand. **Good programmers** write code that humans can understand.",
  "**Experience** is the name everyone gives to their mistakes.",
  "In **science**, there are no shortcuts to **truth**.",
  "Data is a precious thing and will last longer than the systems themselves.",
  "Programs are meant to be read by humans and only incidentally for computers to execute.",
  "**Technology** is **best** when it brings people together.",
  "**Learning** to write programs stretches **your mind**, and helps you think better.",
  "The **purpose** of computing is **insight**, not numbers.",
  "Mathematics is the language in which God has written the universe.",
  "The advance of **science** depends on the production of new techniques, new tools, and new materials.",
  "**Good code** is its own **best** documentation.",
  "The real **question** is not whether machines think but whether men do.",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
  "Your **best** teacher is your last **mistake**.",
  "**Science** is a beautiful gift to humanity; we should not distort it.",
  "**Innovation** is the key to transforming **dreams** into reality.",
  "The brain is like a muscle. When it is in use we feel very good. **Understanding** is joyous.",
  "**Technology** is the campfire around which we tell our stories.",
  "Don’t just be a consumer of **knowledge**, be a creator.",
  "**Failure** will never overtake me if my **determination** to succeed is strong enough.",
  "**Change** is the law of life. And those who look only to the past or present are certain to miss **the future**.",
  "A person who never made a **mistake** never tried anything new.",
  "**The future** belongs to those who **prepare** for it today.",
  "The power of **imagination** makes us infinite.",
  "Do not wait for leaders; do it alone, person to person.",
  "**Science** and everyday life cannot and should not be separated.",
  "The mind is not a vessel to be filled but a fire to be kindled.",
  "**Vision** without **action** is a daydream. Action without vision is a nightmare.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Keep your face always toward the sunshine and shadows will fall behind you.",
  "Since light travels faster than sound, some people appear bright until you hear them speak.",
  "Life isn’t about getting and having, it’s about giving and being.",
  "Whatever the mind of man can conceive and **believe**, it can achieve.",
  "Strive not to be a **success**, but rather to be of **value**.",
  "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
  "I attribute my **success** to this: I never gave or took any excuse.",
  "You miss 100% of the shots you don’t take.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Every strike brings me closer to the next home run.",
  "Definiteness of **purpose** is the starting point of all achievement.",
  "Life is what happens to you while you’re busy making other plans.",
  "We become what we think about.",
  "Life is 10% what happens to you and 90% of how you react to it.",
  "The most common way people give up their power is by **thinking** they don’t have any.",
  "The mind is everything. What you think you become.",
  "The **best** time to plant a tree was 20 years ago. The second **best** time is now.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Winning isn’t everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Every child is an artist. The **problem** is how to remain an artist once he grows up.",
  "You can never cross the ocean until you have the **courage** to lose sight of the shore.",
  "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "Either you run the day, or the day runs you.",
  "Whether you think you can or you think you can’t, you’re right.",
  "The two most **important** days in **your life** are the day you are born and the day you find out why.",
  "Whatever you can do, or **dream** you can, **begin** it. Boldness has genius, power and magic in it.",
  "The **best** revenge is massive **success**.",
  "People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily.",
  "Life shrinks or expands in proportion to one’s **courage**.",
  "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of **your dreams**. Live the life you have imagined.",
  "Few things can help an individual more than to place **responsibility** on him, and to let him know that you trust him.",
  "Certain things catch your eye, but pursue only those that capture the heart.",
  "**Believe** you can and you’re halfway there.",
  "Everything you’ve ever wanted is on the other side of **fear**.",
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
  "**Start** where you are. Use what you have. Do what you can.",
  "Fall seven times and stand up eight.",
  "When one door of **happiness** closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.",
  "Everything has beauty, but not everyone can see.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "When I let go of what I am, I become what I might be.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "**Happiness** is not something readymade. It comes from your own actions.",
  "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.",
  "If the wind will not serve, take to the oars.",
  "You can’t fall if you don’t climb. But there’s no joy in living your whole life on the ground.",
  "We must **believe** that we are gifted for something, and that this thing, at whatever cost, must be attained.",
  "Too many of us are not living our **dreams** because we are living our fears.",
  "**Challenges** are what make life interesting and overcoming them is what makes life meaningful.",
  "If you want to lift yourself up, lift up someone else.",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
  "You take **your life** in your own hands, and what happens? A terrible thing, no one to blame.",
  "What’s money? A man is a **success** if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
  "I didn’t fail the test. I just found 100 ways to do it wrong.",
  "In order to succeed, your desire for **success** should be greater than your **fear** of failure.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no traffic jams along the extra mile.",
  "It is never too late to be what you might have been.",
  "You become what you **believe**.",
  "I would rather die of passion than of boredom.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
  "**Build** your own **dreams**, or someone else will hire you to build theirs.",
  "The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at.",
  "Education costs money. But then so does ignorance.",
  "I have learned over the years that when one’s mind is made up, this diminishes **fear**.",
  "It does not matter how slowly you go as long as you do not stop.",
  "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "You can’t use up **creativity**. The more you use, the more you have.",
  "**Dream** big and dare to fail.",
  "Our lives **begin** to end the day we become silent about things that matter.",
  "Do what you can, where you are, with what you have.",
  "If you do what you’ve always done, you’ll get what you’ve always gotten.",
  "Dreaming, after all, is a form of planning.",
  "It’s your place in the world; it’s **your life**. Go on and do all you can with it, and make it the life you want to live.",
  "You may be disappointed if you fail, but you are doomed if you don’t try.",
  "Remember no one can make you feel inferior without your consent.",
  "Life is what we make it, always has been, always will be.",
  "The **question** isn’t who is going to let me; it’s who is going to stop me.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "It’s not the years in **your life** that count. It’s the life in your years.",
  "**Change** your thoughts and you **change** your world.",
  "Either write something worth reading or do something worth writing.",
  "Nothing is **impossible**, the word itself says, “I’m **possible**!”",
  "The only way to do **great work** is to love what you do.",
  "If you can **dream** it, you can achieve it.",
  "We can’t help everyone, but everyone can help someone.",
  "**Success** is not final, **failure** is not fatal: It is the courage to continue that counts.",
  "**The future** belongs to those who **believe** in the beauty of their dreams.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "In the middle of every difficulty lies **opportunity**.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "**Success** is not the key to **happiness**. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "Act as if what you do makes a difference. It does.",
  "What we **fear** doing most is usually what we most need to do.",
  "The only **impossible** **journey** is the one you never begin.",
  "You must be the **change** you wish to see in the world.",
  "The **best** way to predict **the future** is to create it.",
  "**Success** is walking from **failure** to failure with no loss of enthusiasm.",
  "The only way to achieve the **impossible** is to **believe** it is possible.",
  "You are never too old to set another **goal** or to **dream** a new dream.",
  "**Believe** in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "**Success** is not how high you have climbed, but how you make a positive difference to the world.",
  "You don’t have to be **great** to **start**, but you have to start to be great.",
  "What we achieve inwardly will **change** outer **reality**.",
  "**Success** is not in what you have, but who you are.",
  "**Success** is not the absence of **failure**; it’s the persistence through failure.",
  "You can’t **build** a reputation on what you are going to do.",
  "**Success** is how high you bounce when you hit bottom.",
  "The **best** way to find yourself is to lose yourself in the service of others.",
  "**Success** is not about the destination, it’s about the **journey**.",
  "**Success** is not just about what you accomplish in **your life**, it’s about what you inspire others to do.",
  "**Success** is not measured by what you accomplish, but by the opposition you have encountered, and the **courage** with which you have maintained the struggle against overwhelming odds.",
  "The greatest pleasure in life is doing what people say you cannot do.",
  "People’s lives don’t end when they die, it ends when they lose faith.",
  "If you don’t take risks, you can’t **create** a **future**!",
  "When you give up, that’s when the game ends.",
  "Forgetting is like a wound. The wound may heal, but it has already left a scar.",
  "It’s just pathetic to give up on something before you even give it a shot.",
  "If you don’t share someone’s pain, you can never understand them.",
  "Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.",
  "We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today!",
  "Why should I apologize for being a monster? Has anyone ever apologized for turning me into one?",
  "People become **stronger** because they have memories they can’t forget.",
  "I’ll leave tomorrow’s problems to tomorrow’s me.",
  "If you wanna make people **dream**, you’ve gotta **start** by believing in that dream yourself!",
  "Being lonely is more painful then getting hurt.",
  "You can’t sit around envying other people’s worlds. You have to go out and **change** your own.",
  "It’s not the face that makes someone a monster; it’s the **choices** they make with their lives.",
  "Simplicity is the easiest path to **true beauty**.",
  "If you can’t do something, then don’t. **Focus** on what you can.",
  "You can die anytime, but living takes true **courage**.",
  "Every **journey** begins with a single step. We just have to have **patience**.",
  "It doesn’t do any good to pretend you can’t see what’s going on.",
  "Being weak is nothing to be ashamed of… Staying weak is !!",
  "A dropout will beat a genius through **hard work**.",
  "Reject common sense to make the **impossible** **possible**.",
  "If you really want to be **strong**… Stop caring about what your surrounding thinks of you!",
  "**Vision** is not what your eyes see, but an image that your brain comprehends.",
  "Sometimes, people are just mean. Don’t fight mean with mean. Hold your head high.",
  "**Hard work** is worthless for those that don’t **believe** in themselves.",
  "A place where someone still thinks about you is a place you can call home.",
  "Life comes at a cost. Wouldn’t it be arrogant to die before you’ve repaid that debt?",
  "If you just submit yourself to fate, then that’s the end of it.",
  "People, who can’t throw something **important** away, can never **hope** to change anything.",
  "Whatever you do, enjoy it to the fullest. That is the secret of life.",
  "Power comes in response to a need, not a desire. You have to **create** that need.",
  "There are no regrets. If one can be proud of one’s life, one should not wish for another chance.",
  "You can’t always hold on to the things that are **important**. By letting them go we gain something else.",
  "If you don’t like your destiny, don’t accept it. Instead, have the **courage** to **change** it the way you want it to be.",
  "Don’t beg for things. Do it yourself, or else you won’t get anything.",
  "If you can’t find a reason to fight, then you shouldn’t be fighting.",
  "We can’t waste time worrying about the what if’s.",
  "Fools who don’t respect the past are likely to repeat it.",
  "That’s why I can’t make a **change**. Everything I do is so… Half-assed.",
  "Sometimes it’s necessary to do unnecessary things.",
  "An excellent leader must be passionate because it’s their duty to keep everyone moving **forward**.",
  "Protecting someone means giving them a place to belong. Giving them a place where they can be happy.",
  "**Thinking** you’re no-good and worthless is the worst thing you can do",
  "Sometimes I do feel like I’m a **failure**. Like there’s no **hope** for me. But even so, I’m not gonna give up. Ever!",
  "When you lose sight of your path, listen for the destination in your heart.",
  "The moment you think of giving up, think of the reason why you held on so long.",
  "Don’t give up, there’s no shame in falling down! True shame is to not stand up again!",
  "No matter how hard or **impossible** it is, never lose sight of your **goal**.",
  "Life is not a game of luck. If you wanna win, **work** hard.",
  "The world isn’t perfect. But it’s there for us, doing the **best** it can….that’s what makes it so damn beautiful.",
  "**Fear** is not evil. It tells you what your **weakness** is. And once you know your weakness, you can become stronger as well as kinder.",
  "To know sorrow is not terrifying. What is terrifying is to know you can’t go back to **happiness** you could have.",
  "Knowing you’re different is only the beginning. If you accept these differences you’ll be able to get past them and grow even closer.",
  "If nobody cares to accept you and wants you in this world, accept yourself and you will see that you don’t need them and their selfish ideas.",
  "When you hit the point of no return, that’s the moment it truly becomes a **journey**. If you can still turn back, it’s not really a **journey**.",
  "A person grows up when he’s able to overcome hardships. Protection is **important**, but there are some things that a person must learn on his own.",
  "Who decides limits? And based on what? You said you worked hard? Well, maybe you need to **work** a little harder. Is that really the limit of your **strength**? Could you of tomorrow beat you today? Instead of giving in, move forward.",
  "Mistakes are not shackles that halt one from stepping **forward**. Rather, they are that which sustain and grow one’s heart.",
  "Hatred and Sorrow are power. They are yours to control. All you have to do is to turn them into **strength** and use that **strength** to move forward.",
  "It’s not always **possible** to do what we want to do, but it’s **important** to believe in something before you actually do it.",
  "Life and death are like light and shadow. They’re both always there. But people don’t like **thinking** about death, so subconsciously, they always look away from it.",
  "It’s more **important** to master the cards you’re holding than to complain about the ones your opponent was dealt.",
  "If you’re gonna insist on gambling and then complain when you lose, you had better **work** on your game.",
  "Moving on doesn’t mean you forget about things. It just means you have to accept what’s happened and **continue** living.",
  "If you keep on hiding your true feelings, who is going to be happy? If you are sad, you should say it out loud!",
  "Don’t be upset because of what you can’t do. Do what you do **best**, live as carefree and optimistically as you can, because some people aren’t able to do that.",
  "If you **begin** to regret, you’ll dull **your future** decisions and let others make your choices for you. All that’s left for you then is to die. Each decision you make holds meaning only by affecting your next decision.",
  "Everything has a beginning and an end. Life is just a cycle of starts and stops. There are ends we don’t desire, but they’re inevitable, we have to face them. It’s what being human is all about.",
  "Anything can happen. No one ever thinks it will until it does. What will happen, happens. That’s how the world is. The most **important** thing is to not let the tragedy defeat you. To **believe** that you can get through it.",
  "Your enemies can never hurt you the way your loved ones can. It’s the people close to your heart that can give you the most piercing wound. Love is a double-edged sword, it can heal the wound faster or it can sink the blade even deeper.",
  "You need to accept the fact that you’re not the **best** and have all the will to strive to be better than anyone you face.",
  "I too will obtain everything that I desire. Not because someone asked me to do it, but because I know in my heart that I have something worth fighting for.",
  "You can’t win a game by doing nothing. And if someone else wins it for you then you haven’t accomplished anything. Life is the same way.",
  "You do not need outside enemies. For you, the one you have to fight is none other than your own image.",
  "Just like games, no matter how well you have things lined up in **your life**, there’s always something to keep you on your toes.",
  "Do exactly as you like. That is the **true meaning** of pleasure. Pleasure leads to joy and joy leads to **happiness**.",
  "It doesn’t matter how **strong** the opposition is. It doesn’t matter how fearsome the world is. It doesn’t matter how cruel the world is. Fight!",
  "I don’t like the terms ‘good person’ or ‘bad person.’ It is **impossible** to be entirely good to everyone. To some, you are a good person, while to others, you are a bad person.",
  "As long as you **continue** to fight, you are not defeated.",
  "You’re gonna care what other people think and be someone you’re not your whole life. You’re fine as you are, so talk in your own words.",
  "Everyone had to be drunk on something to keep pushing on.",
  "No one knows what the outcome will be, so choose whatever you’ll regret the least.",
  "Do you need a reason to not want to lose?",
  "If they adjust to me, I have to adjust in turn. Whoever stops adjusting won’t be able to **continue** **forward**.",
  "The last ones standing are the victors—only the strongest. If you want to be the last one standing, become **strong**.",
  "Life’s a bore if you don’t **challenge** yourself.",
  "There are some flowers you only see when you take detours.",
  "Being weak means that there is room to grow.",
  "Today might be the chance to grasp the chance to let your **talent** bloom.",
  "If you’re gonna hit it, hit it until it breaks.",
  "**Knowledge** is the fuel. **Curiosity** is the spark. Action is the engine.",
  "I’d rather be uncertain with depth than certain with ignorance.",
  "Don’t watch the clock; do what it does. **Keep going**.",
  "**Reality** doesn’t need belief. It needs **understanding**.",
  "The electric light did not come from the continuous improvement of the candle.",
  "It is not the strongest of the species that survives, nor the most intelligent, but the most adaptable to **change**.",
  "All our **dreams** can come true, if we have the **courage** to pursue them.",
  "The only place where **success** comes before **work** is in the dictionary.",
  "If you don’t like something, **change** it. If you can’t **change** it, change your attitude.",
  "The longer you try to get what’s been taken from you, the more you lose.",
  "If you want to shine like a sun, first burn like a sun.",
  "If you want to live a happy life, tie it to a **goal**, not to people or things.",
  "**Courage** is knowing it might hurt and doing it anyway. Stupidity is the same. That's why life is hard.",
  "You only live once, but if you do it right, once is enough.",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
  "Insanity is doing the same thing, over and over again, but expecting different results.",
  "A human lives three lives. The first ends with the loss of naivety, the second with the loss of innocence and the third with the loss of life itself. It is inevitable that we will go through all three stages.",
  "Don’t be distracted by the what-ifs, should-haves, and if-onlys. The one thing you choose for yourself, that is the **truth** of your universe.",
  "A life that lives without doing anything is the same as a slow death.",
  "I bet even I can make it. If I live and try as hard as everyone else.",
  "It’s better to do something and regret it than to not do anything and regret it.",
  "We evolve, beyond the person that we were a minute before. Little by little, we advance with each turn. That's how a drill works!",
  "God gave us eyes at the front of our heads so we can look **forward** to **the future**.",
  "I don't want **fear** for a **future** that may not even come to stop me from acting today.",
  "**Experience** is something you gain right after you needed it.",
  "No matter how much you regret it, the past won't **change**. But **the future** is still in your hands.",
  "No one knows what **the future** holds. That’s why its **potential** is infinite.",
  "Everything that happens has a meaning. The preparatory measures are complete. Everything else depends on you.",
  "It's easy to give up. But it doesn't suit you.",
  "Accept that because we were born with nothing, we can become anything!",
  "What matters isn't how you **start** or what happens in the middle. It's how it ends",
  "A **truth** that's told with bad intent beats all the lies you can invent.",
  "The most effective way to do it, is to do it.",
  "If there is no struggle, there is no **progress**.",
  "Permit yourself to **change** **your mind** when something is no longer working for you.",
  "Tradition is nothing but ancestral peer pressure.",
  "Sometimes good things fall apart so better things could fall together.",
  "**Change** brings **opportunity**.",
  "Just because something doesn’t do what you planned it to do doesn’t mean it’s useless.",
  "The **best** way to predict **the future** is to invent it.",
  "The most dangerous phrase in the language is, we’ve always done it this way.",
  "That brain of mine is something more than merely mortal, as time will show.",
  "Not everything that can be counted counts, and not everything that counts can be counted.",
  "**Science** is a way of trying not to fool yourself.",
  "In mathematics you don’t understand things, you just get used to them.",
  "Pure mathematics is, in its way, the poetry of logical ideas.",
  "All of humanity’s problems stem from man’s inability to sit quietly alone.",
  "**Technology** is a useful servant but a dangerous master.",
  "Hardships often **prepare** ordinary people for an extraordinary destiny.",
  "The **great** myth of our times is that **technology** is communication.",
  "Man is a slow, sloppy, and brilliant thinker; computers are fast, accurate, and stupid.",
  "Quality is not an act, it is a **habit**.",
  "Everything is theoretically **impossible**, until it is done.",
  "Aim for the moon. If you miss, you may hit a star.",
  "**Great** things are done by a series of small things brought together.",
  "We are stuck with **technology** when what we really want is just stuff that works.",
  "The **question** of whether machines can think is about as relevant as the **question** of whether submarines can swim.",
  "Don't be pushed around by the fears in **your mind**. Be led by the **dreams** in your heart.",
  "Opportunities don't happen. You **create** them.",
  "Modern **technology** has made the world a small neighborhood.",
  "To be the **best**, you must be able to handle the worst.",
  "Small deeds done are better than **great** deeds planned.",
  "Every once in a while, a new **technology**, an old **problem**, and a big idea turn into an innovation.",
  "The man who has **confidence** in himself gains the **confidence** of others.",
  "The **technology** you use impresses no one. The **experience** you create with it is everything.",
  "Setting **goals** is the first step in turning the invisible into the visible.",
  "Doubt kills more **dreams** than **failure** ever will.",
  "**Action** is the foundational key to all **success**.",
  "What new **technology** does is **create** new opportunities to do a job that customers want done.",
  "The Web as I envisaged it, we have not seen it yet. **The future** is still so much bigger than the past.",
  "**Perseverance** is not a long race; it is many short races one after the other.",
  "**Discipline** is the bridge between **goals** and accomplishment.",
  "Artificial intelligence is growing up fast, as are robots whose facial expressions can elicit empathy.",
  "**Strength** does not come from winning. Your struggles develop your strengths.",
  "Someday is not a day of the week.",
  "One machine can do the **work** of fifty ordinary men. No machine can do the **work** of one extraordinary man.",
  "If you want to fly, give up everything that weighs you down.",
  "**Technology** should be designed so that it requires the least amount of our attention **possible**.",
  "Machines are worshiped because they are beautiful and valued because they confer power.",
  "Don't stop when you're tired. Stop when you're done.",
  "If it keeps up, man will atrophy all his limbs but the push-button finger.",
  "It's not whether you get knocked down, it's whether you get up.",
  "To err is human, but to really foul things up you need a computer.",
  "Don't let yesterday take up too much of today.",
  "Concentrate all your thoughts upon the **work** at hand. The sun's rays do not burn until brought to a **focus**.",
  "**Technology** like art is a soaring exercise of the human **imagination**.",
  "Our technological powers increase, but the side effects and **potential** hazards also escalate.",
  "The machine does not isolate man from the **great** problems of nature but plunges him more deeply into them.",
  "The **goal** is to turn data into information, and information into **insight**.",
  "The **great** engine of content is not **technology**, but stories.",
  "Motivation is what gets you started. **Habit** is what keeps you going.",
  "We can **build** a much more hopeful world if we use **technology** to empower people.",
  "The art of **challenges** is to stay focused on the **solution**.",
  "The production of too many useful things results in too many useless people.",
  "**Technology** is the knack of so arranging the world that we don't have to **experience** it.",
  "The will to win, the desire to succeed, the urge to reach your full **potential**... these are the keys that will unlock the door to personal excellence.",
  "Digital design is like painting, except the paint never dries.",
  "I find that the harder I **work**, the more luck I seem to have.",
  "The move from analog to digital is the biggest **change** since the invention of the printing press.",
  "The real danger is not that computers will **begin** to think like men, but that men will **begin** to think like computers.",
  "Our new digital world will be about 'we' instead of 'me'.",
  "The simple process of focusing on a **goal** is a powerful **technology**.",
  "A computer once beat me at chess, but it was no match for me at kick boxing.",
  "**Success** is most often achieved by those who don't know that **failure** is inevitable.",
  "Technological **progress** has merely provided us with more efficient means for going backwards.",
  "He who has a why to live can bear almost any how.",
  "If you want to achieve greatness stop asking for permission.",
  "The factory of **the future** will have only two employees, a man and a dog.",
];

/** Days since the Unix epoch for a YYYY-MM-DD key, used as a stable daily rotation index. */
function dayNumber(dateKey: string): number {
  return Math.floor(new Date(`${dateKey}T00:00:00Z`).getTime() / 86_400_000);
}

/** Deterministic "thought of the day" — same for everyone on the same date, shifts as custom thoughts are added. */
export function getThoughtOfTheDay(dateKey: string, customThoughts: string[]): string {
  const pool = [...BUILT_IN_THOUGHTS, ...customThoughts];
  if (pool.length === 0) return "Add your first thought below.";
  const idx = ((dayNumber(dateKey) % pool.length) + pool.length) % pool.length;
  return pool[idx];
}

/** Pick a different random thought from the pool, for the manual "shuffle" action. */
export function getRandomThought(customThoughts: string[], exclude?: string): string {
  const pool = [...BUILT_IN_THOUGHTS, ...customThoughts];
  if (pool.length === 0) return "Add your first thought below.";
  if (pool.length === 1) return pool[0];
  let pick = pool[Math.floor(Math.random() * pool.length)];
  let guard = 0;
  while (pick === exclude && guard < 10) {
    pick = pool[Math.floor(Math.random() * pool.length)];
    guard++;
  }
  return pick;
}
