// Original short affirmations — written for this app, not quoted from any external source.
// Words wrapped in **double asterisks** get the rough hand-marker highlight in the UI.
export const BUILT_IN_THOUGHTS: string[] = [
  "**Progress** hides inside repetition. Show up again today.",
  "You don't need to feel ready. You just need to **begin**.",
  "Every chapter you revise is a future point on the **exam**.",
  "Small **consistent** effort beats occasional intensity.",
  "The version of you that clears NEET is built today, **one hour at a time**.",
  "Difficult topics feel that way right up until they don't.",
  "You're not behind. You're exactly where your **effort** has taken you — keep adding to it.",
  "**Rest** is part of the plan, not a break from it.",
  "One **focused** hour is worth more than three distracted ones.",
  "Your future self is counting on the version of you sitting here **right now**.",
  "Doubt is just tiredness talking. **Keep going**.",
  "The syllabus doesn't care how you feel about it — but your **discipline** does.",
  "You've already survived every hard day so far. That's a good **track record**.",
  "**Understanding** beats memorizing, but showing up beats both.",
  "Nobody sees the quiet hours. That's exactly why they **matter**.",
  "A slow chapter finished is better than a fast chapter **half-done**.",
  "Comparison steals focus. Your only competition is **yesterday's you**.",
  "The white coat is built from ordinary Tuesdays like **this one**.",
  "You don't have to feel motivated. You just have to **open the book**.",
  "Confusion is the first step before clarity — **stay in the process**.",
  "Every mock test, good or bad, is data. **Use it**, don't fear it.",
  "The goal isn't a perfect day. It's a day that **moves you forward**.",
  "You are allowed to be a beginner at something you'll one day **master**.",
  "Struggling with a topic means you're finally at the edge of your ability — that's where **growth** happens.",
  "Today's revision is tomorrow's **recall**.",
  "**Discipline** is choosing what you want most over what you want now.",
  "You don't need more time. You need one more **focused hour**, right now.",
  "The exam rewards **preparation**, not panic.",
  "Every mistake corrected today is a mark saved **tomorrow**.",
  "Keep your promises to yourself — that's where real **confidence** comes from.",

  // Imported general motivational/science/perseverance quotes (attributions intentionally omitted)
 "It’s fine to celebrate **success** but it is more **important** to heed the lessons of failure.",
  "**Success** usually comes to those who are too busy to be looking for it.",
  "The human brain has 100 billion neurons, but the network of connections is what matters.",
  "The **purpose** of computing is **insight**, not numbers.",
  "**Innovation** is the key to transforming **dreams** into reality.",
  "**Failure** will never overtake me if my **determination** to succeed is strong enough.",
  "**Change** is the law of life. And those who look only to the past or present are certain to miss **the future**.",
  "**The future** belongs to those who **prepare** for it today.",
  "**Vision** without **action** is a daydream. Action without vision is a nightmare.",
  "Whatever the mind of man can conceive and **believe**, it can achieve.",
  "Strive not to be a **success**, but rather to be of **value**.",
  "I attribute my **success** to this: I never gave or took any excuse.",
  "The most difficult thing is the **decision to act**, the rest is **merely tenacity.**",
  "The most common way people give up their power is by **thinking** they don’t have any.",
  "Winning isn’t everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "You can never cross the ocean until you have the **courage** to lose sight of the shore.",
  "I’ve learned that people will forget what you said, people will forget what you did, but **people will never forget how you made them feel.**",
  "Whatever you can do, or **dream** you can, **begin** it. Boldness has genius, power and magic in it.",
  "Life shrinks or expands in proportion to one’s **courage**.",
  "Go confidently in the direction of **your dreams**. Live the life you have imagined.",
  "Few things can help an individual more than to place **responsibility** on him, and to let him know that you trust him.",
  "**Believe** you can and you’re halfway there.",
  "Everything you’ve ever wanted is on the other side of **fear**.",
  "Fall seven times and stand up eight.",
  "If the wind will not serve, take to the oars.",
  "We must **believe** that we are gifted for something, and that this thing, at whatever cost, must be attained.",
  "Too many of us are not living our **dreams** because we are living our fears.",
  "**Challenges** are what make life interesting and overcoming them is what makes life meaningful.",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
  "In order to succeed, your desire for **success** should be greater than your **fear** of failure.",
  "You become what you **believe**.",
  "**Build** your own **dreams**, or someone else will hire you to build theirs.",
  "I have learned over the years that when one’s mind is made up, this diminishes **fear**.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "**Dream** big and dare to fail.",
  "Our lives **begin** to end the day we become silent about things that matter.",
  "Do what you can, where you are, with what you have.",
  "Dreaming, after all, is a form of planning.",
  "You may be disappointed if you fail, but you are doomed if you don’t try.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "**Change** your thoughts and you **change** your world.",
  "Nothing is **impossible**, the word itself says, “I’m **possible**!”",
  "If you can **dream** it, you can achieve it.",
  "**Success** is not final, **failure** is not fatal: It is the courage to continue that counts.",
  "In the middle of every difficulty lies **opportunity**.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "What we **fear** doing most is usually what we most need to do.",
  "The only **impossible** **journey** is the one you never begin.",
  "You must be the **change** you wish to see in the world.",
  "The **best** way to predict **the future** is to create it.",
  "**Success** is walking from **failure** to failure with no loss of enthusiasm.",
  "The only way to achieve the **impossible** is to **believe** it is possible.",
  "You are never too old to set another **goal** or to **dream** a new dream.",
  "**Believe** in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "**Success** is not how high you have climbed, but how you make a positive difference to the world.",
  "What we achieve inwardly will **change** outer **reality**.",
  "**Success** is not in what you have, but who you are.",
  "**Success** is not the absence of **failure**; it’s the persistence through failure.",
  "**Success** is how high you bounce when you hit bottom.",
  "**Success** is not about the destination, it’s about the **journey**.",
  "**Success** is not just about what you accomplish in **your life**, it’s about what you inspire others to do.",
  "**Success** is not measured by what you accomplish, but by the opposition you have encountered, and the **courage** with which you have maintained the struggle against overwhelming odds.",
  "If you don’t take risks, you can’t **create** a **future**!",
  "When you give up, that’s when the game ends.",
  "It’s just pathetic to give up on something before you even give it a shot.",
  "People become **stronger** because they have memories they can’t forget.",
  "You can’t sit around envying other people’s worlds. You have to go out and **change** your own.",
  "If you can’t do something, then don’t. **Focus** on what you can.",
  "Every **journey** begins with a single step. We just have to have **patience**.",
  "A dropout will beat a genius through **hard work**.",
  "Reject common sense to make the **impossible** **possible**.",
  "**Vision** is not what your eyes see, but an image that your brain comprehends.",
  "Sometimes, people are just mean. Don’t fight mean with mean. Hold your head high.",
  "**Hard work** is worthless for those that don’t **believe** in themselves.",
  "People, who can’t throw something **important** away, can never **hope** to change anything.",
  "Power comes in response to a need, not a desire. You have to **create** that need.",
  "If you don’t like your destiny, don’t accept it. Instead, have the **courage** to **change** it the way you want it to be.",
  "If you can’t find a reason to fight, then you shouldn’t be fighting.",
  "That’s why I can’t make a **change**. Everything I do is so… Half-assed.",
  "An excellent leader must be passionate because it’s their duty to keep everyone moving **forward**.",
  "Sometimes I do feel like I’m a **failure**. Like there’s no **hope** for me. But even so, I’m not gonna give up. Ever!",
  "Don’t give up, there’s no shame in falling down! True shame is to not stand up again!",
  "No matter how hard or **impossible** it is, never lose sight of your **goal**.",
  "Life is not a game of luck. If you wanna win, **work** hard.",
  "**Fear** is not evil. It tells you what your **weakness** is. And once you know your weakness, you can become stronger as well as kinder.",
  "Knowing you’re different is only the beginning. If you accept these differences you’ll be able to get past them and grow even closer.",
  "A person grows up when he’s able to overcome hardships. Protection is **important**, but there are some things that a person must learn on his own.",
  "Who decides limits? And based on what? You said you worked hard? Well, maybe you need to **work** a little harder. Is that really the limit of your **strength**? Could you of tomorrow beat you today? Instead of giving in, move forward.",
  "It’s not always **possible** to do what we want to do, but it’s **important** to believe in something before you actually do it.",
  "Anything can happen. No one ever thinks it will until it does. What will happen, happens. That’s how the world is. The most **important** thing is to not let the tragedy defeat you. To **believe** that you can get through it.",
  "You need to accept the fact that you’re not the **best** and have all the will to strive to be better than anyone you face.",
  "You can’t win a game by doing nothing. And if someone else wins it for you then you haven’t accomplished anything. Life is the same way.",
  "You do not need outside enemies. For you, the one you have to fight is none other than your own image.",
  "It doesn’t matter how **strong** the opposition is. It doesn’t matter how fearsome the world is. It doesn’t matter how cruel the world is. Fight!",
  "I don’t like the terms ‘good person’ or ‘bad person.’ It is **impossible** to be entirely good to everyone. To some, you are a good person, while to others, you are a bad person.",
  "As long as you **continue** to fight, you are not defeated.",
  "If they adjust to me, I have to adjust in turn. Whoever stops adjusting won’t be able to **continue** **forward**.",
  "Life’s a bore if you don’t **challenge** yourself.",
  "**Knowledge** is the fuel. **Curiosity** is the spark. Action is the engine.",
  "Don’t watch the clock; do what it does. **Keep going**.",
  "It is not the strongest of the species that survives, nor the most intelligent, but the most adaptable to **change**.",
  "All our **dreams** can come true, if we have the **courage** to pursue them.",
  "The only place where **success** comes before **work** is in the dictionary.",
  "If you don’t like something, **change** it. If you can’t **change** it, change your attitude.",
  "The longer you try to get what’s been taken from you, the more you lose.",
  "If you want to live a happy life, tie it to a **goal**, not to people or things.",
  "**Courage** is knowing it might hurt and doing it anyway. Stupidity is the same. That's why life is hard.",
  "I bet even I can make it. If I live and try as hard as everyone else.",
  "We evolve, beyond the person that we were a minute before. Little by little, we advance with each turn. That's how a drill works!",
  "God gave us eyes at the front of our heads so we can look **forward** to **the future**.",
  "I don't want **fear** for a **future** that may not even come to stop me from acting today.",
  "No matter how much you regret it, the past won't **change**. But **the future** is still in your hands.",
  "No one knows what **the future** holds. That’s why its **potential** is infinite.",
  "It's easy to give up. But it doesn't suit you.",
  "A **truth** that's told with bad intent beats all the lies you can invent.",
  "If there is no struggle, there is no **progress**.",
  "Permit yourself to **change** **your mind** when something is no longer working for you.",
  "**Change** brings **opportunity**.",
  "The **best** way to predict **the future** is to invent it.",
  "Hardships often **prepare** ordinary people for an extraordinary destiny.",
  "Quality is not an act, it is a **habit**.",
  "Everything is theoretically **impossible**, until it is done.",
  "Opportunities don't happen. You **create** them.",
  "The man who has **confidence** in himself gains the **confidence** of others.",
  "Setting **goals** is the first step in turning the invisible into the visible.",
  "Doubt kills more **dreams** than **failure** ever will.",
  "**Action** is the foundational key to all **success**.",
  "**Perseverance** is not a long race; it is many short races one after the other.",
  "**Discipline** is the bridge between **goals** and accomplishment.",
  "**Strength** does not come from winning. Your struggles develop your strengths.",
  "If you want to fly, give up everything that weighs you down.",
  "Concentrate all your thoughts upon the **work** at hand. The sun's rays do not burn until brought to a **focus**.",
  "Our technological powers increase, but the side effects and **potential** hazards also escalate.",
  "The will to win, the desire to succeed, the urge to reach your full **potential**... these are the keys that will unlock the door to personal excellence.",
  "I find that the harder I **work**, the more luck I seem to have.",
  "The move from analog to digital is the biggest **change** since the invention of the printing press.",
  "**Success** is most often achieved by those who don't know that **failure** is inevitable.",
  "Technological **progress** has merely provided us with more efficient means for going backwards."

];

/** Days since the Unix epoch for a YYYY-MM-DD key, used as a stable daily rotation index. */
function dayNumber(dateKey: string): number {
  return Math.floor(new Date(`${dateKey}T00:00:00Z`).getTime() / 86_400_000);
}

/** Deterministic "thought of the day" — same for everyone on the same date, shifts as custom thoughts are added. */
export function getThoughtOfTheDay(dateKey: string, customThoughts: string[]): string {
  const pool = [...BUILT_IN_THOUGHTS, ...customThoughts];
  if (pool.length === 0) return "Add your first thought below.";
  const idx = ((dayNumber(dateKey) % pool.length) + pool.length) % pool.length;
  return pool[idx];
}

/** Pick a different random thought from the pool, for the manual "shuffle" action. */
export function getRandomThought(customThoughts: string[], exclude?: string): string {
  const pool = [...BUILT_IN_THOUGHTS, ...customThoughts];
  if (pool.length === 0) return "Add your first thought below.";
  if (pool.length === 1) return pool[0];
  let pick = pool[Math.floor(Math.random() * pool.length)];
  let guard = 0;
  while (pick === exclude && guard < 10) {
    pick = pool[Math.floor(Math.random() * pool.length)];
    guard++;
  }
  return pick;
}
