import type { Question } from "@/lib/questionBank";

// NEET Biology Question Bank
// Chapter: Microbes in Human Welfare
// 80 MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Microbes in Household Products ----------
  { id: 'mhw-1',type:'mcq', type: 'mcq', question: "Curd (dahi) is formed from milk through fermentation carried out mainly by which group of bacteria?", options: ["Lactic Acid Bacteria (LAB), such as Lactobacillus", "Saccharomyces cerevisiae (yeast)", "Acetobacter aceti", "Aspergillus niger"], correctIndex: 0, difficulty: "easy", explanation: "Microbes in Household Products" },
  { id: 'mhw-2', type: 'mcq', question: "Lactic Acid Bacteria (LAB) that ferment milk into curd multiply and, in the process, produce acids that:", options: ["Increase milk's pH significantly", "Convert milk sugar entirely into fat", "Coagulate and partially digest milk proteins, giving curd its characteristic texture", "Have no effect on milk proteins at all"], correctIndex: 2, difficulty: "medium", explanation: "Microbes in Household Products" },
  { id: 'mhw-3', type: 'mcq', question: "Curd, being rich in Lactic Acid Bacteria, also provides a notable nutritional benefit by:", options: ["Reducing the vitamin content of milk", "Improving nutritional quality, for instance by increasing certain vitamins such as vitamin B12 in milk", "Introducing harmful pathogens into the gut", "Eliminating all proteins from milk"], correctIndex: 1, difficulty: "medium", explanation: "Microbes in Household Products" },
  { id: 'mhw-4', type: 'mcq', question: "The characteristic large holes seen in Swiss cheese are produced by the release of a large amount of carbon dioxide gas by which bacterium used in its production?", options: ["Lactobacillus", "Saccharomyces cerevisiae", "Acetobacter aceti", "Propionibacterium sharmanii"], correctIndex: 3, difficulty: "hard", explanation: "Microbes in Household Products" },
  { id: 'mhw-5', type: 'mcq', question: "The dough used to make foods such as bread is fermented using which microorganism, which also causes it to rise due to CO2 production?", options: ["Lactobacillus", "Saccharomyces cerevisiae (baker's yeast)", "Aspergillus niger", "Acetobacter aceti"], correctIndex: 1, difficulty: "easy", explanation: "Microbes in Household Products" },
  { id: 'mhw-6', type: 'mcq', question: "The traditional Indian fermented beverage 'toddy', prepared from the sap of palms, is fermented mainly with the help of:", options: ["Yeasts", "Lactic acid bacteria only", "Acetic acid bacteria only", "Rhizobium"], correctIndex: 0, difficulty: "medium", explanation: "Microbes in Household Products" },
  { id: 'mhw-7', type: 'mcq', question: "Which of the following is an example of a fermented milk product, also produced through the action of specific microbial cultures?", options: ["Wine", "Beer", "Cheese", "Vinegar"], correctIndex: 2, difficulty: "easy", explanation: "Microbes in Household Products" },
  { id: 'mhw-8', type: 'mcq', question: "The specific texture, flavour, and aroma of many fermented food products, such as curd or idli/dosa batter, are, to a large extent, determined by:", options: ["The temperature of storage alone, with no microbial role", "The colour of the raw ingredients used", "The specific microorganisms involved in the fermentation process", "The container material used during fermentation"], correctIndex: 2, difficulty: "medium", explanation: "Microbes in Household Products" },

  // ---------- Microbes in Industrial Products: Fermented Beverages ----------
  { id: 'mhw-9', type: 'mcq', question: "Ethanol-based fermented beverages such as wine, beer, whisky, brandy, and rum are all produced with the help of:", options: ["Rhizobium species", "Lactic acid bacteria exclusively", "Acetic acid bacteria exclusively", "Yeasts, particularly Saccharomyces cerevisiae"], correctIndex: 3, difficulty: "easy", explanation: "Fermented Beverages" },
  { id: 'mhw-10', type: 'mcq', question: "Wine and beer are produced by fermenting fruit or cereal extracts without subsequent:", options: ["Distillation of the fermented broth", "Addition of any water at all", "Any microbial involvement whatsoever", "Any addition of yeast"], correctIndex: 0, difficulty: "medium", explanation: "Fermented Beverages" },
  { id: 'mhw-11', type: 'mcq', question: "Unlike wine and beer, alcoholic beverages such as whisky, brandy, and rum are additionally produced by:", options: ["Avoiding fermentation entirely", "Distillation of the fermented broth", "Using only bacteria, with no yeast involved", "Boiling the fruit juice without any fermentation"], correctIndex: 1, difficulty: "medium", explanation: "Fermented Beverages" },
  { id: 'mhw-12', type: 'mcq', question: "The specific type of grain, fruit, or other raw material fermented, together with the particular yeast strain used, largely determines the:", options: ["Legal status of the beverage in every country", "Distinct flavour and specific type of the alcoholic beverage produced", "Temperature at which the beverage must be served", "Colour of the fermentation vessel required"], correctIndex: 1, difficulty: "medium", explanation: "Fermented Beverages" },
  { id: 'mhw-13', type: 'mcq', question: "Which specific species of yeast is most commonly used in the industrial fermentation of sugars to produce ethanol for beverages?", options: ["Saccharomyces cerevisiae", "Aspergillus niger", "Penicillium notatum", "Trichoderma polysporum"], correctIndex: 0, difficulty: "easy", explanation: "Fermented Beverages" },
  { id: 'mhw-14', type: 'mcq', question: "The process by which yeast converts sugars anaerobically into ethanol and carbon dioxide is known as:", options: ["Aerobic respiration", "Nitrogen fixation", "Photosynthesis", "Alcoholic fermentation"], correctIndex: 3, difficulty: "easy", explanation: "Fermented Beverages" },
  { id: 'mhw-15', type: 'mcq', question: "Compared to beer, which is typically produced by fermenting cereal grains, wine is produced by fermenting:", options: ["Distilled spirits", "Grape juice or other fruit juices", "Cereal grains exclusively", "Milk products exclusively"], correctIndex: 1, difficulty: "easy", explanation: "Fermented Beverages" },
  { id: 'mhw-16', type: 'mcq', question: "Fermentation-based beverage production is one of the oldest applications of biotechnology, historically relying entirely on:", options: ["Genetically engineered organisms", "Recombinant DNA technology", "Naturally occurring microorganisms, long before their role was scientifically understood", "Chemical synthesis with no microbial involvement"], correctIndex: 2, difficulty: "medium", explanation: "Fermented Beverages" },

  // ---------- Microbes in Industrial Products: Antibiotics ----------
  { id: 'mhw-17', type: 'mcq', question: "Antibiotics are chemical substances produced by certain microbes that can kill or retard the growth of other, often disease-causing, microbes. The very first antibiotic discovered was:", options: ["Streptomycin", "Penicillin", "Cyclosporin A", "Statins"], correctIndex: 1, difficulty: "easy", explanation: "Antibiotics" },
  { id: 'mhw-18', type: 'mcq', question: "Penicillin was discovered accidentally by Alexander Fleming while working with which fungus, whose mould was found to inhibit the growth of Staphylococcus bacteria?", options: ["Penicillium notatum", "Aspergillus niger", "Trichoderma polysporum", "Monascus purpureus"], correctIndex: 0, difficulty: "easy", explanation: "Antibiotics" },
  { id: 'mhw-19', type: 'mcq', question: "Fleming observed the antibacterial effect of Penicillium mould by accident but did not establish its full commercial and therapeutic potential; this was later achieved by which two scientists, who shared credit with Fleming for this work?", options: ["Watson and Crick", "Cohen and Boyer", "Jenner and Pasteur", "Ernst Chain and Howard Florey"], correctIndex: 3, difficulty: "hard", explanation: "Antibiotics" },
  { id: 'mhw-20', type: 'mcq', question: "Alexander Fleming, Ernst Chain, and Howard Florey were jointly awarded which honour in 1945 for their contributions to the discovery and development of penicillin?", options: ["The Nobel Prize in Physiology or Medicine", "The Nobel Prize in Physics", "The Fields Medal", "The Nobel Prize in Chemistry"], correctIndex: 0, difficulty: "hard", explanation: "Antibiotics" },
  { id: 'mhw-21', type: 'mcq', question: "The large-scale, industrial production of antibiotics like penicillin typically takes place inside:", options: ["Large fermenters/bioreactors under controlled conditions", "Simple test tubes on a laboratory bench", "Open, unregulated field conditions", "Standard household kitchens"], correctIndex: 0, difficulty: "medium", explanation: "Antibiotics" },
  { id: 'mhw-22', type: 'mcq', question: "Antibiotics have proven to be one of the most significant contributions of microbes to human welfare primarily because they:", options: ["Increase the virulence of disease-causing microbes", "Have no measurable effect on any type of bacteria", "Are effective in curbing many bacterial diseases that were, in the past, often fatal or highly damaging", "Are used only in agriculture, never in medicine"], correctIndex: 2, difficulty: "easy", explanation: "Antibiotics" },
  { id: 'mhw-23', type: 'mcq', question: "The discovery and mass production of antibiotics dramatically improved the human ability to control diseases caused mainly by:", options: ["Genetic mutations", "Bacterial infections", "Environmental toxins exclusively", "Nutritional deficiencies exclusively"], correctIndex: 1, difficulty: "easy", explanation: "Antibiotics" },
  { id: 'mhw-24', type: 'mcq', question: "Which of the following best describes an antibiotic, in general microbiological terms?", options: ["A synthetic chemical with no microbial origin whatsoever", "A hormone produced by animal cells", "A structural protein found in all living cells", "A chemical substance produced by one microorganism that kills or inhibits the growth of another microorganism"], correctIndex: 3, difficulty: "easy", explanation: "Antibiotics" },

  // ---------- Microbes in Industrial Products: Organic Acids, Enzymes and Bioactive Molecules ----------
  { id: 'mhw-25', type: 'mcq', question: "Citric acid, widely used in the food and beverage industry, is industrially produced through fermentation using which fungus?", options: ["Saccharomyces cerevisiae", "Aspergillus niger", "Acetobacter aceti", "Lactobacillus"], correctIndex: 1, difficulty: "medium", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-26', type: 'mcq', question: "Acetic acid, commonly known as vinegar in dilute form, is industrially produced through microbial fermentation using which bacterium?", options: ["Acetobacter aceti", "Aspergillus niger", "Lactobacillus", "Clostridium butylicum"], correctIndex: 0, difficulty: "medium", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-27', type: 'mcq', question: "Lactic acid, used in the food industry and other applications, is industrially produced by fermentation with the help of:", options: ["Aspergillus niger", "Saccharomyces cerevisiae", "Lactobacillus", "Penicillium notatum"], correctIndex: 2, difficulty: "easy", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-28', type: 'mcq', question: "Microbially produced lipase enzymes are commonly added to which household product to help remove oily stains and grease from fabric?", options: ["Toothpaste", "Cooking oil", "Detergents", "Fruit juice"], correctIndex: 2, difficulty: "easy", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-29', type: 'mcq', question: "Pectinases and proteases, enzymes produced by certain microbes, are widely used in the beverage industry to:", options: ["Preserve juices without any refrigeration whatsoever", "Add colour to fruit juices", "Increase the sugar content of fruit juices", "Clarify bottled fruit juices"], correctIndex: 3, difficulty: "medium", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-30', type: 'mcq', question: "Which of the following microbially produced enzymes is widely used to remove oily stains from laundry as an ingredient in detergent formulations?", options: ["Lipase", "Amylase exclusively", "Protease, for stains exclusively", "Cellulase exclusively"], correctIndex: 0, difficulty: "medium", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-31', type: 'mcq', question: "Streptokinase, an enzyme produced by the bacterium Streptococcus and modified using genetic engineering, is medically important because it is used as a:", options: ["Vitamin supplement", "Clot-buster, to dissolve blood clots in patients who have suffered a myocardial infarction", "Antibiotic against fungal infections", "Growth hormone for livestock"], correctIndex: 1, difficulty: "medium", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-32', type: 'mcq', question: "The immunosuppressive drug cyclosporin A, used to help prevent organ rejection after transplantation, is produced by which fungus?", options: ["Aspergillus niger", "Trichoderma polysporum", "Penicillium notatum", "Saccharomyces cerevisiae"], correctIndex: 1, difficulty: "hard", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-33', type: 'mcq', question: "Statins, a group of drugs used to lower blood cholesterol levels, are produced with the help of the yeast:", options: ["Monascus purpureus", "Saccharomyces cerevisiae", "Candida albicans", "Aspergillus niger"], correctIndex: 0, difficulty: "medium", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },
  { id: 'mhw-34', type: 'mcq', question: "Statins lower blood cholesterol levels by competitively inhibiting the activity of the enzyme:", options: ["DNA polymerase", "RNA polymerase", "Restriction endonuclease", "HMG-CoA reductase, an enzyme responsible for cholesterol synthesis"], correctIndex: 3, difficulty: "hard", explanation: "Organic Acids, Enzymes and Bioactive Molecules" },

  // ---------- Microbes in Sewage Treatment ----------
  { id: 'mhw-35', type: 'mcq', question: "Sewage, i.e. municipal wastewater containing large amounts of organic matter and microbes, undergoes treatment before release into natural water bodies, primarily to:", options: ["Increase its organic content before release", "Reduce the pollution load and harmful microbial content before safe disposal", "Add more pathogenic microbes before release", "Convert it directly into drinking water without further treatment"], correctIndex: 1, difficulty: "easy", explanation: "Sewage Treatment" },
  { id: 'mhw-36', type: 'mcq', question: "The initial stage of sewage treatment, involving physical removal of large and small particles through sequential filtration and sedimentation, is called:", options: ["Primary treatment", "Tertiary treatment", "Anaerobic sludge digestion", "Secondary treatment"], correctIndex: 0, difficulty: "easy", explanation: "Sewage Treatment" },
  { id: 'mhw-37', type: 'mcq', question: "The biological/secondary treatment stage of sewage treatment primarily involves:", options: ["Adding antibiotics to kill all the microbes present", "Simply storing the effluent without any further processing", "Passing the primary effluent into large aeration tanks where aerobic microbes vigorously degrade organic matter", "Directly releasing the primary effluent into rivers with no further steps"], correctIndex: 2, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-38', type: 'mcq', question: "During secondary/biological sewage treatment, the primary effluent is mechanically agitated and air is pumped into it, allowing vigorous growth of aerobic microbes, which then form aggregates called:", options: ["Plaques", "Flocs", "Biofilms exclusively", "Nodules"], correctIndex: 1, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-39', type: 'mcq', question: "The 'flocs' formed by aerobic microbes during secondary sewage treatment are significant because they:", options: ["Increase the pollution content of the effluent", "Consist entirely of non-living particulate matter", "Have no measurable effect on the sewage's organic content", "Consume a major proportion of the organic matter present in the sewage, thereby reducing its pollution load"], correctIndex: 3, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-40', type: 'mcq', question: "BOD, a key parameter used to measure the level of organic pollution in water, stands for:", options: ["Biochemical Oxygen Demand", "Bacterial Oxygen Demand", "Biochemical Organic Decomposition", "Biological Oxidation Density"], correctIndex: 0, difficulty: "easy", explanation: "Sewage Treatment" },
  { id: 'mhw-41', type: 'mcq', question: "BOD (Biochemical Oxygen Demand) refers to the amount of oxygen that would be consumed if all the organic matter in a given volume of water (e.g. one litre) were:", options: ["Oxidised by bacteria present in that water sample", "Frozen at sub-zero temperatures", "Converted directly into methane gas", "Passed through a UV sterilisation unit"], correctIndex: 0, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-42', type: 'mcq', question: "A higher BOD value for a water sample generally indicates:", options: ["Lower levels of organic pollution in the water", "No relationship at all with the level of pollution", "Higher levels of organic pollution in the water", "That the water is completely free of any microbes"], correctIndex: 2, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-43', type: 'mcq', question: "After secondary treatment, the treated effluent is passed into a settling tank, where the bacterial flocs are allowed to sediment. This sediment is referred to as:", options: ["Primary sludge", "Activated sludge", "Raw sewage", "Biogas slurry"], correctIndex: 1, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-44', type: 'mcq', question: "A small part of the activated sludge from the settling tank is pumped back into the aeration tank to serve as:", options: ["A source of drinking water", "Fertiliser for direct field application", "Raw material for antibiotic production", "An inoculum, to seed the growth of aerobic microbes in the incoming sewage"], correctIndex: 3, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-45', type: 'mcq', question: "The remaining major part of the activated sludge, not recycled as inoculum, is pumped into large tanks called:", options: ["Aeration tanks exclusively", "Anaerobic sludge digesters", "Primary settling tanks exclusively", "Biosafety cabinets"], correctIndex: 1, difficulty: "medium", explanation: "Sewage Treatment" },
  { id: 'mhw-46', type: 'mcq', question: "Inside anaerobic sludge digesters, anaerobic bacteria digest the bacteria and fungi present in the activated sludge, producing a mixture of gases including methane, hydrogen sulfide, and carbon dioxide. This gas mixture is known as:", options: ["Biogas", "Natural gas", "Producer gas", "Syngas"], correctIndex: 0, difficulty: "easy", explanation: "Sewage Treatment" },

  // ---------- Microbes in Biogas Production ----------
  { id: 'mhw-47', type: 'mcq', question: "Biogas, a mixture of gases (mainly methane) produced by microbial activity, is generated when microbes are grown anaerobically on which type of material?", options: ["Purely inorganic minerals", "Sterile distilled water", "Cellulosic (organic) material, such as animal dung and plant waste", "Only refined petroleum products"], correctIndex: 2, difficulty: "easy", explanation: "Biogas Production" },
  { id: 'mhw-48', type: 'mcq', question: "The specific group of anaerobic bacteria responsible for producing a large amount of methane, along with CO2 and H2, during biogas formation are collectively called:", options: ["Nitrifying bacteria", "Denitrifying bacteria", "Methanogens, such as Methanobacterium", "Lactic acid bacteria"], correctIndex: 2, difficulty: "medium", explanation: "Biogas Production" },
  { id: 'mhw-49', type: 'mcq', question: "Methanogenic bacteria involved in biogas production are also naturally found in large populations within which specialised chamber of the digestive system of ruminant animals such as cattle and buffalo?", options: ["The pancreas", "The small intestine exclusively", "The gall bladder", "The rumen"], correctIndex: 3, difficulty: "medium", explanation: "Biogas Production" },
  { id: 'mhw-50', type: 'mcq', question: "The presence of a large population of methanogens in the rumen of cattle and buffalo plays an important role in:", options: ["Helping digest cellulose and contributing to the animal's overall nutrition", "Preventing digestion of any food material", "Producing milk directly", "Causing disease in the animal"], correctIndex: 0, difficulty: "medium", explanation: "Biogas Production" },
  { id: 'mhw-51', type: 'mcq', question: "Since cattle dung is rich in methanogenic bacteria owing to their presence in the rumen, this dung, commonly called 'gobar', is widely used as the raw material for producing:", options: ["Antibiotics", "Biogas, often referred to as 'gobar gas' in India", "Citric acid", "Statins"], correctIndex: 1, difficulty: "easy", explanation: "Biogas Production" },
  { id: 'mhw-52', type: 'mcq', question: "A typical biogas plant consists of a dome-shaped structure, usually made of bricks, into which a slurry of the raw material (e.g. dung) is fed. This structure is commonly known as a:", options: ["Aeration tank", "Biogas digester/plant", "Settling tank", "Anaerobic sludge digester, as used specifically in sewage treatment"], correctIndex: 1, difficulty: "medium", explanation: "Biogas Production" },
  { id: 'mhw-53', type: 'mcq', question: "After anaerobic digestion inside a biogas plant, the digested slurry moves into an overflow tank, and the leftover spent slurry is typically used as:", options: ["A fertiliser for agricultural fields", "Drinking water for livestock", "A raw material for antibiotic production", "A source of citric acid"], correctIndex: 0, difficulty: "easy", explanation: "Biogas Production" },
  { id: 'mhw-54', type: 'mcq', question: "In India, which institute played a particularly significant role in developing biogas plant technology, especially for rural use?", options: ["Indian Institute of Science, Bangalore", "Bhabha Atomic Research Centre", "Central Drug Research Institute", "Indian Agricultural Research Institute (IARI), New Delhi"], correctIndex: 3, difficulty: "hard", explanation: "Biogas Production" },
  { id: 'mhw-55', type: 'mcq', question: "Biogas, produced through the anaerobic microbial breakdown of organic waste, is considered a useful energy resource mainly because it can be used for:", options: ["Sterilising surgical instruments exclusively", "Cooking and lighting purposes, particularly in rural households", "Producing antibiotics exclusively", "Manufacturing plastics exclusively"], correctIndex: 1, difficulty: "easy", explanation: "Biogas Production" },
  { id: 'mhw-56', type: 'mcq', question: "The overall biogas production process, from raw dung/organic waste to usable fuel gas, exemplifies the use of microbes for:", options: ["Antibiotic synthesis", "Organic acid production", "Renewable energy generation", "Biocontrol of agricultural pests"], correctIndex: 2, difficulty: "medium", explanation: "Biogas Production" },

  // ---------- Microbes as Biocontrol Agents ----------
  { id: 'mhw-57', type: 'mcq', question: "The use of biological methods, such as natural predators or pathogens, to control agricultural pests and plant diseases, as an alternative to chemical pesticides, is called:", options: ["Bioremediation", "Biological control (biocontrol)", "Biofortification", "Bioinformatics"], correctIndex: 1, difficulty: "easy", explanation: "Biocontrol Agents" },
  { id: 'mhw-58', type: 'mcq', question: "Ladybird beetles and dragonflies are commonly used as natural biocontrol agents to help control populations of which pests, respectively?", options: ["Aphids and mosquitoes", "Nematodes and fungal spores", "Cotton bollworms and corn borers", "Rodents and locusts"], correctIndex: 0, difficulty: "easy", explanation: "Biocontrol Agents" },
  { id: 'mhw-59', type: 'mcq', question: "Bacillus thuringiensis (Bt), used as a biocontrol agent against butterfly caterpillars on crops such as brassicas, cotton, and soybean, is typically applied by:", options: ["Injecting it directly into the plant's roots", "Genetically modifying the pest insect itself", "Releasing live adult insects infected with the bacteria", "Spraying freeze-dried bacteria mixed with water onto the vulnerable plants"], correctIndex: 3, difficulty: "medium", explanation: "Biocontrol Agents" },
  { id: 'mhw-60', type: 'mcq', question: "When insect larvae feed on Bacillus thuringiensis-treated plants, the bacterial toxin they ingest typically causes them to:", options: ["Die within a few days of ingestion", "Become immune to all future infections", "Develop resistance to all pesticides", "Grow larger and reproduce faster"], correctIndex: 0, difficulty: "medium", explanation: "Biocontrol Agents" },
  { id: 'mhw-61', type: 'mcq', question: "Baculoviruses, used as species-specific biocontrol agents, are pathogens that specifically attack:", options: ["Insects and other arthropods", "Only plants, never animals", "Only bacteria, in a manner similar to bacteriophages", "Only fungi"], correctIndex: 0, difficulty: "medium", explanation: "Biocontrol Agents" },
  { id: 'mhw-62', type: 'mcq', question: "The genus of baculovirus most commonly used as a biological control agent against insect pests, as mentioned in NCERT, is:", options: ["Bacteriophage T4", "Retrovirus", "Nucleopolyhedrovirus", "Adenovirus"], correctIndex: 2, difficulty: "hard", explanation: "Biocontrol Agents" },
  { id: 'mhw-63', type: 'mcq', question: "A major advantage of using baculoviruses as biocontrol agents, compared to broad-spectrum chemical pesticides, is that they are:", options: ["Toxic to a very wide range of organisms, including humans", "Narrow-spectrum, species-specific insecticidal agents with no negative impact on plants, mammals, birds, fish, or non-target insects", "Effective against plant diseases but not insect pests", "Only effective when combined with strong chemical pesticides"], correctIndex: 1, difficulty: "medium", explanation: "Biocontrol Agents" },
  { id: 'mhw-64', type: 'mcq', question: "Because of their narrow host range and environmentally friendly nature, baculoviruses are considered particularly valuable in:", options: ["Large-scale antibiotic manufacturing", "Sewage treatment plants", "Biogas production", "Integrated Pest Management (IPM) programmes"], correctIndex: 3, difficulty: "medium", explanation: "Biocontrol Agents" },

  // ---------- Microbes as Biofertilisers ----------
  { id: 'mhw-65', type: 'mcq', question: "Organisms that enrich the nutrient quality of soil, mainly through the fixation of atmospheric nitrogen or by enhancing nutrient availability, are called:", options: ["Biopesticides", "Biofertilisers", "Bioreactors", "Biosensors"], correctIndex: 1, difficulty: "easy", explanation: "Biofertilisers" },
  { id: 'mhw-66', type: 'mcq', question: "Rhizobium, a well-known nitrogen-fixing biofertiliser, forms a symbiotic association specifically with the roots of:", options: ["Leguminous plants", "Cereal crops such as wheat and rice", "Aquatic plants exclusively", "Coniferous trees exclusively"], correctIndex: 0, difficulty: "easy", explanation: "Biofertilisers" },
  { id: 'mhw-67', type: 'mcq', question: "Azospirillum and Azotobacter, both used as biofertilisers, are examples of nitrogen-fixing bacteria that are characteristically:", options: ["Obligate parasites of plant roots", "Only capable of nitrogen fixation inside root nodules", "Free-living in the soil, fixing atmospheric nitrogen without forming a symbiotic association", "Pathogenic to most crop plants"], correctIndex: 2, difficulty: "medium", explanation: "Biofertilisers" },
  { id: 'mhw-68', type: 'mcq', question: "Fungi that form a mutually beneficial symbiotic association with plant roots, known as mycorrhiza, primarily help the plant by:", options: ["Producing antibiotics within the root", "Fixing atmospheric nitrogen directly", "Increasing the plant's ability to absorb phosphorus from the soil", "Producing large quantities of ethanol"], correctIndex: 2, difficulty: "medium", explanation: "Biofertilisers" },
  { id: 'mhw-69', type: 'mcq', question: "Among fungi forming mycorrhizal associations with plant roots, which genus is most commonly cited as an example in NCERT?", options: ["Trichoderma", "Aspergillus", "Penicillium", "Glomus"], correctIndex: 3, difficulty: "hard", explanation: "Biofertilisers" },
  { id: 'mhw-70', type: 'mcq', question: "Cyanobacteria, widely distributed autotrophic microbes in both aquatic and terrestrial environments, contribute to soil fertility mainly by their ability to:", options: ["Fix atmospheric nitrogen and add organic matter to the soil", "Produce large amounts of antibiotics", "Produce ethanol during fermentation", "Break down cellulose in sewage treatment plants"], correctIndex: 0, difficulty: "easy", explanation: "Biofertilisers" },
  { id: 'mhw-71', type: 'mcq', question: "Which of the following genera are commonly cited examples of nitrogen-fixing cyanobacteria used as biofertilisers, especially in paddy fields?", options: ["Rhizobium and Azospirillum", "Anabaena, Nostoc, and Oscillatoria", "Lactobacillus and Acetobacter", "Aspergillus and Penicillium"], correctIndex: 1, difficulty: "medium", explanation: "Biofertilisers" },
  { id: 'mhw-72', type: 'mcq', question: "Cyanobacteria used as biofertilisers in agricultural fields, especially in paddy cultivation, are commonly referred to by which traditional descriptive term?", options: ["Green manure exclusively", "Blue-green algae", "Golden algae", "Red algae"], correctIndex: 1, difficulty: "easy", explanation: "Biofertilisers" },

  // ---------- Mixed / Assertion-Reason ----------
  { id: 'mhw-73', type: 'mcq', question: "Which of the following pairs correctly matches a microbial product with its industrial or medical application?", options: ["Streptokinase — Dissolving blood clots after a heart attack", "Cyclosporin A — Lowering blood cholesterol", "Statins — Suppressing the immune system after organ transplant", "Citric acid — Fixing atmospheric nitrogen"], correctIndex: 0, difficulty: "medium", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-74', type: 'mcq', question: "Which of the following pairs correctly matches a microbe with the product it is used to produce?", options: ["Saccharomyces cerevisiae — Citric acid", "Acetobacter aceti — Antibiotics", "Lactobacillus — Ethanol", "Aspergillus niger — Citric acid"], correctIndex: 3, difficulty: "medium", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-75', type: 'mcq', question: "Assertion: Activated sludge from sewage treatment is partly recycled back into the aeration tank rather than being entirely discarded.\nReason: Recycling a portion of activated sludge provides a ready inoculum of aerobic microbes that helps efficiently treat newly incoming sewage.\nChoose the correct option:", options: ["The assertion is true, but the reason is false", "Both assertion and reason are true, and the reason correctly explains the assertion", "The assertion is false, but the reason is true", "Both the assertion and the reason are false"], correctIndex: 1, difficulty: "hard", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-76', type: 'mcq', question: "Assertion: Baculoviruses are generally preferred over broad-spectrum chemical pesticides in integrated pest management programmes.\nReason: Baculoviruses are typically species-specific and have no known negative impact on non-target plants, mammals, birds, fish, or beneficial insects.\nChoose the correct option:", options: ["The assertion is true, but the reason is false", "The assertion is false, but the reason is true", "Both assertion and reason are true, and the reason correctly explains the assertion", "Both the assertion and the reason are false"], correctIndex: 2, difficulty: "hard", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-77', type: 'mcq', question: "Which of the following correctly pairs a biofertiliser organism with its primary mechanism of enriching soil fertility?", options: ["Glomus — Free-living nitrogen fixation in open soil", "Rhizobium — Symbiotic nitrogen fixation in leguminous root nodules", "Nostoc — Solely a source of citric acid", "Bacillus thuringiensis — Direct nitrogen fixation in soil"], correctIndex: 1, difficulty: "medium", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-78', type: 'mcq', question: "Assertion: BOD (Biochemical Oxygen Demand) is commonly used as a practical measure of the extent of organic pollution in a water sample.\nReason: A higher BOD indicates a greater amount of organic matter present, which requires more oxygen for microbial oxidation, reflecting a higher pollution load.\nChoose the correct option:", options: ["Both assertion and reason are true, and the reason correctly explains the assertion", "The assertion is true, but the reason is false", "The assertion is false, but the reason is true", "Both the assertion and the reason are false"], correctIndex: 0, difficulty: "hard", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-79', type: 'mcq', question: "Which of the following biotechnological/microbial applications is primarily aimed at improving agricultural soil fertility, rather than food production, waste treatment, or pest control?", options: ["Bt-based biocontrol of caterpillars", "Anaerobic sludge digestion in sewage treatment", "Production of citric acid using Aspergillus niger", "Use of Rhizobium and Azotobacter as biofertilisers"], correctIndex: 3, difficulty: "easy", explanation: "Microbes in Human Welfare: Mixed" },
  { id: 'mhw-80', type: 'mcq', question: "Which of the following best summarises the overarching theme of the chapter 'Microbes in Human Welfare'?", options: ["A wide diversity of naturally occurring microbes provide substantial benefits to humans in food production, industry, sewage treatment, energy generation, and agriculture", "Only genetically modified microbes have any practical use to humans", "Microbes have no measurable role in agriculture, industry, or environmental management", "Microbes are exclusively harmful and must always be eliminated from human environments"], correctIndex: 0, difficulty: "medium", explanation: "Microbes in Human Welfare: Mixed" },

];

export default questions;