import type { Question } from "@/lib/questionBank";

// NEET Biology Question Bank
// Chapter: Biodiversity and Conservation
// ~80 MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctindex (index 0-3), difficulty, topic }

const questions: Question[] = [

  // ---------- Concept of Biodiversity ----------
  { id: 1, question: "The term 'Biological Diversity' to describe the combined diversity of life at all levels of biological organisation was popularised by:", options: ["Robert May", "Edward Wilson", "Norman Myers", "Paul Ehrlich"], correctindex: 1, difficulty: "medium", topic: "Biodiversity Concept" },
  { id: 2, question: "Biodiversity, as described in NCERT, exists at how many hierarchical levels of biological organisation?", options: ["Two", "Three", "Four", "Five"], correctindex: 1, difficulty: "easy", topic: "Biodiversity Concept" },
  { id: 3, question: "The variation seen in the concentration and potency of the active chemical reserpine among different Rauvolfia vomitoria plants growing in different Himalayan ranges is an example of:", options: ["Genetic diversity", "Species diversity", "Ecological diversity", "Ecosystem diversity"], correctindex: 0, difficulty: "medium", topic: "Biodiversity Concept" },
  { id: 4, question: "India, as per NCERT, has more than ______ genetically different strains of rice and about ______ varieties of mangoes, illustrating genetic diversity.", options: ["50,000; 1,000", "20,000; 2,500", "100; 50", "5,000; 500"], correctindex: 0, difficulty: "hard", topic: "Biodiversity Concept" },
  { id: 5, question: "Diversity at the level of ecosystems within a given geographical area is termed:", options: ["Genetic diversity", "Species diversity", "Ecological diversity", "Allelic diversity"], correctindex: 2, difficulty: "medium", topic: "Biodiversity Concept" },
  { id: 6, question: "Compared to Norway, a small country like India shows far greater ecosystem diversity, ranging from tropical rainforests, mangroves, and coral reefs to deserts and alpine vegetation. This illustrates:", options: ["Genetic diversity", "Species diversity", "Ecological diversity", "None of these"], correctindex: 2, difficulty: "medium", topic: "Biodiversity Concept" },
  { id: 7, question: "According to global taxonomic surveys cited in NCERT, the total number of species of plants and animals described so far is approximately:", options: ["7 lakh", "1.5 million", "10 million", "50 million"], correctindex: 1, difficulty: "medium", topic: "Biodiversity Concept" },
  { id: 8, question: "Ecologist Robert May's global estimates place the total number of species on earth (described plus undescribed) at about:", options: ["1.5 million", "7 million", "20 million", "50 million"], correctindex: 1, difficulty: "hard", topic: "Biodiversity Concept" },

  // ---------- Patterns of Biodiversity ----------
  { id: 9, question: "Species diversity of both plants and animals is generally richest:", options: ["Near the poles", "In temperate regions", "In the tropics", "In cold deserts"], correctindex: 2, difficulty: "easy", topic: "Patterns of Biodiversity" },
  { id: 10, question: "The general trend of decreasing species diversity as one moves away from the equator towards the poles is called the:", options: ["Species-area relationship", "Latitudinal gradient", "Rivet popper hypothesis", "Ecological succession"], correctindex: 1, difficulty: "easy", topic: "Patterns of Biodiversity" },
  { id: 11, question: "Which of the following is NOT among the proposed explanations for the higher species richness of tropical regions?", options: ["Longer evolutionary time available for speciation", "A relatively constant, less seasonal environment favouring niche specialisation", "Greater availability of solar energy supporting higher productivity", "Lower annual rainfall limiting overall plant growth"], correctindex: 3, difficulty: "medium", topic: "Patterns of Biodiversity" },
  { id: 12, question: "In the species-area relationship equation, log S = log C + Z log A, the term 'Z' represents the:", options: ["Total species richness", "Regression coefficient (slope of the line)", "Area of the habitat sampled", "Y-intercept of the line"], correctindex: 1, difficulty: "medium", topic: "Patterns of Biodiversity" },
  { id: 13, question: "For relatively small areas within a region, the value of the slope 'Z' in the species-area relationship generally falls in the range:", options: ["0.1 to 0.2", "0.6 to 1.2", "2.0 to 3.0", "5.0 to 6.0"], correctindex: 0, difficulty: "hard", topic: "Patterns of Biodiversity" },
  { id: 14, question: "When species-area relationships are studied for very large areas, such as entire continents, the value of Z becomes steeper and typically lies in the range:", options: ["0.01 to 0.05", "0.1 to 0.2", "0.6 to 1.2", "3.0 to 4.0"], correctindex: 2, difficulty: "hard", topic: "Patterns of Biodiversity" },
  { id: 15, question: "Applying the species-area relationship (with a Z value close to 0.25) in reverse, ecologists predict that if a habitat area is reduced by 90%, the number of species surviving would be reduced by approximately:", options: ["10%", "50%", "90%", "100%"], correctindex: 1, difficulty: "hard", topic: "Patterns of Biodiversity" },
  { id: 16, question: "Which region is often cited as harbouring the greatest levels of species richness of plants and animals on earth, largely owing to its evolutionary age and stable, favourable climate?", options: ["Sahara Desert", "Amazonian rainforest", "Arctic tundra", "Mediterranean scrubland"], correctindex: 1, difficulty: "easy", topic: "Patterns of Biodiversity" },
  { id: 17, question: "The Amazon rainforest, described in NCERT as having the greatest biodiversity on earth, is estimated to harbour at least how many species of plants?", options: ["4,000", "40,000", "4,00,000", "4 million"], correctindex: 1, difficulty: "medium", topic: "Patterns of Biodiversity" },
  { id: 18, question: "Colombia, located close to the equator, has nearly 1,400 species of birds, which is more than the total number of bird species found in a temperate country such as:", options: ["Brazil", "The USA and Canada combined", "Indonesia", "Malaysia"], correctindex: 1, difficulty: "hard", topic: "Patterns of Biodiversity" },

  // ---------- Importance of Biodiversity ----------
  { id: 19, question: "Long-term ecosystem experiments conducted by David Tilman using outdoor plots showed that plots with more plant species diversity:", options: ["Showed greater year-to-year variation in total biomass", "Showed less year-to-year variation in total biomass and had higher productivity", "Went extinct faster than low-diversity plots", "Showed no measurable difference from low-diversity plots"], correctindex: 1, difficulty: "medium", topic: "Importance of Biodiversity" },
  { id: 20, question: "The 'Rivet Popper Hypothesis', which explains why every species in an ecosystem matters, was proposed by:", options: ["Paul Ehrlich", "Robert May", "Edward Wilson", "Norman Myers"], correctindex: 0, difficulty: "medium", topic: "Importance of Biodiversity" },
  { id: 21, question: "In the Rivet Popper Hypothesis, an aeroplane is used as an analogy for an ecosystem. In this analogy, the numerous rivets holding the aircraft's parts together represent:", options: ["The individual species making up the ecosystem", "Abiotic factors like temperature and rainfall", "The human population size", "Predators exclusively"], correctindex: 0, difficulty: "medium", topic: "Importance of Biodiversity" },
  { id: 22, question: "According to the Rivet Popper Hypothesis, as rivets (species) are removed one by one from different parts of the plane, a critical point is eventually reached at which:", options: ["The ecosystem becomes more productive than before", "The loss of a keystone species causes the whole system to collapse", "Species diversity automatically increases", "No effect on the system ever occurs"], correctindex: 1, difficulty: "medium", topic: "Importance of Biodiversity" },
  { id: 23, question: "All of the following are ecosystem services provided by biodiversity-rich natural ecosystems EXCEPT:", options: ["Prevention of soil erosion", "Pollination of crops by insects and birds", "An increase in the global species extinction rate", "Regulation of climate through forests"], correctindex: 2, difficulty: "easy", topic: "Importance of Biodiversity" },
  { id: 24, question: "The value of biodiversity derived from direct, tangible products such as food, firewood, fibre, and pharmaceutical drugs is termed its:", options: ["Ethical value", "Narrowly utilitarian value", "Broadly utilitarian value", "Aesthetic value"], correctindex: 1, difficulty: "medium", topic: "Importance of Biodiversity" },
  { id: 25, question: "The vital role of biodiversity-rich forests and oceans in producing oxygen through photosynthesis for aerobic respiration is best classified under the:", options: ["Narrowly utilitarian value of biodiversity", "Broadly utilitarian value of biodiversity", "Ethical value of biodiversity", "None of these"], correctindex: 1, difficulty: "medium", topic: "Importance of Biodiversity" },
  { id: 26, question: "The view that every species has an intrinsic right to exist on earth, irrespective of its known or unknown economic importance to humans, reflects the:", options: ["Narrowly utilitarian value of biodiversity", "Broadly utilitarian value of biodiversity", "Ethical value of biodiversity", "Aesthetic value of biodiversity"], correctindex: 2, difficulty: "medium", topic: "Importance of Biodiversity" },

  // ---------- Loss of Biodiversity (The Evil Quartet) ----------
  { id: 27, question: "The four major causes of biodiversity loss, together referred to by conservationists as the 'Evil Quartet', include all of the following EXCEPT:", options: ["Habitat loss and fragmentation", "Over-exploitation", "Global cooling caused entirely by volcanic winters", "Alien species invasions"], correctindex: 2, difficulty: "medium", topic: "Loss of Biodiversity" },
  { id: 28, question: "According to NCERT, the single most important cause driving animals and plants to extinction today is:", options: ["Co-extinction", "Habitat loss and fragmentation", "Random genetic mutation", "Genetic drift"], correctindex: 1, difficulty: "easy", topic: "Loss of Biodiversity" },
  { id: 29, question: "Tropical rainforests, which once covered more than 14 per cent of the earth's land surface, now cover only about:", options: ["25%", "10%", "6%", "2%"], correctindex: 2, difficulty: "hard", topic: "Loss of Biodiversity" },
  { id: 30, question: "At the present rate of destruction, tropical rainforests - among the most species-rich habitats on earth - are projected to be lost completely within:", options: ["The next 10 years", "The next 100 years or so", "The next 1,000 years", "They face no risk of being lost"], correctindex: 1, difficulty: "medium", topic: "Loss of Biodiversity" },
  { id: 31, question: "Singapore, cited as a striking example in NCERT, lost what percentage of its original forest cover over a period of 183 years, resulting in the extinction of a large number of species?", options: ["10%", "25%", "50%", "95%"], correctindex: 3, difficulty: "hard", topic: "Loss of Biodiversity" },
  { id: 32, question: "The breaking up of large, continuous habitats into small, isolated patches due to human activities such as road building and agriculture is known as:", options: ["Overexploitation", "Habitat fragmentation", "Co-extinction", "Alien invasion"], correctindex: 1, difficulty: "easy", topic: "Loss of Biodiversity" },
  { id: 33, question: "The extinction of Steller's sea cow (within 27 years of its discovery) and the passenger pigeon are classic examples of species loss caused mainly by:", options: ["Habitat fragmentation", "Overexploitation by humans", "Invasion by an alien species", "Long-term climate change"], correctindex: 1, difficulty: "medium", topic: "Loss of Biodiversity" },
  { id: 34, question: "The deliberate introduction of the Nile perch into Lake Victoria in East Africa is believed to have led to the extinction of about how many species of native cichlid fish?", options: ["20", "200", "2,000", "2"], correctindex: 1, difficulty: "hard", topic: "Loss of Biodiversity" },
  { id: 35, question: "Which of the following is a well-known invasive alien plant species that has caused significant ecological damage after introduction into India?", options: ["Rauvolfia serpentina", "Lantana camara", "Azadirachta indica (Neem)", "Shorea robusta (Sal)"], correctindex: 1, difficulty: "easy", topic: "Loss of Biodiversity" },
  { id: 36, question: "When a species becomes extinct, other species intimately associated with it in an obligatory relationship, such as its host-specific parasites, also become extinct. This phenomenon is called:", options: ["Overexploitation", "Co-extinction", "Habitat fragmentation", "Speciation"], correctindex: 1, difficulty: "medium", topic: "Loss of Biodiversity" },
  { id: 37, question: "The loss of a unique assemblage of coevolved parasites when their specific host fish species becomes extinct is an example of:", options: ["Co-extinction", "Alien species invasion", "Natural selection", "Adaptive radiation"], correctindex: 0, difficulty: "medium", topic: "Loss of Biodiversity" },
  { id: 38, question: "Water hyacinth (Eichhornia crassipes), a notorious weed that has choked many Indian rivers and lakes after its introduction, is native to:", options: ["Africa", "South America", "Australia", "Southeast Asia"], correctindex: 1, difficulty: "medium", topic: "Loss of Biodiversity" },
  { id: 39, question: "Unsustainable hunting and fishing of wild populations for meat, skins, ivory, or the aquarium/pet trade fall under which category of the Evil Quartet?", options: ["Habitat loss", "Over-exploitation", "Co-extinction", "Alien invasion"], correctindex: 1, difficulty: "easy", topic: "Loss of Biodiversity" },
  { id: 40, question: "'Habitat degradation' associated with pollution is best described as:", options: ["The complete physical removal of a habitat", "A reduction in the quality of a habitat without its complete removal", "The introduction of a new predator species", "The extinction of a keystone species"], correctindex: 1, difficulty: "medium", topic: "Loss of Biodiversity" },

  // ---------- Mass Extinctions ----------
  { id: 41, question: "The geological record shows that biodiversity has generally increased over evolutionary time, punctuated by occasional dips caused by:", options: ["Continuous linear growth only", "Mass extinction events", "Human activity right from the start of geological time", "Volcanic winters alone, unrelated to species loss"], correctindex: 1, difficulty: "medium", topic: "Mass Extinctions" },
  { id: 42, question: "The greatest of the five mass extinction events in earth's history, during which nearly 95 per cent of species disappeared, took place at the end of the:", options: ["Ordovician period", "Permian period", "Triassic period", "Cretaceous period"], correctindex: 1, difficulty: "hard", topic: "Mass Extinctions" },
  { id: 43, question: "Non-avian dinosaurs became extinct during the mass extinction event marking the end of the:", options: ["Permian period", "Devonian period", "Cretaceous period", "Ordovician period"], correctindex: 2, difficulty: "medium", topic: "Mass Extinctions" },
  { id: 44, question: "The ongoing, human-driven phase of biodiversity loss is often referred to by ecologists as:", options: ["The first mass extinction", "The sixth mass extinction", "The Permian extinction", "The Cambrian explosion"], correctindex: 1, difficulty: "medium", topic: "Mass Extinctions" },
  { id: 45, question: "In contrast to the previous five mass extinctions triggered by natural events, the present (sixth) extinction is distinguished mainly by:", options: ["Being much slower than earlier extinctions", "Being caused predominantly by human activities and occurring at a much faster rate", "Being fully reversible within a few years", "Affecting only marine species"], correctindex: 1, difficulty: "medium", topic: "Mass Extinctions" },
  { id: 46, question: "The 'Cambrian explosion' referred to in discussions of biodiversity history denotes a period of:", options: ["Mass extinction of marine life", "Rapid diversification of animal life forms", "Global glaciation", "Complete loss of plant diversity"], correctindex: 1, difficulty: "hard", topic: "Mass Extinctions" },

  // ---------- IUCN Red List Categories ----------
  { id: 47, question: "According to the IUCN Red List, a species that is no longer known to exist anywhere in the world is classified as:", options: ["Endangered", "Extinct", "Vulnerable", "Data Deficient"], correctindex: 1, difficulty: "easy", topic: "IUCN Red List" },
  { id: 48, question: "A species that survives only in captivity or as a naturalised population well outside its historic range, with no living individuals remaining in the wild, is classified by IUCN as:", options: ["Extinct", "Extinct in the Wild", "Critically Endangered", "Vulnerable"], correctindex: 1, difficulty: "medium", topic: "IUCN Red List" },
  { id: 49, question: "The IUCN category assigned to a species facing an extremely high risk of extinction in the immediate future is:", options: ["Vulnerable", "Near Threatened", "Critically Endangered", "Least Concern"], correctindex: 2, difficulty: "medium", topic: "IUCN Red List" },
  { id: 50, question: "According to the IUCN Red List (2004) figures cited in NCERT, how many species are recorded to have gone extinct in the last 500 years?", options: ["84", "384", "784", "7,840"], correctindex: 2, difficulty: "hard", topic: "IUCN Red List" },
  { id: 51, question: "Which of the following is cited as a classic example of a species driven to extinction by human activity?", options: ["Bengal tiger", "Dodo of Mauritius", "Blue whale", "Indian elephant"], correctindex: 1, difficulty: "easy", topic: "IUCN Red List" },
  { id: 52, question: "As mentioned in NCERT, which subspecies of tiger have become extinct within the last 100 years?", options: ["Royal Bengal, Sumatran and Siberian tigers", "Bali, Javan and Caspian tigers", "White tigers only", "Indo-Chinese tigers only"], correctindex: 1, difficulty: "hard", topic: "IUCN Red List" },
  { id: 53, question: "A taxon is placed in the IUCN category 'Data Deficient' when:", options: ["It has been confirmed extinct", "There is inadequate information to make a direct or indirect assessment of its risk of extinction", "It has fully recovered from an earlier threatened status", "It has never been considered for assessment at all"], correctindex: 1, difficulty: "medium", topic: "IUCN Red List" },

  // ---------- In-situ Conservation: Protected Areas ----------
  { id: 54, question: "Protecting an entire ecosystem, along with all of its constituent species, within its natural habitat is called:", options: ["Ex-situ conservation", "In-situ conservation", "Cryopreservation", "Captive breeding"], correctindex: 1, difficulty: "easy", topic: "In-situ Conservation" },
  { id: 55, question: "Which of the following is an example of an in-situ conservation strategy?", options: ["Zoological park", "Seed bank", "Biosphere reserve", "Botanical garden"], correctindex: 2, difficulty: "easy", topic: "In-situ Conservation" },
  { id: 56, question: "National Parks, Wildlife Sanctuaries, and Biosphere Reserves in India are protected areas designated primarily for:", options: ["Commercial timber extraction", "In-situ conservation of biodiversity", "Ex-situ conservation exclusively", "Urban and industrial development"], correctindex: 1, difficulty: "easy", topic: "In-situ Conservation" },
  { id: 57, question: "Compared to a wildlife sanctuary, a national park is generally characterised by:", options: ["Fewer restrictions on human activity within its boundaries", "No provision for private land ownership and stricter overall protection", "The complete absence of any legal protection", "Being used exclusively for ex-situ breeding"], correctindex: 1, difficulty: "medium", topic: "In-situ Conservation" },
  { id: 58, question: "Which of the following best distinguishes a Biosphere Reserve from a National Park?", options: ["Biosphere reserves lack any protected core zone", "Biosphere reserves are large protected areas that also integrate sustainable resource use by local communities in buffer/transition zones", "National parks are always geographically larger than biosphere reserves", "There is no real difference between the two"], correctindex: 1, difficulty: "hard", topic: "In-situ Conservation" },
  { id: 59, question: "Protected areas such as national parks and sanctuaries primarily serve to:", options: ["Promote tourism only, with no ecological role", "Conserve biodiversity while maintaining important ecological processes", "Support only scientific research with no conservation value", "Facilitate commercial logging operations"], correctindex: 1, difficulty: "medium", topic: "In-situ Conservation" },
  { id: 60, question: "One of the major ongoing threats that protected areas face from surrounding human settlements is:", options: ["Excessive rainfall", "Encroachment, poaching, and grazing pressure", "Volcanic eruptions", "Ozone layer depletion"], correctindex: 1, difficulty: "medium", topic: "In-situ Conservation" },
  { id: 61, question: "Which Indian protected area is particularly well known for the conservation of the one-horned rhinoceros?", options: ["Gir National Park", "Kaziranga National Park", "Corbett National Park", "Bandipur National Park"], correctindex: 1, difficulty: "easy", topic: "In-situ Conservation" },
  { id: 62, question: "Gir National Park in Gujarat is of special conservation significance for protecting the last wild population of the:", options: ["Asiatic lion", "Bengal tiger", "Snow leopard", "Indian rhinoceros"], correctindex: 0, difficulty: "easy", topic: "In-situ Conservation" },
  { id: 63, question: "The overall network of protected areas (national parks, sanctuaries, and biosphere reserves) in a country is intended to represent:", options: ["Only the most economically valuable forests", "As many distinct ecosystems and habitat types as possible within that country", "Only marine ecosystems", "Only areas with no human settlement nearby"], correctindex: 1, difficulty: "medium", topic: "In-situ Conservation" },

  // ---------- Biodiversity Hotspots ----------
  { id: 64, question: "The concept of 'biodiversity hotspots', used to prioritise regions for conservation, was proposed by:", options: ["Robert May", "Norman Myers", "Edward Wilson", "Paul Ehrlich"], correctindex: 1, difficulty: "medium", topic: "Biodiversity Hotspots" },
  { id: 65, question: "A region qualifies as a biodiversity hotspot mainly on the basis of two criteria: extraordinary levels of plant endemism and:", options: ["Consistently high annual rainfall", "Serious threat from habitat loss, typically 70% or more loss of original habitat", "A very low human population density", "Location at a high latitude"], correctindex: 1, difficulty: "hard", topic: "Biodiversity Hotspots" },
  { id: 66, question: "Originally, how many biodiversity hotspots were identified worldwide, a number that was later revised upward as more regions were assessed?", options: ["9", "25", "50", "100"], correctindex: 1, difficulty: "medium", topic: "Biodiversity Hotspots" },
  { id: 67, question: "Although biodiversity hotspots together cover less than 2% of the earth's land area, they are estimated to harbour about what proportion of the world's endemic plant species?", options: ["10%", "30%", "50%", "90%"], correctindex: 2, difficulty: "hard", topic: "Biodiversity Hotspots" },
  { id: 68, question: "Which of the following is a globally recognised biodiversity hotspot located partly within India?", options: ["Sahara-Sahel region", "Western Ghats and Sri Lanka", "Amazonia", "Congo Basin"], correctindex: 1, difficulty: "easy", topic: "Biodiversity Hotspots" },
  { id: 69, question: "Apart from the Western Ghats, which other Indian region is recognised internationally as part of a biodiversity hotspot owing to its exceptionally high endemism?", options: ["Thar Desert", "Indo-Gangetic Plains", "Eastern Himalaya / Indo-Burma region", "Deccan Plateau"], correctindex: 2, difficulty: "medium", topic: "Biodiversity Hotspots" },
  { id: 70, question: "Focusing conservation efforts on biodiversity hotspots is considered a cost-effective strategy because it offers a way to:", options: ["Maximise short-term economic exploitation of resources", "Prevent the greatest number of species extinctions per unit of conservation investment", "Increase habitat fragmentation deliberately", "Eliminate all invasive species worldwide at once"], correctindex: 1, difficulty: "hard", topic: "Biodiversity Hotspots" },

  // ---------- Sacred Groves ----------
  { id: 71, question: "Patches of forest set aside and protected by local communities purely on the basis of religious and cultural traditions, without any formal legal backing, are called:", options: ["Biosphere reserves", "Sacred groves", "Botanical gardens", "National parks"], correctindex: 1, difficulty: "easy", topic: "Sacred Groves" },
  { id: 72, question: "Sacred groves, which help conserve many rare and threatened species in India, are notably found in regions such as the Khasi and Jaintia Hills of Meghalaya and parts of:", options: ["The Western Ghats of Karnataka and Maharashtra", "The Thar Desert exclusively", "The Gangetic plains exclusively", "The high-altitude Himalayan snowline"], correctindex: 0, difficulty: "medium", topic: "Sacred Groves" },
  { id: 73, question: "The traditional practice of protecting sacred groves is best classified as a form of:", options: ["Ex-situ conservation", "Community-based, culturally-driven in-situ conservation", "Cryopreservation", "Zoo-based captive breeding"], correctindex: 1, difficulty: "medium", topic: "Sacred Groves" },

  // ---------- Ex-situ Conservation ----------
  { id: 74, question: "Conserving threatened species by removing individuals from their natural habitat and maintaining them under human care, such as in zoos or botanical gardens, is termed:", options: ["In-situ conservation", "Ex-situ conservation", "Bioremediation", "Afforestation"], correctindex: 1, difficulty: "easy", topic: "Ex-situ Conservation" },
  { id: 75, question: "The long-term storage of seeds of various crop varieties and their wild relatives, at low temperature for possible future use, is an ex-situ method known as:", options: ["Cryopreservation of gametes", "Seed banking", "In vitro fertilisation", "Tissue culture propagation"], correctindex: 1, difficulty: "medium", topic: "Ex-situ Conservation" },
  { id: 76, question: "Preserving the gametes of threatened plant and animal species in a viable and fertile condition for extended periods, by storing them at very low temperatures, is called:", options: ["Seed banking", "Cryopreservation", "Herbarium storage", "Captive breeding"], correctindex: 1, difficulty: "medium", topic: "Ex-situ Conservation" },
  { id: 77, question: "Beyond public display, modern zoological parks contribute significantly to biodiversity conservation through:", options: ["Captive breeding and, where possible, reintroduction programmes for endangered species", "Entertainment for visitors alone, with no conservation role", "Studies focused solely on habitat destruction", "Commercial trade in wild-caught animals"], correctindex: 0, difficulty: "medium", topic: "Ex-situ Conservation" },
  { id: 78, question: "The propagation of endangered plant species outside their natural habitat using tissue culture techniques is an example of:", options: ["In vitro propagation as an ex-situ method", "Sacred grove protection", "Biosphere reserve zoning", "Wildlife corridor creation"], correctindex: 0, difficulty: "medium", topic: "Ex-situ Conservation" },

  // ---------- International Efforts / Mixed ----------
  { id: 79, question: "The 'Earth Summit' held in 1992, which called for global measures to conserve biological diversity and to sustainably utilise its benefits, took place in:", options: ["Kyoto", "Rio de Janeiro", "Johannesburg", "Nagoya"], correctindex: 1, difficulty: "medium", topic: "International Efforts" },
  { id: 80, question: "Assertion: All 190-plus countries that pledged action at the World Summit on Sustainable Development (Johannesburg, 2002) committed to immediately bringing global biodiversity loss down to zero.\nReason: The actual 2002 pledge committed nations only to significantly reduce, not eliminate, the rate of biodiversity loss by the year 2010.\nChoose the correct option:", options: ["Both assertion and reason are true, and the reason correctly explains the assertion", "The assertion is false; the pledge was only to reduce (not eliminate) the rate of loss by 2010, as the reason correctly states", "Both the assertion and the reason are false", "The assertion is true, but the reason is unrelated to it"], correctindex: 1, difficulty: "hard", topic: "International Efforts" },

];

export default questions;