import type { Question } from "@/lib/questionbank";

// NEET Biology Question Bank
// Chapter: Molecular Basis of Inheritance
// 80 MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctindex (index 0-3), difficulty, topic }
// Note: correctindex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questionss: Question[] = [

  // ---------- DNA Structure ----------
  { id: 1, question: "According to the Watson-Crick model, DNA exists as a:", options: ["Right-handed double helix", "Single-stranded linear molecule", "Left-handed triple helix", "Circular single strand only"], correctindex: 0, difficulty: "easy", topic: "DNA Structure" },
  { id: 2, question: "A nucleotide, the basic structural unit of DNA, is composed of a nitrogenous base, a pentose sugar, and a:", options: ["Fatty acid", "Amino acid", "Phosphate group", "Glycerol molecule"], correctindex: 2, difficulty: "easy", topic: "DNA Structure" },
  { id: 3, question: "The two strands of the DNA double helix are held together by hydrogen bonds formed between complementary nitrogenous bases, with adenine always pairing with:", options: ["Guanine", "Thymine", "Cytosine", "Another adenine"], correctindex: 1, difficulty: "easy", topic: "DNA Structure" },
  { id: 4, question: "In the DNA double helix, guanine always forms a complementary base pair with:", options: ["Adenine", "Thymine", "Another guanine", "Cytosine"], correctindex: 3, difficulty: "easy", topic: "DNA Structure" },
  { id: 5, question: "Adenine and thymine are held together by how many hydrogen bonds in a DNA double helix?", options: ["Three", "Two", "One", "Four"], correctindex: 1, difficulty: "medium", topic: "DNA Structure" },
  { id: 6, question: "Guanine and cytosine are held together by how many hydrogen bonds in a DNA double helix?", options: ["Three", "Two", "One", "Four"], correctindex: 0, difficulty: "medium", topic: "DNA Structure" },
  { id: 7, question: "The two strands of a DNA double helix run in opposite chemical directions, a structural arrangement described as:", options: ["Parallel", "Perpendicular", "Antiparallel", "Coiled coil"], correctindex: 2, difficulty: "medium", topic: "DNA Structure" },
  { id: 8, question: "According to the Watson-Crick model, one complete turn of the DNA double helix spans approximately how many base pairs?", options: ["5", "20", "10", "34"], correctindex: 2, difficulty: "medium", topic: "DNA Structure" },
  { id: 9, question: "The pitch (length of one complete turn) of the DNA double helix, as described by Watson and Crick, is approximately:", options: ["10 Å", "3.4 Å", "20 Å", "34 Å"], correctindex: 3, difficulty: "hard", topic: "DNA Structure" },
  { id: 10, question: "The distance between two successive base pairs (rise per base pair) along the DNA helix axis is approximately:", options: ["3.4 Å", "34 Å", "10 Å", "0.34 Å"], correctindex: 0, difficulty: "hard", topic: "DNA Structure" },
  { id: 11, question: "In a DNA molecule, the two polynucleotide chains are coiled around a common axis in a right-handed manner, with the backbone formed by alternating:", options: ["Nitrogenous bases and hydrogen bonds", "Sugar and phosphate groups", "Amino acids linked by peptide bonds", "Fatty acid chains"], correctindex: 1, difficulty: "easy", topic: "DNA Structure" },
  { id: 12, question: "According to Chargaff's rule, in a double-stranded DNA molecule, the amount of adenine is generally equal to the amount of:", options: ["Guanine", "Thymine", "Cytosine", "Uracil"], correctindex: 1, difficulty: "medium", topic: "DNA Structure" },

  // ---------- DNA Packaging ----------
  { id: 13, question: "In a eukaryotic cell, the negatively charged DNA is wrapped around a positively charged protein core to help package it efficiently within the nucleus. This protein core is composed of:", options: ["Histone proteins", "Ribosomal proteins", "Actin filaments", "Tubulin subunits"], correctindex: 0, difficulty: "easy", topic: "DNA Packaging" },
  { id: 14, question: "A unit of DNA packaging in eukaryotes, consisting of DNA wrapped around a histone protein core, is called a:", options: ["Chromatid", "Centromere", "Ribosome", "Nucleosome"], correctindex: 3, difficulty: "easy", topic: "DNA Packaging" },
  { id: 15, question: "A typical nucleosome core is formed by DNA wrapped around a histone octamer, which is composed of two molecules each of the histone proteins:", options: ["H1 only", "H2A, H2B, H3, and H4", "Only H3 and H4", "Only H1 and H2A"], correctindex: 1, difficulty: "medium", topic: "DNA Packaging" },
  { id: 16, question: "The histone protein 'H1' plays a role distinct from the core histones (H2A, H2B, H3, H4) in chromatin packaging by:", options: ["Forming the nucleosome core itself", "Having no role in chromatin structure at all", "Binding to the linker DNA between adjacent nucleosomes, helping to further condense chromatin", "Acting solely as an enzyme that degrades DNA"], correctindex: 2, difficulty: "medium", topic: "DNA Packaging" },
  { id: 17, question: "Densely packed, transcriptionally largely inactive regions of chromatin, which stain darkly, are called:", options: ["Euchromatin", "Heterochromatin", "Nucleosomes exclusively", "Histones"], correctindex: 1, difficulty: "medium", topic: "DNA Packaging" },
  { id: 18, question: "Loosely packed chromatin regions, which stain lightly and are generally transcriptionally more active, are called:", options: ["Euchromatin", "Heterochromatin", "Nucleosomes exclusively", "Centromeres"], correctindex: 0, difficulty: "medium", topic: "DNA Packaging" },

  // ---------- Search for Genetic Material ----------
  { id: 19, question: "Frederick Griffith's 1928 experiment on Streptococcus pneumoniae, involving live non-virulent (R strain) bacteria and heat-killed virulent (S strain) bacteria, provided the first evidence for a phenomenon he called:", options: ["Semi-conservative replication", "Reverse transcription", "The genetic code", "Transformation"], correctindex: 3, difficulty: "easy", topic: "Search for Genetic Material" },
  { id: 20, question: "In Griffith's transformation experiment, when live R-strain bacteria were mixed with heat-killed S-strain bacteria and injected into mice, the mice died, and the researchers subsequently recovered living, virulent:", options: ["S-strain bacteria", "R-strain bacteria only", "A completely new bacterial species", "No bacteria at all"], correctindex: 0, difficulty: "medium", topic: "Search for Genetic Material" },
  { id: 21, question: "Griffith concluded that some 'transforming principle' from the heat-killed S-strain bacteria had genetically transformed the harmless R-strain bacteria into a virulent form, though he did not identify the chemical nature of this principle. This was later identified as:", options: ["DNA", "RNA exclusively", "A specific protein", "A lipid molecule"], correctindex: 0, difficulty: "medium", topic: "Search for Genetic Material" },
  { id: 22, question: "The 1944 experiment by Avery, MacLeod, and McCarty, which built on Griffith's work, specifically aimed to determine the biochemical identity of the transforming principle by:", options: ["Directly sequencing bacterial DNA using modern methods", "Injecting mice with purified histone proteins", "Purifying DNA, RNA, and proteins separately from S-strain bacteria and testing which fraction could transform R-strain bacteria", "Studying the transformation process only in viruses, not bacteria"], correctindex: 2, difficulty: "medium", topic: "Search for Genetic Material" },
  { id: 23, question: "In the Avery, MacLeod, and McCarty experiment, treatment with which specific enzyme helped demonstrate that DNA, and not protein or RNA, was the transforming principle?", options: ["Trypsin and chymotrypsin (protein-digesting enzymes) alone", "DNase (which digests DNA specifically), alongside protease and RNase controls", "Only RNase, with no other enzymes used", "Restriction endonucleases exclusively"], correctindex: 1, difficulty: "medium", topic: "Search for Genetic Material" },
  { id: 24, question: "The classic 1952 experiment that provided definitive proof that DNA, not protein, is the genetic material was performed by Alfred Hershey and Martha Chase using:", options: ["Streptococcus pneumoniae bacteria", "Purified human chromosomes", "Fruit flies (Drosophila melanogaster)", "Bacteriophages that infect bacteria"], correctindex: 3, difficulty: "easy", topic: "Search for Genetic Material" },
  { id: 25, question: "In the Hershey-Chase experiment, bacteriophage DNA and protein coats were separately labelled with radioactive isotopes: phosphorus-32 was used to label the DNA, while sulfur-35 was used to label:", options: ["Also the DNA, as a control", "The protein coat", "The bacterial cell wall", "Ribosomal RNA"], correctindex: 1, difficulty: "medium", topic: "Search for Genetic Material" },
  { id: 26, question: "In the Hershey-Chase experiment, after infection and subsequent blending/centrifugation to separate phage particles from bacterial cells, radioactivity was found primarily:", options: ["Inside the bacterial cells, associated with the phosphorus-32 label (i.e. the DNA), confirming DNA as the genetic material", "Only outside the bacterial cells, associated with sulfur-35", "Equally distributed between DNA and protein, with no clear pattern", "Nowhere at all; no radioactivity was detected"], correctindex: 0, difficulty: "medium", topic: "Search for Genetic Material" },
  { id: 27, question: "The Hershey-Chase experiment demonstrated that only the ___ of the bacteriophage enters the host bacterial cell during infection, while the protein coat remains outside.", options: ["Ribosomes", "Cell wall", "DNA", "Entire virus particle, including the protein coat"], correctindex: 2, difficulty: "easy", topic: "Search for Genetic Material" },
  { id: 28, question: "Collectively, the work of Griffith, Avery-MacLeod-McCarty, and Hershey-Chase established that the hereditary genetic material in most organisms is:", options: ["Protein", "Lipid", "DNA", "Carbohydrate"], correctindex: 2, difficulty: "easy", topic: "Search for Genetic Material" },

  // ---------- DNA Replication ----------
  { id: 29, question: "The mechanism of DNA replication, in which each of the two parental strands serves as a template for the synthesis of a new complementary strand, resulting in two daughter DNA molecules each containing one old and one new strand, is called:", options: ["Conservative replication", "Dispersive replication", "Random replication", "Semi-conservative replication"], correctindex: 3, difficulty: "easy", topic: "DNA Replication" },
  { id: 30, question: "The classic experiment that experimentally confirmed the semi-conservative mode of DNA replication, using the heavy isotope of nitrogen (15N) to label DNA and track it across generations of E. coli, was performed by:", options: ["Meselson and Stahl", "Griffith and Avery", "Hershey and Chase", "Watson and Crick"], correctindex: 0, difficulty: "easy", topic: "DNA Replication" },
  { id: 31, question: "In the Meselson-Stahl experiment, bacteria were initially grown in a medium containing the heavy nitrogen isotope 15N, and then shifted to normal 14N medium. After one round of replication, the DNA was found to have a density:", options: ["Identical to fully heavy (15N/15N) DNA", "Intermediate between fully heavy and fully light DNA", "Identical to fully light (14N/14N) DNA", "Impossible to measure using their method"], correctindex: 1, difficulty: "medium", topic: "DNA Replication" },
  { id: 32, question: "The specific site on a DNA molecule where the process of replication begins is called the:", options: ["Terminator", "Origin of replication", "Promoter", "Operator"], correctindex: 1, difficulty: "medium", topic: "DNA Replication" },
  { id: 33, question: "During DNA replication, the enzyme primarily responsible for catalysing the synthesis of the new complementary DNA strand is:", options: ["DNA polymerase", "RNA polymerase", "DNA ligase exclusively", "Reverse transcriptase"], correctindex: 0, difficulty: "easy", topic: "DNA Replication" },
  { id: 34, question: "DNA polymerase enzymes can synthesise a new DNA strand only in one specific direction relative to the template, namely:", options: ["3' to 5' exclusively", "In either direction with equal efficiency", "Randomly, in no fixed direction", "5' to 3'"], correctindex: 3, difficulty: "medium", topic: "DNA Replication" },
  { id: 35, question: "Because DNA polymerase can only synthesise DNA in the 5' to 3' direction, one of the two new strands, synthesised discontinuously in short fragments, is called the:", options: ["Leading strand", "Lagging strand", "Template strand exclusively", "Coding strand exclusively"], correctindex: 1, difficulty: "medium", topic: "DNA Replication" },
  { id: 36, question: "The short, discontinuous DNA fragments synthesised on the lagging strand during replication are called:", options: ["Nucleosomes", "Anticodons", "Okazaki fragments", "Ribozymes"], correctindex: 2, difficulty: "medium", topic: "DNA Replication" },
  { id: 37, question: "The enzyme responsible for joining the Okazaki fragments together into a continuous DNA strand during replication is:", options: ["DNA polymerase exclusively", "DNA ligase", "RNA polymerase", "Helicase alone"], correctindex: 1, difficulty: "medium", topic: "DNA Replication" },
  { id: 38, question: "DNA polymerase enzymes generally cannot initiate DNA synthesis on their own from scratch and require a short pre-existing segment to extend, called a(n):", options: ["RNA primer", "Okazaki fragment exclusively", "Anticodon", "Terminator sequence"], correctindex: 0, difficulty: "medium", topic: "DNA Replication" },

  // ---------- Central Dogma and Transcription ----------
  { id: 39, question: "The overall directional flow of genetic information in most living cells, expressed as DNA → RNA → Protein, is known as the:", options: ["Semi-conservative principle", "Wobble hypothesis", "Central tenet of genetics", "Central Dogma of Molecular Biology"], correctindex: 3, difficulty: "easy", topic: "Central Dogma and Transcription" },
  { id: 40, question: "In certain viruses, such as retroviruses, genetic information can flow in the reverse direction, from RNA to DNA, a process called:", options: ["Reverse transcription", "Translation", "Replication", "Transformation"], correctindex: 0, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 41, question: "The overall process by which the genetic information encoded in a DNA sequence is copied into a complementary RNA molecule is called:", options: ["Transcription", "Translation", "Replication", "Transformation"], correctindex: 0, difficulty: "easy", topic: "Central Dogma and Transcription" },
  { id: 42, question: "The enzyme responsible for catalysing RNA synthesis during transcription in prokaryotes is:", options: ["DNA polymerase", "Reverse transcriptase", "RNA polymerase", "DNA ligase"], correctindex: 2, difficulty: "easy", topic: "Central Dogma and Transcription" },
  { id: 43, question: "The specific DNA sequence to which RNA polymerase binds in order to initiate transcription is called the:", options: ["Terminator", "Promoter", "Operator", "Anticodon"], correctindex: 1, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 44, question: "In a DNA molecule undergoing transcription, the strand that serves as the template for RNA synthesis is called the:", options: ["Coding strand", "Sense strand", "Leading strand", "Template strand"], correctindex: 3, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 45, question: "The DNA strand that has the same base sequence as the newly synthesised RNA (except that thymine is replaced by uracil) is called the:", options: ["Template strand", "Coding (sense) strand", "Anticodon strand", "Lagging strand"], correctindex: 1, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 46, question: "In eukaryotes, the primary RNA transcript synthesised directly from DNA, before any processing, is referred to as:", options: ["Heterogeneous nuclear RNA (hnRNA)", "Mature mRNA", "tRNA", "rRNA exclusively"], correctindex: 0, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 47, question: "The process by which non-coding sequences (introns) are removed from hnRNA, and coding sequences (exons) are joined together to form mature mRNA, is called:", options: ["Capping", "Tailing", "Splicing", "Transformation"], correctindex: 2, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 48, question: "The addition of a methylated guanosine cap at the 5' end of the hnRNA molecule, part of eukaryotic RNA processing, is called:", options: ["Tailing", "Splicing", "Capping", "Termination"], correctindex: 2, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 49, question: "The addition of a stretch of adenine residues (a poly-A tail) at the 3' end of the hnRNA molecule, part of eukaryotic RNA processing, is called:", options: ["Capping", "Splicing", "Initiation", "Tailing"], correctindex: 3, difficulty: "medium", topic: "Central Dogma and Transcription" },
  { id: 50, question: "The coding sequences of a eukaryotic gene, which are retained in the mature mRNA after processing, are called:", options: ["Exons", "Introns", "Promoters", "Operators"], correctindex: 0, difficulty: "medium", topic: "Central Dogma and Transcription" },

  // ---------- Genetic Code ----------
  { id: 51, question: "The genetic code, which specifies the correspondence between nucleotide sequences in mRNA and amino acid sequences in proteins, is fundamentally based on groups of how many consecutive nucleotides (a codon) coding for one amino acid?", options: ["Two", "Three", "Four", "One"], correctindex: 1, difficulty: "easy", topic: "Genetic Code" },
  { id: 52, question: "Out of the total 64 possible codons in the genetic code, how many actually code for specific amino acids (sense codons)?", options: ["64", "61", "20", "3"], correctindex: 1, difficulty: "medium", topic: "Genetic Code" },
  { id: 53, question: "The three codons that do not code for any amino acid and instead signal the termination of translation are collectively called:", options: ["Stop (nonsense/termination) codons", "Start codons exclusively", "Silent codons", "Wobble codons"], correctindex: 0, difficulty: "easy", topic: "Genetic Code" },
  { id: 54, question: "The codon that signals the start of translation, and also codes for the amino acid methionine in eukaryotes, is:", options: ["UAA", "UGA", "UAG", "AUG"], correctindex: 3, difficulty: "easy", topic: "Genetic Code" },
  { id: 55, question: "The property of the genetic code whereby a single amino acid can be specified by more than one codon is called:", options: ["Universality", "Degeneracy", "Ambiguity", "Punctuation"], correctindex: 1, difficulty: "medium", topic: "Genetic Code" },
  { id: 56, question: "The genetic code is said to be largely 'universal' because, with a few minor exceptions, it is used in the same way across:", options: ["Only bacterial species", "Only human cells", "Nearly all living organisms, from bacteria to humans", "Only plant species"], correctindex: 2, difficulty: "easy", topic: "Genetic Code" },
  { id: 57, question: "The genetic code is described as being 'unambiguous' because each specific codon codes for:", options: ["Multiple different amino acids simultaneously", "Only one specific amino acid", "No amino acid at all", "A random amino acid each time it appears"], correctindex: 1, difficulty: "medium", topic: "Genetic Code" },
  { id: 58, question: "The genetic code is read in a continuous, non-overlapping fashion starting from a fixed point, a property referred to as the code being:", options: ["Read as a continuous, comma-less (non-overlapping) sequence", "Read backward from the 3' end", "Read in overlapping triplets", "Read discontinuously with large gaps between codons"], correctindex: 0, difficulty: "medium", topic: "Genetic Code" },

  // ---------- tRNA and Translation ----------
  { id: 59, question: "Transfer RNA (tRNA), which carries specific amino acids to the ribosome during translation, has a characteristic secondary structure resembling a:", options: ["Straight, linear chain", "Double helix identical to DNA", "Simple circular loop", "Cloverleaf"], correctindex: 3, difficulty: "easy", topic: "tRNA and Translation" },
  { id: 60, question: "The three-nucleotide sequence on a tRNA molecule that base-pairs with a complementary codon on the mRNA during translation is called the:", options: ["Anticodon", "Promoter", "Operator", "Terminator"], correctindex: 0, difficulty: "easy", topic: "tRNA and Translation" },
  { id: 61, question: "The cellular organelle/complex where translation, i.e. the synthesis of a polypeptide chain from an mRNA template, actually takes place is the:", options: ["Ribosome", "Golgi apparatus", "Lysosome", "Mitochondrion exclusively"], correctindex: 0, difficulty: "easy", topic: "tRNA and Translation" },
  { id: 62, question: "During translation, the covalent bond formed between two adjacent amino acids in the growing polypeptide chain is called a:", options: ["Hydrogen bond", "Glycosidic bond", "Peptide bond", "Phosphodiester bond"], correctindex: 2, difficulty: "easy", topic: "tRNA and Translation" },
  { id: 63, question: "The process of translation is generally divided into three main stages: initiation, elongation, and:", options: ["Replication", "Termination", "Transformation", "Splicing"], correctindex: 1, difficulty: "medium", topic: "tRNA and Translation" },
  { id: 64, question: "Translation is terminated when the ribosome encounters a stop codon on the mRNA, at which point a release factor helps to release the completed:", options: ["tRNA molecule alone", "mRNA molecule alone", "Ribosomal subunits alone, with no polypeptide involved", "Polypeptide chain from the ribosome"], correctindex: 3, difficulty: "medium", topic: "tRNA and Translation" },

  // ---------- Gene Regulation: The Lac Operon ----------
  { id: 65, question: "The lac operon, a classic model system for understanding gene regulation in bacteria, was first proposed by which two French scientists?", options: ["Watson and Crick", "Jacob and Monod", "Griffith and Avery", "Meselson and Stahl"], correctindex: 1, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },
  { id: 66, question: "The lac operon in E. coli contains structural genes that code for enzymes involved in the metabolism of:", options: ["Lactose", "Glucose exclusively", "Fatty acids exclusively", "Amino acids exclusively"], correctindex: 0, difficulty: "easy", topic: "Gene Regulation: The Lac Operon" },
  { id: 67, question: "The lac operon consists of a regulatory gene (i), a promoter, an operator, and three structural genes, commonly referred to as:", options: ["x, y, z", "a, b, c", "z, y, a", "p, q, r"], correctindex: 2, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },
  { id: 68, question: "In the lac operon system, the protein product of the regulatory gene (i) is a repressor protein that, in the absence of lactose, binds to the:", options: ["Promoter, preventing RNA polymerase from binding at all", "Structural genes directly, degrading their DNA", "Operator region, physically blocking transcription of the structural genes", "Ribosome, preventing translation"], correctindex: 2, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },
  { id: 69, question: "When lactose is present in the environment, it is converted into an inducer molecule (allolactose) that binds to the repressor protein, causing it to:", options: ["Bind more tightly to the operator", "Have no effect on the repressor at all", "Migrate to a different part of the cell", "Change shape and detach from the operator, thereby allowing transcription of the structural genes to proceed"], correctindex: 3, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },
  { id: 70, question: "The lac operon is described as an 'inducible' operon because its structural genes are normally switched off and are only activated (transcribed) in the presence of:", options: ["The inducer molecule (allolactose, derived from lactose)", "Glucose exclusively", "Any random external chemical", "Ultraviolet radiation"], correctindex: 0, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },
  { id: 71, question: "Once transcribed and translated, one of the lac operon's structural gene products, β-galactosidase, functions to:", options: ["Synthesise new lactose molecules", "Hydrolyse lactose into glucose and galactose", "Repress the lac operon", "Act as an RNA polymerase"], correctindex: 1, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },
  { id: 72, question: "The lac operon model of gene regulation demonstrates that gene expression in bacteria can be efficiently regulated at the level of:", options: ["Protein degradation exclusively", "Transcription, turning specific genes on or off as needed", "DNA replication exclusively", "Random chance, with no regulatory mechanism at all"], correctindex: 1, difficulty: "medium", topic: "Gene Regulation: The Lac Operon" },

  // ---------- Human Genome Project and DNA Fingerprinting ----------
  { id: 73, question: "The Human Genome Project, an international scientific research effort aimed at determining the complete sequence of human DNA, was declared complete in the year:", options: ["2003", "1990", "2015", "1953"], correctindex: 0, difficulty: "medium", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 74, question: "The total size of the human genome, as determined by the Human Genome Project, is estimated to be approximately:", options: ["3 million base pairs", "30,000 base pairs", "300 million base pairs", "3 billion base pairs"], correctindex: 3, difficulty: "medium", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 75, question: "According to the findings of the Human Genome Project, the human genome is estimated to contain approximately how many protein-coding genes?", options: ["100,000", "20,000 to 25,000", "1 million", "500"], correctindex: 1, difficulty: "hard", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 76, question: "One of the surprising findings of the Human Genome Project was that a very large proportion of the human genome (over 98%) does not code for any protein and was historically referred to as:", options: ["Exonic DNA", "Coding DNA exclusively", "Non-coding/'junk' DNA", "Structural genes"], correctindex: 2, difficulty: "medium", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 77, question: "DNA fingerprinting, a technique used to identify differences between individuals based on unique patterns in their DNA, particularly exploits variation in the number of repeats of short DNA sequences known as:", options: ["Exons", "Variable Number of Tandem Repeats (VNTRs), or satellite DNA", "Promoters", "Anticodons"], correctindex: 1, difficulty: "medium", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 78, question: "The technique of DNA fingerprinting was originally developed by:", options: ["Alec Jeffreys", "James Watson", "Francis Crick", "Frederick Griffith"], correctindex: 0, difficulty: "medium", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 79, question: "DNA fingerprinting has important applications in forensic science, mainly because the pattern of repetitive DNA sequences (VNTRs) is highly variable between individuals, making it useful for:", options: ["Diagnosing genetic diseases exclusively", "Sequencing the entire genome quickly", "Determining the complete protein-coding capacity of an individual", "Establishing individual identity, paternity testing, and criminal forensic investigations"], correctindex: 3, difficulty: "easy", topic: "Human Genome Project and DNA Fingerprinting" },
  { id: 80, question: "Since a child inherits half of their VNTR/satellite DNA banding pattern from each parent, DNA fingerprinting techniques are particularly useful for:", options: ["Paternity and maternity testing, by comparing banding patterns between parents and offspring", "Directly curing genetic diseases", "Replacing the need for DNA replication", "Eliminating the need for the Human Genome Project data"], correctindex: 0, difficulty: "medium", topic: "Human Genome Project and DNA Fingerprinting" },

];

export default questions;