import type { Question } from "@/lib/questionBank";

// NEET Biology Question Bank
// Chapter: Principles of Inheritance and Variation
// 80 MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctindex (index 0-3), difficulty, topic }
// Note: correctindex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Mendel's Experiments and Laws ----------
  { id: 'piv-1', question: "Gregor Mendel conducted his classic hybridization experiments primarily using which plant?", options: ["Garden pea (Pisum sativum)", "Maize", "Fruit fly (Drosophila)", "Tobacco plant"], correctindex: 0, difficulty: "easy", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-2', question: "Mendel chose the garden pea for his experiments largely because it showed several easily distinguishable, contrasting traits, referred to as:", options: ["Recessive traits only", "Codominant traits", "Contrasting/discrete characters", "Polygenic traits"], correctindex: 2, difficulty: "medium", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-3', question: "In a monohybrid cross between a true-breeding tall pea plant and a true-breeding dwarf pea plant, all the F1 offspring were:", options: ["Dwarf", "Tall", "Intermediate in height", "Half tall and half dwarf"], correctindex: 1, difficulty: "easy", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-4', question: "Mendel's Law of Dominance states that, in a heterozygous individual, one allele of a gene pair:", options: ["Blends completely with the other allele", "Has no effect on the phenotype", "Is expressed only in alternate generations", "Masks the expression of the other, recessive allele"], correctindex: 3, difficulty: "easy", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-5', question: "When Mendel self-pollinated the F1 tall plants (from a tall x dwarf cross), the F2 generation showed a phenotypic ratio of tall to dwarf plants of approximately:", options: ["1:1", "3:1", "9:3:3:1", "1:2:1"], correctindex: 1, difficulty: "easy", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-6', question: "The reappearance of the recessive dwarf trait in the F2 generation, after being completely masked in F1, led Mendel to propose his:", options: ["Law of Segregation", "Law of Independent Assortment", "Law of Dominance exclusively", "Chromosomal theory of inheritance"], correctindex: 0, difficulty: "medium", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-7', question: "Mendel's Law of Segregation states that the two alleles of a gene pair:", options: ["Always blend together in the gametes", "Are both always expressed simultaneously", "Separate from each other during gamete formation, so that each gamete receives only one allele", "Never separate under any circumstances"], correctindex: 2, difficulty: "easy", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-8', question: "Mendel's Law of Independent Assortment, deduced from his dihybrid crosses, states that when two pairs of traits are combined in a hybrid, the alleles of one gene pair segregate:", options: ["In a manner completely dependent on the segregation of the other gene pair", "Only when both genes are located on the same chromosome", "Independently of the alleles of the other gene pair", "Only in the F1 generation, never in F2"], correctindex: 2, difficulty: "medium", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-9', question: "In Mendel's classic dihybrid cross involving seed shape (round/wrinkled) and seed colour (yellow/green), the F2 generation showed a characteristic phenotypic ratio of:", options: ["3:1", "1:1", "1:2:1", "9:3:3:1"], correctindex: 3, difficulty: "easy", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-10', question: "A cross between an individual of unknown genotype (showing the dominant phenotype) and a homozygous recessive individual, used to determine whether the unknown individual is homozygous or heterozygous, is called a:", options: ["Test cross", "Back cross exclusively, with no other purpose", "Reciprocal cross", "Dihybrid cross exclusively"], correctindex: 0, difficulty: "medium", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-11', question: "A cross between an F1 hybrid and either of its parents is generally referred to as a:", options: ["Test cross exclusively", "Back cross", "Reciprocal cross exclusively", "Trihybrid cross"], correctindex: 1, difficulty: "medium", topic: "Mendel's Experiments and Laws" },
  { id: 'piv-12', question: "The set of alleles present at a given gene locus in an individual, without reference to the outward physical expression, is called the individual's:", options: ["Phenotype", "Genotype", "Karyotype", "Pedigree"], correctindex: 1, difficulty: "easy", topic: "Mendel's Experiments and Laws" },

  // ---------- Monohybrid and Dihybrid Crosses ----------
  { id: 'piv-13', question: "The observable physical or biochemical characteristics of an organism, resulting from the interaction of its genotype with the environment, are collectively called its:", options: ["Phenotype", "Genotype exclusively", "Karyotype", "Pedigree"], correctindex: 0, difficulty: "easy", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-14', question: "An individual possessing two identical alleles for a given gene (e.g. TT or tt) is described as being:", options: ["Heterozygous", "Hemizygous", "Polygenic", "Homozygous"], correctindex: 3, difficulty: "easy", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-15', question: "An individual possessing two different alleles for a given gene (e.g. Tt) is described as being:", options: ["Homozygous", "Heterozygous", "Hemizygous", "Polygenic"], correctindex: 1, difficulty: "easy", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-16', question: "A graphical, grid-based method commonly used to predict the possible genotypes and phenotypes of offspring from a given genetic cross is called a:", options: ["Pedigree chart", "Karyotype chart", "Punnett square", "Linkage map"], correctindex: 2, difficulty: "easy", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-17', question: "In a standard monohybrid cross between two heterozygous individuals (Tt x Tt), the expected genotypic ratio in the offspring is:", options: ["3:1", "1:2:1", "9:3:3:1", "1:1"], correctindex: 1, difficulty: "medium", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-18', question: "In a dihybrid cross between two individuals heterozygous for two independently assorting genes (e.g. RrYy x RrYy), the expected phenotypic ratio in the offspring, assuming complete dominance, is:", options: ["9:3:3:1", "3:1", "1:1:1:1", "1:2:1"], correctindex: 0, difficulty: "medium", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-19', question: "A test cross between a dihybrid individual (RrYy) and a double homozygous recessive individual (rryy) is expected to produce offspring in which genotypic and phenotypic ratio?", options: ["9:3:3:1", "3:1", "1:2:1", "1:1:1:1"], correctindex: 3, difficulty: "hard", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-20', question: "The physical location of a specific gene on a chromosome is referred to as its:", options: ["Locus", "Allele", "Genotype", "Phenotype"], correctindex: 0, difficulty: "easy", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-21', question: "Different forms of the same gene, occupying the same locus on homologous chromosomes but potentially producing different phenotypic effects, are called:", options: ["Alleles", "Loci", "Genotypes exclusively", "Karyotypes"], correctindex: 0, difficulty: "easy", topic: "Monohybrid and Dihybrid Crosses" },
  { id: 'piv-22', question: "The observation that F1 hybrids in Mendel's experiments consistently resembled one of the two parents (in terms of the dominant trait), while the recessive trait reappeared unaltered in F2, indicated that hereditary factors are:", options: ["Blended and never separated", "Permanently lost after F1", "Discrete, particulate units that retain their identity across generations", "Entirely dependent on environmental conditions"], correctindex: 2, difficulty: "medium", topic: "Monohybrid and Dihybrid Crosses" },

  // ---------- Incomplete Dominance, Codominance and Multiple Alleles ----------
  { id: 'piv-23', question: "In Mirabilis jalapa (the four o'clock plant), a cross between red-flowered and white-flowered plants produces F1 offspring with pink flowers, an intermediate phenotype. This is an example of:", options: ["Complete dominance", "Incomplete dominance", "Codominance", "Multiple allelism"], correctindex: 1, difficulty: "easy", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-24', question: "In cases of incomplete dominance, since the heterozygote shows a distinct, intermediate phenotype, the F2 phenotypic ratio typically becomes identical to the genotypic ratio of:", options: ["3:1", "9:3:3:1", "1:1", "1:2:1"], correctindex: 3, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-25', question: "Codominance is a phenomenon in which, unlike incomplete dominance, both alleles of a heterozygous individual are:", options: ["Completely masked, with neither being expressed", "Fully and independently expressed in the phenotype, with neither dominating the other", "Blended to form an intermediate phenotype", "Expressed only in alternating generations"], correctindex: 1, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-26', question: "The classic example of codominance discussed in the context of human genetics is the inheritance pattern of the:", options: ["ABO blood group system", "Rh blood group system exclusively", "Eye colour trait", "Height trait"], correctindex: 0, difficulty: "easy", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-27', question: "The ABO blood group system in humans is controlled by a single gene with three different alleles, IA, IB, and i, illustrating the phenomenon of:", options: ["Incomplete dominance exclusively", "Pleiotropy", "Multiple allelism", "Polygenic inheritance"], correctindex: 2, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-28', question: "In the ABO blood group system, an individual with the genotype IA IB expresses both A and B antigens on their red blood cells simultaneously, illustrating:", options: ["Incomplete dominance", "Pleiotropy", "Codominance between the IA and IB alleles", "Polygenic inheritance"], correctindex: 2, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-29', question: "In the ABO blood group system, the allele 'i' (responsible for blood group O) is:", options: ["Codominant with both IA and IB", "Dominant over both IA and IB", "Dominant over IA but recessive to IB", "Recessive to both IA and IB"], correctindex: 3, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-30', question: "Although the ABO gene has three alleles (IA, IB, i) at the population level, illustrating multiple allelism, any single individual can carry at most:", options: ["Two of these three alleles", "All three alleles simultaneously", "Only one allele, with no exceptions", "Four alleles"], correctindex: 0, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-31', question: "The concept of 'multiple alleles' refers to a situation in which a single gene locus has:", options: ["Only two possible allelic forms, with no exceptions", "More than two allelic forms within a population, though any individual carries only two of them", "No allelic variation at all", "A completely different structure in every individual"], correctindex: 1, difficulty: "medium", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },
  { id: 'piv-32', question: "Which of the following best distinguishes multiple allelism from codominance?", options: ["They are identical concepts with no distinction", "Multiple allelism refers to the existence of more than two alleles for a gene at the population level, while codominance refers to the simultaneous expression of two alleles in a single heterozygous individual", "Multiple allelism only applies to plants; codominance only applies to animals", "Codominance requires exactly three alleles at a locus"], correctindex: 1, difficulty: "hard", topic: "Incomplete Dominance, Codominance and Multiple Alleles" },

  // ---------- Pleiotropy and Polygenic Inheritance ----------
  { id: 'piv-33', question: "A single gene that influences multiple, seemingly unrelated phenotypic traits simultaneously is said to exhibit:", options: ["Pleiotropy", "Codominance", "Incomplete dominance", "Multiple allelism"], correctindex: 0, difficulty: "medium", topic: "Pleiotropy and Polygenic Inheritance" },
  { id: 'piv-34', question: "The genetic disorder phenylketonuria (PKU) in humans, in which a single mutated gene affects the level of phenylalanine, causing multiple symptoms including mental retardation and pigmentation defects, is often cited as a classic example of:", options: ["Codominance", "Incomplete dominance", "Multiple allelism", "Pleiotropy"], correctindex: 3, difficulty: "medium", topic: "Pleiotropy and Polygenic Inheritance" },
  { id: 'piv-35', question: "Traits controlled by the combined, additive effect of multiple genes, rather than a single gene, are said to show:", options: ["Pleiotropy", "Polygenic inheritance", "Codominance", "Multiple allelism"], correctindex: 1, difficulty: "easy", topic: "Pleiotropy and Polygenic Inheritance" },
  { id: 'piv-36', question: "Human skin colour, which shows a continuous range of variation rather than a small number of discrete categories, is a classic example of a trait controlled by:", options: ["A single gene with complete dominance", "A single gene with codominance", "Polygenic inheritance, involving the additive effects of multiple genes", "A single sex-linked gene"], correctindex: 2, difficulty: "medium", topic: "Pleiotropy and Polygenic Inheritance" },
  { id: 'piv-37', question: "Polygenic traits, unlike simple Mendelian traits, are typically characterised by:", options: ["Sharp, discrete phenotypic categories with no intermediate forms", "A continuous range of phenotypic variation influenced by multiple genes and often the environment", "Complete independence from environmental influence", "Being controlled by a single dominant allele"], correctindex: 1, difficulty: "medium", topic: "Pleiotropy and Polygenic Inheritance" },
  { id: 'piv-38', question: "The additive contribution of multiple genes to a single polygenic trait means that the overall phenotype often follows approximately a:", options: ["Bell-shaped (normal) distribution curve within a population", "Strict 3:1 ratio", "Strict 9:3:3:1 ratio", "All-or-nothing binary pattern"], correctindex: 0, difficulty: "medium", topic: "Pleiotropy and Polygenic Inheritance" },

  // ---------- Chromosomal Theory and Linkage ----------
  { id: 'piv-39', question: "The Chromosomal Theory of Inheritance, proposing that genes are located on chromosomes, was independently put forward by:", options: ["Mendel alone", "Watson and Crick", "Griffith and Avery", "Sutton and Boveri"], correctindex: 3, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-40', question: "The Chromosomal Theory of Inheritance was experimentally validated through detailed studies on the fruit fly (Drosophila melanogaster) conducted primarily by:", options: ["Thomas Hunt Morgan and his colleagues", "Gregor Mendel", "Alfred Hershey and Martha Chase", "Barbara McClintock exclusively"], correctindex: 0, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-41', question: "Genes that are located on the same chromosome and therefore tend to be inherited together, rather than assorting independently, are said to show:", options: ["Linkage", "Codominance", "Polygenic inheritance", "Multiple allelism"], correctindex: 0, difficulty: "easy", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-42', question: "Morgan's experiments on Drosophila found that genes located close together on the same chromosome showed a lower frequency of recombination compared to genes that were:", options: ["Located on entirely different chromosomes", "Also located very close together on the same chromosome", "Located far apart on the same chromosome", "Not present in the genome at all"], correctindex: 2, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-43', question: "The exchange of genetic material between homologous chromosomes during meiosis, which can produce new combinations of linked genes, is called:", options: ["Mutation", "Recombination (crossing over)", "Codominance", "Independent assortment exclusively, with no crossing over involved"], correctindex: 1, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-44', question: "According to Morgan's studies, the frequency of recombination between two linked genes is generally:", options: ["Completely unrelated to the physical distance between them", "Higher for genes located very close together on a chromosome", "Constant, regardless of the distance between the genes", "Lower for genes located close together, and higher for genes located farther apart on the same chromosome"], correctindex: 3, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-45', question: "Genes located very close together on the same chromosome show a very ___ recombination frequency, and are said to be tightly linked.", options: ["High", "Low", "Exactly 50%", "Completely random"], correctindex: 1, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },
  { id: 'piv-46', question: "The recombination frequency between two genes can be used to estimate the relative distance between them on a chromosome, forming the basis for constructing a:", options: ["Genetic (linkage) map", "Karyotype", "Pedigree chart", "Punnett square"], correctindex: 0, difficulty: "medium", topic: "Chromosomal Theory and Linkage" },

  // ---------- Sex Determination ----------
  { id: 'piv-47', question: "In humans, biological sex is determined by a pair of chromosomes referred to as the:", options: ["Autosomes", "Homologous chromosomes exclusively", "Sex chromosomes (X and Y)", "Barr bodies"], correctindex: 2, difficulty: "easy", topic: "Sex Determination" },
  { id: 'piv-48', question: "In humans, a typical female has two X chromosomes (XX), while a typical male has one X and one Y chromosome, a system of sex determination referred to as:", options: ["ZW type", "XO type", "XY type", "Haplodiploidy"], correctindex: 2, difficulty: "easy", topic: "Sex Determination" },
  { id: 'piv-49', question: "In humans, the sex of an offspring is primarily determined by which parent's gamete, since this parent produces two types of gametes with respect to the sex chromosome?", options: ["The mother, since she produces both X and Y bearing eggs", "Neither parent, since sex is determined randomly", "Both parents equally and identically", "The father, since he produces both X-bearing and Y-bearing sperm"], correctindex: 3, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-50', question: "In certain insects, such as grasshoppers, males have only a single sex chromosome (X) and no corresponding partner, a sex-determination system referred to as the:", options: ["XO type", "XY type", "ZW type", "Haplodiploid type"], correctindex: 0, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-51', question: "In birds, the sex-determination system is different from that of humans: males are typically homogametic (ZZ) while females are heterogametic, a system referred to as the:", options: ["XY type", "ZW type", "XO type", "Haplodiploid type"], correctindex: 1, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-52', question: "In the honeybee, sex determination follows a unique system in which fertilised (diploid) eggs develop into females, while unfertilised (haploid) eggs develop into males. This system is called:", options: ["The XY type", "Haplodiploidy", "The ZW type", "The XO type"], correctindex: 1, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-53', question: "In the haplodiploid sex-determination system seen in honeybees, male bees (drones) are notable for being:", options: ["Haploid, developing from unfertilised eggs", "Diploid, just like the females", "Triploid", "Entirely without any genetic material"], correctindex: 0, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-54', question: "In humans, since a mother (XX) can only contribute an X chromosome to her offspring, while the father can contribute either an X or a Y chromosome, the sex ratio in the human population is generally expected to be approximately:", options: ["All male", "All female", "3 males to 1 female", "1:1 (equal numbers of males and females)"], correctindex: 3, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-55', question: "Human sex chromosomes, in addition to determining sex, also carry other genes unrelated to sex determination, some of which are responsible for certain hereditary disorders, referred to as:", options: ["Autosomal disorders exclusively", "Sex-linked (X-linked or Y-linked) disorders", "Polygenic disorders exclusively", "Chromosomal aneuploidies exclusively"], correctindex: 1, difficulty: "medium", topic: "Sex Determination" },
  { id: 'piv-56', question: "Since males in humans possess only a single X chromosome, any recessive allele present on their X chromosome will be:", options: ["Always masked by a corresponding dominant allele on their Y chromosome", "Never expressed under any circumstances", "Directly expressed in the phenotype, since there is no second allele to mask it", "Automatically converted into a dominant allele"], correctindex: 2, difficulty: "medium", topic: "Sex Determination" },

  // ---------- Mendelian Disorders ----------
  { id: 'piv-57', question: "Haemophilia, a Mendelian disorder characterised by excessive bleeding due to a defect in the blood clotting mechanism, is inherited as a(n):", options: ["Autosomal dominant trait", "X-linked recessive trait", "Y-linked trait exclusively", "Polygenic trait"], correctindex: 1, difficulty: "easy", topic: "Mendelian Disorders" },
  { id: 'piv-58', question: "Because haemophilia is X-linked recessive, this disorder is observed much more frequently in:", options: ["Males", "Females", "Equally in males and females", "Neither sex, since it is extremely rare overall"], correctindex: 0, difficulty: "medium", topic: "Mendelian Disorders" },
  { id: 'piv-59', question: "Red-green colour blindness in humans, another classic example of an X-linked recessive Mendelian disorder, results from a defect in one or more of the genes responsible for:", options: ["Rod cell function in the retina", "The lens of the eye", "The optic nerve exclusively", "Cone cell pigments in the retina responsible for colour vision"], correctindex: 3, difficulty: "medium", topic: "Mendelian Disorders" },
  { id: 'piv-60', question: "Sickle cell anaemia, an autosomal recessive Mendelian disorder, is caused by a single point mutation that alters the structure of which protein?", options: ["Haemoglobin", "Insulin", "Keratin", "Collagen"], correctindex: 0, difficulty: "easy", topic: "Mendelian Disorders" },
  { id: 'piv-61', question: "In sickle cell anaemia, the mutated haemoglobin causes red blood cells to become abnormally shaped, particularly under conditions of low oxygen tension, adopting a characteristic:", options: ["Elongated, sickle-like shape", "Perfectly spherical shape", "Flattened, disc shape identical to normal cells", "Star-like shape"], correctindex: 0, difficulty: "easy", topic: "Mendelian Disorders" },
  { id: 'piv-62', question: "Thalassemia, another autosomal recessive Mendelian blood disorder, results from a quantitative defect, specifically a reduced rate of synthesis of one or more:", options: ["Blood clotting factors", "White blood cell types", "Globin chains that make up the haemoglobin molecule", "Platelet precursor cells"], correctindex: 2, difficulty: "medium", topic: "Mendelian Disorders" },
  { id: 'piv-63', question: "Phenylketonuria (PKU), an autosomal recessive Mendelian metabolic disorder, results from the individual's inability to properly convert the amino acid phenylalanine into:", options: ["Glucose", "Tyrosine", "Glycine", "Lactose"], correctindex: 1, difficulty: "medium", topic: "Mendelian Disorders" },
  { id: 'piv-64', question: "If untreated, the accumulation of phenylalanine and its by-products in individuals with phenylketonuria can lead to serious harm, particularly to the:", options: ["Skeletal system exclusively", "Skin exclusively", "Digestive system exclusively", "Central nervous system, resulting in mental retardation"], correctindex: 3, difficulty: "medium", topic: "Mendelian Disorders" },
  { id: 'piv-65', question: "Sickle cell anaemia is inherited in an autosomal recessive manner, meaning that an individual must inherit the mutated allele from:", options: ["Only their father", "Both parents, in order to show the disease", "Only their mother", "Neither parent; it always arises spontaneously"], correctindex: 1, difficulty: "medium", topic: "Mendelian Disorders" },
  { id: 'piv-66', question: "Which of the following Mendelian disorders is inherited as an X-linked recessive trait, rather than an autosomal recessive trait?", options: ["Haemophilia", "Sickle cell anaemia", "Thalassemia", "Phenylketonuria"], correctindex: 0, difficulty: "easy", topic: "Mendelian Disorders" },

  // ---------- Chromosomal Disorders ----------
  { id: 'piv-67', question: "Chromosomal disorders arise mainly due to an abnormal number of chromosomes (aneuploidy) or structural changes within chromosomes, in contrast to Mendelian disorders which typically result from mutations in a:", options: ["Whole chromosome set", "Group of unrelated chromosomes", "Single gene", "Cytoplasmic organelle"], correctindex: 2, difficulty: "easy", topic: "Chromosomal Disorders" },
  { id: 'piv-68', question: "Down syndrome, one of the most common chromosomal disorders in humans, results from the presence of an extra copy of chromosome number:", options: ["18", "13", "21", "23"], correctindex: 2, difficulty: "easy", topic: "Chromosomal Disorders" },
  { id: 'piv-69', question: "Because Down syndrome involves three copies of chromosome 21 instead of the usual two, it is described as a case of:", options: ["Monosomy", "Haploidy", "Polyploidy", "Trisomy"], correctindex: 3, difficulty: "medium", topic: "Chromosomal Disorders" },
  { id: 'piv-70', question: "Turner syndrome, a chromosomal disorder affecting females, results from the presence of only a single X chromosome, with the sex chromosome constitution written as:", options: ["45, X (XO)", "47, XXY", "47, XXX", "46, XY"], correctindex: 0, difficulty: "medium", topic: "Chromosomal Disorders" },
  { id: 'piv-71', question: "Klinefelter syndrome, a chromosomal disorder affecting males, results from the presence of an additional X chromosome, giving a sex chromosome constitution of:", options: ["45, X", "47, XXY", "47, XYY", "46, XX"], correctindex: 1, difficulty: "medium", topic: "Chromosomal Disorders" },
  { id: 'piv-72', question: "Individuals with Klinefelter syndrome (47, XXY) typically show overall body features that are:", options: ["Entirely typical of an unaffected male, with no distinguishing features", "Predominantly male, though often with some feminised characteristics such as gynecomastia", "Predominantly female in every respect", "Impossible to characterise in any way"], correctindex: 1, difficulty: "medium", topic: "Chromosomal Disorders" },
  { id: 'piv-73', question: "Individuals with Turner syndrome (45, X) are generally characterised by underdeveloped ovaries and:", options: ["Short stature and a webbed neck, among other features", "Excessively tall stature, well above the population average", "A completely normal reproductive system with full fertility", "An extra Y chromosome"], correctindex: 0, difficulty: "medium", topic: "Chromosomal Disorders" },
  { id: 'piv-74', question: "Down syndrome is typically associated with a characteristic set of physical and developmental features, including:", options: ["Completely normal cognitive development in all cases", "No distinguishing physical features whatsoever", "Exceptionally tall stature", "Small round head, furrowed tongue, partially open mouth, and varying degrees of mental retardation"], correctindex: 3, difficulty: "medium", topic: "Chromosomal Disorders" },

  // ---------- Pedigree Analysis / Mixed ----------
  { id: 'piv-75', question: "A diagrammatic representation of the inheritance of a particular trait across several generations of a family, commonly used to trace the pattern of a hereditary disorder, is called a:", options: ["Karyotype", "Pedigree chart", "Punnett square", "Genetic linkage map"], correctindex: 1, difficulty: "easy", topic: "Pedigree Analysis" },
  { id: 'piv-76', question: "Pedigree analysis is a particularly valuable tool in human genetics mainly because, unlike with experimental organisms such as pea plants or fruit flies, researchers studying humans cannot:", options: ["Observe any hereditary patterns at all", "Study large family groups", "Perform controlled experimental crosses on human subjects", "Access any historical family records"], correctindex: 2, difficulty: "medium", topic: "Pedigree Analysis" },
  { id: 'piv-77', question: "In a standard pedigree chart, a filled (shaded) symbol is generally used to represent an individual who:", options: ["Is entirely unaffected by the trait being studied", "Is affected by the trait/disorder being studied", "Has not yet been tested for the trait", "Is deceased, regardless of their phenotype"], correctindex: 1, difficulty: "medium", topic: "Pedigree Analysis" },
  { id: 'piv-78', question: "Which of the following disorders would be expected to show an inheritance pattern in a pedigree chart consistent with X-linked recessive inheritance, i.e. affecting males much more frequently than females?", options: ["Haemophilia", "Down syndrome", "Turner syndrome", "Klinefelter syndrome"], correctindex: 0, difficulty: "easy", topic: "Pedigree Analysis" },
  { id: 'piv-79', question: "Which of the following disorders would be expected to show an inheritance pattern in a pedigree chart consistent with autosomal recessive inheritance, potentially affecting both males and females roughly equally?", options: ["Klinefelter syndrome", "Turner syndrome", "Haemophilia", "Sickle cell anaemia"], correctindex: 3, difficulty: "easy", topic: "Pedigree Analysis" },
  { id: 'piv-80', question: "Overall, the combined study of Mendelian genetics, chromosomal theory, sex determination, and pedigree analysis provides the conceptual foundation for understanding:", options: ["How traits, including inherited disorders, are passed from parents to offspring across generations", "Only plant classification", "Only the structure of proteins", "Only the process of photosynthesis"], correctindex: 0, difficulty: "medium", topic: "Pedigree Analysis" },

];

export default questions;