import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Mechanical Properties of Fluids
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Pressure: Basics and Pascal's Law ----------
  { id: 1, type: 'mcq', question: "Pressure exerted by a fluid at a point is defined as the:", options: ["Normal force (thrust) exerted per unit area on the surface", "Total force exerted per unit volume", "Tangential force per unit area", "Weight of the fluid divided by its total volume"], correctIndex: 0, difficulty: "easy", explanation: "Pressure is specifically defined as normal force per unit area, distinct from tangential (shear) force." },
  { id: 2, type: 'mcq', question: "The SI unit of pressure is the:", options: ["Newton (N)", "Joule (J)", "Pascal (Pa), equal to one newton per square metre", "Watt (W)"], correctIndex: 2, difficulty: "easy", explanation: "Pressure = force/area = N/m², which is defined as the pascal (Pa), the SI unit of pressure." },
  { id: 3, type: 'mcq', question: "Pascal's law states that pressure applied to an enclosed, incompressible fluid at rest is transmitted:", options: ["Only in the direction of the applied force", "Equally and undiminished in all directions throughout the fluid", "Only to the walls of the container closest to the point of application", "With a gradual decrease in magnitude as distance from the point of application increases"], correctIndex: 1, difficulty: "easy", explanation: "Pascal's law states that pressure applied anywhere to a confined, incompressible fluid is transmitted equally, undiminished, in every direction." },
  { id: 4, type: 'mcq', question: "Hydraulic lifts and hydraulic brakes are practical devices that work based directly on the application of:", options: ["Bernoulli's principle", "Stokes' law", "The equation of continuity", "Pascal's law"], correctIndex: 3, difficulty: "easy", explanation: "Hydraulic lifts/brakes use a small force applied over a small piston area to generate a large force over a larger piston area, exploiting Pascal's law." },
  { id: 5, type: 'mcq', question: "In a hydraulic lift, a small force F1 applied to a piston of small area A1 can generate a much larger force F2 on a piston of larger area A2, related by:", options: ["F1A1 = F2A2, with areas multiplied instead of matched to force", "F1/A1 = F2/A2 (equal pressures on both pistons)", "F1 = F2, regardless of the areas", "F1 × F2 = A1 × A2"], correctIndex: 1, difficulty: "medium", explanation: "Since pressure is transmitted equally, P1 = P2, i.e. F1/A1 = F2/A2, which is what allows a hydraulic lift to multiply force using a larger output piston area." },
  { id: 6, type: 'mcq', question: "Atmospheric pressure at sea level, in commonly used units, is approximately:", options: ["1.013 × 10⁵ Pa (about 76 cm of mercury)", "9.8 Pa", "6.67 × 10⁻¹¹ Pa", "3 × 10⁸ Pa"], correctIndex: 0, difficulty: "easy", explanation: "Standard atmospheric pressure at sea level is approximately 1.013 × 10⁵ Pa, equivalent to a mercury column of about 76 cm." },
  { id: 7, type: 'mcq', question: "The pressure measured relative to atmospheric pressure (i.e. the excess pressure above atmospheric), as commonly read by a simple pressure gauge, is called:", options: ["Absolute pressure", "Hydrostatic pressure exclusively", "Gauge pressure", "Static pressure exclusively"], correctIndex: 2, difficulty: "medium", explanation: "Gauge pressure is defined as the pressure difference above (or below) atmospheric pressure, which is what most simple pressure gauges actually measure." },
  { id: 8, type: 'mcq', question: "Absolute pressure at a point is related to gauge pressure and atmospheric pressure by the equation:", options: ["Absolute pressure = gauge pressure − atmospheric pressure", "Absolute pressure = atmospheric pressure / gauge pressure", "Absolute pressure = atmospheric pressure + gauge pressure", "Absolute pressure = gauge pressure alone, with no reference to atmosphere"], correctIndex: 2, difficulty: "medium", explanation: "Absolute pressure is the true total pressure at a point, equal to atmospheric pressure plus whatever gauge pressure is measured." },
  { id: 9, type: 'mcq', question: "A mercury barometer, used to measure atmospheric pressure, works on the principle that the height of the mercury column supported is:", options: ["Independent of atmospheric pressure entirely", "Inversely proportional to atmospheric pressure", "Determined solely by the diameter of the barometer tube", "Directly proportional to the atmospheric pressure acting on the mercury reservoir"], correctIndex: 3, difficulty: "medium", explanation: "In a barometer, atmospheric pressure pushes mercury up the evacuated tube until the weight of the column balances it, so a taller column directly indicates higher atmospheric pressure." },
  { id: 10, type: 'mcq', question: "A fluid at rest exerts pressure on the walls of its container:", options: ["Perpendicular (normal) to the container walls, at every point", "Only parallel to the container walls", "Only at the bottom of the container, never on the side walls", "Only when the container is completely sealed"], correctIndex: 0, difficulty: "medium", explanation: "A fluid at rest exerts pressure perpendicular to any surface it contacts, since a tangential component would cause the fluid to flow (fluids at rest cannot sustain shear stress)." },

  // ---------- Pressure Variation with Depth and Hydraulic Machines ----------
  { id: 11, type: 'mcq', question: "The pressure at a depth h below the free surface of a fluid of density ρ, in a uniform gravitational field g, is given by (ignoring atmospheric pressure) the formula:", options: ["P = ρg/h", "P = hρg", "P = h/(ρg)", "P = h + ρg"], correctIndex: 1, difficulty: "easy", explanation: "The pressure due to a fluid column of height h and density ρ is given by P = hρg." },
  { id: 12, type: 'mcq', question: "As depth below the free surface of a fluid increases, the pressure at that depth:", options: ["Decreases", "Increases", "Remains exactly constant", "Becomes negative"], correctIndex: 1, difficulty: "easy", explanation: "Since P = hρg, pressure increases linearly with increasing depth h below the fluid's free surface." },
  { id: 13, type: 'mcq', question: "Pressure at a given depth within a static fluid depends on the depth and the fluid's density, but is essentially independent of the:", options: ["Shape and cross-sectional area of the container", "Density of the fluid", "Value of gravitational acceleration", "Depth below the surface"], correctIndex: 0, difficulty: "medium", explanation: "Static fluid pressure depends only on depth, fluid density, and g — not on the shape or cross-sectional area of the container (the 'hydrostatic paradox')." },
  { id: 14, type: 'mcq', question: "The total absolute pressure at a depth h below the surface of a fluid open to the atmosphere is given by:", options: ["P = hρg alone, ignoring the atmosphere", "P = atmospheric pressure alone, ignoring depth", "P = atmospheric pressure − hρg", "P = atmospheric pressure + hρg"], correctIndex: 3, difficulty: "medium", explanation: "Total (absolute) pressure at depth h combines atmospheric pressure plus the additional pressure due to the fluid column itself." },
  { id: 15, type: 'mcq', question: "In a hydraulic brake system used in automobiles, a relatively small force applied by the driver's foot on the brake pedal is transmitted through brake fluid to produce a much larger force at the:", options: ["Steering wheel", "Brake pads/wheel cylinders, which then create the braking force on the wheels", "Engine directly", "Fuel tank"], correctIndex: 1, difficulty: "medium", explanation: "Hydraulic brakes use Pascal's law to transmit and amplify force from a small pedal piston to larger pistons at the wheel cylinders, producing sufficient braking force." },
  { id: 16, type: 'mcq', question: "A hydraulic press, based on Pascal's law, can be used to exert an enormous force on an object (such as compressing scrap metal) by applying a relatively:", options: ["Small force to a small-area piston connected to a much larger-area piston", "Large force to an equally large-area piston, with no area difference at all", "Small force to a piston of identical area to the output piston", "Force unrelated to piston area entirely"], correctIndex: 0, difficulty: "medium", explanation: "The mechanical advantage of a hydraulic press comes from applying a small force on a small-area piston, which by Pascal's law produces a proportionally larger force on a much larger output piston." },
  { id: 17, type: 'mcq', question: "For a hydraulic lift in equilibrium, the ratio of the output force to the input force is equal to the ratio of the:", options: ["Input piston area to the output piston area", "Heights of the two pistons", "Output piston's cross-sectional area to the input piston's cross-sectional area", "Densities of the fluid at the input and output ends"], correctIndex: 2, difficulty: "medium", explanation: "From F1/A1 = F2/A2, the force ratio F2/F1 equals the area ratio A2/A1 — output force scales with output piston area." },
  { id: 18, type: 'mcq', question: "Which of the following best explains why hydraulic systems are considered a practical way to achieve significant force amplification without requiring an external energy source beyond the applied input force?", options: ["They violate the principle of conservation of energy in a controlled way", "They generate energy internally through fluid friction", "Pascal's law allows force to be transmitted and multiplied through area differences, while the work input still equals the work output (larger force over a smaller distance, or vice versa)", "They rely entirely on external electrical power, not on the fluid mechanics involved"], correctIndex: 2, difficulty: "medium", explanation: "Hydraulic force multiplication doesn't violate energy conservation — the smaller piston moves a larger distance while the larger piston moves a smaller distance, keeping work input equal to work output." },

  // ---------- Streamline Flow and the Equation of Continuity ----------
  { id: 19, type: 'mcq', question: "Fluid flow in which every particle of the fluid passing through a given point follows exactly the same path as the particle before it, with no crossing of paths, is called:", options: ["Turbulent flow", "Random flow", "Compressible flow", "Streamline (laminar) flow"], correctIndex: 3, difficulty: "easy", explanation: "Streamline (laminar) flow is defined by fluid particles following smooth, non-intersecting paths, in contrast to turbulent flow." },
  { id: 20, type: 'mcq', question: "Fluid flow characterised by irregular, chaotic motion, with eddies and vortices forming and fluid particles crossing paths, is called:", options: ["Turbulent flow", "Streamline flow", "Steady flow exclusively", "Incompressible flow exclusively"], correctIndex: 0, difficulty: "easy", explanation: "Turbulent flow is characterised by irregular, chaotic fluid motion with crossing paths, eddies, and vortices, as opposed to smooth streamline flow." },
  { id: 21, type: 'mcq', question: "The equation of continuity for the flow of an incompressible fluid through a pipe of varying cross-sectional area states that:", options: ["The product of the cross-sectional area and the fluid velocity (Av) remains constant along the pipe", "The cross-sectional area alone remains constant", "The fluid velocity alone remains constant, regardless of pipe area", "The pressure alone remains constant throughout the pipe"], correctIndex: 0, difficulty: "medium", explanation: "The equation of continuity, A1v1 = A2v2, follows from conservation of mass for an incompressible fluid, keeping volume flow rate constant along the pipe." },
  { id: 22, type: 'mcq', question: "According to the equation of continuity, when a fluid flows from a wider section of a pipe into a narrower section, its velocity:", options: ["Decreases", "Remains exactly the same", "Increases", "Becomes zero"], correctIndex: 2, difficulty: "medium", explanation: "Since Av is constant, a decrease in cross-sectional area (narrower pipe) must be compensated by an increase in velocity to keep the product constant." },
  { id: 23, type: 'mcq', question: "The equation of continuity, A1v1 = A2v2, is fundamentally a statement of the conservation of:", options: ["Energy", "Momentum", "Mass (for an incompressible fluid, this becomes conservation of volume flow rate)", "Charge"], correctIndex: 2, difficulty: "medium", explanation: "The equation of continuity arises from mass flowing into a pipe section equalling mass flowing out, i.e. conservation of mass." },
  { id: 24, type: 'mcq', question: "A garden hose fitted with a narrow nozzle causes water to spray out with a much higher velocity than inside the wider hose, which is a direct practical illustration of:", options: ["Pascal's law", "Stokes' law", "Surface tension", "The equation of continuity"], correctIndex: 3, difficulty: "medium", explanation: "The nozzle narrows the cross-sectional area, and by the equation of continuity (Av = constant), the water's exit velocity must increase correspondingly." },
  { id: 25, type: 'mcq', question: "The equation of continuity assumes that the fluid flowing through the pipe is:", options: ["Highly compressible, with significant density changes", "Incompressible, with essentially constant density throughout", "A perfect vacuum", "Completely frictionless and massless"], correctIndex: 1, difficulty: "medium", explanation: "The simple form A1v1 = A2v2 specifically assumes an incompressible fluid, so mass conservation reduces to volume flow rate conservation." },
  { id: 26, type: 'mcq', question: "For a fluid flowing steadily through a pipe of continuously decreasing cross-sectional area, the volume of fluid passing through any cross-section per unit time (the volume flow rate):", options: ["Remains the same at every cross-section", "Continuously decreases along the pipe", "Continuously increases along the pipe", "Becomes zero at the narrowest point"], correctIndex: 0, difficulty: "medium", explanation: "The equation of continuity guarantees the volume flow rate (Av) is the same at every cross-section for steady incompressible flow, regardless of area variation." },

  // ---------- Bernoulli's Theorem and Applications ----------
  { id: 27, type: 'mcq', question: "Bernoulli's theorem, derived from the principle of conservation of energy for a flowing, non-viscous, incompressible fluid, states that along a streamline:", options: ["Pressure alone remains constant, with no dependence on velocity or height", "Only kinetic energy per unit volume remains constant", "The sum of pressure, kinetic energy per unit volume, and potential energy per unit volume remains constant", "Only potential energy per unit volume remains constant"], correctIndex: 2, difficulty: "medium", explanation: "Bernoulli's equation states P + (1/2)ρv² + ρgh = constant along a streamline, representing conservation of total mechanical energy per unit volume." },
  { id: 28, type: 'mcq', question: "Bernoulli's principle applies strictly to fluid flow that is:", options: ["Highly viscous and compressible", "Turbulent and unsteady", "Steady, non-viscous (ideal), and incompressible", "Occurring only in a vacuum"], correctIndex: 2, difficulty: "medium", explanation: "The standard derivation assumes the fluid is non-viscous, incompressible, and the flow is steady — the idealised conditions under which the equation strictly holds." },
  { id: 29, type: 'mcq', question: "According to Bernoulli's principle, for horizontal flow (where the height term remains constant), an increase in a fluid's velocity is generally accompanied by a corresponding:", options: ["Increase in the fluid's pressure", "Increase in the fluid's density", "No change in pressure at all", "Decrease in the fluid's pressure"], correctIndex: 3, difficulty: "medium", explanation: "For horizontal Bernoulli flow, P + (1/2)ρv² = constant, so an increase in velocity must be compensated by a decrease in pressure." },
  { id: 30, type: 'mcq', question: "A Venturi meter, a device used to measure the flow rate of a fluid through a pipe, works based on the application of:", options: ["Bernoulli's principle, combined with the equation of continuity", "Stokes' law alone", "Pascal's law alone", "Newton's law of viscosity alone"], correctIndex: 0, difficulty: "medium", explanation: "Converting a Venturi meter's measured pressure difference into a flow rate requires both the equation of continuity and Bernoulli's equation." },
  { id: 31, type: 'mcq', question: "In a Venturi meter, the fluid velocity is higher in the narrow, constricted section of the pipe compared to the wider section, and correspondingly the pressure in the narrow section is:", options: ["Higher than in the wider section", "Lower than in the wider section", "Exactly equal to the pressure in the wider section", "Completely independent of the velocity change"], correctIndex: 1, difficulty: "medium", explanation: "By Bernoulli's principle, since velocity is higher in the constricted section, the pressure there must be correspondingly lower." },
  { id: 32, type: 'mcq', question: "The dynamic lift experienced by an aircraft wing, which allows it to overcome gravity during flight, is largely explained using Bernoulli's principle, based on the fact that air flows:", options: ["At the same speed above and below the wing, producing no pressure difference", "Faster over the curved upper surface of the wing than beneath the flatter lower surface, creating a pressure difference", "Only below the wing, with no airflow above it at all", "Only above the wing, with no airflow beneath it at all"], correctIndex: 1, difficulty: "medium", explanation: "The wing's aerofoil shape causes air to travel faster over the curved top, producing lower pressure above than below (by Bernoulli's principle), resulting in upward lift." },
  { id: 33, type: 'mcq', question: "The spinning motion of a ball (such as in cricket or football) causing it to curve or swerve in flight, explained using differential air pressure created by the ball's spin combined with Bernoulli's principle, is known as the:", options: ["Magnus effect", "Doppler effect", "Photoelectric effect", "Coriolis effect"], correctIndex: 0, difficulty: "medium", explanation: "The Magnus effect describes exactly this phenomenon — a spinning ball's rotation creates a velocity (and pressure) difference on either side, producing a curving sideways force." },
  { id: 34, type: 'mcq', question: "Torricelli's law, a specific application of Bernoulli's principle, gives the speed of efflux of a liquid flowing out through a small hole located at a depth h below the free surface of the liquid in a container as:", options: ["v = gh", "v = h/(2g)", "v = gh²", "v = √(2gh)"], correctIndex: 3, difficulty: "medium", explanation: "Applying Bernoulli's equation between the liquid surface and the hole gives the efflux speed v = √(2gh), the same form as a freely falling object's speed." },
  { id: 35, type: 'mcq', question: "According to Torricelli's law, the speed with which liquid flows out of a small opening located deeper below the liquid's free surface, compared to a shallower opening, is:", options: ["Smaller", "Greater", "Exactly the same, regardless of depth", "Zero, since deeper openings cannot allow outflow"], correctIndex: 1, difficulty: "medium", explanation: "Since v = √(2gh), a greater depth h below the surface results in a greater efflux speed at the opening." },
  { id: 36, type: 'mcq', question: "A perfume atomizer/spray bottle, which draws liquid up a tube and disperses it into a fine mist when air is blown rapidly across the top of the tube, operates based on:", options: ["Pascal's law exclusively", "Stokes' law exclusively", "Bernoulli's principle, where the fast-moving air stream creates a region of reduced pressure that draws the liquid upward", "Newton's law of viscosity exclusively"], correctIndex: 2, difficulty: "medium", explanation: "The rapid airflow across the tube's top lowers local air pressure there (Bernoulli's principle), and the resulting pressure difference draws liquid up the tube." },
  { id: 37, type: 'mcq', question: "In the human circulatory system, a localised narrowing of a blood vessel due to plaque build-up causes blood to speed up at that constriction, and by Bernoulli's principle, the pressure at the narrowed section:", options: ["Increases significantly", "Remains completely unaffected", "Decreases, which can, in certain cases, contribute to a local collapse or further complications of the vessel wall", "Becomes infinitely large"], correctIndex: 2, difficulty: "medium", explanation: "As blood speeds up through a narrowed vessel, Bernoulli's principle predicts the pressure there decreases, which is medically relevant in arterial-narrowing conditions." },
  { id: 38, type: 'mcq', question: "Which of the following statements about Bernoulli's principle is INCORRECT?", options: ["It follows from the work-energy theorem applied to a flowing fluid", "It strictly applies to ideal fluids with negligible viscosity", "It predicts that fluid pressure increases wherever fluid velocity increases, for horizontal flow", "It is used to explain aircraft lift and the functioning of a Venturi meter"], correctIndex: 2, difficulty: "medium", explanation: "This statement is backwards — Bernoulli's principle predicts pressure decreases (not increases) where velocity increases, for horizontal flow." },

  // ---------- Viscosity: Basics and Newton's Law ----------
  { id: 39, type: 'mcq', question: "Viscosity is the property of a fluid by virtue of which it develops an internal resistance (a kind of internal friction) that opposes:", options: ["Any change in the fluid's temperature", "Any change in the fluid's pressure", "Any change in the fluid's density", "Relative motion between adjacent layers of the fluid"], correctIndex: 3, difficulty: "easy", explanation: "Viscosity refers to the internal friction that resists relative sliding motion between adjacent fluid layers moving at different velocities." },
  { id: 40, type: 'mcq', question: "According to Newton's law of viscous flow, the viscous force (internal friction) between two adjacent layers of a fluid is directly proportional to the area of contact between the layers and to the:", options: ["Velocity gradient (rate of change of velocity with distance) perpendicular to the flow", "Absolute velocity of the fluid, with no dependence on how it varies with position", "Total volume of the fluid", "Fluid's temperature exclusively"], correctIndex: 0, difficulty: "medium", explanation: "Newton's law of viscosity states F = ηA(dv/dx), where the viscous force is proportional to area and to the velocity gradient between adjacent layers." },
  { id: 41, type: 'mcq', question: "The proportionality constant in Newton's law of viscosity, which is a characteristic property of a given fluid, is called its:", options: ["Surface tension", "Coefficient of viscosity", "Bulk modulus", "Density"], correctIndex: 1, difficulty: "medium", explanation: "The proportionality constant η in F = ηA(dv/dx) is defined as the coefficient of viscosity, a characteristic property of the fluid." },
  { id: 42, type: 'mcq', question: "The SI unit of the coefficient of viscosity is the:", options: ["Newton (N)", "Pascal (Pa)", "Joule (J)", "Poiseuille (Pa·s), also equal to N·s/m²"], correctIndex: 3, difficulty: "medium", explanation: "The SI unit of viscosity coefficient is the poiseuille (Pa·s), equivalent to N·s/m², derived from F = ηA(dv/dx)." },
  { id: 43, type: 'mcq', question: "As the temperature of a liquid increases, its coefficient of viscosity generally:", options: ["Increases", "Decreases", "Remains exactly unchanged", "Becomes infinite"], correctIndex: 1, difficulty: "medium", explanation: "For liquids, increasing temperature typically weakens intermolecular cohesive forces, causing viscosity to decrease as temperature rises." },
  { id: 44, type: 'mcq', question: "As the temperature of a gas increases, its coefficient of viscosity generally:", options: ["Increases", "Decreases", "Remains exactly unchanged", "Becomes zero"], correctIndex: 0, difficulty: "medium", explanation: "Gas viscosity arises mainly from molecular momentum transfer, which increases with higher molecular speeds at higher temperature, so gas viscosity increases with temperature." },
  { id: 45, type: 'mcq', question: "A fluid such as honey, which flows very slowly and offers substantial resistance to relative motion between its layers, is described as having a:", options: ["Very low coefficient of viscosity", "Zero coefficient of viscosity", "High coefficient of viscosity", "Coefficient of viscosity that is entirely independent of temperature"], correctIndex: 2, difficulty: "medium", explanation: "A fluid that strongly resists internal relative motion (flows slowly, feels 'thick') has a high coefficient of viscosity, in contrast to a low-viscosity fluid like water." },
  { id: 46, type: 'mcq', question: "An 'ideal fluid', as assumed in the standard derivation of Bernoulli's theorem, is one that is taken to have:", options: ["A very high coefficient of viscosity", "A viscosity that varies unpredictably with velocity", "Zero (or negligible) viscosity", "Infinite viscosity"], correctIndex: 2, difficulty: "medium", explanation: "The idealisation used in deriving Bernoulli's theorem assumes the fluid is non-viscous, i.e. has zero (or negligible) internal friction between its layers." },

  // ---------- Poiseuille's Formula, Stokes' Law and Terminal Velocity ----------
  { id: 47, type: 'mcq', question: "Poiseuille's formula describes the volume flow rate of a viscous fluid flowing through a narrow tube under streamline conditions, and shows that the flow rate is proportional to the fourth power of the tube's:", options: ["Length", "Viscosity coefficient", "Applied pressure difference", "Radius"], correctIndex: 3, difficulty: "hard", explanation: "Poiseuille's formula, Q = πPr⁴/(8ηl), shows an extremely strong (fourth-power) dependence of volume flow rate on the tube's radius." },
  { id: 48, type: 'mcq', question: "According to Poiseuille's formula, the volume flow rate of a viscous fluid through a narrow tube is inversely proportional to the:", options: ["Radius of the tube", "Length of the tube and the fluid's coefficient of viscosity", "Pressure difference across the tube", "Fourth power of the tube's radius"], correctIndex: 1, difficulty: "medium", explanation: "In Q = πPr⁴/(8ηl), the flow rate Q is inversely proportional to both the tube length l and the fluid's viscosity η." },
  { id: 49, type: 'mcq', question: "Poiseuille's formula for viscous flow through a tube is given by Q = πPr⁴/(8ηl), where Q represents:", options: ["The pressure difference across the tube", "The volume of fluid flowing per unit time (volume flow rate)", "The viscosity coefficient of the fluid", "The velocity of an individual fluid particle"], correctIndex: 1, difficulty: "medium", explanation: "Q in Poiseuille's formula specifically denotes the volume flow rate — the volume of fluid passing through the tube per unit time." },
  { id: 50, type: 'mcq', question: "Stokes' law gives the viscous drag force experienced by a small spherical object moving through a viscous fluid, and states that this force is directly proportional to the object's radius, its velocity, and the fluid's:", options: ["Coefficient of viscosity", "Density alone, with no viscosity term", "Surface tension", "Bulk modulus"], correctIndex: 0, difficulty: "easy", explanation: "Stokes' law states F = 6πηrv, where the viscous drag force is proportional to the coefficient of viscosity η, the sphere's radius r, and its velocity v." },
  { id: 51, type: 'mcq', question: "Stokes' law, F = 6πηrv, applies specifically to the motion of:", options: ["Any arbitrarily-shaped object moving through a vacuum", "Objects moving through a completely frictionless fluid", "A small sphere moving slowly through a viscous fluid, under conditions of streamline (laminar) flow around it", "Objects moving faster than the speed of sound"], correctIndex: 2, difficulty: "medium", explanation: "Stokes' law is specifically derived for a small sphere moving slowly enough through a viscous fluid that the flow around it remains streamlined." },
  { id: 52, type: 'mcq', question: "When a small spherical object (e.g. a raindrop or a ball bearing) falls through a viscous fluid under gravity, it eventually reaches a constant, maximum velocity called its:", options: ["Escape velocity", "Orbital velocity", "Terminal velocity", "Critical velocity, in the context of Reynolds number"], correctIndex: 2, difficulty: "easy", explanation: "Terminal velocity is the specific term for the constant maximum speed reached when the net force on a falling object in a viscous fluid becomes zero." },
  { id: 53, type: 'mcq', question: "Terminal velocity is reached when the net force acting on the falling object becomes zero, which occurs when the upward viscous drag force and buoyant force together exactly balance the:", options: ["Object's kinetic energy", "Surface tension of the fluid", "Object's initial velocity", "Downward gravitational force (weight) acting on the object"], correctIndex: 3, difficulty: "medium", explanation: "At terminal velocity, the sum of upward viscous drag and buoyant forces exactly equals and opposes the downward gravitational weight of the object." },
  { id: 54, type: 'mcq', question: "According to Stokes' law, the terminal velocity of a small sphere falling through a viscous fluid is directly proportional to the:", options: ["Radius of the sphere", "Square of the sphere's radius", "Cube root of the sphere's radius", "Inverse of the sphere's radius"], correctIndex: 1, difficulty: "medium", explanation: "Combining Stokes' law with the force-balance condition at terminal velocity yields vt ∝ r² — a frequently tested NEET relationship." },
  { id: 55, type: 'mcq', question: "According to the terminal velocity formula derived from Stokes' law, a larger sphere falling through the same viscous fluid, compared to a smaller sphere of the same material, will reach:", options: ["A smaller terminal velocity", "A larger terminal velocity", "Exactly the same terminal velocity, regardless of size", "Zero terminal velocity"], correctIndex: 1, difficulty: "medium", explanation: "Since terminal velocity is proportional to r², a larger sphere of the same density reaches a higher terminal velocity than a smaller one." },
  { id: 56, type: 'mcq', question: "The terminal velocity formula, vt = (2r²(ρ−σ)g)/(9η), shows that a denser object falling through a fluid, compared to one of lower density but the same size, will have a:", options: ["Higher terminal velocity", "Lower terminal velocity", "Terminal velocity of exactly zero", "Terminal velocity completely unrelated to its density"], correctIndex: 0, difficulty: "medium", explanation: "In vt ∝ (ρ−σ), a larger density difference (denser object) produces a correspondingly higher terminal velocity." },

  // ---------- Reynolds Number and Turbulence ----------
  { id: 57, type: 'mcq', question: "Reynolds number, a dimensionless quantity used to predict whether fluid flow through a pipe will be streamline (laminar) or turbulent, depends on the fluid's density, velocity, the pipe's diameter, and the fluid's:", options: ["Surface tension", "Bulk modulus", "Coefficient of viscosity", "Specific heat capacity"], correctIndex: 2, difficulty: "medium", explanation: "Reynolds number is defined as Re = ρvd/η, combining fluid density, flow velocity, characteristic pipe dimension, and viscosity coefficient." },
  { id: 58, type: 'mcq', question: "A relatively low value of Reynolds number generally indicates that the fluid flow is likely to be:", options: ["Turbulent", "Highly compressible", "Streamline (laminar)", "Impossible to characterise"], correctIndex: 2, difficulty: "medium", explanation: "A low Reynolds number indicates viscous forces dominate over inertial forces, favouring smooth, streamline flow." },
  { id: 59, type: 'mcq', question: "A relatively high value of Reynolds number generally indicates that the fluid flow is likely to become:", options: ["Perfectly streamline", "Completely stationary", "Free of any viscosity effects", "Turbulent"], correctIndex: 3, difficulty: "medium", explanation: "A high Reynolds number indicates inertial forces dominate over viscous forces, which tends to destabilise smooth flow and produce turbulence." },
  { id: 60, type: 'mcq', question: "Reynolds number is a dimensionless quantity, meaning it:", options: ["Has no physical units, allowing direct comparison of flow behaviour across different fluids and pipe sizes", "Can only be applied to water flowing through glass tubes", "Has the same units as viscosity", "Has the same units as velocity"], correctIndex: 0, difficulty: "medium", explanation: "Being dimensionless, Reynolds number provides a universal criterion for comparing flow regimes across different fluids, velocities, and pipe geometries." },

  // ---------- Surface Tension and Surface Energy ----------
  { id: 61, type: 'mcq', question: "Surface tension is the property of a liquid surface by virtue of which it behaves like a stretched elastic membrane, tending to:", options: ["Maximise its surface area at all times", "Minimise its surface area", "Increase its volume indefinitely", "Have no measurable effect on the liquid's shape"], correctIndex: 1, difficulty: "easy", explanation: "Surface tension causes a liquid's free surface to contract to the smallest possible surface area for a given volume." },
  { id: 62, type: 'mcq', question: "Surface tension is defined quantitatively as the force acting per unit length along a line drawn on the liquid's surface, and has SI units of:", options: ["N/m²", "N/m", "N·m", "N·m²"], correctIndex: 1, difficulty: "medium", explanation: "Surface tension is force per unit length, so its SI unit is newtons per metre (N/m), distinct from pressure (N/m²)." },
  { id: 63, type: 'mcq', question: "At the molecular level, surface tension arises because molecules at the liquid's surface experience a net inward force (an unbalanced cohesive attraction), since they have:", options: ["Fewer neighbouring liquid molecules above them, compared to molecules deep within the bulk of the liquid", "More neighbouring molecules than those deep within the bulk of the liquid", "No intermolecular forces acting on them at all", "Identical intermolecular force environments to molecules in the bulk"], correctIndex: 0, difficulty: "medium", explanation: "Surface molecules lack neighbours above them, so cohesive pull from molecules below and to the sides creates a net inward force, giving rise to surface tension." },
  { id: 64, type: 'mcq', question: "The energy required to increase the surface area of a liquid by a unit amount, against the inward pull of surface tension, is called the:", options: ["Kinetic energy of the surface", "Potential energy of the bulk liquid", "Viscous energy", "Surface energy (numerically equal to the surface tension)"], correctIndex: 3, difficulty: "medium", explanation: "Surface energy is defined as the work done per unit area to increase a liquid's surface area, and is numerically equal to the surface tension coefficient." },
  { id: 65, type: 'mcq', question: "Which of the following forces is primarily responsible for causing water to 'wet' a clean glass surface, spreading out over it rather than forming discrete droplets?", options: ["Cohesive forces between water molecules alone, with no role for the glass", "Adhesive forces between water molecules and glass molecules, being stronger than the cohesive forces within water itself", "Gravitational force pulling the water down onto the glass", "The viscosity of the water"], correctIndex: 1, difficulty: "medium", explanation: "When adhesive forces exceed cohesive forces, the liquid tends to spread out and wet the surface rather than forming beads." },
  { id: 66, type: 'mcq', question: "Mercury placed on a clean glass surface tends to form spherical droplets rather than spreading out, mainly because, for mercury on glass:", options: ["Adhesive forces are much stronger than cohesive forces", "Cohesive forces (between mercury atoms) are stronger than adhesive forces (between mercury and glass)", "There are no intermolecular forces acting at all", "Gravity has no effect on mercury"], correctIndex: 1, difficulty: "medium", explanation: "Because cohesive attraction among mercury atoms is stronger than adhesion to glass, mercury minimises contact and forms compact, spherical droplets." },
  { id: 67, type: 'mcq', question: "Water droplets and soap bubbles tend to assume a spherical shape (in the absence of other forces such as gravity) mainly because a sphere:", options: ["Has the minimum possible surface area for a given enclosed volume, and surface tension acts to minimise surface area", "Has the maximum possible surface area for a given enclosed volume", "Is the only shape that can hold any liquid at all", "Has no surface tension acting on it"], correctIndex: 0, difficulty: "medium", explanation: "Since surface tension minimises surface area for a given volume, and a sphere has the smallest surface-area-to-volume ratio, liquid drops tend toward a spherical shape." },
  { id: 68, type: 'mcq', question: "As the temperature of a liquid increases, its surface tension generally:", options: ["Increases", "Remains completely unaffected by temperature", "Becomes infinite", "Decreases"], correctIndex: 3, difficulty: "medium", explanation: "Higher temperature increases molecular kinetic energy and weakens intermolecular cohesive forces, which reduces surface tension." },
  { id: 69, type: 'mcq', question: "Detergents and soaps are effective cleaning agents partly because they act to ___ the surface tension of water, allowing it to spread more easily and penetrate into small crevices, such as those in fabric fibres.", options: ["Increase", "Decrease", "Have no effect on", "Double, exactly"], correctIndex: 1, difficulty: "medium", explanation: "Detergents/soaps are surfactants that lower the surface tension of water, allowing it to wet and spread over surfaces more effectively." },
  { id: 70, type: 'mcq', question: "Certain insects, such as water striders, are able to walk on the surface of water without sinking, primarily due to the effect of the water's:", options: ["High density", "Surface tension, which supports their weight via the surface acting like a stretched membrane", "High viscosity", "High compressibility"], correctIndex: 1, difficulty: "medium", explanation: "The water surface's tension creates a supportive, membrane-like effect strong enough to bear the small weight of lightweight insects like water striders." },

  // ---------- Angle of Contact, Capillarity, and Excess Pressure ----------
  { id: 71, type: 'mcq', question: "The angle of contact between a liquid and a solid surface, measured within the liquid, at the point where the liquid surface meets the solid surface, is a measure of:", options: ["The relative strength of cohesive forces within the liquid compared to adhesive forces between the liquid and the solid", "The total surface area of the liquid", "The liquid's coefficient of viscosity", "The liquid's density alone"], correctIndex: 0, difficulty: "medium", explanation: "The angle of contact reflects the balance between cohesive forces (within the liquid) and adhesive forces (between liquid and solid)." },
  { id: 72, type: 'mcq', question: "For a liquid such as water in a clean glass tube, which wets the glass, the angle of contact is generally:", options: ["Greater than 90°", "Exactly 180°", "Less than 90° (often close to 0°)", "Undefined"], correctIndex: 2, difficulty: "medium", explanation: "Water wets clean glass well, corresponding to a small (acute) angle of contact, characteristic of strong adhesion to the solid surface." },
  { id: 73, type: 'mcq', question: "For mercury in a glass tube, which does not wet the glass, the angle of contact is generally:", options: ["Less than 90°", "Exactly 0°", "Greater than 90° (obtuse)", "Undefined"], correctIndex: 2, difficulty: "medium", explanation: "Since mercury's cohesive forces dominate over its adhesion to glass, it forms an obtuse angle of contact, consistent with its non-wetting behaviour." },
  { id: 74, type: 'mcq', question: "Capillarity refers to the phenomenon in which a liquid rises (or falls) within a narrow tube (a capillary), as compared to the level of the liquid in a larger surrounding reservoir, primarily due to the combined effects of:", options: ["Gravity acting alone, with no role for surface tension", "Viscosity acting alone", "Bulk modulus of the liquid", "Surface tension and the angle of contact between the liquid and the tube's material"], correctIndex: 3, difficulty: "medium", explanation: "Capillary rise (or depression) results from the interplay of surface tension along the tube's inner circumference and the wetting behaviour (angle of contact) of the liquid." },
  { id: 75, type: 'mcq', question: "A liquid that wets the material of a narrow capillary tube (small angle of contact, such as water in glass) will, when the tube is dipped into it:", options: ["Fall below the level of the liquid outside the tube", "Rise above the level of the liquid outside the tube", "Remain at exactly the same level as outside the tube", "Immediately overflow the tube completely"], correctIndex: 1, difficulty: "medium", explanation: "For a wetting liquid (small angle of contact), surface tension pulls the liquid up the narrow capillary tube, producing capillary rise." },
  { id: 76, type: 'mcq', question: "A liquid that does not wet the material of a narrow capillary tube (large, obtuse angle of contact, such as mercury in glass) will, when the tube is dipped into it:", options: ["Fall below the level of the liquid outside the tube (capillary depression)", "Rise well above the level of the liquid outside the tube", "Remain at exactly the same level as outside the tube", "Immediately evaporate completely"], correctIndex: 0, difficulty: "medium", explanation: "For a non-wetting liquid (obtuse angle of contact), surface tension actually depresses the liquid level within the capillary tube." },
  { id: 77, type: 'mcq', question: "According to the formula for capillary rise, h = 2T cosθ / (rρg), the height of capillary rise h is inversely proportional to the:", options: ["Surface tension T", "Cosine of the angle of contact", "Radius r of the capillary tube", "Acceleration due to gravity, but only when measured at the equator"], correctIndex: 2, difficulty: "medium", explanation: "In h = 2Tcosθ/(rρg), h is inversely proportional to the capillary tube's radius r, meaning narrower tubes produce greater capillary rise." },
  { id: 78, type: 'mcq', question: "According to the capillary rise formula, a narrower capillary tube, compared to a wider one of the same material and liquid, will show:", options: ["A smaller height of capillary rise", "Exactly the same height of capillary rise", "A greater height of capillary rise", "No capillary rise at all"], correctIndex: 2, difficulty: "medium", explanation: "Since h ∝ 1/r, a narrower tube (smaller r) produces a greater capillary rise, all else being equal." },
  { id: 79, type: 'mcq', question: "The excess pressure inside a spherical liquid drop, compared to the pressure outside, arises due to surface tension and is given by the formula:", options: ["ΔP = T/(2r)", "ΔP = 4T/r", "ΔP = T × r", "ΔP = 2T/r"], correctIndex: 3, difficulty: "medium", explanation: "For a single-surfaced spherical drop, the excess internal pressure due to surface tension is ΔP = 2T/r." },
  { id: 80, type: 'mcq', question: "The excess pressure inside a soap bubble (which has two liquid surfaces, an inner and an outer film) is given by ΔP = 4T/r, which is twice the excess pressure inside a simple liquid drop of the same radius, because:", options: ["A soap bubble has two surfaces (inner and outer), each contributing surface tension, effectively doubling the total restoring effect compared to a drop's single surface", "Soap bubbles always have twice the surface tension coefficient of a plain liquid drop", "Soap bubbles are always twice the size of liquid drops", "The formula is simply a historical convention with no physical basis"], correctIndex: 0, difficulty: "medium", explanation: "A soap bubble is a thin film with two surfaces (inside and outside) both contributing to surface tension, doubling the excess pressure formula compared to a drop's single surface." },

];

export default questions;