import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Kinetic Theory of Gases
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Assumptions of Kinetic Theory ----------
  { id: 1, type: 'mcq', question: "The kinetic theory of gases is based on the fundamental assumption that a gas consists of a very large number of molecules that are in constant, random:", options: ["Motion", "Rest, with no movement at all", "Chemical reaction with each other", "Alignment along a single fixed direction"], correctIndex: 0, difficulty: "easy", explanation: "The kinetic theory's foundational postulate is that gas molecules are in continuous, random motion, colliding with each other and the container walls." },
  { id: 2, type: 'mcq', question: "According to the kinetic theory of gases, the size of individual gas molecules is assumed to be:", options: ["Comparable to the average distance between molecules", "Much larger than the average distance between molecules", "Negligible compared to the average distance between molecules (i.e. molecules are treated as point masses)", "Impossible to define or estimate"], correctIndex: 2, difficulty: "medium", explanation: "Kinetic theory idealises gas molecules as point masses, negligible in size compared to the much larger average distance separating them." },
  { id: 3, type: 'mcq', question: "Kinetic theory assumes that collisions between gas molecules, and between molecules and the container walls, are:", options: ["Completely inelastic, with molecules sticking together after collision", "Perfectly elastic, meaning both kinetic energy and momentum are conserved", "Random events unrelated to any conservation laws", "Extremely rare, occurring only once in a very long time"], correctIndex: 1, difficulty: "medium", explanation: "A key assumption is that all molecular collisions are perfectly elastic, conserving both total kinetic energy and momentum." },
  { id: 4, type: 'mcq', question: "Between successive collisions, gas molecules are assumed to move in straight lines, since kinetic theory assumes there are no intermolecular forces acting between them, except:", options: ["When molecules are extremely far apart", "Under all conditions, without exception", "Only in liquids, never in gases", "During the brief instant of an actual collision"], correctIndex: 3, difficulty: "medium", explanation: "Kinetic theory assumes negligible intermolecular forces except during the very brief moment molecules are in direct collision." },
  { id: 5, type: 'mcq', question: "Since gas molecules are assumed to move freely between collisions, following Newton's laws of motion, this reflects the kinetic theory's treatment of a gas as a system governed by:", options: ["Purely quantum mechanical rules, with no classical description possible", "Classical (Newtonian) mechanics", "Chemical reaction kinetics exclusively", "Relativistic mechanics exclusively"], correctIndex: 1, difficulty: "medium", explanation: "The kinetic theory of gases is a classical (Newtonian) mechanical model, treating molecules as classical particles obeying Newton's laws between collisions." },
  { id: 6, type: 'mcq', question: "According to kinetic theory, the actual volume occupied by the molecules of a gas themselves is assumed to be:", options: ["Negligible compared to the total volume of the container", "Equal to the total volume of the container", "Larger than the total volume of the container", "Impossible to compare to the container volume"], correctIndex: 0, difficulty: "medium", explanation: "For an ideal gas, the physical volume occupied by the molecules is considered negligible relative to the much larger container volume." },
  { id: 7, type: 'mcq', question: "Kinetic theory assumes that gas molecules move with a wide range of individual speeds and in all possible directions, described statistically. This assumption underlies the concept of:", options: ["A single, fixed speed shared identically by every molecule", "Molecules moving only along the container walls", "A statistical distribution of molecular speeds (such as the Maxwell-Boltzmann distribution)", "Molecules that never actually move at all"], correctIndex: 2, difficulty: "medium", explanation: "Because individual molecular speeds and directions vary randomly, kinetic theory relies on statistical descriptions like the Maxwell-Boltzmann speed distribution." },
  { id: 8, type: 'mcq', question: "The kinetic theory model, which successfully explains macroscopic gas properties (pressure, temperature, etc.) in terms of the microscopic motion of individual molecules, exemplifies the broader scientific approach of:", options: ["Pure empirical observation with no theoretical model at all", "Relativistic field theory", "Statistical mechanics, connecting microscopic particle behaviour to macroscopic, measurable properties", "Quantum electrodynamics"], correctIndex: 2, difficulty: "medium", explanation: "Kinetic theory is a foundational example of statistical mechanics, deriving macroscopic gas properties from statistical behaviour of microscopic particles." },

  // ---------- Gas Laws ----------
  { id: 9, type: 'mcq', question: "Boyle's law states that, at constant temperature, the pressure of a fixed mass of an ideal gas is:", options: ["Directly proportional to its volume", "Directly proportional to the square of its volume", "Unrelated to its volume", "Inversely proportional to its volume"], correctIndex: 3, difficulty: "easy", explanation: "Boyle's law states PV = constant at fixed temperature, meaning pressure and volume are inversely proportional." },
  { id: 10, type: 'mcq', question: "Boyle's law can be mathematically expressed, for a fixed mass of gas at constant temperature, as:", options: ["P1V1 = P2V2", "P1/V1 = P2/V2", "P1 + V1 = P2 + V2", "P1V1² = P2V2²"], correctIndex: 0, difficulty: "easy", explanation: "This is the standard statement of Boyle's law: at constant temperature, the product of pressure and volume remains constant." },
  { id: 11, type: 'mcq', question: "Charles' law states that, at constant pressure, the volume of a fixed mass of an ideal gas is:", options: ["Inversely proportional to its absolute temperature", "Directly proportional to its absolute temperature", "Completely independent of its temperature", "Directly proportional to the square of its absolute temperature"], correctIndex: 1, difficulty: "easy", explanation: "Charles' law states V/T = constant at fixed pressure, meaning volume is directly proportional to absolute temperature." },
  { id: 12, type: 'mcq', question: "Charles' law can be mathematically expressed, for a fixed mass of gas at constant pressure, as:", options: ["V1T1 = V2T2", "V1 + T1 = V2 + T2", "V1/T1² = V2/T2²", "V1/T1 = V2/T2"], correctIndex: 3, difficulty: "easy", explanation: "This is the standard statement of Charles' law: at constant pressure, the ratio of volume to absolute temperature remains constant." },
  { id: 13, type: 'mcq', question: "Gay-Lussac's law (also called the pressure law) states that, at constant volume, the pressure of a fixed mass of an ideal gas is:", options: ["Inversely proportional to its absolute temperature", "Directly proportional to its absolute temperature", "Completely independent of its temperature", "Inversely proportional to the square of its absolute temperature"], correctIndex: 1, difficulty: "medium", explanation: "Gay-Lussac's law states P/T = constant at fixed volume, meaning pressure is directly proportional to absolute temperature." },
  { id: 14, type: 'mcq', question: "Gay-Lussac's law can be mathematically expressed, for a fixed mass of gas at constant volume, as:", options: ["P1/T1 = P2/T2", "P1T1 = P2T2", "P1 + T1 = P2 + T2", "P1/T1² = P2/T2²"], correctIndex: 0, difficulty: "medium", explanation: "This is the standard statement of Gay-Lussac's law: at constant volume, the ratio of pressure to absolute temperature remains constant." },
  { id: 15, type: 'mcq', question: "Avogadro's law states that equal volumes of different ideal gases, at the same temperature and pressure, contain:", options: ["Different numbers of molecules, depending on the specific gas", "Equal numbers of molecules, regardless of the specific gas", "No molecules at all, since gases are considered empty space", "A number of molecules that depends only on the gas's molar mass"], correctIndex: 1, difficulty: "medium", explanation: "Avogadro's law states that, at the same temperature and pressure, equal volumes of any ideal gas contain the same number of molecules." },
  { id: 16, type: 'mcq', question: "Avogadro's number, representing the number of molecules present in exactly one mole of a substance, has an approximate value of:", options: ["6.022 × 10²³", "3.14 × 10⁸", "9.8 × 10⁻¹¹", "1.6 × 10⁻¹⁹"], correctIndex: 0, difficulty: "easy", explanation: "Avogadro's number, NA ≈ 6.022 × 10²³ per mole, gives the number of elementary entities in one mole of substance." },
  { id: 17, type: 'mcq', question: "The individual gas laws (Boyle's, Charles', and Gay-Lussac's laws) are, in fact, special cases of the more general:", options: ["Zeroth law of thermodynamics", "Second law of thermodynamics", "Ideal gas equation, PV = nRT", "Stefan-Boltzmann law"], correctIndex: 2, difficulty: "medium", explanation: "Each individual gas law describes the relationship between two of P, V, T while holding the third constant — all are special cases of PV = nRT." },
  { id: 18, type: 'mcq', question: "Real gases obey the ideal gas laws (Boyle's, Charles', etc.) most closely under conditions of:", options: ["Very high pressure and very low temperature", "Conditions close to their liquefaction point", "Low pressure and relatively high temperature", "Extremely high density"], correctIndex: 2, difficulty: "medium", explanation: "Real gases behave most ideally at low pressure and relatively high temperature, where intermolecular forces and finite molecular volume become negligible." },

  // ---------- The Ideal Gas Equation ----------
  { id: 19, type: 'mcq', question: "The ideal gas equation, combining Boyle's law, Charles' law, and Avogadro's law into a single relation, is given by:", options: ["PV = T/n", "P/V = nT", "PT = nV", "PV = nRT"], correctIndex: 3, difficulty: "easy", explanation: "The ideal gas equation, PV = nRT, is the combined statement of the individual gas laws via the universal gas constant R." },
  { id: 20, type: 'mcq', question: "In the ideal gas equation PV = nRT, the symbol R represents:", options: ["The universal (molar) gas constant, the same for all ideal gases", "Avogadro's number", "The Boltzmann constant", "A quantity that varies from gas to gas"], correctIndex: 0, difficulty: "easy", explanation: "R, the universal gas constant, is a fundamental physical constant with the same value for all ideal gases." },
  { id: 21, type: 'mcq', question: "The ideal gas equation can also be written in terms of the number of molecules N (rather than the number of moles n) and the Boltzmann constant k as:", options: ["PV = NkT", "PV = N/(kT)", "PV = Nk/T", "PV = N + kT"], correctIndex: 0, difficulty: "medium", explanation: "Since n = N/NA and R = NAk, PV = nRT can be equivalently written as PV = NkT." },
  { id: 22, type: 'mcq', question: "The Boltzmann constant, k, is related to the universal gas constant R and Avogadro's number NA by the relation:", options: ["k = R × NA", "k = NA/R", "k = R/NA", "k = R + NA"], correctIndex: 2, difficulty: "medium", explanation: "The Boltzmann constant is defined as the gas constant per molecule, k = R/NA." },
  { id: 23, type: 'mcq', question: "An 'ideal gas' is a theoretical/hypothetical gas that is assumed to strictly obey the ideal gas equation, PV = nRT, under:", options: ["Only very specific, extreme conditions of pressure and temperature", "No conditions whatsoever, since ideal gases do not exist in reality", "All conditions of temperature and pressure", "Only conditions close to absolute zero"], correctIndex: 2, difficulty: "medium", explanation: "An ideal gas is defined as a theoretical gas that obeys PV = nRT exactly under all conditions — a useful idealisation." },
  { id: 24, type: 'mcq', question: "At standard temperature and pressure (STP), one mole of any ideal gas is found to occupy a volume of approximately:", options: ["1 litre", "100 litres", "6.022 × 10²³ litres", "22.4 litres"], correctIndex: 3, difficulty: "medium", explanation: "A well-known derived result is that one mole of an ideal gas occupies approximately 22.4 litres at standard temperature and pressure." },
  { id: 25, type: 'mcq', question: "The ideal gas equation PV = nRT is considered an 'equation of state' because it relates the:", options: ["Chemical composition of a gas to its colour", "Macroscopic state variables (pressure, volume, temperature) of a gas to one another", "Kinetic energy of individual gas molecules directly, with no reference to P, V, or T", "Age of a gas sample to its current temperature"], correctIndex: 1, difficulty: "medium", explanation: "An equation of state relates the macroscopic thermodynamic variables that together describe the state of a system." },
  { id: 26, type: 'mcq', question: "Real gases deviate from the ideal gas equation most significantly under conditions of:", options: ["High pressure and low temperature, close to the point of liquefaction", "Low pressure and high temperature", "Standard temperature and pressure exclusively", "Exactly 0 K, where all gases behave ideally"], correctIndex: 0, difficulty: "medium", explanation: "Real gases deviate most from ideal behaviour under high pressure and low temperature, where intermolecular forces and finite molecular volume matter." },

  // ---------- Pressure of a Gas: Kinetic Theory Derivation ----------
  { id: 27, type: 'mcq', question: "Using kinetic theory, the pressure exerted by an ideal gas on the walls of its container can be derived and expressed in terms of the gas's density ρ and the mean square speed of its molecules, <v²>, as:", options: ["P = ρ<v²>", "P = (2/3)ρ<v²>", "P = (1/3)ρ<v²>", "P = 3ρ<v²>"], correctIndex: 2, difficulty: "medium", explanation: "This is the standard kinetic theory result, P = (1/3)ρ<v²>, derived from momentum transfer in molecular wall collisions." },
  { id: 28, type: 'mcq', question: "The pressure exerted by a gas, as derived from kinetic theory, arises fundamentally from:", options: ["The gravitational attraction between gas molecules", "A static force exerted uniformly by the gas, with no molecular motion involved", "The continuous bombardment of the container's walls by rapidly moving gas molecules, transferring momentum upon each collision", "Chemical reactions occurring between the gas and the container material"], correctIndex: 2, difficulty: "medium", explanation: "Kinetic theory explains pressure as the macroscopic, averaged effect of countless molecular collisions with the container walls." },
  { id: 29, type: 'mcq', question: "Combining the kinetic theory pressure formula with the definition of average kinetic energy, the pressure of an ideal gas can also be related to its average translational kinetic energy per unit volume, E, by the relation:", options: ["P = E", "P = E/2", "P = 3E", "PV = (2/3)E"], correctIndex: 3, difficulty: "medium", explanation: "This relation, PV = (2/3)E, directly connects gas pressure to the kinetic energy of its constituent molecules." },
  { id: 30, type: 'mcq', question: "According to the kinetic theory derivation, the pressure of an ideal gas is directly proportional to the:", options: ["Mean square speed of its molecules", "Mean speed of its molecules, but not the mean square speed", "Volume of the container alone", "Number of molecules alone, with no dependence on their speed"], correctIndex: 0, difficulty: "medium", explanation: "P = (1/3)ρ<v²> shows pressure is directly proportional to the mean square molecular speed, not simply the mean speed." },
  { id: 31, type: 'mcq', question: "For a fixed volume and fixed number of gas molecules, if the average kinetic energy of the molecules increases (e.g. due to heating), the pressure exerted by the gas, according to kinetic theory, will:", options: ["Decrease", "Increase", "Remain exactly the same", "Become negative"], correctIndex: 1, difficulty: "medium", explanation: "Since P = (1/3)ρ<v²>, increasing the molecules' average kinetic energy (at fixed density) increases the pressure." },
  { id: 32, type: 'mcq', question: "The kinetic theory derivation of gas pressure considers the momentum change of a gas molecule as it collides elastically with a container wall, and then calculates the total force by summing the effects of:", options: ["A single molecule's collision only, with no generalisation to the entire gas", "An enormous number of such molecular collisions occurring per unit time over the wall's area", "Only collisions between molecules themselves, ignoring the walls entirely", "Gravitational forces on the molecules"], correctIndex: 1, difficulty: "medium", explanation: "The full derivation requires summing/averaging momentum transferred by a very large number of molecular collisions per unit time." },
  { id: 33, type: 'mcq', question: "The kinetic theory formula for pressure, P = (1/3)ρ<v²>, applies to a gas assumed to be:", options: ["Enclosed in a container, with molecules colliding elastically with its walls", "Completely free, with no container walls involved at all", "In a solid state, not a gaseous state", "At absolute zero temperature"], correctIndex: 0, difficulty: "medium", explanation: "The derivation specifically models a gas enclosed within a container, deriving pressure from molecular collisions against its walls." },
  { id: 34, type: 'mcq', question: "The mean square speed <v²> appearing in the kinetic theory pressure formula is defined as the:", options: ["Simple arithmetic average of the speeds of all molecules", "Speed of the single fastest molecule in the gas", "Speed of the single slowest molecule in the gas", "Average of the squares of the individual speeds of all the gas molecules"], correctIndex: 3, difficulty: "hard", explanation: "<v²> denotes the average of the squared speeds of all molecules, not the square of the average speed — an important distinction." },

  // ---------- RMS Speed and the Kinetic Interpretation of Temperature ----------
  { id: 35, type: 'mcq', question: "The root mean square (rms) speed of gas molecules is defined as the square root of the:", options: ["Simple average of the individual molecular speeds", "Mean (average) of the squares of the individual molecular speeds", "Product of all the individual molecular speeds", "Difference between the fastest and slowest molecular speeds"], correctIndex: 1, difficulty: "medium", explanation: "The rms speed is defined as vrms = √<v²>, the square root of the mean of the squared individual speeds." },
  { id: 36, type: 'mcq', question: "The formula for the rms speed of gas molecules, in terms of the universal gas constant R, absolute temperature T, and molar mass M, is given by:", options: ["vrms = √(RT/M)", "vrms = √(3RT/M)", "vrms = 3RT/M", "vrms = √(RT/3M)"], correctIndex: 1, difficulty: "easy", explanation: "This is the standard formula for rms speed, vrms = √(3RT/M), derived from the kinetic theory pressure formula and ideal gas equation." },
  { id: 37, type: 'mcq', question: "According to the rms speed formula, vrms = √(3RT/M), the rms speed of gas molecules is directly proportional to the:", options: ["Square root of the absolute temperature", "Absolute temperature itself, without any square root", "Square of the absolute temperature", "Inverse of the absolute temperature"], correctIndex: 0, difficulty: "medium", explanation: "Since vrms ∝ √T, rms speed increases with the square root of absolute temperature." },
  { id: 38, type: 'mcq', question: "According to the rms speed formula, for gases at the same temperature, the rms speed of a gas is inversely proportional to the square root of its:", options: ["Pressure", "Volume", "Number of moles", "Molar mass"], correctIndex: 3, difficulty: "medium", explanation: "Since vrms = √(3RT/M), at fixed temperature lighter molecules have a higher rms speed than heavier ones, vrms ∝ 1/√M." },
  { id: 39, type: 'mcq', question: "Comparing hydrogen gas and oxygen gas at the same temperature, since hydrogen has a much smaller molar mass than oxygen, hydrogen molecules will have a ___ rms speed than oxygen molecules.", options: ["Smaller", "Much larger", "Identical", "Undefined, since the comparison is not valid"], correctIndex: 1, difficulty: "medium", explanation: "Since vrms ∝ 1/√M and hydrogen's molar mass is much smaller, hydrogen molecules move at a considerably higher rms speed at the same temperature." },
  { id: 40, type: 'mcq', question: "The kinetic theory of gases provides a microscopic interpretation of temperature, showing that the average translational kinetic energy of a gas molecule is directly proportional to the gas's:", options: ["Absolute temperature", "Pressure alone, with no dependence on temperature", "Volume alone, with no dependence on temperature", "Molar mass alone, with no dependence on temperature"], correctIndex: 0, difficulty: "medium", explanation: "The key kinetic theory result is that average molecular kinetic energy is directly proportional to absolute temperature." },
  { id: 41, type: 'mcq', question: "The average translational kinetic energy of a single gas molecule, according to kinetic theory, is given by the formula:", options: ["(1/2)kT", "kT", "(3/2)kT", "3kT"], correctIndex: 2, difficulty: "medium", explanation: "This is the standard kinetic theory result for average translational kinetic energy per molecule, (3/2)kT." },
  { id: 42, type: 'mcq', question: "According to the kinetic theory interpretation of temperature, at absolute zero (0 K), the translational kinetic energy of gas molecules would theoretically be:", options: ["Maximum", "Undefined", "Zero", "Infinite"], correctIndex: 2, difficulty: "medium", explanation: "Since average translational KE ∝ T, at T = 0 K the theoretical average translational kinetic energy would be zero." },
  { id: 43, type: 'mcq', question: "A crucial insight from kinetic theory is that the average kinetic energy of gas molecules at a given temperature is:", options: ["Different for every different type of gas, depending on the molecules' individual masses", "Dependent on the pressure of the gas, not just its temperature", "Dependent on the volume of the container holding the gas", "The same for all ideal gases at the same absolute temperature, regardless of the specific gas or its molecular mass"], correctIndex: 3, difficulty: "hard", explanation: "Since average translational KE = (3/2)kT depends only on temperature, gases of different types at the same temperature share the same average kinetic energy, even though their rms speeds differ." },
  { id: 44, type: 'mcq', question: "Since average translational kinetic energy per molecule is the same for all ideal gases at a given temperature, but rms speed depends on molar mass, it follows that lighter gas molecules must move ___ than heavier gas molecules to have the same average kinetic energy.", options: ["Slower", "Faster", "At exactly the same speed", "Not at all, since they cannot have equal kinetic energy"], correctIndex: 1, difficulty: "medium", explanation: "Since KE = (1/2)mv² and average KE is fixed by temperature alone, a lighter molecule must move faster to achieve the same average kinetic energy." },
  { id: 45, type: 'mcq', question: "The kinetic interpretation of temperature, connecting average molecular kinetic energy directly to absolute temperature, is one of the most significant conceptual achievements of the kinetic theory of gases because it:", options: ["Provides a microscopic (molecular-level) physical meaning for the macroscopic, everyday concept of temperature", "Has no real conceptual significance at all, being purely mathematical", "Applies only to solids, not to gases", "Contradicts the ideal gas equation entirely"], correctIndex: 0, difficulty: "medium", explanation: "This result bridges the microscopic (molecular motion) and macroscopic (measured temperature) descriptions, giving temperature a physical, mechanical meaning." },
  { id: 46, type: 'mcq', question: "Using the kinetic theory relation PV = (1/3)Nm<v²> (where N is the number of molecules and m is the mass of each molecule), combined with the ideal gas equation PV = NkT, one can directly derive the relation:", options: ["(1/2)m<v²> = (3/2)kT", "m<v²> = kT, without any numerical factor", "(1/2)m<v²> = kT/3", "m<v²> = 3kT/2, without the factor of one-half"], correctIndex: 0, difficulty: "hard", explanation: "Equating the two expressions for PV and solving gives (1/2)m<v²> = (3/2)kT — the foundational relation connecting molecular motion to temperature." },

  // ---------- Maxwell Speed Distribution ----------
  { id: 47, type: 'mcq', question: "The Maxwell-Boltzmann speed distribution describes how the speeds of gas molecules in a sample are:", options: ["All identical, with no variation at all", "Distributed in exactly two discrete, fixed values", "Statistically distributed across a continuous range of values, at a given temperature", "Completely random, with no describable pattern or distribution at all"], correctIndex: 2, difficulty: "medium", explanation: "The Maxwell-Boltzmann distribution provides a precise statistical description of how molecular speeds are distributed at a given temperature." },
  { id: 48, type: 'mcq', question: "According to the Maxwell-Boltzmann speed distribution, the speed at which the largest number (or fraction) of gas molecules are moving, corresponding to the peak of the distribution curve, is called the:", options: ["Rms speed", "Average speed", "Most probable speed", "Terminal speed"], correctIndex: 2, difficulty: "medium", explanation: "The most probable speed corresponds to the peak (maximum) of the Maxwell-Boltzmann distribution curve." },
  { id: 49, type: 'mcq', question: "Among the three characteristic molecular speeds derived from the Maxwell-Boltzmann distribution — most probable speed (vp), average speed (vavg), and rms speed (vrms) — for a given gas at a given temperature, the correct ordering from smallest to largest is:", options: ["vrms < vavg < vp", "vavg < vp < vrms", "vp < vrms < vavg", "vp < vavg < vrms"], correctIndex: 3, difficulty: "hard", explanation: "A well-known result is vp < vavg < vrms — the most probable speed is always smallest and rms speed always largest." },
  { id: 50, type: 'mcq', question: "As the temperature of a gas increases, the Maxwell-Boltzmann speed distribution curve, when plotted, shows a peak that:", options: ["Shifts toward higher speeds and becomes broader/flatter overall", "Shifts toward lower speeds and becomes narrower/taller", "Remains at exactly the same position, regardless of temperature", "Disappears entirely at higher temperatures"], correctIndex: 0, difficulty: "medium", explanation: "As temperature increases, molecules move faster on average, shifting the peak higher while the increased speed spread broadens/flattens the curve." },
  { id: 51, type: 'mcq', question: "The Maxwell-Boltzmann speed distribution demonstrates that, even at a fixed, uniform temperature, individual gas molecules within a sample:", options: ["All move at exactly the identical speed", "Possess a wide range of different speeds, statistically distributed around some central, characteristic value", "Have no speed at all, since temperature alone determines their motion", "Move only in one single, fixed direction"], correctIndex: 1, difficulty: "medium", explanation: "Even at a fixed temperature, individual molecules show a broad range of different instantaneous speeds, as the Maxwell-Boltzmann distribution describes." },
  { id: 52, type: 'mcq', question: "The existence of a statistical distribution of molecular speeds, as described by Maxwell-Boltzmann statistics, is a direct consequence of the random, chaotic nature of:", options: ["Only a small handful of 'special' molecules within the gas", "Countless molecular collisions constantly occurring between gas molecules, redistributing their individual energies and speeds", "External magnetic fields acting on the gas", "Gravitational forces alone"], correctIndex: 1, difficulty: "medium", explanation: "Continuous, random molecular collisions constantly redistribute kinetic energy, producing and maintaining the statistical spread of speeds." },

  // ---------- Degrees of Freedom and the Equipartition of Energy ----------
  { id: 53, type: 'mcq', question: "The number of independent ways in which a molecule can possess or store energy (e.g. through translational or rotational motion) is called its number of:", options: ["Degrees of freedom", "Molar masses", "Avogadro constants", "Thermal conductivities"], correctIndex: 0, difficulty: "easy", explanation: "Degrees of freedom refers to the number of independent modes in which a molecule can possess energy." },
  { id: 54, type: 'mcq', question: "A monatomic gas molecule (e.g. helium), which can be treated essentially as a point mass, has how many translational degrees of freedom, corresponding to independent motion along the three spatial axes?", options: ["1", "2", "3", "6"], correctIndex: 2, difficulty: "easy", explanation: "A monatomic molecule, having only translational motion, has exactly 3 degrees of freedom, corresponding to the x, y, and z axes." },
  { id: 55, type: 'mcq', question: "A diatomic gas molecule, at ordinary temperatures, has 3 translational degrees of freedom plus an additional 2 rotational degrees of freedom (about the two axes perpendicular to the line joining the two atoms), giving a total of:", options: ["3 degrees of freedom", "4 degrees of freedom", "5 degrees of freedom", "7 degrees of freedom"], correctIndex: 2, difficulty: "medium", explanation: "A diatomic molecule at ordinary temperatures has 3 translational plus 2 rotational degrees of freedom, totalling 5." },
  { id: 56, type: 'mcq', question: "At sufficiently high temperatures, a diatomic gas molecule may also exhibit vibrational motion along the bond connecting its two atoms, which, if included, adds:", options: ["No additional degrees of freedom at all", "Exactly 1 additional degree of freedom", "Exactly 3 additional degrees of freedom", "2 additional degrees of freedom (one for vibrational kinetic energy, one for vibrational potential energy)"], correctIndex: 3, difficulty: "hard", explanation: "Vibrational motion contributes two additional degrees of freedom (kinetic and potential), though typically 'frozen out' at ordinary temperatures." },
  { id: 57, type: 'mcq', question: "The Law of Equipartition of Energy states that, in thermal equilibrium, the total energy of a gas system is distributed:", options: ["Unequally among the different degrees of freedom, favouring translational motion exclusively", "Equally among all the available degrees of freedom of the system", "Entirely into potential energy, with none into kinetic energy", "Randomly, with no discernible pattern at all"], correctIndex: 1, difficulty: "medium", explanation: "The Law of Equipartition states energy is shared equally among all the active/available degrees of freedom in thermal equilibrium." },
  { id: 58, type: 'mcq', question: "According to the Law of Equipartition of Energy, each degree of freedom of a gas molecule contributes an average energy of:", options: ["kT per molecule, for each degree of freedom", "(1/2)kT per molecule, for each degree of freedom", "(3/2)kT per molecule, for each degree of freedom, regardless of the total number of degrees of freedom", "2kT per molecule, for each degree of freedom"], correctIndex: 1, difficulty: "medium", explanation: "The Law of Equipartition assigns exactly (1/2)kT of average energy to each individual degree of freedom." },
  { id: 59, type: 'mcq', question: "For a monatomic gas molecule with 3 (translational) degrees of freedom, applying the Law of Equipartition of Energy gives a total average energy per molecule of:", options: ["(3/2)kT", "(5/2)kT", "3kT", "kT"], correctIndex: 0, difficulty: "medium", explanation: "With 3 degrees of freedom, each contributing (1/2)kT, total average energy is 3 × (1/2)kT = (3/2)kT." },
  { id: 60, type: 'mcq', question: "For a diatomic gas molecule with 5 degrees of freedom (3 translational + 2 rotational, at ordinary temperatures), applying the Law of Equipartition of Energy gives a total average energy per molecule of:", options: ["(3/2)kT", "kT", "2kT", "(5/2)kT"], correctIndex: 3, difficulty: "medium", explanation: "With 5 degrees of freedom, each contributing (1/2)kT, total average energy is 5 × (1/2)kT = (5/2)kT." },
  { id: 61, type: 'mcq', question: "A polyatomic gas molecule (with 3 atoms or more, generally non-linear), considering translational, rotational, and (in some treatments) vibrational contributions, is typically assigned a total of ___ or more degrees of freedom.", options: ["6", "2", "1", "0, since polyatomic molecules are considered to have no degrees of freedom"], correctIndex: 0, difficulty: "medium", explanation: "A non-linear polyatomic molecule typically has 3 translational + 3 rotational degrees of freedom, giving a minimum of 6." },
  { id: 62, type: 'mcq', question: "The Law of Equipartition of Energy is fundamentally derived from classical statistical mechanics and works particularly well for describing the thermal behaviour of gases at temperatures where quantum mechanical effects (such as the 'freezing out' of certain vibrational modes) can be:", options: ["Considered dominant over all classical effects", "Ignored entirely at every possible temperature, with no exceptions ever", "Reasonably neglected, i.e. at moderate, not extremely low or high, temperatures", "Used to completely replace the classical equipartition approach"], correctIndex: 2, difficulty: "medium", explanation: "The classical equipartition theorem works well at moderate temperatures, where quantum effects like frozen-out vibrational modes can be reasonably neglected." },

  // ---------- Specific Heats from Degrees of Freedom ----------
  { id: 63, type: 'mcq', question: "Using the Law of Equipartition of Energy, the molar specific heat at constant volume (Cv) of an ideal gas can be expressed in terms of its degrees of freedom f as:", options: ["Cv = fR", "Cv = R/f", "Cv = (f/2)R", "Cv = 2fR"], correctIndex: 2, difficulty: "medium", explanation: "Since molar internal energy is (f/2)RT, differentiating gives Cv = dU/dT = (f/2)R." },
  { id: 64, type: 'mcq', question: "Using Mayer's relation (Cp − Cv = R) combined with the equipartition-derived expression for Cv, the molar specific heat at constant pressure (Cp) of an ideal gas, in terms of degrees of freedom f, is given by:", options: ["Cp = (f/2)R, identical to Cv", "Cp = fR", "Cp = ((f+2)/2)R", "Cp = ((f−2)/2)R"], correctIndex: 2, difficulty: "medium", explanation: "Adding R to Cv = (f/2)R (per Mayer's relation) gives Cp = ((f+2)/2)R." },
  { id: 65, type: 'mcq', question: "Using the degrees-of-freedom-based expressions for Cp and Cv, the specific heat ratio γ = Cp/Cv can be expressed in terms of f as:", options: ["γ = f/2", "γ = f + 2", "γ = 2/f", "γ = 1 + (2/f)"], correctIndex: 3, difficulty: "hard", explanation: "Dividing Cp by Cv gives γ = (f+2)/f = 1 + (2/f), connecting γ directly to degrees of freedom." },
  { id: 66, type: 'mcq', question: "For a monatomic gas with f = 3 degrees of freedom, using γ = 1 + (2/f), the value of γ works out to:", options: ["1.4", "1.67 (i.e. 5/3)", "1", "2"], correctIndex: 1, difficulty: "medium", explanation: "Substituting f = 3 gives γ = 1 + (2/3) = 5/3 ≈ 1.67, matching the known value for monatomic gases." },
  { id: 67, type: 'mcq', question: "For a diatomic gas with f = 5 degrees of freedom, using γ = 1 + (2/f), the value of γ works out to:", options: ["1.67", "1.4 (i.e. 7/5)", "2", "1"], correctIndex: 1, difficulty: "medium", explanation: "Substituting f = 5 gives γ = 1 + (2/5) = 7/5 = 1.4, matching the known value for diatomic gases." },
  { id: 68, type: 'mcq', question: "Comparing the specific heat ratio γ for monatomic gases (γ ≈ 1.67) to that for diatomic gases (γ ≈ 1.4), γ generally ___ as the number of degrees of freedom f of the gas molecule increases.", options: ["Decreases", "Increases", "Remains exactly the same, regardless of f", "Becomes undefined"], correctIndex: 0, difficulty: "medium", explanation: "Since γ = 1 + (2/f), a larger f results in a smaller γ, consistent with monatomic gases (fewer f) having a higher γ than diatomic gases." },
  { id: 69, type: 'mcq', question: "The molar internal energy of an ideal gas, expressed in terms of its degrees of freedom f, the universal gas constant R, and absolute temperature T, is given by:", options: ["U = fRT", "U = RT/f", "U = 2fRT", "U = (f/2)RT"], correctIndex: 3, difficulty: "hard", explanation: "By the equipartition theorem, total molar internal energy is the sum of (1/2)RT per degree of freedom, giving U = (f/2)RT." },
  { id: 70, type: 'mcq', question: "Since the internal energy of an ideal gas, U = (f/2)RT, depends only on temperature (and the fixed value of f for a given gas), it follows that the internal energy of an ideal gas is a function of:", options: ["Temperature alone", "Pressure alone", "Volume alone", "Both pressure and volume, but not temperature"], correctIndex: 0, difficulty: "medium", explanation: "Since U = (f/2)RT for a given ideal gas, internal energy depends only on temperature, consistent with general kinetic theory results." },

  // ---------- Mean Free Path and Avogadro's Number ----------
  { id: 71, type: 'mcq', question: "The mean free path of a gas molecule is defined as the average distance travelled by the molecule between two successive:", options: ["Changes in temperature", "Collisions with other molecules", "Full revolutions around the container", "Changes in the container's volume"], correctIndex: 1, difficulty: "medium", explanation: "Mean free path is defined as the average distance a molecule travels between one collision and the next." },
  { id: 72, type: 'mcq', question: "The mean free path of gas molecules is inversely related to the number density of molecules (number of molecules per unit volume) and to the:", options: ["Absolute temperature of the gas alone", "Square of the effective diameter of the molecules", "Total mass of the gas sample", "Molar mass of the gas alone"], correctIndex: 1, difficulty: "medium", explanation: "The mean free path formula, λ = 1/(√2 π d² n), shows inverse dependence on number density n and the square of molecular diameter d." },
  { id: 73, type: 'mcq', question: "As the number density of molecules in a gas (molecules per unit volume) increases, the mean free path of the molecules:", options: ["Decreases", "Increases", "Remains exactly unchanged", "Becomes infinite"], correctIndex: 0, difficulty: "medium", explanation: "Since λ ∝ 1/n, a higher number density leads to more frequent collisions and hence a shorter mean free path." },
  { id: 74, type: 'mcq', question: "Increasing the pressure of a gas at constant temperature, which increases the number density of molecules, would generally cause the mean free path to:", options: ["Increase", "Remain exactly unchanged", "Become infinite", "Decrease"], correctIndex: 3, difficulty: "medium", explanation: "Higher pressure at constant temperature means higher number density, which reduces the mean free path since collisions become more frequent." },
  { id: 75, type: 'mcq', question: "As the effective diameter of the gas molecules (the size parameter relevant to collisions) increases, the mean free path:", options: ["Increases", "Decreases", "Remains exactly unchanged", "Becomes independent of molecular size entirely"], correctIndex: 1, difficulty: "medium", explanation: "Since λ ∝ 1/d², larger molecules have a greater chance of colliding sooner, resulting in a shorter mean free path." },
  { id: 76, type: 'mcq', question: "The concept of mean free path is particularly useful in understanding transport phenomena in gases, such as:", options: ["Diffusion, viscosity, and thermal conductivity of gases", "Purely electrical phenomena, unrelated to molecular motion", "Nuclear decay processes", "Gravitational interactions between planets"], correctIndex: 0, difficulty: "medium", explanation: "Mean free path is a key parameter in kinetic theory models of gas transport processes like diffusion, viscosity, and thermal conductivity." },
  { id: 77, type: 'mcq', question: "Avogadro's number, NA ≈ 6.022 × 10²³ per mole, represents the number of elementary entities (atoms, molecules, or ions) present in exactly:", options: ["One gram of any substance", "One mole of any substance", "One litre of any gas at STP", "One cubic metre of any substance"], correctIndex: 1, difficulty: "easy", explanation: "Avogadro's number is the number of elementary entities contained in exactly one mole of a substance." },
  { id: 78, type: 'mcq', question: "Avogadro's number connects the macroscopic mole-based description of a substance (used in chemistry/physics calculations) to the:", options: ["Density of the substance alone", "Actual, discrete number of individual atoms or molecules present", "Colour of the substance", "Melting point of the substance"], correctIndex: 1, difficulty: "medium", explanation: "Avogadro's number is the essential conversion factor between the practical 'mole' unit and the actual discrete count of atoms/molecules." },
  { id: 79, type: 'mcq', question: "The universal gas constant R, Avogadro's number NA, and the Boltzmann constant k are related to one another by the equation:", options: ["k = NA + R", "k = NA − R", "k = NA × R", "k = R/NA"], correctIndex: 3, difficulty: "medium", explanation: "This relation, k = R/NA, expresses the Boltzmann constant as the gas constant expressed on a per-molecule basis." },
  { id: 80, type: 'mcq', question: "Overall, the kinetic theory of gases, encompassing molecular motion, gas laws, rms speed, degrees of freedom, and mean free path, provides the essential microscopic foundation for understanding:", options: ["The macroscopic thermal, mechanical, and transport properties of gases in terms of the behaviour of their constituent molecules", "Only nuclear reactions within stars", "Only electromagnetic wave propagation, with no relevance to gas behaviour", "Only chemical bonding at the atomic level"], correctIndex: 0, difficulty: "medium", explanation: "This chapter's concepts collectively connect molecular-level behaviour to the observable, macroscopic properties of gases." },

];

export default questions;