import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Thermodynamics
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctindex (index 0-3), difficulty, explanation }
// Note: correctindex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Thermal Equilibrium and the Zeroth Law ----------
  { id: 1, question: "The Zeroth law of thermodynamics states that if two systems are each in thermal equilibrium with a third system, then they:", options: ["Are also in thermal equilibrium with each other", "Must have exactly the same mass", "Must be made of the same material", "Cannot ever reach thermal equilibrium with each other"], correctindex: 0, difficulty: "easy", explanation: "The Zeroth law establishes the transitive property of thermal equilibrium, the fundamental basis for a consistent temperature scale." },
  { id: 2, question: "Two systems are said to be in thermal equilibrium with each other when:", options: ["They have exactly the same mass", "They are in physical contact but have very different temperatures", "There is no net flow of heat between them when they are placed in thermal contact", "They have exactly the same volume"], correctindex: 2, difficulty: "medium", explanation: "Thermal equilibrium is defined by the absence of net heat exchange between two systems in thermal contact, which occurs when they've reached the same temperature." },
  { id: 3, question: "The Zeroth law of thermodynamics provides the logical/physical basis for defining and using the concept of:", options: ["Entropy", "Temperature", "Internal energy", "Work"], correctindex: 1, difficulty: "medium", explanation: "The Zeroth law justifies the use of a thermometer and a consistent temperature scale, since it establishes thermal equilibrium as a well-defined, transitive relationship." },
  { id: 4, question: "Although logically fundamental, the Zeroth law of thermodynamics was formally recognised and named after the First and Second laws had already been established, mainly because:", options: ["It was considered entirely unnecessary until much later", "It was discovered before either of the other two laws", "It has no real connection to the other laws of thermodynamics", "Its fundamental importance in defining temperature was only fully appreciated afterward"], correctindex: 3, difficulty: "hard", explanation: "The Zeroth law is named after the First and Second laws because, although logically foundational, its critical role in rigorously defining temperature was only recognised in retrospect." },
  { id: 5, question: "A thermodynamic system is said to be in thermal equilibrium internally when:", options: ["Different parts of the system have widely varying temperatures", "Every part of the system has reached the same, uniform temperature", "The system is actively undergoing rapid temperature changes", "The system has zero internal energy"], correctindex: 1, difficulty: "medium", explanation: "Internal thermal equilibrium requires a uniform temperature throughout the system, with no ongoing internal heat flow." },
  { id: 6, question: "Two objects placed in direct physical contact will eventually reach thermal equilibrium, at which point:", options: ["Heat transfer between them stops, since they have reached the same temperature", "Heat transfer between them becomes maximal", "One object's temperature becomes infinitely high", "Both objects lose all of their internal energy entirely"], correctindex: 0, difficulty: "easy", explanation: "At thermal equilibrium, since both objects are at the same temperature, there is no longer a temperature gradient to drive further net heat flow." },

  // ---------- Heat, Work and Internal Energy Basics ----------
  { id: 7, question: "In thermodynamics, heat is best described as:", options: ["A substance contained within a body", "A property that a body possesses, like mass or volume", "Energy that is transferred between a system and its surroundings solely due to a temperature difference", "A form of mechanical work performed exclusively by external forces"], correctindex: 2, difficulty: "medium", explanation: "Modern thermodynamics defines heat specifically as energy in transit due to a temperature difference, not as a substance a body 'contains'." },
  { id: 8, question: "The internal energy of a thermodynamic system refers to the total energy contained within the system due to the:", options: ["Position of the system relative to some external reference point", "Overall velocity of the system as a whole, moving through space", "Molecular motion (kinetic energy) and intermolecular interactions (potential energy) of its constituent particles", "Total mass of the system alone, with no dependence on molecular motion"], correctindex: 2, difficulty: "medium", explanation: "Internal energy is the sum of microscopic kinetic and potential energies from molecular motion/interactions, distinct from a system's macroscopic (bulk) kinetic or potential energy." },
  { id: 9, question: "Unlike heat and work, which are quantities associated with a thermodynamic process (a change taking place), internal energy is a:", options: ["Process-dependent quantity, just like heat and work", "Purely external quantity, unrelated to the system itself", "Quantity that has no well-defined value at any given instant", "State function, meaning its value depends only on the current state of the system, not on the path taken to reach that state"], correctindex: 3, difficulty: "medium", explanation: "Internal energy is a state function, depending only on the system's current state, unlike heat and work whose values depend on the specific path/process taken." },
  { id: 10, question: "The internal energy of an ideal gas depends only on its:", options: ["Absolute temperature", "Pressure alone, with no dependence on temperature", "Volume alone, with no dependence on temperature", "Shape of the container holding the gas"], correctindex: 0, difficulty: "medium", explanation: "For an ideal gas, internal energy is a function of temperature alone, since there are no intermolecular forces contributing volume/pressure-dependent potential energy." },
  { id: 11, question: "Work done by a thermodynamic system, such as a gas expanding and pushing against a piston, is calculated (for a quasi-static process) as the integral of pressure with respect to:", options: ["Temperature", "Volume", "Time", "Mass"], correctindex: 1, difficulty: "medium", explanation: "The work done by a gas during a quasi-static volume change is W = ∫P dV, the integral of pressure with respect to volume." },
  { id: 12, question: "When a gas expands, doing work on its surroundings (e.g. pushing a piston outward), the work done by the gas is conventionally taken as:", options: ["Negative", "Positive", "Always exactly zero", "Undefined"], correctindex: 1, difficulty: "medium", explanation: "By the standard sign convention, work done BY the gas (as during expansion) is taken as positive." },
  { id: 13, question: "When a gas is compressed by an external agent, with work being done ON the gas, this work (from the gas's perspective, as work done by the gas) is conventionally taken as:", options: ["Negative", "Positive", "Always exactly zero", "Infinite"], correctindex: 0, difficulty: "easy", explanation: "When external work compresses a gas, the work done BY the gas is negative under the standard sign convention." },
  { id: 14, question: "On a pressure-volume (P-V) diagram, the work done by a gas during a given process is represented graphically by:", options: ["The slope of the P-V curve at any point", "The value of pressure at the starting point of the process", "The value of volume at the ending point of the process", "The area under the P-V curve, between the initial and final volumes"], correctindex: 3, difficulty: "medium", explanation: "Since W = ∫P dV, the work done during a process corresponds exactly to the area under the P-V curve between the initial and final volumes." },

  // ---------- First Law of Thermodynamics ----------
  { id: 15, question: "The First Law of Thermodynamics is fundamentally a statement of the principle of conservation of:", options: ["Momentum", "Energy", "Mass alone", "Charge"], correctindex: 1, difficulty: "easy", explanation: "The First Law is the thermodynamic expression of the general principle of conservation of energy, applied to heat, work, and internal energy." },
  { id: 16, question: "The First Law of Thermodynamics can be mathematically expressed as ΔQ = ΔU + ΔW, where ΔQ represents:", options: ["The heat supplied to the system", "The work done on the system", "The change in internal energy of the system", "The total entropy change of the system"], correctindex: 0, difficulty: "easy", explanation: "In the standard form of the First Law, ΔQ represents the heat supplied to the system from its surroundings." },
  { id: 17, question: "In the equation ΔQ = ΔU + ΔW, the term ΔU represents:", options: ["The heat supplied to the system", "The work done by the system", "The change in the internal energy of the system", "The change in the system's entropy"], correctindex: 2, difficulty: "medium", explanation: "ΔU denotes the change in the internal energy of the system between its initial and final states." },
  { id: 18, question: "In the equation ΔQ = ΔU + ΔW, the term ΔW represents:", options: ["The change in internal energy", "The heat supplied to the system", "The work done by the system on its surroundings", "The entropy change"], correctindex: 2, difficulty: "medium", explanation: "ΔW represents the work done BY the system on its surroundings, in this standard form of the First Law." },
  { id: 19, question: "According to the First Law of Thermodynamics, the heat supplied to a system is used partly to increase its internal energy, and partly to:", options: ["Increase the system's mass", "Decrease the system's entropy", "Change the system's chemical composition", "Enable the system to do external work on its surroundings"], correctindex: 3, difficulty: "medium", explanation: "The First Law states heat input is partitioned between raising internal energy and enabling external work, ΔQ = ΔU + ΔW." },
  { id: 20, question: "For a thermodynamic process in which a system's volume remains constant (an isochoric process), the work done by the system, according to the First Law, is:", options: ["Maximum", "Zero", "Negative infinity", "Always equal to the heat supplied"], correctindex: 1, difficulty: "medium", explanation: "Since W = ∫P dV, with no volume change (dV = 0), the work done in an isochoric process is exactly zero." },
  { id: 21, question: "In an isochoric process (constant volume, zero work done), the First Law of Thermodynamics simplifies to show that all the heat supplied to the system goes directly into:", options: ["Doing external work", "Increasing the system's internal energy", "Changing the system's mass", "Decreasing the system's temperature"], correctindex: 1, difficulty: "medium", explanation: "Since ΔW = 0 for an isochoric process, ΔQ = ΔU, meaning all supplied heat directly increases internal energy (and temperature)." },
  { id: 22, question: "For a cyclic process, in which a thermodynamic system returns exactly to its original initial state after undergoing a series of changes, the net change in internal energy over the complete cycle is:", options: ["Zero, since internal energy is a state function and the system returns to its starting state", "Always maximum at the end of the cycle", "Equal to the total heat supplied during the cycle", "Undefined for cyclic processes"], correctindex: 0, difficulty: "medium", explanation: "Since internal energy is a state function and a cyclic process returns to the original state, the net change over one complete cycle is zero." },
  { id: 23, question: "For a cyclic process, since the net change in internal energy is zero, the First Law of Thermodynamics implies that the net heat supplied to the system over the complete cycle equals the:", options: ["Zero, exactly, in every cyclic process", "Change in the system's entropy", "Average temperature of the cycle", "Net work done by the system over the cycle"], correctindex: 3, difficulty: "medium", explanation: "With ΔU = 0 for a full cycle, ΔQ = ΔW, meaning net heat input over the cycle equals net work output." },
  { id: 24, question: "The First Law of Thermodynamics does NOT, by itself, provide any information about:", options: ["Energy conservation during a thermodynamic process", "The direction in which a spontaneous thermodynamic process will naturally proceed", "The relationship between heat, work, and internal energy", "Whether energy is exchanged as heat or as work"], correctindex: 1, difficulty: "medium", explanation: "The First Law only accounts for energy conservation, not which direction a process will naturally occur — that directional information comes from the Second Law." },

  // ---------- Specific Heats of Gases ----------
  { id: 25, question: "The specific heat capacity of a gas at constant volume, denoted Cv, is generally ___ the specific heat capacity of the same gas at constant pressure, denoted Cp.", options: ["Larger than", "Smaller than", "Exactly equal to", "Unrelated to"], correctindex: 1, difficulty: "medium", explanation: "Cp is always greater than Cv, because at constant pressure some heat must also go into external work (expansion), requiring more heat for the same temperature rise." },
  { id: 26, question: "The relationship between the molar specific heats of an ideal gas at constant pressure (Cp) and constant volume (Cv), known as Mayer's relation, is given by:", options: ["Cp − Cv = R", "Cp + Cv = R", "Cp × Cv = R", "Cp/Cv = R"], correctindex: 0, difficulty: "easy", explanation: "Mayer's relation, Cp − Cv = R, quantifies the difference between the two molar specific heats of an ideal gas." },
  { id: 27, question: "The physical reason behind Mayer's relation, Cp − Cv = R, is that at constant pressure, in addition to raising the gas's internal energy (temperature), the supplied heat must also account for:", options: ["A decrease in the gas's volume", "A change in the gas's chemical composition", "The external work done by the gas as it expands against constant pressure", "A change in the gas's mass"], correctindex: 2, difficulty: "medium", explanation: "At constant pressure the gas expands as it's heated, doing work against external pressure, so extra heat is needed for the same temperature rise, accounting for R." },
  { id: 28, question: "The ratio of the specific heats of a gas, Cp/Cv, is commonly denoted by the symbol γ (gamma), and this ratio appears prominently in the equation governing:", options: ["Isothermal processes", "Isobaric processes exclusively", "Adiabatic processes", "Isochoric processes exclusively"], correctindex: 2, difficulty: "medium", explanation: "γ = Cp/Cv is the key parameter in the adiabatic process equation, PV^γ = constant." },
  { id: 29, question: "For a monatomic ideal gas, the value of the specific heat ratio γ is approximately:", options: ["1", "2", "1.33", "1.67 (i.e. 5/3)"], correctindex: 3, difficulty: "medium", explanation: "For a monatomic ideal gas, Cv = (3/2)R and Cp = (5/2)R, giving γ = 5/3 ≈ 1.67." },
  { id: 30, question: "For a diatomic ideal gas (at ordinary temperatures, considering only translational and rotational degrees of freedom), the value of the specific heat ratio γ is approximately:", options: ["1.4 (i.e. 7/5)", "1.67", "1", "2"], correctindex: 0, difficulty: "medium", explanation: "For a diatomic ideal gas, Cv = (5/2)R and Cp = (7/2)R, giving γ = 7/5 = 1.4." },
  { id: 31, question: "For an ideal gas, both Cp and Cv are generally taken to depend on:", options: ["The pressure of the gas alone", "The nature of the gas (specifically, its degrees of freedom/atomicity — monatomic, diatomic, etc.)", "The volume of the gas's container alone", "The shape of the container holding the gas"], correctindex: 1, difficulty: "medium", explanation: "Cp and Cv are determined by the gas's molecular structure (degrees of freedom), not by external conditions like pressure, volume, or container shape." },
  { id: 32, question: "Since Cp − Cv = R for an ideal gas, and Cp is always greater than Cv, this confirms that Cp/Cv (i.e. γ) must always be:", options: ["Less than 1", "Greater than 1", "Exactly equal to 1", "Negative"], correctindex: 1, difficulty: "medium", explanation: "Since Cp > Cv for any ideal gas (as Cp − Cv = R > 0), the ratio γ = Cp/Cv must always be greater than 1." },

  // ---------- Isothermal and Adiabatic Processes ----------
  { id: 33, question: "An isothermal process is a thermodynamic process that occurs at:", options: ["Constant temperature throughout", "Constant pressure throughout", "Constant volume throughout", "Constant entropy throughout"], correctindex: 0, difficulty: "easy", explanation: "An isothermal process is defined as one in which the system's temperature remains constant throughout." },
  { id: 34, question: "For an ideal gas undergoing an isothermal process, since temperature remains constant and internal energy depends only on temperature, the change in internal energy (ΔU) is:", options: ["Maximum", "Negative", "Equal to the heat supplied minus the work done, but never zero", "Zero"], correctindex: 3, difficulty: "medium", explanation: "Since internal energy of an ideal gas depends only on temperature, and temperature is constant, ΔU = 0 throughout an isothermal process." },
  { id: 35, question: "For an ideal gas undergoing an isothermal process, applying the First Law of Thermodynamics (with ΔU = 0) shows that all the heat supplied to the gas is converted directly into:", options: ["An increase in the gas's internal energy", "Work done by the gas", "A change in the gas's mass", "Heat lost to the surroundings, with no work being done"], correctindex: 1, difficulty: "medium", explanation: "Since ΔU = 0, ΔQ = ΔW, meaning all supplied heat converts entirely into work done by the gas." },
  { id: 36, question: "For an isothermal process involving an ideal gas, the relationship between pressure P and volume V is given by:", options: ["PV^γ = constant", "PV = constant", "P/V = constant", "P + V = constant"], correctindex: 1, difficulty: "medium", explanation: "An isothermal process for an ideal gas follows Boyle's law, PV = constant, since PV = nRT and T is fixed." },
  { id: 37, question: "The work done by an ideal gas during an isothermal expansion from volume V1 to volume V2 is given by the formula:", options: ["W = nRT ln(V2/V1)", "W = nRT(V2 − V1), without any logarithm", "W = nRT/(V2 − V1)", "W = nRT × (V2/V1)², squared"], correctindex: 0, difficulty: "medium", explanation: "This is the standard formula for isothermal work, derived by integrating P dV = (nRT/V) dV, giving a natural logarithm term." },
  { id: 38, question: "On a pressure-volume (P-V) diagram, the curve representing an isothermal process for an ideal gas is:", options: ["A straight, horizontal line", "A straight, vertical line", "A hyperbola (following PV = constant)", "A perfect circle"], correctindex: 2, difficulty: "medium", explanation: "Since PV = constant defines an inverse relationship between P and V, the isotherm traced is a hyperbola." },
  { id: 39, question: "An adiabatic process is a thermodynamic process during which:", options: ["Temperature remains exactly constant throughout", "Pressure remains exactly constant throughout", "No heat is exchanged between the system and its surroundings", "Volume remains exactly constant throughout"], correctindex: 2, difficulty: "medium", explanation: "An adiabatic process is defined as one with no heat transfer (Q = 0) between the system and its surroundings." },
  { id: 40, question: "For an ideal gas undergoing an adiabatic process, applying the First Law of Thermodynamics (with ΔQ = 0) shows that:", options: ["The internal energy of the gas remains exactly constant", "Work done by the gas is always exactly zero", "Heat is exchanged, but internal energy remains constant", "Any work done by (or on) the gas comes entirely at the expense of (or addition to) its internal energy"], correctindex: 3, difficulty: "medium", explanation: "Since ΔQ = 0, ΔU = −ΔW, meaning work done by the gas exactly decreases its internal energy (and vice versa for work done on it)." },
  { id: 41, question: "For an adiabatic process involving an ideal gas, the relationship between pressure P and volume V is given by:", options: ["PV = constant", "PV^γ = constant", "P/V^γ = constant", "P + V^γ = constant"], correctindex: 1, difficulty: "medium", explanation: "The adiabatic process equation for an ideal gas is PV^γ = constant, distinct from the simpler PV = constant for isothermal processes." },
  { id: 42, question: "On a pressure-volume (P-V) diagram, comparing an adiabatic curve and an isothermal curve passing through the same initial point, the adiabatic curve is:", options: ["Less steep (shallower) than the isothermal curve", "Steeper than the isothermal curve", "Identical in steepness to the isothermal curve", "A perfectly straight, vertical line"], correctindex: 1, difficulty: "medium", explanation: "Since γ > 1, the adiabatic curve falls more steeply than the isothermal curve for the same starting point." },
  { id: 43, question: "During an adiabatic expansion of an ideal gas (with no heat exchanged, doing positive work on the surroundings), the temperature of the gas:", options: ["Decreases", "Increases", "Remains exactly constant", "Becomes undefined"], correctindex: 0, difficulty: "easy", explanation: "Since work done by the gas comes entirely at the expense of its internal energy with no heat input to compensate, the gas's temperature drops." },
  { id: 44, question: "During an adiabatic compression of an ideal gas (with no heat exchanged, work being done on the gas), the temperature of the gas:", options: ["Decreases", "Remains exactly constant", "Becomes undefined", "Increases"], correctindex: 3, difficulty: "easy", explanation: "Work done ON the gas adds entirely to its internal energy with no heat escaping to compensate, so temperature rises during adiabatic compression." },
  { id: 45, question: "A rapid compression stroke in certain internal combustion engines (e.g. a diesel engine, where fuel ignites due to the heat of compression alone) is a practical example that closely approximates a(n):", options: ["Isothermal process", "Adiabatic process", "Isochoric process", "Constant-entropy-free process, a term with no standard meaning"], correctindex: 1, difficulty: "medium", explanation: "The compression occurs too rapidly for significant heat exchange, closely approximating an adiabatic process, whose temperature rise ignites the diesel fuel." },
  { id: 46, question: "The work done by a gas during an adiabatic process, in terms of the initial and final pressure-volume values (P1V1 and P2V2) and the specific heat ratio γ, is given by the formula:", options: ["W = (P1V1 + P2V2)/(γ − 1)", "W = (P1V1 − P2V2)/(γ − 1)", "W = (P1V1 − P2V2) × (γ − 1)", "W = (P1V1 − P2V2)/(γ + 1)"], correctindex: 1, difficulty: "hard", explanation: "This is the standard formula for adiabatic work, derived from integrating P dV using PV^γ = constant." },

  // ---------- Isochoric, Isobaric, and Cyclic Processes ----------
  { id: 47, question: "An isochoric process is a thermodynamic process that occurs at:", options: ["Constant volume throughout", "Constant pressure throughout", "Constant temperature throughout", "Constant entropy throughout"], correctindex: 0, difficulty: "easy", explanation: "An isochoric (isovolumetric) process is defined as one occurring at constant volume." },
  { id: 48, question: "An isobaric process is a thermodynamic process that occurs at:", options: ["Constant volume throughout", "Constant temperature throughout", "Constant pressure throughout", "Constant entropy throughout"], correctindex: 2, difficulty: "easy", explanation: "An isobaric process is defined as one occurring at constant pressure." },
  { id: 49, question: "The work done by a gas during an isobaric process, as its volume changes from V1 to V2 at constant pressure P, is given by the simple formula:", options: ["W = P/(V2 − V1)", "W = P × V1 × V2", "W = P(V2 − V1)", "W = P ln(V2/V1)"], correctindex: 2, difficulty: "medium", explanation: "Since pressure is constant, the work integral simplifies to W = P × ΔV = P(V2 − V1)." },
  { id: 50, question: "For an isobaric process in which a gas is heated at constant pressure, the heat supplied is used partly to raise the gas's internal energy and partly to:", options: ["Change the gas's pressure, which is held constant by definition", "Decrease the gas's entropy", "Alter the gas's chemical identity", "Do external work as the gas expands against the constant pressure"], correctindex: 3, difficulty: "medium", explanation: "In isobaric heating, the gas's volume must increase (per the ideal gas law), so it does work against the constant external pressure as it expands." },
  { id: 51, question: "On a P-V diagram, an isobaric process is represented by a:", options: ["Vertical straight line", "Horizontal straight line", "Hyperbolic curve", "Steeply falling curve"], correctindex: 1, difficulty: "medium", explanation: "Since pressure remains constant while volume changes, an isobaric process traces a horizontal straight line." },
  { id: 52, question: "On a P-V diagram, an isochoric process is represented by a:", options: ["Horizontal straight line", "Vertical straight line", "Hyperbolic curve", "Circle"], correctindex: 1, difficulty: "medium", explanation: "Since volume remains constant while pressure changes, an isochoric process traces a vertical straight line." },
  { id: 53, question: "A cyclic thermodynamic process is one in which the system, after undergoing a series of changes, eventually:", options: ["Returns exactly to its original initial state", "Ends in a completely different, unrelated state", "Loses all of its internal energy permanently", "Gains an infinite amount of internal energy"], correctindex: 0, difficulty: "easy", explanation: "A cyclic process is defined by the system returning to its exact original thermodynamic state after the complete sequence of changes." },
  { id: 54, question: "On a P-V diagram, a cyclic process is represented by a:", options: ["Single point, since the system does not actually change", "Straight line with no closure", "Curve extending infinitely in one direction", "Closed loop, since the process starts and ends at the same point"], correctindex: 3, difficulty: "medium", explanation: "Because a cyclic process begins and ends at the identical state, it forms a closed loop on a P-V diagram." },

  // ---------- Heat Engines and Efficiency ----------
  { id: 55, question: "A heat engine is a device that converts a portion of the heat energy supplied to it (typically from a high-temperature source) into:", options: ["Purely electrical energy, in every case", "Useful mechanical work", "Purely chemical energy", "Purely nuclear energy"], correctindex: 1, difficulty: "medium", explanation: "A heat engine converts some of the input heat energy into useful mechanical work, rejecting the rest to a lower-temperature sink." },
  { id: 56, question: "A heat engine operates in a cyclic manner, absorbing heat Q1 from a hot reservoir, performing net work W, and rejecting some heat Q2 to a cold reservoir, related by the energy balance equation:", options: ["Q1 = Q2, with W being irrelevant", "Q1 = W + Q2", "Q1 = W − Q2", "W = Q1 + Q2"], correctindex: 1, difficulty: "medium", explanation: "By energy conservation over one complete cycle (ΔU = 0), heat absorbed Q1 equals net work output W plus heat rejected Q2." },
  { id: 57, question: "The efficiency of a heat engine is defined as the ratio of:", options: ["The net work output to the total heat input", "The total heat input to the net work output", "The heat rejected to the heat absorbed", "The temperature of the cold reservoir to that of the hot reservoir"], correctindex: 0, difficulty: "easy", explanation: "Efficiency (η) is defined as η = W/Q1, the fraction of total heat input converted into useful work output." },
  { id: 58, question: "Using the relation Q1 = W + Q2, the efficiency of a heat engine can also be expressed as:", options: ["η = Q1/Q2", "η = Q2/Q1", "η = 1 − (Q2/Q1)", "η = 1 + (Q2/Q1)"], correctindex: 2, difficulty: "medium", explanation: "Substituting W = Q1 − Q2 into η = W/Q1 gives the equivalent, frequently used form η = 1 − (Q2/Q1)." },
  { id: 59, question: "No real heat engine can achieve an efficiency of 100%, since this would require the engine to:", options: ["Reject an infinite amount of heat to the cold reservoir", "Absorb no heat at all from the hot reservoir", "Convert all the absorbed heat into work with no heat rejected to the cold reservoir at all, which is impossible according to the Second Law of Thermodynamics", "Operate at a temperature of exactly 0 K"], correctindex: 2, difficulty: "medium", explanation: "A 100% efficient heat engine would need zero heat rejection — precisely what the Second Law (Kelvin-Planck statement) forbids for a cyclic process." },
  { id: 60, question: "The efficiency of a heat engine, being a ratio of two quantities with the same units (energy), is:", options: ["Measured in joules", "Measured in watts", "Measured in kelvin", "A dimensionless quantity, often expressed as a percentage"], correctindex: 3, difficulty: "medium", explanation: "Since efficiency is the ratio of work output to heat input (both in the same energy units), it is inherently dimensionless." },
  { id: 61, question: "The maximum possible theoretical efficiency for a heat engine operating between two given temperatures is achieved by a:", options: ["Standard petrol/gasoline engine", "Carnot engine (an idealised, reversible engine)", "Diesel engine, exclusively", "Steam engine, exclusively"], correctindex: 1, difficulty: "medium", explanation: "The Carnot engine represents the theoretical upper limit of efficiency for any engine operating between two fixed temperatures, since it uses only reversible processes." },
  { id: 62, question: "In practice, real heat engines always have an efficiency ___ that of an ideal, reversible Carnot engine operating between the same two temperatures.", options: ["Greater than", "Less than", "Exactly equal to", "Completely unrelated to"], correctindex: 1, difficulty: "medium", explanation: "Real engines involve irreversibilities (friction, non-quasi-static processes), so their actual efficiency always falls below the Carnot efficiency." },
  { id: 63, question: "Increasing the temperature of the hot reservoir (source) supplying heat to a heat engine, while keeping the cold reservoir (sink) temperature fixed, generally:", options: ["Increases the theoretical maximum efficiency of the engine", "Decreases the theoretical maximum efficiency of the engine", "Has no effect on the theoretical efficiency at all", "Makes the engine's efficiency undefined"], correctindex: 0, difficulty: "medium", explanation: "Since Carnot efficiency is η = 1 − (T2/T1), increasing T1 (with T2 fixed) increases the theoretical maximum efficiency." },
  { id: 64, question: "Decreasing the temperature of the cold reservoir (sink) to which a heat engine rejects heat, while keeping the hot reservoir temperature fixed, generally:", options: ["Decreases the theoretical maximum efficiency of the engine", "Has no effect on the theoretical efficiency at all", "Makes the theoretical efficiency undefined", "Increases the theoretical maximum efficiency of the engine"], correctindex: 3, difficulty: "medium", explanation: "Since η = 1 − (T2/T1), decreasing T2 (with T1 fixed) increases the theoretical maximum efficiency." },

  // ---------- The Carnot Engine ----------
  { id: 65, question: "The Carnot cycle, an idealised, fully reversible thermodynamic cycle, consists of two isothermal processes and two:", options: ["Isobaric processes", "Adiabatic processes", "Isochoric processes", "Cyclic processes, a term that doesn't fit here"], correctindex: 1, difficulty: "medium", explanation: "The Carnot cycle consists of two isothermal processes (heat absorption/rejection) and two adiabatic processes (compression/expansion with no heat exchange)." },
  { id: 66, question: "In the Carnot cycle, heat is absorbed from the hot reservoir during a(n):", options: ["Adiabatic expansion", "Isothermal expansion", "Isothermal compression", "Adiabatic compression"], correctindex: 1, difficulty: "medium", explanation: "Heat absorption occurs during the isothermal expansion stage, where the working substance expands at constant hot-reservoir temperature." },
  { id: 67, question: "In the Carnot cycle, heat is rejected to the cold reservoir during a(n):", options: ["Isothermal compression", "Isothermal expansion", "Adiabatic expansion", "Adiabatic compression exclusively, with no heat rejection involved"], correctindex: 0, difficulty: "medium", explanation: "Heat rejection occurs during the isothermal compression stage, at constant cold-reservoir temperature." },
  { id: 68, question: "The efficiency of a Carnot engine operating between a hot reservoir at absolute temperature T1 and a cold reservoir at absolute temperature T2 is given by the formula:", options: ["η = T2/T1", "η = T1/T2", "η = T1 − T2", "η = 1 − (T2/T1)"], correctindex: 3, difficulty: "easy", explanation: "This is the standard Carnot efficiency formula, showing efficiency depends only on the reservoirs' absolute temperatures, not the working substance." },
  { id: 69, question: "A key theoretical result, known as Carnot's theorem, states that no heat engine operating between two given temperatures can be more efficient than a:", options: ["Standard internal combustion engine operating between the same temperatures", "Reversible Carnot engine operating between the same two temperatures", "Refrigerator operating between the same two temperatures", "Engine using a specific, particular working substance, such as steam"], correctindex: 1, difficulty: "medium", explanation: "Carnot's theorem establishes the reversible Carnot engine as the absolute upper bound on efficiency for any engine between two fixed temperatures." },
  { id: 70, question: "According to the Carnot efficiency formula, a Carnot engine can only achieve 100% efficiency (η = 1) if the cold reservoir temperature T2 is:", options: ["Equal to the hot reservoir temperature T1", "Equal to absolute zero (0 K)", "Equal to room temperature", "Negative, in absolute temperature terms"], correctindex: 1, difficulty: "medium", explanation: "Setting η = 1 − (T2/T1) = 1 requires T2 = 0 K — a physically unattainable condition, which is why no engine can be 100% efficient." },
  { id: 71, question: "Since the Carnot engine's efficiency depends only on the absolute temperatures of the two reservoirs, it is entirely independent of the:", options: ["Particular working substance used in the engine", "Temperature difference between the reservoirs", "Existence of a hot and a cold reservoir at all", "Numerical value of either reservoir's temperature"], correctindex: 0, difficulty: "medium", explanation: "A striking result of Carnot's analysis is that theoretical efficiency depends only on the two reservoir temperatures, not on the specific working substance used." },
  { id: 72, question: "The Carnot engine, being a purely theoretical, idealised construct based on fully reversible processes, serves primarily as a:", options: ["Practical, commercially built engine used in modern vehicles", "Device that can be constructed cheaply for everyday use", "Benchmark/upper theoretical limit against which the performance of real, practical heat engines can be compared", "Type of refrigerator, and has no relevance to heat engines"], correctindex: 2, difficulty: "medium", explanation: "Because it assumes idealised reversibility, the Carnot engine cannot be built in practice but serves as the crucial theoretical benchmark for real engine performance." },

  // ---------- Refrigerators and the Second Law ----------
  { id: 73, question: "A refrigerator can be thought of as a device that operates essentially like a heat engine running in reverse, since it uses external work to:", options: ["Convert heat entirely into work, with no heat rejection", "Extract heat from a cold region (the interior) and expel it to a hotter region (the surroundings)", "Generate heat spontaneously without any external work input", "Eliminate the need for any temperature difference at all"], correctindex: 1, difficulty: "medium", explanation: "A refrigerator uses external work to pump heat from a colder space to a warmer space, the reverse of the natural direction heat would otherwise flow." },
  { id: 74, question: "The performance of a refrigerator is quantified by its coefficient of performance (COP), defined as the ratio of the heat extracted from the cold reservoir to the:", options: ["Heat rejected to the hot reservoir", "Work input required to achieve this heat extraction", "Temperature of the cold reservoir alone", "Temperature of the hot reservoir alone"], correctindex: 1, difficulty: "medium", explanation: "COP is defined as β = Q2/W, the ratio of heat extracted from the cold space to the external work input required." },
  { id: 75, question: "Unlike the efficiency of a heat engine, which is always less than 1, the coefficient of performance of a refrigerator:", options: ["Can be greater than 1, and often is, for practical refrigerators", "Must always be exactly equal to 1", "Must always be less than 1, just like engine efficiency", "Is always negative"], correctindex: 0, difficulty: "medium", explanation: "COP can exceed 1 (and often does), since it compares heat moved to work input, not heat converted to work." },
  { id: 76, question: "The Second Law of Thermodynamics, in its Kelvin-Planck statement, asserts that it is impossible to construct a device that operates in a cycle and:", options: ["Converts work entirely into heat, with no other effect", "Transfers heat from a hot body to a cold body, with no other effect", "Absorbs heat and rejects an equal amount of heat, doing no work at all", "Absorbs heat from a single reservoir and converts it completely into an equivalent amount of work, with no other effect"], correctindex: 3, difficulty: "hard", explanation: "The Kelvin-Planck statement forbids a cyclic device from converting heat from a single reservoir entirely into work with no other effect — i.e. forbids a 100%-efficient heat engine." },
  { id: 77, question: "The Second Law of Thermodynamics, in its Clausius statement, asserts that it is impossible for heat to flow spontaneously (without any external work input) from a:", options: ["Hotter body to a colder body", "Colder body to a hotter body", "Body to itself, which is a trivial and meaningless statement", "Vacuum to any material body"], correctindex: 1, difficulty: "medium", explanation: "The Clausius statement forbids heat from spontaneously flowing from a colder to a hotter body without external work — why a refrigerator needs work input." },
  { id: 78, question: "The Kelvin-Planck and Clausius statements of the Second Law of Thermodynamics, though phrased differently, have been shown to be:", options: ["Completely unrelated and independent of each other", "Logically equivalent to one another; violating one implies violating the other", "Contradictory statements that cannot both be true", "Only applicable to engines, with the Clausius statement having no relevance to refrigerators"], correctindex: 1, difficulty: "medium", explanation: "Although phrased differently, the two statements are logically equivalent formulations of the same underlying Second Law." },
  { id: 79, question: "Entropy, a thermodynamic quantity central to the Second Law, is often described as a measure of the degree of:", options: ["Disorder or randomness within a system", "Total mass within a system", "Total mechanical energy within a system", "Electric charge within a system"], correctindex: 0, difficulty: "easy", explanation: "Entropy is commonly interpreted, at the statistical/molecular level, as a measure of the disorder or randomness of a system's microscopic arrangement." },
  { id: 80, question: "According to the Second Law of Thermodynamics, the total entropy of an isolated system (and, more broadly, of the universe as a whole) undergoing any spontaneous, natural (irreversible) process:", options: ["Always decreases", "Always remains exactly constant", "Becomes negative", "Never decreases; it either increases or, for an idealised reversible process, remains constant"], correctindex: 3, difficulty: "medium", explanation: "The Second Law states total entropy of an isolated system can never decrease — it increases for real irreversible processes and stays constant only for idealised reversible ones." },

];

export default questions;