import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Magnetism and Matter
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, type, question, options[4], correctIndex (index 0-3), explanation, difficulty }
// Note: correct-answer positions are randomised with a roughly even spread across A/B/C/D (no repeating cycle).

const questions: Question[] = [

  // ---------- Bar Magnet and Magnetic Dipole ----------
  { id: 'magnetism-1', type: "mcq", question: "Every magnet, regardless of its shape, is found to possess two poles, referred to as its:", options: ["North pole and South pole", "Axial pole and equatorial pole", "Positive pole and negative pole", "East pole and West pole"], correctIndex: 0, explanation: "A fundamental property of magnets is that they always have two poles, conventionally called the north pole and the south pole.", difficulty: "easy" },
  { id: 'magnetism-2', type: "mcq", question: "Unlike electric charges, which can exist in isolation as either purely positive or purely negative, magnetic poles:", options: ["Can also exist in isolation, as either a pure north pole or a pure south pole", "Do not exist at all, in any form", "Exist only in superconducting materials", "Always occur in pairs (as a north pole and a south pole together); an isolated magnetic monopole has never been experimentally observed"], correctIndex: 3, explanation: "A key distinction from electric charge is that magnetic poles always occur in north-south pairs; no isolated magnetic monopole has ever been experimentally detected.", difficulty: "medium" },
  { id: 'magnetism-3', type: "mcq", question: "If a bar magnet is cut into two equal halves, each half will:", options: ["Become a new, complete magnet with both a north pole and a south pole", "Have only a south pole, with no north pole", "Lose all of its magnetic properties entirely", "Have only a north pole, with no south pole"], correctIndex: 0, explanation: "Cutting a bar magnet does not isolate individual poles; each resulting piece becomes a smaller but complete magnet with both poles.", difficulty: "medium" },
  { id: 'magnetism-4', type: "mcq", question: "The magnetic dipole moment of a bar magnet, analogous to the electric dipole moment, is defined as the product of the pole strength and the:", options: ["Distance between the two poles (the magnetic length)", "Volume of the magnet", "Cross-sectional area of the magnet", "Mass of the magnet"], correctIndex: 0, explanation: "Magnetic dipole moment m is defined as m = qm × 2l, the product of pole strength and the distance between the two poles.", difficulty: "medium" },
  { id: 'magnetism-5', type: "mcq", question: "The SI unit of magnetic dipole moment is:", options: ["Weber (Wb)", "Ampere-metre² (A·m²)", "Henry (H)", "Tesla (T)"], correctIndex: 1, explanation: "Magnetic dipole moment has the SI unit ampere-metre squared (A·m²).", difficulty: "easy" },
  { id: 'magnetism-6', type: "mcq", question: "The direction of the magnetic dipole moment vector of a bar magnet is conventionally taken to point:", options: ["From the north pole towards the south pole, inside the magnet", "From the south pole towards the north pole, inside the magnet", "In a direction that varies randomly", "Perpendicular to the line joining the two poles"], correctIndex: 1, explanation: "By convention, the magnetic dipole moment vector points from the south pole to the north pole, along the magnet's axis.", difficulty: "medium" },
  { id: 'magnetism-7', type: "mcq", question: "Magnetic field lines around a bar magnet, external to the magnet itself, are conventionally drawn:", options: ["Emerging from the south pole and entering the north pole", "Only within the interior of the magnet, never outside it", "Emerging from the north pole and entering the south pole", "Forming straight lines with no curvature at all"], correctIndex: 2, explanation: "Outside a bar magnet, field lines conventionally emerge from the north pole and curve to enter the south pole.", difficulty: "medium" },
  { id: 'magnetism-8', type: "mcq", question: "A key property of magnetic field lines is that they always form:", options: ["Random, unpredictable patterns", "Lines that intersect each other at multiple points", "Continuous closed loops, since magnetic field lines have no beginning or end", "Straight, open lines that never close"], correctIndex: 2, explanation: "Unlike electric field lines, magnetic field lines always form closed loops, continuing inside the magnet from south back to north.", difficulty: "medium" },
  { id: 'magnetism-9', type: "mcq", question: "The fact that magnetic field lines never begin or end at a single point (unlike electric field lines, which begin/end on charges) reflects the physical fact that:", options: ["Magnetic fields are always weaker than electric fields", "Isolated magnetic monopoles (a single, isolated magnetic 'charge') do not exist in nature", "Magnetic fields do not actually exist", "Magnetic poles have infinite strength"], correctIndex: 1, explanation: "The closed-loop nature of magnetic field lines directly reflects the non-existence of isolated magnetic monopoles.", difficulty: "medium" },
  { id: 'magnetism-10', type: "mcq", question: "Two magnetic field lines can never intersect each other at any point, because if they did, it would imply that the magnetic field at that point has:", options: ["Zero magnitude", "No physical meaning at all", "Infinite magnitude", "Two different directions simultaneously, which is physically impossible for a well-defined field"], correctIndex: 3, explanation: "Intersecting field lines would imply the field has two different directions at that point, not physically meaningful for a well-defined vector field.", difficulty: "medium" },
  { id: 'magnetism-11', type: "mcq", question: "The density (closeness) of magnetic field lines drawn in a given region is representative of the:", options: ["Temperature of the magnet", "Electric charge present in that region", "Strength (magnitude) of the magnetic field in that region", "Direction of the magnetic field alone, with no information about strength"], correctIndex: 2, explanation: "Where field lines are drawn closer together, the field is stronger; more spread apart means weaker field.", difficulty: "medium" },
  { id: 'magnetism-12', type: "mcq", question: "A small compass needle placed in an external magnetic field will align itself such that its own magnetic dipole moment points:", options: ["In the same direction as the external magnetic field at that point", "In the direction opposite to the external magnetic field", "In a random, unpredictable direction", "Perpendicular to the external field"], correctIndex: 0, explanation: "A compass needle experiences a torque that aligns its dipole moment parallel to the field direction at its location.", difficulty: "medium" },

  // ---------- Magnetic Field due to a Bar Magnet ----------
  { id: 'magnetism-13', type: "mcq", question: "The magnetic field at a point on the axial line of a bar magnet (i.e. along the line extending through both poles), at a distance r from the centre of the magnet (with r much greater than the magnet's length), is given by the formula:", options: ["B = (μ0/4π) × (2m/r²)", "B = (μ0/4π) × (m/r³)", "B = (μ0/4π) × (m/r²)", "B = (μ0/4π) × (2m/r³)"], correctIndex: 3, explanation: "This is the standard formula for the magnetic field at an axial point of a bar magnet, treated as a dipole.", difficulty: "medium" },
  { id: 'magnetism-14', type: "mcq", question: "The magnetic field at a point on the equatorial line of a bar magnet (i.e. on the perpendicular bisector of the line joining the two poles), at a distance r from the centre, is given by the formula:", options: ["B = (μ0/4π) × (2m/r²)", "B = (μ0/4π) × (2m/r³)", "B = (μ0/4π) × (m/r²)", "B = (μ0/4π) × (m/r³)"], correctIndex: 3, explanation: "This is the standard formula for the magnetic field at an equatorial point, exactly half the axial field at the same distance.", difficulty: "medium" },
  { id: 'magnetism-15', type: "mcq", question: "Comparing the magnetic field at equal distances from the centre of a bar magnet, the axial field is found to be:", options: ["Half the magnitude of the equatorial field", "Twice the magnitude of the equatorial field", "Four times the magnitude of the equatorial field", "Equal in magnitude to the equatorial field"], correctIndex: 1, explanation: "Comparing the two formulas shows the axial field is exactly twice as strong as the equatorial field at the same distance.", difficulty: "medium" },
  { id: 'magnetism-16', type: "mcq", question: "The magnetic field due to a bar magnet, at points far from the magnet (large r), decreases with distance approximately as:", options: ["1/r²", "1/r³", "1/r⁴", "1/r"], correctIndex: 1, explanation: "Both axial and equatorial field formulas show an inverse-cube dependence (1/r³), characteristic of a dipole field.", difficulty: "medium" },
  { id: 'magnetism-17', type: "mcq", question: "The direction of the magnetic field at an axial point of a bar magnet (for a point beyond the north pole) is:", options: ["Along the same direction as the magnetic dipole moment of the magnet", "Always directed vertically downward, regardless of the magnet's orientation", "Opposite to the direction of the magnetic dipole moment", "Perpendicular to the magnet's axis"], correctIndex: 0, explanation: "At an axial point, the resultant field points in the same direction as the magnet's own dipole moment vector.", difficulty: "medium" },
  { id: 'magnetism-18', type: "mcq", question: "The direction of the magnetic field at an equatorial point of a bar magnet is:", options: ["Along the same direction as the magnetic dipole moment", "Perpendicular to the magnet's axis", "Opposite (antiparallel) to the direction of the magnetic dipole moment", "Always directed vertically upward, regardless of the magnet's orientation"], correctIndex: 2, explanation: "At an equatorial point, the resultant field points opposite (antiparallel) to the magnet's dipole moment vector.", difficulty: "medium" },
  { id: 'magnetism-19', type: "mcq", question: "A bar magnet, when treated as a magnetic dipole, can be mathematically analysed using formulas that closely parallel those used for an electric dipole, reflecting the underlying:", options: ["Complete lack of any similarity between electric and magnetic phenomena", "Difference in the physical units used for each type of dipole", "Fact that magnetic dipoles are simply electric dipoles with reversed charge", "Mathematical (and, in the modern view via Ampere's model, physical) analogy between electric and magnetic dipole moments"], correctIndex: 3, explanation: "The formulas for the field of a bar magnet closely mirror those for an electric dipole, reflecting the deep mathematical analogy between the two.", difficulty: "medium" },
  { id: 'magnetism-20', type: "mcq", question: "The concept of a magnetic dipole approximation for a bar magnet, used in the axial and equatorial field formulas, is valid specifically when the distance r from the magnet is:", options: ["Exactly equal to the physical length of the magnet", "Much greater than the physical length of the magnet itself", "Completely unrelated to the magnet's own physical length", "Much smaller than the physical length of the magnet itself"], correctIndex: 1, explanation: "The simple dipole formulas are approximations valid for points far from the magnet (r >> length of the magnet).", difficulty: "medium" },
  { id: 'magnetism-21', type: "mcq", question: "According to Ampere's hypothesis regarding the origin of magnetism in materials, every atom of a magnetic material behaves like a tiny current loop, which itself acts as a:", options: ["Source of gravitational field", "Perfectly non-magnetic entity", "Small magnetic dipole", "Point electric charge"], correctIndex: 2, explanation: "Ampere proposed that magnetism arises from tiny current loops at the atomic level, each acting as a small magnetic dipole.", difficulty: "medium" },
  { id: 'magnetism-22', type: "mcq", question: "The modern understanding of magnetism, building on Ampere's original hypothesis, attributes the magnetic properties of materials to the motion of:", options: ["Neutrons within the atomic nucleus alone", "Protons within the atomic nucleus alone", "Electrons (both their orbital motion around the nucleus and their intrinsic spin)", "The atomic nucleus as a whole, with no contribution from electrons"], correctIndex: 2, explanation: "Modern physics attributes material magnetism primarily to electron motion — both orbital motion and intrinsic spin.", difficulty: "medium" },

  // ---------- Gauss's Law for Magnetism ----------
  { id: 'magnetism-23', type: "mcq", question: "Gauss's law for magnetism states that the net magnetic flux through any closed surface is always:", options: ["Dependent on the shape of the closed surface", "Maximum", "Equal to the enclosed magnetic pole strength", "Zero"], correctIndex: 3, explanation: "Gauss's law for magnetism states the total magnetic flux through any closed surface is always exactly zero.", difficulty: "easy" },
  { id: 'magnetism-24', type: "mcq", question: "The physical basis for Gauss's law for magnetism (net flux through a closed surface = 0) is the fact that:", options: ["Magnetic field lines are always straight and never curve", "Magnetic fields are always uniform in every region of space", "Magnetic fields do not actually exist", "Magnetic monopoles do not exist, so every field line entering a closed surface must also exit it"], correctIndex: 3, explanation: "Since magnetic field lines form closed loops with no isolated source/sink, any line entering a closed surface must also exit it." , difficulty: "medium" },
  { id: 'magnetism-25', type: "mcq", question: "Gauss's law for magnetism can be contrasted with Gauss's law for electricity, which states that the net electric flux through a closed surface is proportional to the enclosed:", options: ["Mass", "Electric charge", "Magnetic dipole moment", "Magnetic pole strength"], correctIndex: 1, explanation: "Gauss's law for electricity relates net electric flux to the total electric charge enclosed within a surface.", difficulty: "medium" },
  { id: 'magnetism-26', type: "mcq", question: "The key structural difference between Gauss's law for electricity and Gauss's law for magnetism directly reflects the fact that:", options: ["Electric fields do not exist at all", "Isolated electric charges exist, while isolated magnetic charges (monopoles) do not", "Magnetic fields are always stronger than electric fields", "There is no meaningful difference between the two laws"], correctIndex: 1, explanation: "The non-zero source term in Gauss's law for electricity (charge), versus the always-zero result for magnetism, reflects the non-existence of magnetic monopoles.", difficulty: "medium" },
  { id: 'magnetism-27', type: "mcq", question: "Gauss's law for magnetism is considered one of the four fundamental equations of classical electromagnetism, known collectively as:", options: ["The laws of thermodynamics", "Kepler's laws", "Maxwell's equations", "Newton's laws"], correctIndex: 2, explanation: "Gauss's law for magnetism is one of the four Maxwell's equations forming the complete classical theory of electromagnetism.", difficulty: "medium" },
  { id: 'magnetism-28', type: "mcq", question: "The statement 'net magnetic flux through any closed surface is zero' applies to:", options: ["Only specific, symmetric closed surfaces, such as spheres", "Any closed surface whatsoever, regardless of its shape or what magnetic sources it may enclose", "Only surfaces enclosing a bar magnet specifically", "Only open, non-closed surfaces"], correctIndex: 1, explanation: "Gauss's law for magnetism is completely general, holding for any closed surface regardless of shape or enclosed sources.", difficulty: "medium" },

  // ---------- Earth's Magnetism ----------
  { id: 'magnetism-29', type: "mcq", question: "The Earth itself behaves approximately like a giant magnetic dipole, with its magnetic field originating primarily from:", options: ["A large, permanently magnetised iron bar buried at the Earth's centre", "The gravitational interaction between the Earth and the Moon", "Electric currents generated by the motion of molten, conducting material in the Earth's outer core", "Radioactive decay processes in the Earth's crust"], correctIndex: 2, explanation: "The Earth's magnetic field is understood to arise from a 'geodynamo' — currents generated by convective motion in the molten outer core.", difficulty: "medium" },
  { id: 'magnetism-30', type: "mcq", question: "The Earth's magnetic south pole is located, somewhat counter-intuitively, near the Earth's geographic:", options: ["Equator", "North pole", "Centre", "South pole"], correctIndex: 1, explanation: "Because a compass's north pole points toward Earth's geographic north, the Earth's actual magnetic south pole is located near the geographic north pole.", difficulty: "medium" },
  { id: 'magnetism-31', type: "mcq", question: "The angle between the geographic meridian (the plane containing the true geographic north-south direction) and the magnetic meridian (the vertical plane containing the Earth's magnetic field direction at a point) is called the:", options: ["Magnetic dip (inclination)", "Magnetic latitude", "Magnetic declination", "Horizontal component of the Earth's field"], correctIndex: 2, explanation: "Magnetic declination is the angle between true (geographic) north and magnetic north at a given location.", difficulty: "medium" },
  { id: 'magnetism-32', type: "mcq", question: "The angle that the Earth's total magnetic field vector makes with the horizontal, at a given point on the Earth's surface, is called the:", options: ["Magnetic dip (or angle of inclination)", "Magnetic latitude", "Magnetic declination", "Magnetic meridian angle"], correctIndex: 0, explanation: "Magnetic dip (inclination) is the angle the Earth's total field vector makes with the horizontal plane at a location.", difficulty: "medium" },
  { id: 'magnetism-33', type: "mcq", question: "At the Earth's magnetic equator, the value of the magnetic dip (angle of inclination) is:", options: ["180°", "0°, since the field is purely horizontal there", "90°", "45°"], correctIndex: 1, explanation: "At the magnetic equator, the field is oriented purely horizontally, giving a dip angle of 0°.", difficulty: "medium" },
  { id: 'magnetism-34', type: "mcq", question: "At the Earth's magnetic poles, the value of the magnetic dip (angle of inclination) is:", options: ["45°", "0°", "30°", "90°, since the field is oriented purely vertically there"], correctIndex: 3, explanation: "At the magnetic poles, the field points purely vertically, giving a dip angle of 90°.", difficulty: "medium" },
  { id: 'magnetism-35', type: "mcq", question: "The Earth's total magnetic field at a given point can be resolved into two perpendicular components: a horizontal component and a:", options: ["Diagonal component", "Tangential component, unrelated to the field direction", "Radial component, unrelated to the field direction", "Vertical component"], correctIndex: 3, explanation: "The Earth's field vector is commonly resolved into a horizontal component (H) and a vertical component (Z).", difficulty: "medium" },
  { id: 'magnetism-36', type: "mcq", question: "Declination, dip, and the horizontal component of the Earth's magnetic field are together known as the three:", options: ["Elements of the Earth's magnetic field", "Types of magnetic materials", "Laws of magnetism", "Forms of magnetic monopoles"], correctIndex: 0, explanation: "These three quantities are collectively known as the elements of the Earth's magnetic field, fully specifying the field at any location.", difficulty: "medium" },
  { id: 'magnetism-37', type: "mcq", question: "Knowing the horizontal component (H) and the angle of dip (δ) at a location, the vertical component (Z) and the total magnetic field (B) of the Earth's field at that location can be calculated using the relations:", options: ["Z = H/δ, and B = H − Z", "Z = H cos δ, and B = H sin δ", "Z = H tan δ, and B = H/cos δ", "Z = H × δ, and B = H + Z"], correctIndex: 2, explanation: "From the geometric relationship, Z = H tan δ and B = H/cos δ (equivalently B = √(H² + Z²))." , difficulty: "hard" },
  { id: 'magnetism-38', type: "mcq", question: "In India, which lies at relatively low geomagnetic latitudes, the angle of dip is generally found to be:", options: ["Exactly 90° everywhere in the country", "Exactly 0° everywhere in the country", "Moderate, i.e. neither 0° nor 90°, varying by specific location", "Undefined, since dip cannot be measured in tropical regions"], correctIndex: 2, explanation: "Since India lies at moderate geomagnetic latitudes, the dip observed varies by location, generally moderate rather than at either extreme.", difficulty: "medium" },
  { id: 'magnetism-39', type: "mcq", question: "The magnetic declination at a given location on Earth's surface arises because the Earth's magnetic axis (connecting its magnetic poles) is:", options: ["Exactly aligned with the Earth's rotational (geographic) axis, with no tilt at all", "Located at the Earth's exact centre, with no external effect", "Completely unrelated to the geographic poles", "Tilted at an angle relative to the Earth's rotational (geographic) axis, and the two sets of poles do not exactly coincide"], correctIndex: 3, explanation: "Because the Earth's magnetic axis is tilted relative to its geographic axis, magnetic north differs from true north at most locations.", difficulty: "medium" },
  { id: 'magnetism-40', type: "mcq", question: "Earth's magnetic field is important not only for compass navigation, but also because it helps to:", options: ["Directly increase the Earth's average surface temperature", "Prevent all earthquakes from occurring", "Have no scientific or practical significance beyond compass navigation", "Shield the Earth's surface (to a significant extent) from potentially harmful charged particles arriving from the Sun (the solar wind)"], correctIndex: 3, explanation: "The Earth's magnetic field deflects much of the charged particle radiation (solar wind) that would otherwise bombard the atmosphere and surface.", difficulty: "medium" },

  // ---------- Magnetization and Magnetic Intensity ----------
  { id: 'magnetism-41', type: "mcq", question: "The process by which a material acquires or develops a net magnetic dipole moment, when placed in an external magnetic field, is called:", options: ["Polarisation", "Conduction", "Magnetization", "Ionisation"], correctIndex: 2, explanation: "Magnetization refers to the process by which a material develops a net magnetic moment per unit volume in response to an applied field.", difficulty: "medium" },
  { id: 'magnetism-42', type: "mcq", question: "Magnetization (M) of a material is defined as the net magnetic dipole moment per unit:", options: ["Volume of the material", "Length of the material", "Mass of the material", "Surface area of the material"], correctIndex: 0, explanation: "Magnetization is defined as the net magnetic dipole moment per unit volume of the material.", difficulty: "medium" },
  { id: 'magnetism-43', type: "mcq", question: "Magnetic field intensity (H), a quantity related to but distinct from the magnetic field B, is defined in terms of the free currents present, independent of the material's own internal magnetisation. The relationship between B, H, and magnetization M is given by:", options: ["B = μ0(H + M)", "B = μ0(H − M)", "B = μ0 × H × M", "B = H + μ0M"], correctIndex: 0, explanation: "This standard relation, B = μ0(H + M), connects total field B to applied field intensity H and the material's magnetization M.", difficulty: "hard" },
  { id: 'magnetism-44', type: "mcq", question: "Magnetic susceptibility (χ) of a material is defined as the ratio of magnetization (M) to the applied magnetic field intensity (H), and quantifies:", options: ["The material's electrical resistance", "The material's density", "The material's specific heat capacity", "How readily/strongly a material becomes magnetised in response to an applied magnetic field"], correctIndex: 3, explanation: "Magnetic susceptibility, χ = M/H, quantifies how strongly a material becomes magnetised in response to an applied field.", difficulty: "medium" },
  { id: 'magnetism-45', type: "mcq", question: "A material with a negative value of magnetic susceptibility is classified as being:", options: ["Non-magnetic, with no classification at all", "Diamagnetic", "Paramagnetic", "Ferromagnetic"], correctIndex: 1, explanation: "Diamagnetic materials are characterised by a small, negative magnetic susceptibility.", difficulty: "medium" },
  { id: 'magnetism-46', type: "mcq", question: "A material with a small, positive value of magnetic susceptibility is classified as being:", options: ["Paramagnetic", "Superconducting, with no other classification needed", "Diamagnetic", "Ferromagnetic"], correctIndex: 0, explanation: "Paramagnetic materials are characterised by a small, positive magnetic susceptibility.", difficulty: "medium" },
  { id: 'magnetism-47', type: "mcq", question: "A material with a very large, positive value of magnetic susceptibility, capable of retaining significant magnetization even after the external field is removed, is classified as being:", options: ["Antiferromagnetic, a category not covered at this level", "Paramagnetic", "Ferromagnetic", "Diamagnetic"], correctIndex: 2, explanation: "Ferromagnetic materials show very large, positive susceptibility and can retain substantial magnetization after the field is removed.", difficulty: "medium" },
  { id: 'magnetism-48', type: "mcq", question: "Relative permeability (μr) of a material, related to magnetic susceptibility by μr = 1 + χ, is a dimensionless quantity that measures:", options: ["The material's melting point relative to a reference substance", "The density of the material relative to water", "How much more (or less) easily magnetic field lines pass through the material compared to a vacuum", "The electrical conductivity of the material"], correctIndex: 2, explanation: "Relative permeability quantifies how much more or less readily magnetic field lines penetrate a material compared to a vacuum.", difficulty: "medium" },

  // ---------- Diamagnetism ----------
  { id: 'magnetism-49', type: "mcq", question: "Diamagnetic materials are characterised by the property that, when placed in an external magnetic field, they develop a weak induced magnetization in a direction:", options: ["Identical to the direction of the applied field", "Perpendicular to the applied field", "Random and unpredictable", "Opposite to the direction of the applied field"], correctIndex: 3, explanation: "Diamagnetic materials develop weak magnetization directed opposite to the applied external field.", difficulty: "easy" },
  { id: 'magnetism-50', type: "mcq", question: "Diamagnetic materials, when placed in a non-uniform magnetic field, tend to experience a force directing them:", options: ["In a direction unrelated to field strength", "Exactly along the field lines, regardless of field strength variation", "Towards regions of stronger magnetic field", "Away from regions of stronger magnetic field, towards weaker field regions"], correctIndex: 3, explanation: "Because diamagnetic materials develop opposite magnetization, they experience weak repulsion from stronger-field regions.", difficulty: "medium" },
  { id: 'magnetism-51', type: "mcq", question: "Diamagnetism arises in materials whose constituent atoms/molecules have:", options: ["No net (permanent) magnetic dipole moment in the absence of an external field", "A strong net (permanent) magnetic dipole moment even in the absence of an external field", "Free, unpaired electrons in every atomic orbital", "A permanently aligned magnetic domain structure"], correctIndex: 0, explanation: "Diamagnetism dominates specifically in materials whose atoms have no net permanent magnetic dipole moment, typically due to paired electrons.", difficulty: "medium" },
  { id: 'magnetism-52', type: "mcq", question: "Diamagnetism is present, at least weakly, in all materials, but it is generally only the dominant, observable effect in substances that do not also exhibit:", options: ["Any measurable mass", "Thermal expansion", "Electrical conductivity", "Stronger paramagnetic or ferromagnetic behaviour, which would otherwise mask the weak diamagnetic response"], correctIndex: 3, explanation: "Since diamagnetism is a weak effect, it's only clearly observable in materials lacking stronger paramagnetic or ferromagnetic responses.", difficulty: "medium" },
  { id: 'magnetism-53', type: "mcq", question: "Which of the following is a classic example of a diamagnetic material?", options: ["Sodium", "Bismuth", "Aluminium", "Iron"], correctIndex: 1, explanation: "Bismuth is a classic example of a strongly diamagnetic material.", difficulty: "medium" },
  { id: 'magnetism-54', type: "mcq", question: "Copper, water, and gold are all common examples of materials that exhibit:", options: ["Paramagnetic behaviour", "Diamagnetic behaviour", "Strong ferromagnetic behaviour", "No magnetic response of any kind"], correctIndex: 1, explanation: "Copper, water, and gold are all classified as diamagnetic materials with weak, negative susceptibility.", difficulty: "easy" },
  { id: 'magnetism-55', type: "mcq", question: "Superconductors, when placed in an external magnetic field below their critical temperature, exhibit a special, extreme case of diamagnetism, in which the magnetic field is:", options: ["Completely expelled from the interior of the superconductor (the Meissner effect)", "Unaffected by the superconducting state", "Strongly amplified within the superconductor", "Converted entirely into an electric field"], correctIndex: 0, explanation: "Superconductors exhibit 'perfect diamagnetism', completely expelling field lines below their critical temperature — the Meissner effect.", difficulty: "medium" },
  { id: 'magnetism-56', type: "mcq", question: "The magnetic susceptibility of a diamagnetic material is generally found to be:", options: ["Positive and increasing rapidly with temperature", "Small in magnitude, negative, and largely independent of temperature", "Exactly zero at all temperatures", "Large in magnitude, positive, and strongly dependent on temperature"], correctIndex: 1, explanation: "Diamagnetic susceptibility is small, negative, and largely independent of temperature, since it arises from an induced response.", difficulty: "medium" },

  // ---------- Paramagnetism ----------
  { id: 'magnetism-57', type: "mcq", question: "Paramagnetic materials are characterised by the property that their constituent atoms/molecules possess a net (permanent) magnetic dipole moment, but in the absence of an external field, these individual dipole moments are:", options: ["Randomly oriented, due to thermal motion, resulting in zero net magnetization", "Completely absent, with no dipole moments at all", "All perfectly aligned in the same direction", "Aligned in a fixed, alternating pattern"], correctIndex: 0, explanation: "In a paramagnetic material, individual atomic moments are randomly oriented due to thermal agitation, giving zero net magnetization.", difficulty: "medium" },
  { id: 'magnetism-58', type: "mcq", question: "When a paramagnetic material is placed in an external magnetic field, the individual atomic magnetic dipole moments tend to:", options: ["Align themselves opposite to the applied field", "Instantly and completely align, achieving maximum possible magnetization", "Partially align themselves in the direction of the applied field, resulting in weak net magnetization", "Remain completely randomly oriented, unaffected by the field"], correctIndex: 2, explanation: "An external field partially aligns atomic dipoles (not completely, due to competing thermal randomisation), producing weak net magnetization.", difficulty: "medium" },
  { id: 'magnetism-59', type: "mcq", question: "Paramagnetic materials, when placed in a non-uniform magnetic field, tend to experience a force directing them:", options: ["Perpendicular to the field gradient", "Away from regions of stronger magnetic field", "In a direction unrelated to field strength", "Towards regions of stronger magnetic field"], correctIndex: 3, explanation: "Since paramagnetic materials develop magnetization in the same direction as the field, they experience weak attraction to stronger-field regions.", difficulty: "medium" },
  { id: 'magnetism-60', type: "mcq", question: "Which of the following is a classic example of a paramagnetic material?", options: ["Bismuth", "Gold", "Copper", "Aluminium"], correctIndex: 3, explanation: "Aluminium is a classic example of a paramagnetic material, showing weak, positive susceptibility.", difficulty: "easy" },
  { id: 'magnetism-61', type: "mcq", question: "Sodium and platinum are also common examples of materials that exhibit:", options: ["Diamagnetic behaviour", "Paramagnetic behaviour", "Strong ferromagnetic behaviour", "No magnetic response of any kind"], correctIndex: 1, explanation: "Sodium and platinum are both classified as paramagnetic materials.", difficulty: "medium" },
  { id: 'magnetism-62', type: "mcq", question: "Curie's law, which describes the temperature dependence of paramagnetic susceptibility, states that susceptibility (χ) is:", options: ["Inversely proportional to absolute temperature T (χ = C/T)", "Proportional to the square of the absolute temperature", "Completely independent of temperature", "Directly proportional to absolute temperature T"], correctIndex: 0, explanation: "Curie's law, χ = C/T, states paramagnetic susceptibility decreases with increasing temperature.", difficulty: "medium" },
  { id: 'magnetism-63', type: "mcq", question: "According to Curie's law, as the temperature of a paramagnetic material increases, its magnetic susceptibility:", options: ["Remains exactly unchanged", "Decreases", "Becomes negative", "Increases"], correctIndex: 1, explanation: "Since χ = C/T, an increase in temperature results in a decrease in paramagnetic susceptibility.", difficulty: "medium" },
  { id: 'magnetism-64', type: "mcq", question: "The temperature dependence described by Curie's law (paramagnetic susceptibility decreasing with increasing temperature) reflects the ongoing competition, at the atomic level, between the aligning effect of the external field and the:", options: ["Randomising effect of thermal motion/agitation of the atoms", "Randomising effect of the material's electrical resistance", "Aligning effect of the material's density", "Aligning effect of the material's own gravitational field"], correctIndex: 0, explanation: "Curie's law reflects competition between the field's aligning tendency and thermal energy's randomising tendency.", difficulty: "medium" },

  // ---------- Ferromagnetism and Hysteresis ----------
  { id: 'magnetism-65', type: "mcq", question: "Ferromagnetic materials are characterised by very strong magnetic effects, arising because groups of neighbouring atomic dipole moments spontaneously align themselves within small regions called:", options: ["Antinodes", "Nodes", "Magnetic domains", "Unit cells exclusively, with no other structural significance"], correctIndex: 2, explanation: "Ferromagnetism arises because, within small regions called magnetic domains, neighbouring atomic moments spontaneously align.", difficulty: "medium" },
  { id: 'magnetism-66', type: "mcq", question: "In an unmagnetised ferromagnetic material, although individual magnetic domains are each strongly magnetised internally, the overall material shows little or no net magnetization because:", options: ["The various domains are randomly oriented relative to each other, so their individual moments largely cancel out overall", "The domains themselves have no magnetic moment at all", "Ferromagnetic materials never actually contain domains", "The domains are all perfectly aligned already, cancelling by symmetry"], correctIndex: 0, explanation: "In an unmagnetised sample, domains point in different, essentially random directions, so their contributions largely cancel out.", difficulty: "medium" },
  { id: 'magnetism-67', type: "mcq", question: "When a ferromagnetic material is placed in an external magnetic field, magnetization increases mainly because the domains aligned (or nearly aligned) with the applied field:", options: ["Remain completely unaffected by the external field", "Shrink and eventually disappear entirely", "Grow in size at the expense of domains oriented in other directions, and/or domain orientations rotate to align more closely with the field", "Convert into paramagnetic domains"], correctIndex: 2, explanation: "Under an external field, favourably oriented domains grow larger and/or rotate to align more closely with the field.", difficulty: "medium" },
  { id: 'magnetism-68', type: "mcq", question: "Ferromagnetic materials exhibit a very large, positive magnetic susceptibility, dramatically greater than that of paramagnetic materials, and are also notable for their ability to:", options: ["Lose all magnetization the instant the external field is removed, with no memory effect", "Retain a significant amount of magnetization even after the external field has been removed (a property called retentivity)", "Only respond to extremely strong external fields, with no response to weak fields", "Show no magnetic response whatsoever"], correctIndex: 1, explanation: "Ferromagnetic materials can retain substantial magnetization after the field is removed, a property called retentivity.", difficulty: "medium" },
  { id: 'magnetism-69', type: "mcq", question: "Iron, cobalt, and nickel are classic, well-known examples of:", options: ["Paramagnetic materials exclusively, with no ferromagnetic behaviour", "Diamagnetic materials", "Ferromagnetic materials", "Materials with zero magnetic susceptibility"], correctIndex: 2, explanation: "Iron, cobalt, and nickel are the classic elemental examples of strongly ferromagnetic materials.", difficulty: "easy" },
  { id: 'magnetism-70', type: "mcq", question: "The graphical relationship between the magnetic field B (or magnetization M) and the applied field intensity H, for a ferromagnetic material undergoing a full cycle of magnetization and demagnetization, traces out a characteristic closed curve called a:", options: ["Hysteresis loop", "Standing wave pattern", "Interference pattern", "Resonance curve"], correctIndex: 0, explanation: "The characteristic B-H curve traced through a full magnetization cycle, showing lag, is called a hysteresis loop.", difficulty: "medium" },
  { id: 'magnetism-71', type: "mcq", question: "On the hysteresis loop of a ferromagnetic material, the value of magnetic field B (or magnetization) remaining in the material when the external field H is reduced to exactly zero is called the:", options: ["Coercivity", "Susceptibility", "Curie temperature", "Retentivity (or remanence)"], correctIndex: 3, explanation: "Retentivity (remanence) is the residual magnetization remaining after the magnetizing field is reduced to zero.", difficulty: "medium" },
  { id: 'magnetism-72', type: "mcq", question: "On the hysteresis loop of a ferromagnetic material, the magnitude of the reverse magnetic field intensity H required to reduce the material's residual magnetization back to exactly zero is called the:", options: ["Curie temperature", "Coercivity", "Retentivity", "Susceptibility"], correctIndex: 1, explanation: "Coercivity is the reverse field intensity needed to bring residual magnetization back down to zero.", difficulty: "medium" },
  { id: 'magnetism-73', type: "mcq", question: "Materials used to make permanent magnets are specifically chosen for having a hysteresis loop with high retentivity and high:", options: ["Density, exclusively", "Electrical conductivity", "Magnetic susceptibility, exclusively", "Coercivity"], correctIndex: 3, explanation: "Good permanent magnet materials require both high retentivity and high coercivity.", difficulty: "medium" },
  { id: 'magnetism-74', type: "mcq", question: "At a sufficiently high temperature, called the Curie temperature (specific to each ferromagnetic material), a ferromagnetic substance loses its strong ferromagnetic properties and instead behaves as a:", options: ["Paramagnetic material", "Perfectly non-magnetic material, with zero susceptibility", "Diamagnetic material", "Superconductor"], correctIndex: 0, explanation: "Above the Curie temperature, thermal agitation disrupts the domain structure and the material becomes paramagnetic.", difficulty: "medium" },

  // ---------- Permanent Magnets and Electromagnets ----------
  { id: 'magnetism-75', type: "mcq", question: "A permanent magnet is made from a ferromagnetic material chosen for its ability to retain strong magnetization indefinitely once magnetised, which requires the material to have:", options: ["Low retentivity and low coercivity", "Low retentivity but high coercivity", "High retentivity and high coercivity", "High retentivity but low coercivity"], correctIndex: 2, explanation: "A good permanent magnet material needs both high retentivity and high coercivity, giving it a wide hysteresis loop.", difficulty: "medium" },
  { id: 'magnetism-76', type: "mcq", question: "Steel is a commonly used material for making permanent magnets because, compared to soft iron, it has:", options: ["Comparable retentivity but notably higher coercivity, making it harder to demagnetise", "Zero coercivity, making it easy to magnetise and demagnetise", "No magnetic properties whatsoever", "Lower retentivity and lower coercivity"], correctIndex: 0, explanation: "Steel has comparable retentivity to soft iron but notably higher coercivity, resisting demagnetisation once magnetised.", difficulty: "medium" },
  { id: 'magnetism-77', type: "mcq", question: "Soft iron, in contrast to steel, is preferred for making electromagnets (temporary magnets activated by an electric current) because it has:", options: ["Zero magnetic susceptibility", "Very high coercivity, making it extremely difficult to demagnetise", "The same magnetic properties as steel, with no meaningful difference", "High retentivity is undesirable here; soft iron instead has low coercivity, allowing it to be easily magnetised and easily demagnetised"], correctIndex: 3, explanation: "Electromagnets need easy magnetisation and demagnetisation, which requires low coercivity — soft iron is ideal for this.", difficulty: "medium" },
  { id: 'magnetism-78', type: "mcq", question: "The area enclosed within the hysteresis loop of a ferromagnetic material, when it undergoes repeated cycles of magnetization and demagnetization, is proportional to the:", options: ["Material's electrical resistance", "Energy dissipated (as heat) within the material during each complete magnetization cycle", "Material's Curie temperature", "Material's density"], correctIndex: 1, explanation: "The area enclosed by the hysteresis loop represents energy lost as heat during each complete magnetization cycle.", difficulty: "medium" },
  { id: 'magnetism-79', type: "mcq", question: "For applications such as transformer cores, which undergo continuous, repeated cycles of magnetization (due to alternating current), materials with a narrow hysteresis loop (like soft iron) are preferred mainly to:", options: ["Make the transformer core as heavy as possible", "Maximise the permanent magnetization retained in the core", "Minimise the energy lost as heat during each magnetization cycle, improving efficiency", "Prevent the transformer from working at all"], correctIndex: 2, explanation: "Using a narrow-loop material like soft iron in continuously-cycled applications minimises wasted energy and maximises efficiency.", difficulty: "medium" },
  { id: 'magnetism-80', type: "mcq", question: "Overall, the study of magnetism and matter in this chapter — covering bar magnets, Earth's magnetism, and the magnetic properties of materials (diamagnetism, paramagnetism, and ferromagnetism) — provides the essential foundation for understanding a wide range of practical applications, including:", options: ["Compass navigation, permanent magnets, electromagnets, transformers, and the classification of materials by their magnetic response", "Only chemical bonding at the atomic level", "Only electrical circuits, with no relevance to magnetism", "Only nuclear reactions in stars"], correctIndex: 0, explanation: "This chapter's concepts underpin technologies from compass navigation to permanent magnets, electromagnets, and transformers.", difficulty: "medium" },

];

export default questions;