import type { Question } from "@/lib/questionbank";
// NEET Physics Question Bank
// Chapter: Thermal Properties of Matter
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Temperature Scales and Measurement ----------
  { id: 'matter-1', type: 'mcq', question: "The Celsius, Fahrenheit, and Kelvin scales are the three most commonly used temperature scales; among these, the ___ scale is defined such that its zero point corresponds to absolute zero, the theoretical temperature at which molecular motion is minimal.", options: ["Kelvin", "Celsius", "Fahrenheit", "None of these scales has this property"], correctIndex: 0, difficulty: "easy", explanation: "The Kelvin (absolute) scale is specifically defined so that 0 K corresponds to absolute zero, unlike Celsius and Fahrenheit, whose zero points are arbitrary reference points." },
  { id: 'matter-2', type: 'mcq', question: "The relationship between temperature in Celsius (C) and temperature in Kelvin (K) is given by:", options: ["K = C × 9/5", "K = C − 273", "K = C + 273", "K = C/273"], correctIndex: 2, difficulty: "easy", explanation: "The Kelvin scale is offset from Celsius by 273 (more precisely 273.15), so K = C + 273." },
  { id: 'matter-3', type: 'mcq', question: "The relationship between temperature in Fahrenheit (F) and temperature in Celsius (C) is given by:", options: ["F = C + 32", "F = (9/5)C + 32", "F = (5/9)C + 32", "F = C × 32"], correctIndex: 1, difficulty: "medium", explanation: "The correct conversion formula is F = (9/5)C + 32, reflecting both the scale factor and offset between the two scales." },
  { id: 'matter-4', type: 'mcq', question: "On the Celsius scale, the freezing point and boiling point of water at standard atmospheric pressure are taken as:", options: ["32°C and 212°C", "0°C and 100 K", "273°C and 373°C", "0°C and 100°C"], correctIndex: 3, difficulty: "easy", explanation: "The Celsius scale is defined with water's freezing point at 0°C and boiling point at 100°C, under standard atmospheric pressure." },
  { id: 'matter-5', type: 'mcq', question: "On the Fahrenheit scale, the freezing point and boiling point of water at standard atmospheric pressure are:", options: ["0°F and 100°F", "32°F and 212°F", "273°F and 373°F", "0°F and 212°F"], correctIndex: 1, difficulty: "easy", explanation: "On the Fahrenheit scale, water freezes at 32°F and boils at 212°F under standard atmospheric pressure." },
  { id: 'matter-6', type: 'mcq', question: "Absolute zero, the theoretical lower limit of temperature at which a system's thermal energy is minimal, corresponds to a temperature of:", options: ["0 K, or approximately −273.15°C", "0°C exactly", "100°C exactly", "0°F exactly"], correctIndex: 0, difficulty: "medium", explanation: "Absolute zero is precisely defined as 0 K, equivalent to approximately −273.15°C, and is not attainable in practice." },
  { id: 'matter-7', type: 'mcq', question: "A change of one degree on the Kelvin scale corresponds to a change of ___ on the Celsius scale.", options: ["Half a degree", "Two degrees", "Exactly one degree, since the two scales have the same size divisions, differing only by an additive offset", "Nine-fifths of a degree"], correctIndex: 2, difficulty: "medium", explanation: "Kelvin and Celsius scales have identically sized degree intervals; only the zero points differ (by 273), so a 1-degree change is the same magnitude on both." },
  { id: 'matter-8', type: 'mcq', question: "Devices used to measure temperature, called thermometers, generally rely on some measurable physical property of a substance that changes predictably (e.g. linearly) with temperature, such as the:", options: ["Colour of the substance alone, with no other property involved", "Chemical composition of the substance, which is assumed to change with temperature", "Volume of a liquid (e.g. mercury) or the electrical resistance of a material", "Taste of the substance"], correctIndex: 2, difficulty: "medium", explanation: "Common thermometers exploit physical properties like the thermal expansion of a liquid (mercury/alcohol) or the change in electrical resistance of a material with temperature." },

  // ---------- Thermal Expansion: Linear, Areal, and Volume ----------
  { id: 'matter-9', type: 'mcq', question: "The increase in the length of a solid rod when its temperature is raised, expressed as a fraction of its original length per unit rise in temperature, is quantified by its:", options: ["Specific heat capacity", "Latent heat", "Thermal conductivity", "Coefficient of linear expansion"], correctIndex: 3, difficulty: "easy", explanation: "The coefficient of linear expansion (α) quantifies the fractional change in length of a solid per unit rise in temperature." },
  { id: 'matter-10', type: 'mcq', question: "The change in length ΔL of a rod of original length L, when its temperature increases by ΔT, is given by the formula:", options: ["ΔL = αLΔT", "ΔL = α/(LΔT)", "ΔL = αL/ΔT", "ΔL = α + L + ΔT"], correctIndex: 0, difficulty: "easy", explanation: "This is the standard formula for linear thermal expansion, ΔL = αLΔT." },
  { id: 'matter-11', type: 'mcq', question: "The coefficient of superficial (areal) expansion, β, which describes the fractional change in area of a solid per unit rise in temperature, is related to the coefficient of linear expansion α by the approximate relation:", options: ["β = α/2", "β = 2α", "β = α²", "β = 3α"], correctIndex: 1, difficulty: "medium", explanation: "For small expansions, the areal expansion coefficient is approximately twice the linear expansion coefficient, β ≈ 2α, since area scales as the square of a linear dimension." },
  { id: 'matter-12', type: 'mcq', question: "The coefficient of cubical (volume) expansion, γ, which describes the fractional change in volume of a solid per unit rise in temperature, is related to the coefficient of linear expansion α by the approximate relation:", options: ["γ = α/3", "γ = α²", "γ = 2α", "γ = 3α"], correctIndex: 3, difficulty: "medium", explanation: "For small expansions, γ ≈ 3α, since volume scales as the cube of a linear dimension." },
  { id: 'matter-13', type: 'mcq', question: "For a given solid material, the relationship between the coefficients of linear, areal, and volume expansion can be summarised as:", options: ["α : β : γ = 3 : 2 : 1", "α : β : γ = 1 : 2 : 3", "α : β : γ = 1 : 1 : 1", "α : β : γ = 3 : 1 : 2"], correctIndex: 1, difficulty: "medium", explanation: "Since β ≈ 2α and γ ≈ 3α, the ratio of linear, areal, and volume expansion coefficients is 1:2:3." },
  { id: 'matter-14', type: 'mcq', question: "A bimetallic strip, made by bonding together two different metals with different coefficients of linear expansion, is commonly used in devices such as thermostats because, when heated, it:", options: ["Bends due to the unequal expansion of the two metals, which can be used to make or break an electrical contact", "Remains perfectly straight regardless of temperature change", "Melts immediately at any temperature above 0°C", "Contracts uniformly with no bending at all"], correctIndex: 0, difficulty: "medium", explanation: "Since the two bonded metals expand at different rates when heated, the strip bends, a mechanical response exploited in thermostats." },
  { id: 'matter-15', type: 'mcq', question: "When a solid object with a hole in it (e.g. a metal ring or a washer) is uniformly heated, the size of the hole:", options: ["Decreases, as the surrounding material contracts inward", "Increases, expanding in the same proportion as if the hole were filled with the same solid material", "Remains exactly unchanged, regardless of heating", "Becomes perfectly square, regardless of its original shape"], correctIndex: 1, difficulty: "medium", explanation: "A hole in a heated solid expands just as if it were made of the same material as the surrounding solid — a classic, often counter-intuitive result." },
  { id: 'matter-16', type: 'mcq', question: "Railway tracks are typically laid with small gaps between successive rail segments mainly to:", options: ["Allow room for thermal expansion of the rails during hot weather, preventing buckling", "Save on the cost of rail material, with no relation to temperature", "Make trains travel faster over the gaps", "Allow for easier disassembly of the tracks"], correctIndex: 0, difficulty: "medium", explanation: "Without expansion gaps, rails heated during hot weather would expand and could buckle due to compressive stress; the gaps accommodate this safely." },
  { id: 'matter-17', type: 'mcq', question: "For a liquid, only the coefficient of ___ expansion is typically meaningful, since a liquid does not have a fixed, well-defined shape of its own.", options: ["Linear", "Areal", "Volume (cubical)", "None of these apply to liquids"], correctIndex: 2, difficulty: "medium", explanation: "Since liquids take the shape of their container and lack a fixed length or area, only volume (cubical) expansion is meaningful for liquids." },
  { id: 'matter-18', type: 'mcq', question: "The apparent expansion of a liquid, as observed when it is heated inside a container, is generally different from its real (absolute) expansion because:", options: ["Liquids never actually expand when heated", "The container itself always remains at a fixed, unchanging volume", "The container itself also expands when heated, so part of the liquid's apparent volume increase is offset by the container's own expansion", "Apparent and real expansion are always identical, by definition"], correctIndex: 2, difficulty: "medium", explanation: "Since the container also expands upon heating, the liquid's apparent expansion (relative to the container) is generally less than its true absolute expansion." },
  { id: 'matter-19', type: 'mcq', question: "Gases generally show a much ___ coefficient of volume expansion compared to solids and liquids, for the same rise in temperature.", options: ["Smaller", "Identical", "Undefined", "Larger"], correctIndex: 3, difficulty: "medium", explanation: "Gas molecules are far more loosely bound and free to move than those in solids/liquids, so gases expand much more readily for the same temperature increase." },
  { id: 'matter-20', type: 'mcq', question: "Thermal expansion at the microscopic level occurs because an increase in temperature causes atoms/molecules in a solid to:", options: ["Vibrate with greater amplitude about their mean positions, increasing the average interatomic spacing", "Stop vibrating entirely", "Move closer together on average", "Undergo nuclear fusion"], correctIndex: 0, difficulty: "medium", explanation: "Higher temperature increases atomic vibrational amplitude around equilibrium lattice positions, increasing average spacing and producing macroscopic expansion." },

  // ---------- Anomalous Expansion of Water ----------
  { id: 'matter-21', type: 'mcq', question: "Water exhibits an unusual property known as 'anomalous expansion', whereby, unlike most substances, its volume:", options: ["Decreases (density increases) as it is cooled from 4°C down to 0°C, rather than continuing to contract as expected", "Continuously decreases as temperature decreases from 100°C down to 0°C, with no exceptions", "Remains exactly constant at all temperatures below 100°C", "Increases uniformly and continuously as temperature decreases from any starting point"], correctIndex: 0, difficulty: "medium", explanation: "Anomalous expansion refers specifically to water expanding (density decreasing) as it cools from 4°C toward 0°C, rather than continuing to contract as most substances do." },
  { id: 'matter-22', type: 'mcq', question: "Water has its maximum density at a temperature of approximately:", options: ["0°C", "100°C", "4°C", "37°C"], correctIndex: 2, difficulty: "medium", explanation: "Water's density peaks at approximately 4°C; both above and below this temperature, its density is lower." },
  { id: 'matter-23', type: 'mcq', question: "The anomalous expansion of water is ecologically significant because it explains why, in cold climates, bodies of water such as lakes and ponds:", options: ["Freeze completely solid from top to bottom almost instantly", "Freeze at the surface first, while the denser water at 4°C sinks to the bottom, allowing aquatic life to survive beneath the ice layer", "Never freeze under any circumstances", "Boil away completely during winter"], correctIndex: 1, difficulty: "medium", explanation: "Because water at 4°C is densest and sinks, while ice and near-freezing water stay near the surface, lakes freeze top-down, insulating the water below." },
  { id: 'matter-24', type: 'mcq', question: "If water did not exhibit anomalous expansion and instead behaved like most typical liquids (continuously contracting as it cooled toward its freezing point), lakes in cold climates would likely:", options: ["Behave exactly as they do currently, with no meaningful difference", "Never freeze at all, under any circumstances", "Only freeze at the bottom, never at the surface", "Freeze from the bottom up, since the coldest (densest) water would sink first, potentially threatening aquatic life"], correctIndex: 3, difficulty: "hard", explanation: "Without anomalous expansion, the coldest water would remain densest all the way to 0°C and sink, causing lakes to freeze from the bottom up — far more threatening to aquatic life." },

  // ---------- Specific Heat Capacity and Calorimetry ----------
  { id: 'matter-25', type: 'mcq', question: "The specific heat capacity of a substance is defined as the amount of heat required to raise the temperature of a unit mass of that substance by:", options: ["A specific, arbitrary temperature range, always 100 degrees", "One degree (Celsius or Kelvin)", "Half a degree", "A temperature range that varies depending on the substance's melting point"], correctIndex: 1, difficulty: "easy", explanation: "Specific heat capacity is defined as the heat needed to raise the temperature of one unit mass of a substance by exactly one degree." },
  { id: 'matter-26', type: 'mcq', question: "The relationship between the heat energy Q absorbed (or released) by a substance, its mass m, specific heat capacity c, and the resulting temperature change ΔT is given by:", options: ["Q = mcΔT", "Q = m/(cΔT)", "Q = mc/ΔT", "Q = m + c + ΔT"], correctIndex: 0, difficulty: "easy", explanation: "This is the fundamental calorimetry formula, Q = mcΔT." },
  { id: 'matter-27', type: 'mcq', question: "Water has an unusually ___ specific heat capacity compared to most common substances, meaning it can absorb or release a relatively large amount of heat with only a modest change in its own temperature.", options: ["Low", "Undefined", "High", "Negative"], correctIndex: 2, difficulty: "medium", explanation: "Water's specific heat capacity (about 4186 J/kg·K) is notably higher than most other common substances, giving it a strong capacity to buffer temperature changes." },
  { id: 'matter-28', type: 'mcq', question: "The unusually high specific heat capacity of water is one reason why coastal regions generally experience:", options: ["More extreme temperature swings than inland regions", "No seasonal temperature variation at all", "More moderate (less extreme) temperature variations than inland regions, due to the ocean's thermal buffering effect", "Consistently higher average temperatures than inland regions, regardless of season"], correctIndex: 2, difficulty: "medium", explanation: "Because large bodies of water absorb/release substantial heat with only modest temperature change, they moderate nearby land temperatures, giving milder seasonal swings." },
  { id: 'matter-29', type: 'mcq', question: "The principle of calorimetry, used to determine unknown specific heats or final equilibrium temperatures when substances at different temperatures are mixed, states that (assuming no heat is lost to the surroundings):", options: ["Heat gained is always greater than heat lost", "Heat lost is always greater than heat gained", "Heat lost and heat gained are entirely unrelated quantities", "Heat lost by the hotter substance(s) is exactly equal to the heat gained by the cooler substance(s)"], correctIndex: 3, difficulty: "medium", explanation: "The calorimetry principle is a statement of energy conservation: heat lost by a hotter body exactly equals heat gained by a cooler body it's in contact with." },
  { id: 'matter-30', type: 'mcq', question: "Molar specific heat capacity, as distinguished from ordinary specific heat capacity, is defined as the amount of heat required to raise the temperature of one:", options: ["Mole of a substance by one degree (Celsius or Kelvin)", "Kilogram of a substance by one degree", "Litre of a substance by one degree", "Cubic metre of a substance by one degree"], correctIndex: 0, difficulty: "medium", explanation: "Molar specific heat capacity is defined per mole of substance rather than per unit mass." },
  { id: 'matter-31', type: 'mcq', question: "The specific heat capacity of a substance can vary depending on the specific conditions under which heat is added, such as whether the process occurs at constant pressure or at constant:", options: ["Temperature, which would make the concept of specific heat undefined", "Volume", "Mass, which is already assumed fixed in the definition", "Density, though density is not directly controlled in these processes"], correctIndex: 1, difficulty: "medium", explanation: "For gases especially, specific heat is distinguished as constant pressure (Cp) or constant volume (Cv), since the heat needed differs under these conditions." },
  { id: 'matter-32', type: 'mcq', question: "The original definition of the 'calorie' as a unit of heat energy was based on the amount of heat required to raise the temperature of:", options: ["One kilogram of iron by one degree Celsius", "One gram of water by one degree Celsius", "One litre of air by one degree Celsius", "One mole of any gas by one degree Kelvin"], correctIndex: 1, difficulty: "medium", explanation: "The calorie was historically defined as the heat needed to raise one gram of water by 1°C, tying the unit directly to water's specific heat capacity." },
  { id: 'matter-33', type: 'mcq', question: "In a calorimetric experiment, a hot metal block is dropped into a container of cooler water, and the system is allowed to reach thermal equilibrium. At equilibrium, the metal and water:", options: ["Reach the same final temperature", "Retain their original, different temperatures indefinitely", "Both reach a temperature of exactly 0°C, regardless of initial conditions", "Both reach a temperature of exactly 100°C, regardless of initial conditions"], correctIndex: 0, difficulty: "easy", explanation: "Thermal equilibrium means the two objects in contact eventually reach the same common final temperature, with no further net heat exchange." },
  { id: 'matter-34', type: 'mcq', question: "In calorimetry problems, the heat capacity of the calorimeter vessel itself (sometimes called the 'water equivalent') is often taken into account because:", options: ["The calorimeter is assumed to have no thermal properties at all", "The calorimeter always has zero mass, so it never matters", "It has no effect whatsoever on the final calculated temperature", "The calorimeter vessel itself also absorbs some heat during the process, which must be included for an accurate energy balance"], correctIndex: 3, difficulty: "medium", explanation: "The calorimeter container has mass and specific heat, so it also absorbs/releases heat during the experiment, and ignoring this introduces error." },

  // ---------- Latent Heat and Change of State ----------
  { id: 'matter-35', type: 'mcq', question: "The amount of heat required to change the state of a unit mass of a substance, without any accompanying change in its temperature, is called its:", options: ["Specific heat capacity", "Latent heat", "Thermal conductivity", "Coefficient of expansion"], correctIndex: 1, difficulty: "easy", explanation: "Latent heat refers specifically to heat absorbed/released during a phase change at constant temperature, distinct from specific heat capacity." },
  { id: 'matter-36', type: 'mcq', question: "The latent heat associated with the change of state from solid to liquid (or liquid to solid) is called the latent heat of:", options: ["Vaporisation", "Fusion", "Sublimation", "Condensation exclusively"], correctIndex: 1, difficulty: "easy", explanation: "Latent heat of fusion refers to the heat involved in the solid-liquid (melting/freezing) phase transition." },
  { id: 'matter-37', type: 'mcq', question: "The latent heat associated with the change of state from liquid to gas (or gas to liquid) is called the latent heat of:", options: ["Vaporisation", "Fusion", "Deposition", "Compression"], correctIndex: 0, difficulty: "easy", explanation: "Latent heat of vaporisation refers to the heat involved in the liquid-gas (boiling/condensation) phase transition." },
  { id: 'matter-38', type: 'mcq', question: "During a phase change, such as ice melting into water, heat is continuously supplied to the substance, yet the substance's temperature:", options: ["Rises rapidly and continuously", "Rises, but very slowly", "Falls, despite the heat input", "Remains constant until the entire phase change is complete"], correctIndex: 3, difficulty: "medium", explanation: "During a phase change, supplied heat goes into breaking/forming intermolecular bonds rather than increasing kinetic energy, so temperature stays constant." },
  { id: 'matter-39', type: 'mcq', question: "The specific latent heat of fusion of ice (the heat required to melt one unit mass of ice at 0°C into water at 0°C) is a notably ___ value, reflecting the substantial energy needed to break the hydrogen-bonded ice lattice.", options: ["Small", "Large", "Negative", "Zero"], correctIndex: 1, difficulty: "medium", explanation: "Ice has a relatively large latent heat of fusion (about 334 kJ/kg), reflecting the significant energy needed to break its hydrogen-bonded crystal lattice." },
  { id: 'matter-40', type: 'mcq', question: "The specific latent heat of vaporisation of water (the heat required to convert one unit mass of water at 100°C into steam at 100°C) is:", options: ["Considerably larger than its latent heat of fusion", "Considerably smaller than its latent heat of fusion", "Exactly equal to its latent heat of fusion", "Undefined, since water does not have a latent heat of vaporisation"], correctIndex: 0, difficulty: "medium", explanation: "Water's latent heat of vaporisation (about 2256 kJ/kg) is considerably larger than its latent heat of fusion (about 334 kJ/kg), reflecting the much greater energy needed to fully separate liquid molecules into gas." },
  { id: 'matter-41', type: 'mcq', question: "The relationship Q = mL, used to calculate the heat required for a phase change, relates the heat Q, the mass m of the substance, and:", options: ["The specific heat capacity of the substance", "The temperature change of the substance", "The specific latent heat L (of fusion or vaporisation, as appropriate)", "The thermal conductivity of the substance"], correctIndex: 2, difficulty: "medium", explanation: "This is the standard formula for heat involved in a phase change, Q = mL, where L is the appropriate specific latent heat." },
  { id: 'matter-42', type: 'mcq', question: "A temperature-time graph obtained by continuously heating a solid substance at a constant rate, passing through melting and then boiling, typically shows flat (horizontal) plateaus at the melting point and boiling point, indicating that:", options: ["The heating process was interrupted at these points", "The substance's temperature actually decreased briefly at these points", "All the heat supplied during these intervals goes into the phase change itself, rather than raising the temperature", "The measuring thermometer malfunctioned at these specific points"], correctIndex: 2, difficulty: "medium", explanation: "The flat plateaus correspond to phase-change intervals, during which supplied heat is entirely consumed by the phase transition (latent heat) rather than temperature rise." },
  { id: 'matter-43', type: 'mcq', question: "Sublimation refers to the direct change of state of a substance from:", options: ["Liquid to gas, without passing through the solid state", "Gas to liquid, without passing through the solid state", "Solid to liquid, without passing through the gas state", "Solid directly to gas (or vice versa), without passing through the intermediate liquid state"], correctIndex: 3, difficulty: "medium", explanation: "Sublimation is defined as the direct transition between solid and gas phases, bypassing the liquid phase entirely." },
  { id: 'matter-44', type: 'mcq', question: "Evaporation, the process by which a liquid gradually converts to vapour even at temperatures below its normal boiling point, occurs because:", options: ["All molecules in the liquid have exactly the same kinetic energy at any given temperature", "Some molecules at the liquid's surface happen to have enough kinetic energy to escape into the vapour phase, even though the bulk liquid is below its boiling point", "The liquid must first reach its boiling point before any evaporation can occur", "Evaporation requires the addition of a catalyst substance"], correctIndex: 1, difficulty: "medium", explanation: "Molecular speeds within a liquid follow a distribution, and some surface molecules always have enough kinetic energy to escape as vapour, even below the boiling point." },

  // ---------- Conduction ----------
  { id: 'matter-45', type: 'mcq', question: "Heat transfer through a solid medium, occurring via the direct transfer of thermal energy between adjacent particles without any bulk movement of the material itself, is called:", options: ["Conduction", "Convection", "Radiation", "Sublimation"], correctIndex: 0, difficulty: "easy", explanation: "Conduction is heat transfer through direct particle interaction within a medium, with no bulk motion — the dominant mechanism in solids." },
  { id: 'matter-46', type: 'mcq', question: "According to the basic law of heat conduction, the rate of heat flow through a uniform rod is directly proportional to the cross-sectional area of the rod and the temperature difference between its ends, and inversely proportional to the rod's:", options: ["Thermal conductivity", "Mass", "Length", "Specific heat capacity"], correctIndex: 2, difficulty: "medium", explanation: "Q/t = KA(T1−T2)/L shows the rate of heat flow is inversely proportional to the rod's length L." },
  { id: 'matter-47', type: 'mcq', question: "The formula for the rate of heat conduction through a rod, Q/t = KA(T1 − T2)/L, includes a proportionality constant K, called the material's:", options: ["Specific heat capacity", "Thermal conductivity", "Coefficient of linear expansion", "Latent heat"], correctIndex: 1, difficulty: "medium", explanation: "The proportionality constant K in the heat conduction formula is the thermal conductivity of the material." },
  { id: 'matter-48', type: 'mcq', question: "A material with a high thermal conductivity, such as copper or silver, conducts heat:", options: ["Very poorly", "Very efficiently, allowing rapid heat transfer for a given temperature gradient", "Not at all, since metals are generally poor conductors of heat", "Only when exposed to direct sunlight"], correctIndex: 1, difficulty: "medium", explanation: "Metals such as copper and silver have high thermal conductivity, allowing heat to flow through them rapidly for a given temperature difference." },
  { id: 'matter-49', type: 'mcq', question: "Materials such as wood, rubber, and glass wool, which conduct heat poorly, are commonly referred to as good thermal:", options: ["Insulators", "Conductors", "Radiators", "Convectors"], correctIndex: 0, difficulty: "easy", explanation: "Materials with low thermal conductivity are termed insulators, useful for retaining or blocking heat transfer." },
  { id: 'matter-50', type: 'mcq', question: "In steady-state heat conduction through a rod, the rate of heat flow at every cross-section along the rod's length is:", options: ["Progressively increasing toward the colder end", "Progressively decreasing toward the colder end", "Zero at the midpoint of the rod", "The same at every cross-section"], correctIndex: 3, difficulty: "medium", explanation: "In the steady state, the rate of heat flow through any cross-section must be identical, since no heat accumulates anywhere along the rod." },
  { id: 'matter-51', type: 'mcq', question: "The SI unit of thermal conductivity is:", options: ["J/kg·K", "W/(m·K)", "W/m²", "J/(kg·°C)"], correctIndex: 1, difficulty: "medium", explanation: "From K = (Q/t) × L/(A × ΔT), the units of thermal conductivity work out to W/(m·K)." },
  { id: 'matter-52', type: 'mcq', question: "Comparing thermal conduction to electrical conduction, temperature difference in a heat-conducting rod plays a role analogous to:", options: ["Electrical resistance", "Electric current", "Voltage (potential difference) in an electrical circuit", "Electrical capacitance"], correctIndex: 2, difficulty: "medium", explanation: "The heat conduction equation is mathematically analogous to Ohm's law, with temperature difference playing the role of voltage driving the heat 'current'." },
  { id: 'matter-53', type: 'mcq', question: "For two rods of the same material and cross-sectional area joined end-to-end (in series) to conduct heat, the combined thermal resistance of the two-rod system is:", options: ["Less than the resistance of either individual rod", "Exactly equal to the resistance of just one of the rods", "Greater than the resistance of either individual rod alone, since resistances in series add up", "Always exactly zero, regardless of the rods' properties"], correctIndex: 2, difficulty: "medium", explanation: "Just as electrical resistances in series add, thermal resistances of rods in series for conduction also add, giving a combined resistance greater than either alone." },
  { id: 'matter-54', type: 'mcq', question: "Double-glazed windows, consisting of two glass panes with a layer of trapped air (or vacuum) in between, help reduce heat loss from buildings mainly because the trapped air layer:", options: ["Has an extremely high thermal conductivity", "Conducts heat perfectly, with zero thermal resistance", "Has a low thermal conductivity, acting as an effective insulating barrier", "Increases convective heat loss significantly"], correctIndex: 2, difficulty: "medium", explanation: "Trapped, unable-to-circulate air has low thermal conductivity, so the layer between the panes acts as an effective insulator, reducing conductive heat loss." },

  // ---------- Convection ----------
  { id: 'matter-55', type: 'mcq', question: "Heat transfer that occurs due to the actual bulk movement of a fluid (liquid or gas), carrying thermal energy from one place to another, is called:", options: ["Conduction", "Radiation", "Sublimation", "Convection"], correctIndex: 3, difficulty: "easy", explanation: "Convection is heat transfer via the bulk physical movement of a fluid medium, distinct from conduction and radiation." },
  { id: 'matter-56', type: 'mcq', question: "Convection currents in a fluid, such as those set up when a pot of water is heated from below, typically occur because heated fluid becomes:", options: ["Less dense and rises, while cooler, denser fluid sinks to take its place", "More dense and sinks immediately", "Completely stationary and does not move at all", "Converted directly into a gas at any temperature"], correctIndex: 0, difficulty: "medium", explanation: "Heating typically reduces a fluid's density, causing warmer, less dense fluid to rise while cooler, denser fluid sinks, setting up a circulating current." },
  { id: 'matter-57', type: 'mcq', question: "Convection that occurs naturally due to density differences created by temperature variations, without any external mechanical assistance (like a fan or pump), is called:", options: ["Forced convection", "Natural (free) convection", "Radiative convection, a term not used in standard physics", "Conductive convection, a contradictory term"], correctIndex: 1, difficulty: "medium", explanation: "Natural (free) convection occurs spontaneously due to buoyancy-driven density differences, as opposed to mechanically-driven forced convection." },
  { id: 'matter-58', type: 'mcq', question: "Convection that occurs when a fluid is actively circulated by an external device, such as a fan or a pump, is called:", options: ["Natural convection", "Forced convection", "Radiative convection", "Passive convection"], correctIndex: 1, difficulty: "medium", explanation: "Forced convection refers to fluid circulation driven by an external mechanical source, as opposed to buoyancy-driven natural convection." },

  // ---------- Radiation: Stefan's Law and Wien's Law ----------
  { id: 'matter-59', type: 'mcq', question: "Heat transfer that occurs through electromagnetic waves, requiring no material medium at all (and thus able to travel through a vacuum), is called:", options: ["Radiation", "Conduction", "Convection", "Sublimation"], correctIndex: 0, difficulty: "easy", explanation: "Radiation is the only heat transfer mode that requires no material medium, occurring via electromagnetic waves that travel through vacuum." },
  { id: 'matter-60', type: 'mcq', question: "A theoretical, idealised object that absorbs all electromagnetic radiation incident upon it, reflecting none, and also emits radiation with maximum possible efficiency at a given temperature, is called a:", options: ["Perfect insulator", "Perfect conductor", "Black body", "Perfect reflector"], correctIndex: 2, difficulty: "medium", explanation: "A black body absorbs all incident radiation (reflecting none) and is the most efficient possible emitter of thermal radiation at any given temperature." },
  { id: 'matter-61', type: 'mcq', question: "The Stefan-Boltzmann law states that the total power radiated per unit area by a black body is directly proportional to:", options: ["The absolute temperature of the body", "The fourth power of the absolute temperature of the body", "The square of the absolute temperature of the body", "The square root of the absolute temperature of the body"], correctIndex: 1, difficulty: "medium", explanation: "The Stefan-Boltzmann law, E = σT⁴, shows radiated power per unit area depends on the fourth power of absolute temperature." },
  { id: 'matter-62', type: 'mcq', question: "The Stefan-Boltzmann law can be mathematically expressed as E = σT⁴, where σ is:", options: ["The specific heat capacity of the radiating body", "The thermal conductivity of the radiating body", "The Stefan-Boltzmann constant, a universal physical constant", "A quantity that varies with the material of the radiating body"], correctIndex: 2, difficulty: "medium", explanation: "σ is a fixed, universal physical constant (approximately 5.67 × 10⁻⁸ W/m²K⁴), the same for all black bodies regardless of material." },
  { id: 'matter-63', type: 'mcq', question: "According to the Stefan-Boltzmann law, if the absolute temperature of a black body is doubled, the total power it radiates per unit area increases by a factor of:", options: ["2", "4", "16", "8"], correctIndex: 2, difficulty: "medium", explanation: "Since E ∝ T⁴, doubling the absolute temperature increases radiated power by a factor of 2⁴ = 16." },
  { id: 'matter-64', type: 'mcq', question: "Wien's displacement law relates the wavelength at which a black body emits the maximum intensity of radiation to its:", options: ["Surface area", "Total mass", "Specific heat capacity", "Absolute temperature"], correctIndex: 3, difficulty: "medium", explanation: "Wien's displacement law, λmaxT = constant, directly relates the peak-emission wavelength of a black body's spectrum to its absolute temperature." },
  { id: 'matter-65', type: 'mcq', question: "According to Wien's displacement law, λmax T = b (where b is Wien's constant), as the absolute temperature of a black body increases, the wavelength at which it radiates most intensely:", options: ["Increases (shifts toward longer wavelengths)", "Decreases (shifts toward shorter wavelengths)", "Remains exactly unchanged", "Becomes infinite"], correctIndex: 1, difficulty: "medium", explanation: "Since λmax T = constant, an increase in T must be accompanied by a decrease in λmax, shifting peak emission toward shorter wavelengths." },
  { id: 'matter-66', type: 'mcq', question: "A very hot object, such as a metal filament heated to a high temperature, glows first red, then progressively whiter/bluer as its temperature increases further. This behaviour is consistent with:", options: ["Wien's displacement law, since higher temperature shifts the peak emission wavelength toward shorter (bluer) wavelengths", "The Stefan-Boltzmann law exclusively, with no reference to wavelength at all", "Newton's law of cooling exclusively", "Kirchhoff's law exclusively"], correctIndex: 0, difficulty: "medium", explanation: "This colour shift with increasing temperature is a direct, visually observable illustration of Wien's displacement law." },
  { id: 'matter-67', type: 'mcq', question: "The Sun's peak radiation intensity occurs in the visible part of the electromagnetic spectrum, while a much cooler object, such as a human body, emits radiation with its peak intensity in the:", options: ["Ultraviolet region, with a shorter wavelength than the Sun's peak", "Visible region, identical to the Sun's peak", "Gamma-ray region", "Infrared region, with a longer wavelength than the Sun's peak, consistent with its much lower temperature"], correctIndex: 3, difficulty: "medium", explanation: "Since the human body is far cooler than the Sun, Wien's law predicts its peak emission wavelength is much longer, placing it in the infrared region." },
  { id: 'matter-68', type: 'mcq', question: "Radiation emitted by all objects with a temperature above absolute zero, dependent on their temperature and other surface characteristics, is generally referred to as:", options: ["Reflected radiation exclusively", "Thermal (black-body-type) radiation", "Nuclear radiation", "Radioactive decay"], correctIndex: 1, difficulty: "medium", explanation: "Any object above absolute zero continuously emits thermal (black-body-type) radiation, governed by the Stefan-Boltzmann and Wien laws." },
  { id: 'matter-69', type: 'mcq', question: "The 'greenhouse effect', by which certain gases in the Earth's atmosphere trap outgoing infrared radiation and thereby warm the planet's surface, is fundamentally related to the concepts of thermal radiation because:", options: ["Earth's surface, warmed by the Sun, re-radiates energy predominantly as infrared radiation, some of which is absorbed by atmospheric greenhouse gases rather than escaping directly to space", "Greenhouse gases have no interaction with radiation of any kind", "The Earth's surface only emits visible light, never infrared radiation", "Greenhouse gases actively cool the Earth's surface by reflecting all incoming solar radiation"], correctIndex: 0, difficulty: "medium", explanation: "Earth absorbs short-wavelength solar radiation and re-emits longer-wavelength infrared (per Wien's law, since it's much cooler than the Sun); certain gases absorb this infrared, trapping heat." },
  { id: 'matter-70', type: 'mcq', question: "A rough, dark-coloured surface is generally a much ___ emitter and absorber of thermal radiation than a smooth, shiny, light-coloured surface.", options: ["Poorer", "Less efficient", "Weaker", "Better/more efficient"], correctIndex: 3, difficulty: "medium", explanation: "Dark, rough surfaces approximate black-body behaviour more closely and are both better absorbers and better emitters than shiny, reflective surfaces." },

  // ---------- Newton's Law of Cooling and Kirchhoff's Law ----------
  { id: 'matter-71', type: 'mcq', question: "Newton's law of cooling states that the rate at which a hot body loses heat to its surroundings is directly proportional to the:", options: ["Absolute temperature of the body itself", "Temperature difference between the body and its surroundings, provided this difference is relatively small", "Surface area of the body alone, with no dependence on temperature", "Fourth power of the temperature difference"], correctIndex: 1, difficulty: "medium", explanation: "Newton's law of cooling, valid for small temperature differences, states the rate of heat loss is proportional to the temperature difference, not its fourth power." },
  { id: 'matter-72', type: 'mcq', question: "Newton's law of cooling is generally considered a good approximation of the more exact Stefan-Boltzmann law specifically when the temperature difference between the body and its surroundings is:", options: ["Extremely large", "Small", "Exactly equal to zero, in which case the law becomes meaningless", "Negative, i.e. when the surroundings are hotter than the body"], correctIndex: 1, difficulty: "medium", explanation: "Newton's law of cooling is derived as a linear (small-difference) approximation of the exact fourth-power Stefan-Boltzmann relationship." },
  { id: 'matter-73', type: 'mcq', question: "According to Newton's law of cooling, a body will cool down faster when the temperature difference between the body and its surroundings is:", options: ["Larger", "Smaller", "Exactly zero", "Unrelated to the cooling rate"], correctIndex: 0, difficulty: "easy", explanation: "Since cooling rate is directly proportional to temperature difference, a larger difference produces a faster initial rate of cooling." },
  { id: 'matter-74', type: 'mcq', question: "A graph of temperature versus time for an object cooling according to Newton's law typically shows a curve that:", options: ["Is a straight line with a constant, unchanging slope throughout", "Rises continuously over time", "Remains perfectly flat/horizontal at all times", "Falls off steeply at first and then more gradually, eventually approaching the surrounding temperature asymptotically"], correctIndex: 3, difficulty: "medium", explanation: "Since cooling rate decreases as the temperature difference shrinks, the curve falls steeply at first and levels off gradually as it approaches ambient temperature." },
  { id: 'matter-75', type: 'mcq', question: "Kirchhoff's law of thermal radiation states that, for a body in thermal equilibrium, the ratio of its emissive power to its absorptive power, at a given wavelength and temperature, is:", options: ["Always equal to zero", "The same for all bodies, and equal to the emissive power of a perfect black body at that same wavelength and temperature", "Always infinite", "Different for every different material, with no universal relationship"], correctIndex: 1, difficulty: "hard", explanation: "Kirchhoff's law establishes that the ratio of emissive to absorptive power is a universal function equal to the black body's emissive power under the same conditions." },
  { id: 'matter-76', type: 'mcq', question: "According to Kirchhoff's law, a good absorber of thermal radiation at a particular wavelength is also necessarily a good:", options: ["Reflector of radiation at that same wavelength", "Emitter of radiation at that same wavelength", "Insulator against radiation at that same wavelength", "Conductor of heat by conduction, unrelated to radiation"], correctIndex: 1, difficulty: "medium", explanation: "Kirchhoff's law implies good absorbers at a given wavelength are also good emitters at that same wavelength, and vice versa." },
  { id: 'matter-77', type: 'mcq', question: "A perfectly black surface, being the best possible absorber of radiation, is, according to Kirchhoff's law, also necessarily the:", options: ["Best possible emitter of radiation, at any given temperature", "Worst possible emitter of radiation", "Best possible reflector of radiation", "Only surface that does not follow Kirchhoff's law"], correctIndex: 0, difficulty: "medium", explanation: "Since a black body absorbs radiation perfectly, Kirchhoff's law requires it to also be the best possible emitter of thermal radiation." },
  { id: 'matter-78', type: 'mcq', question: "A shiny, silvery surface, which is a poor absorber of thermal radiation (reflecting most of it instead), is, according to Kirchhoff's law, also necessarily a:", options: ["Very efficient emitter of thermal radiation", "Perfect black body", "Surface with an emissive power greater than that of a black body", "Poor emitter of thermal radiation"], correctIndex: 3, difficulty: "medium", explanation: "Since Kirchhoff's law ties absorptive and emissive efficiency together, a poor absorber like a shiny surface is necessarily also a poor emitter." },
  { id: 'matter-79', type: 'mcq', question: "The practical application of Kirchhoff's law can be seen in the design of thermos flasks, which use a silvered (shiny) inner surface mainly to:", options: ["Minimise heat loss (or gain) by radiation, since a shiny surface is both a poor absorber and a poor emitter of thermal radiation", "Maximise heat loss by radiation, cooling the contents rapidly", "Increase the rate of conduction through the flask wall", "Have no effect on heat transfer whatsoever"], correctIndex: 0, difficulty: "medium", explanation: "A silvered inner surface reflects most incident radiation and, by Kirchhoff's law, is also a poor emitter, minimising radiative heat exchange." },
  { id: 'matter-80', type: 'mcq', question: "Overall, the combined study of specific heat, latent heat, and the three modes of heat transfer (conduction, convection, and radiation) provides the essential framework for understanding:", options: ["Only chemical reaction mechanisms", "How thermal energy is stored, changes matter's state, and moves between and within objects and their surroundings", "Only electromagnetic wave propagation in a vacuum, with no relevance to matter", "Only nuclear reactions within stars"], correctIndex: 1, difficulty: "medium", explanation: "This chapter's concepts together explain how heat is stored (specific/latent heat) and how it moves (conduction, convection, radiation) — foundational to thermal physics." },

];

export default questions;