import type { Question } from "@/lib/questionbank";
// NEET Physics Question Bank
// Chapter: Oscillations
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Periodic and Oscillatory Motion Basics ----------
  { id: 'oscillation-1', type: 'mcq', question: "Motion that repeats itself at regular intervals of time is called:", options: ["Periodic motion", "Random motion", "Uniformly accelerated motion", "Non-repetitive motion"], correctIndex: 0, difficulty: "easy", explanation: "Periodic motion is defined as motion that repeats identically after fixed, regular time intervals." },
  { id: 'oscillation-2', type: 'mcq', question: "The fixed time interval after which a periodic motion repeats itself is called its:", options: ["Frequency", "Amplitude", "Time period", "Phase"], correctIndex: 2, difficulty: "easy", explanation: "The time period (T) is defined as the time taken to complete one full cycle of a periodic motion." },
  { id: 'oscillation-3', type: 'mcq', question: "The number of complete oscillations (or cycles) a periodic motion undergoes per unit time is called its:", options: ["Time period", "Frequency", "Amplitude", "Angular displacement"], correctIndex: 1, difficulty: "easy", explanation: "Frequency (f) is the number of complete cycles occurring per unit time, the reciprocal of the time period." },
  { id: 'oscillation-4', type: 'mcq', question: "Frequency (f) and time period (T) of a periodic motion are related by the equation:", options: ["f = T", "f = T²", "f × T² = 1", "f = 1/T"], correctIndex: 3, difficulty: "easy", explanation: "Frequency and time period are reciprocals of one another, f = 1/T." },
  { id: 'oscillation-5', type: 'mcq', question: "Periodic motion in which a body moves back and forth repeatedly about a fixed mean (equilibrium) position is more specifically called:", options: ["Circular motion exclusively", "Oscillatory (or vibratory) motion", "Uniform motion", "Projectile motion"], correctIndex: 1, difficulty: "medium", explanation: "Oscillatory motion is characterised by repeated back-and-forth movement about a fixed equilibrium (mean) position." },
  { id: 'oscillation-6', type: 'mcq', question: "The SI unit of frequency, equal to one cycle per second, is the:", options: ["Hertz (Hz)", "Newton (N)", "Radian per second (rad/s)", "Joule (J)"], correctIndex: 0, difficulty: "easy", explanation: "The hertz (Hz) is the standard SI unit of frequency, one complete cycle per second." },
  { id: 'oscillation-7', type: 'mcq', question: "Angular frequency (ω), used to describe periodic and oscillatory motion, is related to the ordinary frequency (f) by the equation:", options: ["ω = f/(2π)", "ω = f", "ω = 2πf", "ω = f²/(2π)"], correctIndex: 2, difficulty: "medium", explanation: "Angular frequency is defined as ω = 2πf, converting cycles per second into radians per second." },
  { id: 'oscillation-8', type: 'mcq', question: "All simple harmonic motions (SHM) are necessarily periodic and oscillatory, but not all periodic/oscillatory motions are necessarily SHM, since SHM refers specifically to oscillatory motion that satisfies a particular:", options: ["Fixed value of amplitude, regardless of restoring force", "Constraint on the total energy of the system alone", "Mathematical/dynamical condition, involving a restoring force directly proportional to displacement from the mean position", "Requirement that the motion be circular"], correctIndex: 2, difficulty: "medium", explanation: "SHM is a restrictive category of oscillatory motion, defined specifically by a restoring force proportional to displacement." },

  // ---------- SHM: Definition and Equations ----------
  { id: 'oscillation-9', type: 'mcq', question: "Simple Harmonic Motion (SHM) is defined as an oscillatory motion in which the restoring force acting on the oscillating body is:", options: ["Constant in magnitude, regardless of displacement", "Directly proportional to the square of the displacement from the mean position", "Independent of the displacement from the mean position", "Directly proportional to the displacement from the mean position, and always directed towards that mean position"], correctIndex: 3, difficulty: "easy", explanation: "SHM is defined by a restoring force F = −kx, proportional to displacement and always directed towards equilibrium." },
  { id: 'oscillation-10', type: 'mcq', question: "The mathematical equation defining the restoring force in SHM, F = −kx, includes a negative sign to indicate that the force is:", options: ["Always directed opposite to the displacement, i.e. towards the mean (equilibrium) position", "Always negative in magnitude, regardless of direction", "Unrelated to the direction of displacement", "Only present when displacement is exactly zero"], correctIndex: 0, difficulty: "medium", explanation: "The negative sign shows the restoring force always acts opposite to displacement, pulling the body back toward its mean position." },
  { id: 'oscillation-11', type: 'mcq', question: "The displacement x(t) of a particle executing SHM, as a function of time t, can be expressed by the general equation:", options: ["x(t) = A + ωt", "x(t) = A sin(ωt + φ)", "x(t) = A/(ωt + φ)", "x(t) = A ω t², a quadratic function"], correctIndex: 1, difficulty: "medium", explanation: "This is the standard general equation for SHM displacement, where A is amplitude, ω is angular frequency, and φ is the phase constant." },
  { id: 'oscillation-12', type: 'mcq', question: "In the SHM displacement equation, x(t) = A sin(ωt + φ), the term A represents the:", options: ["Angular frequency of the motion", "Time period of the motion", "Phase constant of the motion", "Amplitude, i.e. the maximum displacement of the particle from its mean position"], correctIndex: 3, difficulty: "medium", explanation: "A represents the amplitude, the maximum magnitude of displacement from the equilibrium position." },
  { id: 'oscillation-13', type: 'mcq', question: "In the SHM displacement equation, x(t) = A sin(ωt + φ), the term φ (phi) represents the:", options: ["Amplitude", "Phase constant, determining the particle's position/state of motion at time t = 0", "Angular frequency", "Time period"], correctIndex: 1, difficulty: "medium", explanation: "The phase constant φ specifies the initial phase of the oscillation at t = 0." },
  { id: 'oscillation-14', type: 'mcq', question: "The differential equation that formally defines simple harmonic motion, relating the second derivative of displacement with respect to time to the displacement itself, is:", options: ["d²x/dt² = −ω²x", "d²x/dt² = ω²x", "dx/dt = −ω²x", "d²x/dt² = −ωx"], correctIndex: 0, difficulty: "medium", explanation: "This is the defining differential equation of SHM, showing acceleration proportional to (and opposite in sign to) displacement." },
  { id: 'oscillation-15', type: 'mcq', question: "The angular frequency ω in SHM is related to the force constant k (as in F = −kx) and the mass m of the oscillating body by the relation:", options: ["ω = k/m", "ω = √(k/m)", "ω = m/k", "ω² = k + m"], correctIndex: 1, difficulty: "medium", explanation: "This standard relation, ω = √(k/m), connects angular frequency to force constant and mass." },
  { id: 'oscillation-16', type: 'mcq', question: "The time period of an SHM, in terms of the mass m and force constant k, can be expressed as:", options: ["T = 2π√(m/k)", "T = 2π√(k/m)", "T = 2πm/k", "T = (1/2π)√(m/k)"], correctIndex: 0, difficulty: "medium", explanation: "This is the standard time period formula for SHM, T = 2π√(m/k), from T = 2π/ω and ω = √(k/m)." },
  { id: 'oscillation-17', type: 'mcq', question: "The point about which an oscillating body undergoing SHM moves back and forth, and at which the net restoring force on the body is zero, is called the:", options: ["Extreme position", "Point of maximum acceleration", "Point of maximum potential energy", "Mean (equilibrium) position"], correctIndex: 3, difficulty: "easy", explanation: "The mean (equilibrium) position is where the restoring force is zero, since displacement (and F = −kx) is zero there." },
  { id: 'oscillation-18', type: 'mcq', question: "The points at which an SHM particle momentarily comes to rest before reversing direction, corresponding to maximum displacement from the mean position, are called the:", options: ["Mean positions", "Extreme positions", "Points of zero potential energy", "Points of maximum kinetic energy"], correctIndex: 1, difficulty: "medium", explanation: "The extreme positions are where the SHM particle reaches its maximum displacement (the amplitude) and momentarily has zero velocity." },
  { id: 'oscillation-19', type: 'mcq', question: "Every particle executing simple harmonic motion must, by definition, execute periodic motion, but the converse is not necessarily true, since:", options: ["Periodic motion always implies a linear (non-oscillatory) restoring force", "Periodic and SHM are, in fact, identical terms with no distinction at all", "SHM is a broader category that always includes all forms of periodic motion", "Not every periodic motion satisfies the specific requirement of a restoring force directly proportional to displacement"], correctIndex: 3, difficulty: "medium", explanation: "SHM is a more restrictive subset of periodic motion; not all periodic motion satisfies the specific F ∝ −x requirement." },
  { id: 'oscillation-20', type: 'mcq', question: "A particle executing SHM completes one full oscillation (returns to its exact starting position and direction of motion) when its phase (ωt + φ) increases by exactly:", options: ["2π radians", "π radians", "π/2 radians", "4π radians"], correctIndex: 0, difficulty: "medium", explanation: "Since sine functions are periodic with period 2π, the phase must increase by exactly 2π radians for one complete oscillation." },

  // ---------- Velocity and Acceleration in SHM ----------
  { id: 'oscillation-21', type: 'mcq', question: "The velocity of a particle executing SHM, in terms of its displacement x, amplitude A, and angular frequency ω, is given by the formula:", options: ["v = ω√(A² − x²)", "v = ω(A² − x²)", "v = ω√(A² + x²)", "v = ω(A − x)"], correctIndex: 0, difficulty: "easy", explanation: "This is the standard formula for the instantaneous speed of a particle in SHM at displacement x." },
  { id: 'oscillation-22', type: 'mcq', question: "According to the SHM velocity formula, v = ω√(A² − x²), the velocity of the particle is maximum when the displacement x is:", options: ["Equal to the amplitude A", "Equal to half the amplitude", "Zero, i.e. when the particle passes through the mean (equilibrium) position", "Equal to −A"], correctIndex: 2, difficulty: "medium", explanation: "Velocity is maximised when A² − x² is largest, which occurs at x = 0 (the mean position)." },
  { id: 'oscillation-23', type: 'mcq', question: "The maximum velocity (vmax) attained by a particle executing SHM, occurring at the mean position, is given by the formula:", options: ["vmax = ω/A", "vmax = Aω", "vmax = A/ω", "vmax = Aω²"], correctIndex: 1, difficulty: "medium", explanation: "Setting x = 0 in v = ω√(A² − x²) gives vmax = Aω." },
  { id: 'oscillation-24', type: 'mcq', question: "According to the SHM velocity formula, the velocity of the particle becomes zero when the displacement x equals:", options: ["Zero", "Half of the amplitude", "A value greater than the amplitude", "The amplitude A (i.e. at the extreme positions)"], correctIndex: 3, difficulty: "medium", explanation: "Velocity becomes zero when x = ±A, at the extreme positions where the particle momentarily stops." },
  { id: 'oscillation-25', type: 'mcq', question: "The acceleration of a particle executing SHM, in terms of its displacement x and angular frequency ω, is given by the formula:", options: ["a = ωx", "a = −ω²x", "a = ω²x, without the negative sign", "a = −ωx²"], correctIndex: 1, difficulty: "medium", explanation: "This is the standard formula for acceleration in SHM, a = −ω²x." },
  { id: 'oscillation-26', type: 'mcq', question: "According to the SHM acceleration formula, a = −ω²x, the magnitude of acceleration is maximum when the displacement x is:", options: ["Equal to the amplitude A (i.e. at the extreme positions)", "Equal to zero (i.e. at the mean position)", "Equal to half the amplitude", "Undefined, since acceleration has no maximum value in SHM"], correctIndex: 0, difficulty: "medium", explanation: "Since |a| = ω²|x|, acceleration magnitude is maximum when |x| is maximum, at the extreme positions." },
  { id: 'oscillation-27', type: 'mcq', question: "The maximum acceleration (amax) of a particle executing SHM, occurring at the extreme positions, is given by the formula:", options: ["amax = Aω", "amax = A/ω²", "amax = Aω²", "amax = A/ω"], correctIndex: 2, difficulty: "medium", explanation: "Substituting x = A into a = −ω²x gives the magnitude of maximum acceleration, amax = Aω²." },
  { id: 'oscillation-28', type: 'mcq', question: "In SHM, the acceleration of the particle is minimum (in magnitude, equal to zero) at the:", options: ["Extreme positions", "Points where velocity is also zero", "Mean (equilibrium) position", "Points where kinetic energy is zero"], correctIndex: 2, difficulty: "medium", explanation: "Since a = −ω²x, acceleration is zero at x = 0, the mean position, where velocity is maximum." },
  { id: 'oscillation-29', type: 'mcq', question: "In SHM, velocity is maximum at the mean position while acceleration is zero there, and conversely, velocity is zero at the extreme positions while acceleration is maximum there. This illustrates that velocity and acceleration in SHM are generally:", options: ["Always exactly equal to each other at every point", "Always exactly proportional to each other, with the same sign", "Completely unrelated quantities", "Out of phase with each other, being maximum/minimum at opposite points in the oscillation cycle"], correctIndex: 3, difficulty: "medium", explanation: "Velocity and acceleration reach their respective extremes at opposite points in the SHM cycle, reflecting their phase difference." },
  { id: 'oscillation-30', type: 'mcq', question: "The direction of the acceleration of a particle in SHM, at any instant, is always:", options: ["Directed towards the mean (equilibrium) position, opposite to the direction of displacement", "Directed away from the mean position, in the same direction as displacement", "Perpendicular to the direction of displacement", "Constant in direction, regardless of the particle's position"], correctIndex: 0, difficulty: "medium", explanation: "Since a = −ω²x, acceleration always points opposite to displacement, toward the mean position, consistent with the restoring nature of SHM." },

  // ---------- Energy in SHM ----------
  { id: 'oscillation-31', type: 'mcq', question: "The kinetic energy of a particle executing SHM, at a given displacement x, is given by the formula:", options: ["KE = (1/2)mω²x²", "KE = (1/2)mω²(A² − x²)", "KE = (1/2)mω²(A² + x²)", "KE = mω²A²"], correctIndex: 1, difficulty: "medium", explanation: "This is the standard formula for kinetic energy in SHM, derived from KE = (1/2)mv² using v = ω√(A² − x²)." },
  { id: 'oscillation-32', type: 'mcq', question: "The potential energy of a particle executing SHM, at a given displacement x, is given by the formula:", options: ["PE = (1/2)mω²(A² − x²)", "PE = (1/2)mω²x²", "PE = (1/2)mω²A²", "PE = mω²x"], correctIndex: 1, difficulty: "medium", explanation: "The potential energy stored in SHM at displacement x is given by PE = (1/2)mω²x²." },
  { id: 'oscillation-33', type: 'mcq', question: "The total mechanical energy of a particle executing SHM, at any point during its oscillation, is given by the formula:", options: ["TE = (1/2)mω²A²", "TE = (1/2)mω²x²", "TE = mω²A", "TE = (1/2)mω²(A − x)²"], correctIndex: 0, difficulty: "easy", explanation: "Adding KE and PE gives the total energy TE = (1/2)mω²A², constant and independent of x." },
  { id: 'oscillation-34', type: 'mcq', question: "A key property of SHM is that, although kinetic energy and potential energy individually vary with displacement, their sum (the total mechanical energy) remains:", options: ["Zero at all times", "Maximum only at the extreme positions", "Maximum only at the mean position", "Constant throughout the motion, at every value of displacement"], correctIndex: 3, difficulty: "medium", explanation: "Total mechanical energy in SHM (for an undamped system) is conserved and constant throughout the oscillation." },
  { id: 'oscillation-35', type: 'mcq', question: "At the mean (equilibrium) position of an SHM, the kinetic energy of the oscillating particle is:", options: ["Zero", "Maximum, equal to the total mechanical energy", "Equal to the potential energy at that point", "Undefined"], correctIndex: 1, difficulty: "medium", explanation: "At x = 0, all total mechanical energy exists as kinetic energy (since PE = 0 there), so KE is maximum." },
  { id: 'oscillation-36', type: 'mcq', question: "At the extreme positions of an SHM, the potential energy of the oscillating particle is:", options: ["Maximum, equal to the total mechanical energy", "Zero", "Equal to the kinetic energy at that point", "Undefined"], correctIndex: 0, difficulty: "medium", explanation: "At x = ±A, all total mechanical energy exists as potential energy (since velocity, and KE, are zero there)." },
  { id: 'oscillation-37', type: 'mcq', question: "A graph of kinetic energy versus displacement for a particle in SHM has the shape of a(n):", options: ["Straight line", "Hyperbola", "Inverted parabola, maximum at x=0 and decreasing to zero at x=±A", "Perfect circle"], correctIndex: 2, difficulty: "medium", explanation: "Since KE = (1/2)mω²(A² − x²), plotting KE against x produces an inverted parabola peaking at x = 0." },
  { id: 'oscillation-38', type: 'mcq', question: "A graph of potential energy versus displacement for a particle in SHM has the shape of a(n):", options: ["Straight line", "Inverted parabola", "Upright parabola, minimum (zero) at x=0 and increasing to maximum at x=±A", "Hyperbola"], correctIndex: 2, difficulty: "medium", explanation: "Since PE = (1/2)mω²x², plotting PE against x gives an upright parabola, minimum at the mean position." },
  { id: 'oscillation-39', type: 'mcq', question: "Since total mechanical energy TE = (1/2)mω²A² for a particle in SHM, TE is directly proportional to the:", options: ["Displacement x at any given instant", "Angular frequency ω alone, without any dependence on amplitude", "Amplitude A alone, without any dependence on frequency", "Square of the amplitude A and the square of the angular frequency ω"], correctIndex: 3, difficulty: "medium", explanation: "The formula TE = (1/2)mω²A² shows total energy depends on both the square of amplitude and the square of angular frequency." },
  { id: 'oscillation-40', type: 'mcq', question: "If the amplitude of an SHM is doubled while its angular frequency remains unchanged, the total mechanical energy of the system becomes:", options: ["Four times its original value", "Twice its original value", "Half its original value", "Unchanged, since energy depends only on frequency"], correctIndex: 0, difficulty: "medium", explanation: "Since TE ∝ A², doubling the amplitude (with ω fixed) increases total energy by a factor of 2² = 4." },

  // ---------- The Simple Pendulum ----------
  { id: 'oscillation-41', type: 'mcq', question: "A simple pendulum consists of a point mass (bob) suspended from a fixed support by a light, inextensible string, and for small angular displacements, its motion closely approximates:", options: ["Uniform circular motion", "Simple harmonic motion", "Uniformly accelerated linear motion", "Random, non-periodic motion"], correctIndex: 1, difficulty: "easy", explanation: "For small angular displacements, the restoring force on a simple pendulum's bob is approximately proportional to displacement, closely approximating SHM." },
  { id: 'oscillation-42', type: 'mcq', question: "The time period of a simple pendulum of length L, oscillating under gravitational acceleration g, is given by the formula:", options: ["T = 2π√(g/L)", "T = 2π√(L/g)", "T = 2πL/g", "T = (1/2π)√(L/g)"], correctIndex: 1, difficulty: "easy", explanation: "This is the standard formula for the time period of a simple pendulum undergoing small-amplitude oscillations." },
  { id: 'oscillation-43', type: 'mcq', question: "According to the simple pendulum time period formula, T = 2π√(L/g), the time period is directly proportional to the:", options: ["Square root of the pendulum's length", "Pendulum's length itself, without any square root", "Square of the pendulum's length", "Inverse of the pendulum's length"], correctIndex: 0, difficulty: "medium", explanation: "Since T ∝ √L, the time period increases with the square root of the pendulum's length." },
  { id: 'oscillation-44', type: 'mcq', question: "According to the simple pendulum time period formula, the time period is inversely proportional to the:", options: ["Length of the pendulum", "Mass of the pendulum bob", "Amplitude of oscillation, for small angles", "Square root of the acceleration due to gravity"], correctIndex: 3, difficulty: "medium", explanation: "Since T ∝ 1/√g, a larger value of g results in a shorter time period." },
  { id: 'oscillation-45', type: 'mcq', question: "A key result for the simple pendulum is that its time period, T = 2π√(L/g), is completely independent of the:", options: ["Length of the string used", "Mass of the bob attached to the string", "Local value of gravitational acceleration", "Amplitude, but only for very large angular displacements"], correctIndex: 1, difficulty: "medium", explanation: "The time period formula contains no mass term, meaning the period is independent of the bob's mass for small-angle oscillations." },
  { id: 'oscillation-46', type: 'mcq', question: "If a simple pendulum's length is quadrupled, while gravitational acceleration remains constant, its time period will become:", options: ["Twice its original value", "Four times its original value", "Half its original value", "Unchanged, since period is independent of length"], correctIndex: 0, difficulty: "medium", explanation: "Since T ∝ √L, quadrupling the length (L → 4L) increases the time period by a factor of √4 = 2." },
  { id: 'oscillation-47', type: 'mcq', question: "A pendulum clock, calibrated correctly at sea level, is taken to a location with a slightly lower value of gravitational acceleration g (e.g. at higher altitude). As a result, the pendulum's time period will:", options: ["Decrease, causing the clock to run fast", "Remain exactly unchanged, since period is independent of g", "Increase, causing the clock to run slow", "Become undefined"], correctIndex: 2, difficulty: "medium", explanation: "Since T ∝ 1/√g, a lower g increases the time period, causing the pendulum to swing more slowly and the clock to run slow." },
  { id: 'oscillation-48', type: 'mcq', question: "A 'seconds pendulum' is a specific simple pendulum whose time period is exactly:", options: ["One minute", "One hour", "Two seconds (i.e. one second for each half-swing)", "Half a second"], correctIndex: 2, difficulty: "medium", explanation: "A seconds pendulum is defined as one with a time period of exactly 2 seconds." },
  { id: 'oscillation-49', type: 'mcq', question: "For a simple pendulum undergoing free fall (e.g. inside a freely falling lift or spacecraft in orbit, where the effective gravitational acceleration experienced is zero), the time period of the pendulum, according to T = 2π√(L/g), would become:", options: ["Zero", "Equal to the period at sea level, unaffected by free fall", "Extremely short, approaching zero", "Infinite (i.e. the pendulum would not oscillate at all, as there is no effective restoring force)"], correctIndex: 3, difficulty: "hard", explanation: "In free fall (effective g = 0), the formula predicts an infinite period, meaning the pendulum experiences no effective restoring force and does not oscillate." },
  { id: 'oscillation-50', type: 'mcq', question: "The simple pendulum approximation as SHM breaks down and becomes progressively less accurate for:", options: ["Very small angular displacements only", "Large angular displacements, where the restoring force is no longer well-approximated as directly proportional to angular displacement", "Any angular displacement whatsoever, since a simple pendulum never approximates SHM", "Changes in the pendulum's mass alone"], correctIndex: 1, difficulty: "medium", explanation: "The SHM approximation relies on sinθ ≈ θ; for large angular displacements this approximation breaks down." },

  // ---------- The Spring-Mass System ----------
  { id: 'oscillation-51', type: 'mcq', question: "For a mass m attached to an ideal spring of force constant k, oscillating horizontally on a frictionless surface, the motion executed is:", options: ["Simple harmonic motion", "Uniformly accelerated motion, without any oscillation", "Circular motion", "Random, non-periodic motion"], correctIndex: 0, difficulty: "easy", explanation: "A mass-spring system, governed by Hooke's law (F = −kx), is a classic exact example of SHM." },
  { id: 'oscillation-52', type: 'mcq', question: "The time period of oscillation of a mass m attached to a spring of force constant k is given by the formula:", options: ["T = 2π√(k/m)", "T = 2πkm", "T = 2π√(m/k)", "T = (1/2π)√(k/m)"], correctIndex: 2, difficulty: "medium", explanation: "This is the standard time period formula for a mass-spring SHM system, T = 2π√(m/k)." },
  { id: 'oscillation-53', type: 'mcq', question: "According to the spring-mass time period formula, T = 2π√(m/k), a stiffer spring (larger force constant k), for the same mass m, results in a:", options: ["Longer time period", "Time period unrelated to k", "Shorter time period", "Time period of exactly zero"], correctIndex: 2, difficulty: "medium", explanation: "Since T ∝ 1/√k, a stiffer spring results in a shorter time period." },
  { id: 'oscillation-54', type: 'mcq', question: "According to the spring-mass time period formula, a heavier mass attached to the same spring, for a fixed force constant k, results in a:", options: ["Shorter time period", "Time period unrelated to mass", "Time period of exactly zero", "Longer time period"], correctIndex: 3, difficulty: "medium", explanation: "Since T ∝ √m, a heavier mass results in a longer time period." },
  { id: 'oscillation-55', type: 'mcq', question: "When two identical springs, each with force constant k, are connected in series and attached to a mass m, the effective spring constant of the combination is:", options: ["2k", "k/2", "k²", "k, unchanged from a single spring"], correctIndex: 1, difficulty: "medium", explanation: "For springs in series, 1/keff = 1/k1 + 1/k2, so for two identical springs, keff = k/2." },
  { id: 'oscillation-56', type: 'mcq', question: "When two identical springs, each with force constant k, are connected in parallel and attached to a mass m, the effective spring constant of the combination is:", options: ["k/2", "2k", "k²", "k, unchanged from a single spring"], correctIndex: 1, difficulty: "medium", explanation: "For springs in parallel, keff = k1 + k2, so for two identical springs, keff = 2k." },
  { id: 'oscillation-57', type: 'mcq', question: "Since a series combination of two identical springs has a smaller effective spring constant than a single spring, a mass attached to this series combination will oscillate with a time period that is ___ than if it were attached to just one of the springs alone.", options: ["Longer", "Shorter", "Exactly the same", "Undefined"], correctIndex: 0, difficulty: "medium", explanation: "Since T ∝ 1/√k, and the series combination has a smaller keff (k/2), the resulting time period is longer." },
  { id: 'oscillation-58', type: 'mcq', question: "Since a parallel combination of two identical springs has a larger effective spring constant than a single spring, a mass attached to this parallel combination will oscillate with a time period that is ___ than if it were attached to just one of the springs alone.", options: ["Exactly the same", "Undefined", "Longer", "Shorter"], correctIndex: 3, difficulty: "medium", explanation: "Since T ∝ 1/√k, and the parallel combination has a larger keff (2k), the resulting time period is shorter." },

  // ---------- SHM as Projection of Circular Motion and Phase ----------
  { id: 'oscillation-59', type: 'mcq', question: "Simple harmonic motion can be conceptually understood as the projection, onto a single diameter, of a reference point moving with:", options: ["Variable, non-uniform speed along a straight line", "Uniform speed along a circular path", "Uniform acceleration along a straight line", "Random, unpredictable motion"], correctIndex: 1, difficulty: "medium", explanation: "SHM can be visualised as the one-dimensional projection of a point moving with constant angular velocity around a reference circle." },
  { id: 'oscillation-60', type: 'mcq', question: "The radius of the 'reference circle' used in the geometric interpretation of SHM as circular motion corresponds directly to the SHM's:", options: ["Amplitude", "Angular frequency", "Time period", "Phase constant"], correctIndex: 0, difficulty: "medium", explanation: "The radius of the reference circle equals the amplitude of the SHM, since the maximum projected displacement corresponds to the SHM's maximum displacement." },
  { id: 'oscillation-61', type: 'mcq', question: "The angular velocity of the reference point moving around the reference circle, in the circular-motion interpretation of SHM, corresponds directly to the SHM's:", options: ["Angular frequency ω", "Amplitude", "Time period alone, with no relation to angular frequency", "Phase constant alone"], correctIndex: 0, difficulty: "medium", explanation: "The angular speed of the reference point around the circle is set equal to the angular frequency (ω) of the corresponding SHM." },
  { id: 'oscillation-62', type: 'mcq', question: "In SHM, the velocity of the particle is found to lead the displacement in phase by:", options: ["A full cycle (2π radians)", "Zero phase difference; they are exactly in phase", "π radians (180°)", "π/2 radians (90°)"], correctIndex: 3, difficulty: "hard", explanation: "Differentiating x = A sin(ωt) gives v = Aω cos(ωt), exactly 90° out of phase with (leading) the displacement." },
  { id: 'oscillation-63', type: 'mcq', question: "In SHM, the acceleration of the particle is found to be out of phase with the displacement by:", options: ["π/2 radians (90°)", "π radians (180°), i.e. acceleration and displacement are exactly opposite in direction at any instant", "2π radians (a full cycle, effectively in phase)", "Zero phase difference; they are exactly in phase"], correctIndex: 1, difficulty: "medium", explanation: "Since a = −ω²x, acceleration is always exactly opposite in sign to displacement, a phase difference of π radians (180°)." },
  { id: 'oscillation-64', type: 'mcq', question: "The phase relationships in SHM (velocity leading displacement by 90°, and acceleration being 180° out of phase with displacement) reflect the successive time-derivative relationship between these quantities, since each differentiation with respect to time in SHM introduces an additional phase shift of:", options: ["A full cycle (2π radians)", "Zero, since differentiation does not affect phase", "π radians (180°) per derivative", "π/2 radians (90°) per derivative"], correctIndex: 3, difficulty: "hard", explanation: "Each differentiation of a sinusoidal function shifts its phase by 90°, so velocity leads displacement by 90° and acceleration leads by 180°." },

  // ---------- Damped Oscillations ----------
  { id: 'oscillation-65', type: 'mcq', question: "Real oscillating systems, unlike idealised SHM, generally experience a gradual loss of mechanical energy over time due to resistive forces such as friction or air resistance, resulting in:", options: ["An increase in amplitude over time", "Damped oscillations, in which the amplitude progressively decreases over time", "A constant, unchanging amplitude, exactly as in ideal SHM", "Oscillations that stop completely and instantly, with no gradual decrease"], correctIndex: 1, difficulty: "medium", explanation: "Real-world oscillators experience energy dissipation from resistive forces, causing damped oscillations with progressively decreasing amplitude." },
  { id: 'oscillation-66', type: 'mcq', question: "In damped oscillations, the amplitude of the motion is typically found to decrease with time according to an approximately:", options: ["Linear function of time", "Exponentially decaying function of time", "Function that increases without limit", "Perfectly periodic, non-decreasing function"], correctIndex: 1, difficulty: "medium", explanation: "For common damping (proportional to velocity), amplitude decreases exponentially with time." },
  { id: 'oscillation-67', type: 'mcq', question: "The damping force acting on an oscillating system, responsible for the gradual loss of mechanical energy, commonly arises from sources such as:", options: ["Friction and air/fluid resistance", "The oscillator's own restoring force, which is not a damping force", "Gravitational attraction alone", "The oscillator's own inertia alone"], correctIndex: 0, difficulty: "easy", explanation: "Common physical sources of damping include friction and air or fluid resistance (drag) opposing the motion." },
  { id: 'oscillation-68', type: 'mcq', question: "As a damped oscillation proceeds, since the amplitude progressively decreases, the total mechanical energy of the oscillating system also progressively:", options: ["Increases", "Remains exactly constant, just as in ideal SHM", "Becomes infinite", "Decreases, since it is being continuously dissipated (e.g. as heat) by the damping force"], correctIndex: 3, difficulty: "medium", explanation: "As the damping force does negative work over each cycle, mechanical energy is continuously dissipated, causing amplitude and total energy to decrease." },
  { id: 'oscillation-69', type: 'mcq', question: "'Critical damping' refers to the specific level of damping at which an oscillating system, when disturbed from equilibrium, returns to its equilibrium position:", options: ["After oscillating back and forth many times", "As quickly as possible, without oscillating back and forth at all", "Never, remaining permanently displaced", "After an infinitely long time, oscillating indefinitely"], correctIndex: 1, difficulty: "medium", explanation: "Critical damping is the precise threshold at which the system returns to equilibrium in the shortest possible time without oscillatory overshoot." },
  { id: 'oscillation-70', type: 'mcq', question: "A shock absorber in a vehicle's suspension system is a practical, real-world application designed to provide sufficient damping so that, after hitting a bump, the vehicle:", options: ["Settles back to its equilibrium position quickly, without prolonged oscillation", "Oscillates indefinitely, for as long as possible", "Bounces with an ever-increasing amplitude", "Experiences no damping whatsoever, behaving like an ideal SHM system"], correctIndex: 0, difficulty: "medium", explanation: "Shock absorbers provide near-critical damping, allowing suspension to quickly settle after a disturbance rather than continuing to oscillate." },
  { id: 'oscillation-71', type: 'mcq', question: "'Underdamping' refers to a level of damping that is relatively light, such that the oscillating system:", options: ["Does not oscillate at all, returning directly to equilibrium", "Continues to oscillate, but with a progressively decreasing amplitude, before eventually settling at equilibrium", "Oscillates with a constant, unchanging amplitude, exactly as in ideal SHM", "Never returns to equilibrium at all"], correctIndex: 1, difficulty: "medium", explanation: "Underdamped systems continue to oscillate with continuously diminishing amplitude, eventually settling at equilibrium." },
  { id: 'oscillation-72', type: 'mcq', question: "'Overdamping' refers to a level of damping so strong that the oscillating system, when displaced from equilibrium:", options: ["Oscillates rapidly with a large amplitude", "Returns to equilibrium slowly, without oscillating back and forth at all", "Never returns to equilibrium under any circumstances", "Behaves exactly as it would under critical damping, with no distinguishable difference"], correctIndex: 1, difficulty: "medium", explanation: "In an overdamped system, damping is strong enough to prevent oscillation, but the return to equilibrium is slower than critical damping." },

  // ---------- Forced Oscillations and Resonance ----------
  { id: 'oscillation-73', type: 'mcq', question: "Oscillations that occur when a body, after being displaced from equilibrium, is left to oscillate on its own, without any continued external driving force, are called:", options: ["Free oscillations", "Forced oscillations", "Resonant oscillations exclusively", "Damped oscillations exclusively, with no other classification"], correctIndex: 0, difficulty: "easy", explanation: "Free oscillations occur when a system oscillates on its own at its natural frequency, without a continuing external driving force." },
  { id: 'oscillation-74', type: 'mcq', question: "The natural frequency of a system undergoing free oscillations is a characteristic property determined by the system's own physical parameters, such as its mass and:", options: ["The colour of the material", "The ambient temperature exclusively, with no other factor involved", "The atmospheric pressure exclusively", "Its restoring force characteristics (e.g. the spring constant, or length for a pendulum)"], correctIndex: 3, difficulty: "medium", explanation: "Natural frequency depends on intrinsic physical parameters like mass and restoring-force characteristics, not external conditions." },
  { id: 'oscillation-75', type: 'mcq', question: "Oscillations that occur when a system is continuously driven by an external periodic force are called:", options: ["Free oscillations", "Forced oscillations", "Damped oscillations exclusively, unrelated to any driving force", "Random oscillations"], correctIndex: 1, difficulty: "easy", explanation: "Forced oscillations occur when an external periodic driving force continuously acts on the oscillating system." },
  { id: 'oscillation-76', type: 'mcq', question: "In forced oscillations, after any initial transient behaviour has settled, the system eventually oscillates at the frequency of the:", options: ["System's own natural frequency, regardless of the driving force", "External driving force, rather than at its own natural frequency", "Average of the natural and driving frequencies", "Difference between the natural and driving frequencies"], correctIndex: 1, difficulty: "medium", explanation: "In steady-state forced oscillations, the system ultimately oscillates at the frequency imposed by the external driving force." },
  { id: 'oscillation-77', type: 'mcq', question: "Resonance is the phenomenon in which the amplitude of a forced oscillation becomes especially large when the frequency of the external driving force:", options: ["Closely matches (or equals) the natural frequency of the oscillating system", "Is much higher than the natural frequency of the system", "Is much lower than the natural frequency of the system", "Has no relationship at all to the natural frequency"], correctIndex: 0, difficulty: "easy", explanation: "Resonance occurs when the driving frequency approaches or matches the system's own natural frequency." },
  { id: 'oscillation-78', type: 'mcq', question: "A classic, cautionary real-world example illustrating the potentially destructive effects of resonance is the historical collapse of certain bridges when marching soldiers' footsteps happened to match the bridge's:", options: ["Total mass", "Colour", "Length alone, with no relation to frequency", "Natural frequency of oscillation"], correctIndex: 3, difficulty: "medium", explanation: "When a periodic driving force matches a structure's natural frequency, resonance can build up dangerously large oscillation amplitudes." },
  { id: 'oscillation-79', type: 'mcq', question: "At resonance, the amplitude of a forced oscillation, in the idealised case of negligible damping, would theoretically become:", options: ["Zero", "Extremely (theoretically infinitely) large", "Exactly equal to the driving force's own amplitude, with no dependence on frequency matching", "Independent of whether resonance conditions are met at all"], correctIndex: 1, difficulty: "medium", explanation: "In the idealised, undamped case, resonance theoretically causes oscillation amplitude to grow without bound." },
  { id: 'oscillation-80', type: 'mcq', question: "In real, physical systems, damping (due to friction, air resistance, etc.) has the important practical effect of preventing the amplitude at resonance from becoming infinite, instead limiting it to a:", options: ["Finite, though still often very large, maximum value", "Value of exactly zero, eliminating resonance entirely", "Value that has no dependence on the amount of damping present", "Value that always exceeds the driving force's own amplitude by an identical fixed ratio, regardless of damping"], correctIndex: 0, difficulty: "medium", explanation: "Real-world damping continuously dissipates energy, capping resonance amplitude at a large but finite maximum value." },

];

export default questions; 