import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Gravitation
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Kepler's Laws ----------
  { id: 1, type: 'mcq', question: "Kepler's first law of planetary motion states that every planet moves around the Sun in a(n):", options: ["Elliptical orbit with the Sun at one focus", "Perfect circular orbit with the Sun at the centre", "Parabolic path", "Straight line"], correctIndex: 0, difficulty: "easy", explanation: "Kepler's first law (law of orbits) explicitly states planetary orbits are ellipses with the Sun at one of the two foci, not circles." },
  { id: 2, type: 'mcq', question: "Kepler's second law, also called the law of areas, states that the line joining a planet to the Sun sweeps out:", options: ["Different areas in different, unequal time intervals", "A constant angle in equal time intervals", "Equal areas in equal intervals of time", "A decreasing area as the planet approaches the Sun"], correctIndex: 2, difficulty: "easy", explanation: "The law of areas states the radius vector sweeps equal areas in equal times, a direct consequence of conservation of angular momentum since gravity is a central force." },
  { id: 3, type: 'mcq', question: "Kepler's law of areas is a direct consequence of the conservation of:", options: ["Linear momentum", "Angular momentum", "Mechanical energy exclusively", "Mass"], correctIndex: 1, difficulty: "medium", explanation: "Since gravitational force is central (directed along the Sun-planet line), it exerts no torque about the Sun, so angular momentum is conserved — this directly implies the equal-areas law." },
  { id: 4, type: 'mcq', question: "According to Kepler's second law, a planet moves ___ when it is closer to the Sun (at perihelion) than when it is farther away (at aphelion).", options: ["At the same constant speed", "Slower", "Not at all", "Faster"], correctIndex: 3, difficulty: "medium", explanation: "To sweep equal areas in equal time, the planet must move faster when close to the Sun since a smaller radius needs a longer arc to sweep the same area." },
  { id: 5, type: 'mcq', question: "Kepler's third law, the law of periods, states that the square of the time period of revolution of a planet around the Sun is proportional to:", options: ["The planet's mass", "The cube of the semi-major axis of its elliptical orbit", "The square of the semi-major axis", "The planet's orbital speed"], correctIndex: 1, difficulty: "easy", explanation: "Kepler's third law states T² ∝ a³, where a is the semi-major axis — the precise mathematical form of the law of periods." },
  { id: 6, type: 'mcq', question: "Kepler's third law can be expressed as T² = k a³, where the constant k is:", options: ["The same for all planets orbiting the same central body (e.g. the Sun)", "Different for every planet, depending on its mass", "Dependent on the planet's own gravitational field strength", "Equal to the universal gravitational constant G directly"], correctIndex: 0, difficulty: "medium", explanation: "The proportionality constant in T² = ka³ depends only on the mass of the central body being orbited, so it is the same for all planets orbiting that same body." },
  { id: 7, type: 'mcq', question: "Kepler's laws of planetary motion were later shown by Newton to be consistent with, and explainable in terms of, the:", options: ["Special theory of relativity", "Law of conservation of mass", "Universal law of gravitation", "Photoelectric effect"], correctIndex: 2, difficulty: "easy", explanation: "Newton demonstrated that all three of Kepler's empirical laws follow mathematically from his universal law of gravitation combined with the laws of motion." },
  { id: 8, type: 'mcq', question: "If the time period of a planet's revolution around the Sun is T and the semi-major axis of its orbit is a, then according to Kepler's third law, T²/a³ is:", options: ["Different for each planet in the solar system", "Proportional to the planet's mass", "A constant, the same for all planets orbiting the Sun", "Inversely proportional to a"], correctIndex: 2, difficulty: "medium", explanation: "T² ∝ a³ means T²/a³ is a fixed constant for all planets orbiting the same central body — the essence of Kepler's third law." },
  { id: 9, type: 'mcq', question: "For a planet moving in an elliptical orbit around the Sun, its speed is maximum at the point in its orbit called the:", options: ["Apogee", "Aphelion", "Focus", "Perihelion, the point of closest approach to the Sun"], correctIndex: 3, difficulty: "medium", explanation: "At perihelion the planet is closest to the Sun, and by the law of areas its orbital speed must be at its maximum there." },
  { id: 10, type: 'mcq', question: "For a planet moving in an elliptical orbit around the Sun, its speed is minimum at the point in its orbit called the:", options: ["Aphelion, the point farthest from the Sun", "Perihelion", "Focus", "Perigee"], correctIndex: 0, difficulty: "medium", explanation: "At aphelion the planet is farthest from the Sun, and by the equal-areas law its speed is at its minimum there." },

  // ---------- Newton's Law of Gravitation ----------
  { id: 11, type: 'mcq', question: "Newton's universal law of gravitation states that the force of attraction between two point masses is directly proportional to the product of their masses and:", options: ["Directly proportional to the distance between them", "Inversely proportional to the square of the distance between them", "Independent of the distance between them", "Proportional to the cube of the distance between them"], correctIndex: 1, difficulty: "easy", explanation: "Newton's law states F = Gm1m2/r², i.e. the force is inversely proportional to r² — the inverse-square nature of gravity." },
  { id: 12, type: 'mcq', question: "The value of the universal gravitational constant G, as determined experimentally (e.g. by Cavendish's experiment), is approximately:", options: ["9.8 m/s²", "6.67 × 10⁻¹¹ N m²/kg²", "3 × 10⁸ m/s", "1.6 × 10⁻¹⁹ C"], correctIndex: 1, difficulty: "easy", explanation: "G has the standard, universally accepted value of approximately 6.67 × 10⁻¹¹ N m²/kg², first measured by Henry Cavendish." },
  { id: 13, type: 'mcq', question: "The gravitational force between two masses, according to Newton's law of gravitation, acts along the line joining the two masses and is:", options: ["Always attractive in nature", "Always repulsive in nature", "Sometimes attractive and sometimes repulsive, depending on the masses", "Zero for masses of equal magnitude"], correctIndex: 0, difficulty: "easy", explanation: "Unlike electric force, gravitational force between any two masses is always attractive, never repulsive." },
  { id: 14, type: 'mcq', question: "Newton's law of gravitation applies to:", options: ["Only celestial bodies such as planets and stars", "Only objects on the surface of Earth", "Only extremely massive objects", "Any two bodies with mass, anywhere in the universe — hence the term 'universal'"], correctIndex: 3, difficulty: "easy", explanation: "The law is termed 'universal' precisely because it applies to any two masses anywhere in the universe, not just to large astronomical bodies." },
  { id: 15, type: 'mcq', question: "If the distance between two masses is doubled, the gravitational force of attraction between them becomes:", options: ["Twice as large", "One-quarter of the original value", "Half of the original value", "Four times as large"], correctIndex: 1, difficulty: "medium", explanation: "Since F ∝ 1/r², doubling r reduces the force by a factor of 2² = 4, so the new force is one-quarter of the original." },
  { id: 16, type: 'mcq', question: "If the distance between two masses is halved, the gravitational force of attraction between them becomes:", options: ["Four times as large", "Half as large", "One-quarter as large", "Twice as large"], correctIndex: 0, difficulty: "medium", explanation: "Since F ∝ 1/r², halving r increases the force by a factor of 2² = 4." },
  { id: 17, type: 'mcq', question: "The gravitational force between two point masses m1 and m2 separated by a distance r is given by the equation:", options: ["F = G(m1+m2)/r²", "F = G m1m2 / r", "F = G m1m2 / r²", "F = G m1m2 r²"], correctIndex: 2, difficulty: "easy", explanation: "This is the standard mathematical statement of Newton's law of gravitation, F = Gm1m2/r²." },
  { id: 18, type: 'mcq', question: "Gravitational force is one of the four fundamental forces of nature and is generally considered to be:", options: ["The strongest of the four fundamental forces", "Equal in strength to the electromagnetic force", "The weakest of the four fundamental forces", "Stronger than the strong nuclear force"], correctIndex: 2, difficulty: "medium", explanation: "Despite governing large-scale astronomical structure, gravity is by far the weakest of the four fundamental forces." },
  { id: 19, type: 'mcq', question: "Newton's law of gravitation obeys Newton's third law, meaning that the gravitational force exerted by mass A on mass B is:", options: ["Larger than the force exerted by B on A, if A is more massive", "Smaller than the force exerted by B on A, if A is more massive", "Unrelated in magnitude to the force exerted by B on A", "Equal in magnitude and opposite in direction to the force exerted by B on A"], correctIndex: 3, difficulty: "medium", explanation: "Gravitational forces obey Newton's third law — the mutual attractive forces between two masses are always equal in magnitude and opposite in direction, regardless of the individual masses." },
  { id: 20, type: 'mcq', question: "The gravitational constant G, unlike the acceleration due to gravity g, is:", options: ["A universal constant, with the same value everywhere in the universe", "Different on the Moon compared to on Earth", "Dependent on the altitude above Earth's surface", "Dependent on the mass of the smaller of the two interacting bodies"], correctIndex: 0, difficulty: "medium", explanation: "G is a universal constant with a fixed value everywhere, unlike g, which varies with the mass and radius of the specific astronomical body and location." },

  // ---------- Acceleration due to Gravity: Variation ----------
  { id: 21, type: 'mcq', question: "The acceleration due to gravity on the surface of the Earth is related to the universal gravitational constant G, Earth's mass M, and Earth's radius R by the formula:", options: ["g = GM/R²", "g = GM/R", "g = GMR²", "g = G/MR²"], correctIndex: 0, difficulty: "easy", explanation: "Equating the gravitational force on a mass m (GmM/R²) to mg gives g = GM/R², the standard surface-gravity formula." },
  { id: 22, type: 'mcq', question: "The standard/average value of acceleration due to gravity at the Earth's surface is approximately:", options: ["6.67 m/s²", "11.2 m/s²", "9.8 m/s²", "3.8 m/s²"], correctIndex: 2, difficulty: "easy", explanation: "The commonly used average value of g at Earth's surface is 9.8 m/s² (often approximated as 9.81 or 10 m/s² in numerical problems)." },
  { id: 23, type: 'mcq', question: "As one moves to a height h above the Earth's surface (with h much smaller than Earth's radius R), the acceleration due to gravity g' at that height, compared to the surface value g, approximately follows the relation:", options: ["g' = g(1 + 2h/R)", "g' = g(1 − 2h/R)", "g' = g(1 + h/R)²", "g' = g, with no change at all"], correctIndex: 1, difficulty: "medium", explanation: "For h << R, the exact inverse-square formula g' = g/(1+h/R)² is binomially approximated to g' = g(1 − 2h/R), showing g decreases with height." },
  { id: 24, type: 'mcq', question: "As one moves to a depth d below the Earth's surface, the acceleration due to gravity g' at that depth, compared to the surface value g, follows the relation:", options: ["g' = g(1 + d/R)", "g' = g(1 − 2d/R)", "g' = g, unchanged regardless of depth", "g' = g(1 − d/R)"], correctIndex: 3, difficulty: "medium", explanation: "Below the surface, only mass enclosed within radius (R−d) contributes to gravity; the uniform-density model gives g' = g(1 − d/R)." },
  { id: 25, type: 'mcq', question: "According to the depth-variation formula for gravity, as one descends toward the centre of the Earth (d approaching R), the value of g:", options: ["Increases continuously, becoming infinite at the centre", "Decreases continuously, becoming zero at the centre", "Remains constant at the surface value", "Oscillates unpredictably"], correctIndex: 1, difficulty: "medium", explanation: "From g' = g(1 − d/R), as d → R (the very centre), g' → 0, meaning gravitational acceleration vanishes at the Earth's centre." },
  { id: 26, type: 'mcq', question: "Comparing the variation of g with height and with depth (for small h and d), the value of g decreases:", options: ["More rapidly with an increase in height than with an equal increase in depth", "More rapidly with an increase in depth than with an equal increase in height", "At exactly the same rate for both height and depth", "Only with depth, never with height"], correctIndex: 0, difficulty: "medium", explanation: "The approximate formulas g(1−2h/R) for height versus g(1−d/R) for depth show a factor-of-2 steeper drop-off with height for the same small distance from the surface." },
  { id: 27, type: 'mcq', question: "The acceleration due to gravity at the Earth's poles, compared to at the equator, is:", options: ["Smaller at the poles", "Exactly the same at both locations", "Slightly larger at the poles", "Zero at the poles"], correctIndex: 2, difficulty: "medium", explanation: "Because Earth is slightly flattened at the poles and rotational effects are absent there, g is slightly greater at the poles than at the equator." },
  { id: 28, type: 'mcq', question: "One reason the acceleration due to gravity is smaller at the equator than at the poles is that Earth's rotation causes an object at the equator to experience a greater:", options: ["Gravitational attraction from the Sun", "Distance from the Moon", "Centrifugal effect, which partially offsets the true gravitational pull", "Magnetic field strength"], correctIndex: 2, difficulty: "medium", explanation: "The centrifugal effect from Earth's rotation is maximum at the equator (largest rotation radius) and reduces the net apparent gravitational acceleration there compared to the poles." },
  { id: 29, type: 'mcq', question: "If the Earth were to stop rotating about its axis entirely, the acceleration due to gravity 'g' at the equator would:", options: ["Decrease further from its current value", "Become exactly zero", "Remain completely unchanged", "Increase slightly from its current value"], correctIndex: 3, difficulty: "hard", explanation: "Stopping Earth's rotation would eliminate the centrifugal effect currently reducing apparent g at the equator, so g there would increase slightly." },
  { id: 30, type: 'mcq', question: "The variation of acceleration due to gravity with latitude, due to Earth's rotation, is such that g is:", options: ["Minimum at the equator and maximum at the poles", "Maximum at the equator and minimum at the poles", "The same at all latitudes", "Zero at the equator"], correctIndex: 0, difficulty: "medium", explanation: "The centrifugal effect is strongest at the equator and zero at the poles, making g minimum at the equator and maximum at the poles." },
  { id: 31, type: 'mcq', question: "At the exact centre of the Earth, the net gravitational force on an object (assuming a uniform, spherically symmetric Earth) is:", options: ["Maximum, since it is closest to all the mass", "Zero, since the gravitational pull from all directions cancels out", "Directed towards the nearest pole", "Equal to its value at the surface"], correctIndex: 1, difficulty: "medium", explanation: "At the exact centre of a uniform sphere, gravitational pull from mass on all sides is symmetric and cancels out exactly, giving zero net force." },
  { id: 32, type: 'mcq', question: "The weight of a body is defined as the force with which the Earth attracts it, and is given by:", options: ["W = m/g", "W = mg", "W = m + g", "W = g/m"], correctIndex: 1, difficulty: "easy", explanation: "Weight is simply the gravitational force on a mass m due to Earth's gravity g, given by W = mg." },
  { id: 33, type: 'mcq', question: "Since g varies slightly with height, depth, and latitude, the weight of a given object (with constant mass m):", options: ["Also varies correspondingly with location, since W = mg", "Remains exactly constant everywhere, regardless of g", "Depends only on the object's mass, with no dependence on g at all", "Is undefined at any location other than the equator"], correctIndex: 0, difficulty: "medium", explanation: "Since W = mg and mass m is constant for a given object, variation in g with location directly produces a corresponding variation in weight." },
  { id: 34, type: 'mcq', question: "Mass and weight are fundamentally different physical quantities because mass is a measure of the amount of matter in a body (and is constant), while weight:", options: ["Is also always exactly constant, identical to mass", "Has no relationship to gravitational acceleration at all", "Is measured in the same units as mass", "Depends on the local value of gravitational acceleration, and can therefore vary with location"], correctIndex: 3, difficulty: "easy", explanation: "Mass is intrinsic and location-independent, while weight (W=mg) depends on local g and changes from place to place (e.g., less on the Moon)." },

  // ---------- Gravitational Potential Energy and Field ----------
  { id: 35, type: 'mcq', question: "The gravitational potential energy of a system of two masses m and M separated by a distance r, taking the reference (zero) potential energy at infinite separation, is given by:", options: ["U = +GMm/r", "U = −GMm/r", "U = GMm r", "U = −GMm r²"], correctIndex: 1, difficulty: "medium", explanation: "With zero PE at infinite separation, gravitational PE for two attracting masses is negative: U = −GMm/r, becoming less negative as r increases." },
  { id: 36, type: 'mcq', question: "The gravitational potential energy of a two-mass system is taken to be negative because:", options: ["Since gravity is attractive, work must be done against the force to separate the masses to infinity, where PE is defined as zero — meaning PE at any finite separation is lower (negative) than at infinity", "Negative energy has no real physical meaning and is purely a mathematical convention with no basis", "Gravitational force is actually repulsive at short distances", "Mass itself is considered a negative quantity in this context"], correctIndex: 0, difficulty: "medium", explanation: "Because gravitational attraction does positive work as masses come together, and PE is zero at infinite separation, PE at any finite (closer) separation must be negative." },
  { id: 37, type: 'mcq', question: "The gravitational potential (V) at a point in space, due to a mass M, is defined as the work done per unit mass in bringing a test mass from infinity to that point, and is given by:", options: ["V = +GM/r", "V = GMr", "V = −GM/r", "V = −GM r²"], correctIndex: 2, difficulty: "medium", explanation: "Gravitational potential is negative, given by V = −GM/r, representing work done per unit mass bringing a test mass from infinity." },
  { id: 38, type: 'mcq', question: "The gravitational field at a point due to a mass M, at a distance r from it, is defined as the force experienced per unit mass placed at that point, and has magnitude:", options: ["GM r²", "GM r", "GM/r²", "GM/r"], correctIndex: 2, difficulty: "easy", explanation: "Gravitational field strength is force per unit test mass, E = F/m = GM/r², directly from Newton's law of gravitation." },
  { id: 39, type: 'mcq', question: "The relationship between gravitational potential V and gravitational field E along a given direction is given by:", options: ["E = V × r", "E = V/r, with no derivative involved", "E = ∫V dr", "E = −dV/dr (the negative gradient of potential)"], correctIndex: 3, difficulty: "hard", explanation: "Just as electric field is the negative gradient of electric potential, gravitational field is the negative gradient of gravitational potential, E = −dV/dr." },
  { id: 40, type: 'mcq', question: "The work done in moving a mass m from one point to another in a gravitational field is equal to the mass times the:", options: ["Difference in gravitational potential between the two points", "Sum of the gravitational potentials at the two points", "Product of the gravitational potentials at the two points", "Square of the distance between the two points"], correctIndex: 0, difficulty: "medium", explanation: "Work done W = m(V1 − V2), the mass times the difference in gravitational potential between the initial and final points." },
  { id: 41, type: 'mcq', question: "Since gravitational potential energy at infinity is taken as zero, and gravity is attractive, the gravitational potential energy of a system of two masses at any finite separation is always:", options: ["Positive", "Negative or zero", "Undefined", "Equal to zero at every finite separation"], correctIndex: 1, difficulty: "medium", explanation: "Under the standard convention, attractive gravitational PE at any finite separation is always negative (approaching zero only as r → ∞)." },
  { id: 42, type: 'mcq', question: "Gravitational field lines around an isolated point mass are directed:", options: ["Radially outward, away from the mass", "Radially inward, toward the mass", "Tangentially, in circles around the mass", "Parallel straight lines in a fixed direction, regardless of position"], correctIndex: 1, difficulty: "medium", explanation: "Since gravity is always attractive, gravitational field lines point radially inward toward the source mass, unlike electric field lines around a positive charge." },

  // ---------- Escape Velocity ----------
  { id: 43, type: 'mcq', question: "Escape velocity is defined as the minimum velocity with which a body must be projected from the surface of a planet so that it:", options: ["Just escapes the planet's gravitational field and never returns", "Reaches exactly the height of one planetary radius", "Orbits the planet indefinitely in a circular path", "Falls back to the surface after a fixed time"], correctIndex: 0, difficulty: "easy", explanation: "Escape velocity is the minimum launch speed needed for a body to escape a planet's gravitational pull entirely, reaching infinity with (at minimum) zero residual kinetic energy." },
  { id: 44, type: 'mcq', question: "The escape velocity from a planet of mass M and radius R is given by the formula:", options: ["ve = GM/R", "ve = √(GM/R)", "ve = GM/R²", "ve = √(2GM/R)"], correctIndex: 3, difficulty: "easy", explanation: "Setting total mechanical energy (KE+PE) to zero at the surface gives (1/2)mve² = GMm/R, which rearranges to ve = √(2GM/R)." },
  { id: 45, type: 'mcq', question: "Escape velocity can also be expressed in terms of the acceleration due to gravity g and the planet's radius R as:", options: ["ve = √(gR)", "ve = √(2gR)", "ve = gR²", "ve = √(g/R)"], correctIndex: 1, difficulty: "easy", explanation: "Substituting g = GM/R² into ve = √(2GM/R) gives the equivalent form ve = √(2gR)." },
  { id: 46, type: 'mcq', question: "The escape velocity from the surface of the Earth is approximately:", options: ["11.2 km/s", "9.8 km/s", "1.6 km/s", "3 × 10^5 km/s"], correctIndex: 0, difficulty: "easy", explanation: "Using Earth's mass and radius, the standard value of escape velocity from Earth's surface is approximately 11.2 km/s." },
  { id: 47, type: 'mcq', question: "The escape velocity of a body from a planet's surface is independent of:", options: ["The planet's mass", "The planet's radius", "The mass of the escaping body itself", "The value of the universal gravitational constant G"], correctIndex: 2, difficulty: "medium", explanation: "In ve = √(2GM/R), the mass of the escaping projectile cancels out entirely, so escape velocity depends only on the planet's mass and radius." },
  { id: 48, type: 'mcq', question: "The escape velocity from the Moon's surface, compared to that from the Earth's surface, is:", options: ["Larger, because the Moon has a larger radius", "Exactly equal, since both bodies exist in the same gravitational environment", "Much smaller, mainly because the Moon has significantly less mass", "Impossible to calculate, since the Moon has no atmosphere"], correctIndex: 2, difficulty: "medium", explanation: "Since ve = √(2GM/R) and the Moon has far less mass than Earth, the Moon's escape velocity (about 2.4 km/s) is much smaller than Earth's (11.2 km/s)." },
  { id: 49, type: 'mcq', question: "A relatively low escape velocity, such as that of the Moon, is one important reason why a body may have:", options: ["An unusually thick and stable atmosphere", "An extremely strong magnetic field", "A very high average surface temperature", "Little to no retained atmosphere, since gas molecules can more easily reach and exceed the escape velocity"], correctIndex: 3, difficulty: "medium", explanation: "With a low escape velocity, even thermal speeds of light gas molecules can exceed it, allowing atmospheric gases to gradually escape — why bodies like the Moon lack a substantial atmosphere." },
  { id: 50, type: 'mcq', question: "The relationship between escape velocity (ve) and orbital velocity (vo) for a satellite in a circular orbit just above a planet's surface is given by:", options: ["ve = √2 × vo", "ve = vo/√2", "ve = vo", "ve = 2 × vo"], correctIndex: 0, difficulty: "medium", explanation: "Comparing ve = √(2GM/R) with vo = √(GM/R) directly gives ve = √2 · vo, a standard tested relation." },
  { id: 51, type: 'mcq', question: "If a body is projected with a velocity greater than the escape velocity from a planet's surface, it will:", options: ["Fall back to the surface after reaching a certain maximum height", "Escape the planet's gravitational field with some residual velocity remaining even at infinity", "Enter a stable circular orbit around the planet", "Immediately disintegrate due to excess energy"], correctIndex: 1, difficulty: "medium", explanation: "A launch speed exceeding escape velocity means positive total energy, so the body escapes to infinity and retains a positive residual velocity there." },
  { id: 52, type: 'mcq', question: "The concept of escape velocity is derived using the principle of conservation of:", options: ["Linear momentum", "Total mechanical energy (kinetic energy + gravitational potential energy)", "Angular momentum exclusively", "Mass"], correctIndex: 1, difficulty: "medium", explanation: "The escape velocity formula comes from equating initial KE+PE at the surface to final KE+PE at infinity — conservation of total mechanical energy." },

  // ---------- Orbital Velocity and Satellites ----------
  { id: 53, type: 'mcq', question: "The orbital velocity of a satellite moving in a stable circular orbit close to a planet's surface, of mass M and radius R, is given by:", options: ["vo = √(GM/R)", "vo = GM/R", "vo = √(2GM/R)", "vo = GM/R²"], correctIndex: 0, difficulty: "easy", explanation: "Setting required centripetal force equal to gravitational force (mvo²/R = GMm/R²) and solving for vo gives vo = √(GM/R)." },
  { id: 54, type: 'mcq', question: "Orbital velocity can also be expressed in terms of the acceleration due to gravity g at the surface and the orbital radius R as:", options: ["vo = √(2gR)", "vo = gR²", "vo = gR", "vo = √(gR²/r), or equivalently √(gR) for an orbit close to the surface"], correctIndex: 3, difficulty: "medium", explanation: "Using g = GM/R², the orbital velocity formula rewrites in terms of g, giving vo ≈ √(gR) for orbits close to the planet's surface." },
  { id: 55, type: 'mcq', question: "The orbital velocity required for a satellite decreases as the radius of its orbit:", options: ["Decreases", "Increases", "Remains the same, regardless of orbital radius", "Becomes undefined"], correctIndex: 1, difficulty: "medium", explanation: "Since vo = √(GM/r), orbital velocity is inversely related to the square root of orbital radius, so vo decreases as the orbit gets larger." },
  { id: 56, type: 'mcq', question: "The time period of a satellite in a circular orbit of radius r around a planet of mass M is given by the formula:", options: ["T = 2π√(r³/GM)", "T = 2π√(GM/r³)", "T = 2πr/GM", "T = 2π√(r/GM)"], correctIndex: 0, difficulty: "medium", explanation: "This follows from combining the centripetal force equation with T = 2πr/v — the rotational-motion equivalent of Kepler's third law for satellites." },
  { id: 57, type: 'mcq', question: "The time period of revolution of a satellite around a planet increases as its orbital radius:", options: ["Decreases", "Remains unchanged", "Increases", "Becomes negative"], correctIndex: 2, difficulty: "medium", explanation: "Since T ∝ r^(3/2), the orbital period increases as orbital radius increases — satellites farther out take longer to complete one revolution." },
  { id: 58, type: 'mcq', question: "A geostationary satellite is one that appears stationary relative to a point on the Earth's surface because its orbital period exactly matches:", options: ["The Moon's orbital period around the Earth", "The time taken by light to travel from the Sun to the Earth", "The Earth's rotational period about its own axis (approximately 24 hours)", "The orbital period of the International Space Station"], correctIndex: 2, difficulty: "easy", explanation: "A geostationary satellite has an orbital period equal to Earth's rotation period (about 24 hours), so it appears fixed over the same point as Earth rotates beneath it." },
  { id: 59, type: 'mcq', question: "For a satellite to remain geostationary, in addition to having the correct orbital period, its orbit must also be:", options: ["Highly elliptical, with a very eccentric path", "Polar, passing directly over both the North and South poles", "Retrograde, moving opposite to Earth's rotation", "Circular and located directly above the Earth's equator, in the plane of the equator"], correctIndex: 3, difficulty: "medium", explanation: "A truly geostationary orbit requires both the correct 24-hour period and a circular, equatorial path so the satellite's position relative to a ground point never changes." },
  { id: 60, type: 'mcq', question: "The approximate height of a geostationary satellite above the Earth's surface is about:", options: ["36,000 km", "400 km", "1,000 km", "1.5 million km"], correctIndex: 0, difficulty: "medium", explanation: "Solving T = 2π√(r³/GM) for a 24-hour period with Earth's mass gives an orbital radius corresponding to a height of roughly 36,000 km." },
  { id: 61, type: 'mcq', question: "Geostationary satellites are particularly useful for applications such as:", options: ["Deep space exploration missions beyond the solar system", "Telecommunications and broadcasting, since they remain fixed relative to ground receivers", "Studying the Earth's core directly", "Measuring the mass of distant galaxies"], correctIndex: 1, difficulty: "medium", explanation: "Because a geostationary satellite stays fixed relative to a point on Earth, ground antennas can remain pointed at a constant sky location, making them ideal for telecommunications." },
  { id: 62, type: 'mcq', question: "A satellite that passes over (or nearly over) both the North and South poles once during each revolution, while the Earth rotates beneath it, is called a:", options: ["Geostationary satellite", "Polar satellite", "Elliptical satellite", "Lagrange-point satellite"], correctIndex: 1, difficulty: "medium", explanation: "A polar orbit passes near the poles on each revolution, allowing the satellite to eventually scan the entire Earth's surface as the planet rotates beneath it — hence 'polar satellite'." },
  { id: 63, type: 'mcq', question: "Polar orbiting satellites are typically placed at much lower altitudes than geostationary satellites and are especially useful for:", options: ["Earth observation and remote sensing, since they can scan the entire globe over successive orbits", "Continuous, fixed-point telecommunications relay", "Studying only equatorial regions exclusively", "Avoiding Earth's gravitational field entirely"], correctIndex: 0, difficulty: "medium", explanation: "Because a polar satellite's orbital plane stays roughly fixed while Earth rotates beneath it, successive passes cover different longitude strips, enabling complete global imaging." },
  { id: 64, type: 'mcq', question: "The orbital speed required for a satellite in a very low orbit close to the Earth's surface (where r ≈ R) is approximately:", options: ["11.2 km/s, the same as escape velocity", "3 × 10^5 km/s", "9.8 km/s", "Approximately 7.9 km/s (about 8 km/s)"], correctIndex: 3, difficulty: "hard", explanation: "Using vo = √(gR) with Earth's g ≈ 9.8 m/s² and R ≈ 6400 km gives an orbital velocity close to the well-known value of about 7.9 km/s." },
  { id: 65, type: 'mcq', question: "According to Kepler's third law, applied to artificial satellites of the Earth, satellites at a greater orbital radius have:", options: ["Shorter orbital periods than satellites closer to Earth", "Longer orbital periods than satellites closer to Earth", "Exactly the same orbital period regardless of altitude", "No defined orbital period at all"], correctIndex: 1, difficulty: "medium", explanation: "T ∝ r^(3/2) means larger orbital radii correspond to longer orbital periods, consistent with Kepler's third law applied to Earth satellites." },
  { id: 66, type: 'mcq', question: "The gravitational force acting on a satellite in a stable circular orbit provides exactly the:", options: ["Tangential force needed to change its speed", "Centripetal force required to keep it moving in its circular path", "Force needed to escape the planet's gravity entirely", "Frictional force opposing its motion"], correctIndex: 1, difficulty: "easy", explanation: "For a satellite in stable circular orbit, gravity itself supplies exactly the centripetal force needed to keep it curving around the planet, with no extra propulsion needed." },

  // ---------- Energy of Satellite and Weightlessness ----------
  { id: 67, type: 'mcq', question: "The kinetic energy of a satellite of mass m in a circular orbit of radius r around a planet of mass M is given by:", options: ["KE = GMm/2r", "KE = GMm/r", "KE = −GMm/2r", "KE = −GMm/r"], correctIndex: 0, difficulty: "easy", explanation: "Using KE = (1/2)mvo² and vo² = GM/r, the kinetic energy of an orbiting satellite is KE = GMm/2r (always positive)." },
  { id: 68, type: 'mcq', question: "The gravitational potential energy of a satellite of mass m in a circular orbit of radius r around a planet of mass M is given by:", options: ["PE = GMm/2r", "PE = GMm/r", "PE = −GMm/2r", "PE = −GMm/r"], correctIndex: 3, difficulty: "easy", explanation: "The gravitational PE of the satellite-planet system, with the standard convention (PE = 0 at infinity), is U = −GMm/r." },
  { id: 69, type: 'mcq', question: "The total mechanical energy of a satellite in a stable circular orbit, obtained by adding its kinetic and potential energies, is given by:", options: ["TE = +GMm/2r", "TE = −GMm/2r", "TE = −GMm/r", "TE = 0"], correctIndex: 1, difficulty: "medium", explanation: "Adding KE = GMm/2r and PE = −GMm/r gives TE = −GMm/2r, so the total orbital energy is negative — half the magnitude of the PE, opposite sign." },
  { id: 70, type: 'mcq', question: "The fact that the total energy of a satellite in a bound circular orbit is negative indicates that:", options: ["The satellite is actually escaping the planet's gravitational field", "The satellite has more kinetic energy than potential energy in magnitude", "The formula for total energy must be incorrect", "The satellite is gravitationally bound to the planet and cannot escape without additional energy input"], correctIndex: 3, difficulty: "medium", explanation: "A negative total mechanical energy is the defining signature of a gravitationally bound orbit — the satellite lacks enough energy to reach infinity without an external energy boost." },
  { id: 71, type: 'mcq', question: "The 'binding energy' of a satellite in orbit, i.e. the minimum energy that must be supplied to it to make it escape the planet's gravitational field completely, is equal in magnitude to:", options: ["Its kinetic energy alone", "Its total mechanical energy (with the sign reversed), i.e. +GMm/2r", "Its potential energy alone", "Twice its kinetic energy"], correctIndex: 1, difficulty: "medium", explanation: "To escape, total energy must be raised from −GMm/2r to (at minimum) zero, so the binding energy required equals +GMm/2r." },
  { id: 72, type: 'mcq', question: "For a satellite in a stable circular orbit, the magnitude of its potential energy is related to its kinetic energy by:", options: ["PE equals KE in magnitude", "PE is exactly twice the magnitude of KE (with opposite sign)", "PE is exactly half the magnitude of KE", "PE and KE have no fixed relationship for a circular orbit"], correctIndex: 1, difficulty: "medium", explanation: "Comparing KE = GMm/2r with |PE| = GMm/r shows |PE| = 2·KE, a standard and frequently tested relation for circular orbits." },
  { id: 73, type: 'mcq', question: "An astronaut inside a satellite orbiting the Earth experiences a condition commonly referred to as 'weightlessness' mainly because:", options: ["Both the astronaut and the satellite are in continuous free fall around the Earth, so there is no normal contact force between them", "There is no gravitational force acting on the astronaut at that altitude", "The astronaut's mass becomes zero in orbit", "The satellite is moving faster than the escape velocity"], correctIndex: 0, difficulty: "medium", explanation: "Both astronaut and satellite fall together at the same rate under gravity, so there's no relative contact force between them — this apparent absence of support force is felt as weightlessness." },
  { id: 74, type: 'mcq', question: "Weightlessness experienced by astronauts in an orbiting satellite is more accurately described as a state of:", options: ["Zero gravity, since gravity is entirely absent at orbital altitudes", "Increased gravity compared to Earth's surface", "Zero mass", "Apparent weightlessness, due to the astronaut and satellite being in the same free-fall condition, rather than a true absence of gravitational force"], correctIndex: 3, difficulty: "medium", explanation: "Gravity at orbital altitudes is still substantial; what astronauts experience is apparent weightlessness from mutual free fall, not the actual absence of gravity." },
  { id: 75, type: 'mcq', question: "If a satellite's orbital radius is increased, its total mechanical energy (which is negative for a bound orbit):", options: ["Becomes more negative", "Increases, i.e. becomes less negative (closer to zero)", "Remains exactly the same", "Becomes positive"], correctIndex: 1, difficulty: "medium", explanation: "Since TE = −GMm/2r, a larger r makes the magnitude of TE smaller, so the negative total energy becomes less negative as orbital radius increases." },
  { id: 76, type: 'mcq', question: "As the orbital radius of a satellite increases, its orbital kinetic energy:", options: ["Increases", "Remains exactly the same", "Decreases", "Becomes negative"], correctIndex: 2, difficulty: "medium", explanation: "Since KE = GMm/2r, kinetic energy is inversely proportional to orbital radius, so a satellite farther out has lower kinetic energy." },
  { id: 77, type: 'mcq', question: "To move a satellite from a lower orbit to a higher orbit around the same planet, external energy must be supplied mainly to:", options: ["Decrease the satellite's total mechanical energy further", "Convert all of the satellite's kinetic energy into heat", "Increase the satellite's total mechanical energy, raising it to the (less negative) value corresponding to the higher orbit", "Reduce the satellite's mass"], correctIndex: 2, difficulty: "medium", explanation: "Moving to a higher, more loosely bound orbit requires increasing (making less negative) the satellite's total mechanical energy, which requires external energy, typically from propulsion." },
  { id: 78, type: 'mcq', question: "The overall behaviour of satellites, from low Earth orbit to geostationary orbit, is governed by the same underlying physical principle as the motion of planets around the Sun, namely:", options: ["The photoelectric effect", "The special theory of relativity", "Newton's law of gravitation combined with the laws of motion (essentially the same physics behind Kepler's laws)", "Coulomb's law of electrostatics"], correctIndex: 2, difficulty: "easy", explanation: "Artificial satellites obey the same gravitational physics that governs planetary orbits, which is why Kepler-like relations (T² ∝ r³) apply to them too." },
  { id: 79, type: 'mcq', question: "Which of the following correctly ranks the magnitude of total mechanical energy for satellites in circular orbits of increasing radius (r1 < r2 < r3) around the same planet?", options: ["|TE| is the same for all three orbits, regardless of radius", "|TE| increases as radius increases, from r1 to r3", "|TE| is undefined for larger orbital radii", "|TE| decreases as radius increases, so the orbit at r1 has the largest magnitude of total energy (most tightly bound)"], correctIndex: 3, difficulty: "hard", explanation: "Since |TE| = GMm/2r, a smaller radius r1 gives a larger magnitude of total energy, meaning that orbit is more tightly bound than orbits at larger radii." },
  { id: 80, type: 'mcq', question: "Overall, the physics of orbital motion — covering Kepler's laws, Newton's law of gravitation, escape velocity, and satellite energy — collectively explains:", options: ["How both natural celestial bodies (planets, moons) and artificial satellites move under the influence of gravity", "Only the behaviour of subatomic particles", "Only chemical reactions on Earth's surface", "Only the propagation of electromagnetic waves"], correctIndex: 0, difficulty: "medium", explanation: "This chapter's concepts form a unified framework — the same gravitational laws govern planets, moons, and artificial satellites alike, from Kepler's laws to Newton's force law and its energy consequences." },

];

export default questions;