import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Mechanical Properties of Solids
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correct-answer positions are randomised with a roughly even spread across A/B/C/D (no repeating cycle).

const questions: Question[] = [

  // ---------- Elasticity Basics and Stress-Strain Concept ----------
  { id: 'solid-1', type: 'mcq', question: "The property of a material by virtue of which it tends to regain its original shape and size after the removal of a deforming force is called:", options: ["Elasticity", "Malleability", "Ductility", "Plasticity"], correctIndex: 0, difficulty: "easy", explanation: "Elasticity is precisely defined as the tendency of a deformed body to regain its original configuration once the deforming force is removed." },
  { id: 'solid-2', type: 'mcq', question: "A body that does not regain its original shape at all after the removal of a deforming force, retaining the deformation permanently, is said to be:", options: ["Perfectly elastic", "Isotropic", "Rigid", "Perfectly plastic"], correctIndex: 3, difficulty: "easy", explanation: "A perfectly plastic body shows no tendency to recover its original shape after deformation — the exact opposite behaviour of a perfectly elastic body." },
  { id: 'solid-3', type: 'mcq', question: "Quartz fibre and phosphor bronze are examples of materials that behave as nearly:", options: ["Perfectly rigid, with zero deformation under any load", "Perfectly plastic", "Non-crystalline liquids", "Perfectly elastic"], correctIndex: 3, difficulty: "medium", explanation: "Quartz fibre and phosphor bronze are classic NCERT examples of materials showing almost perfectly elastic behaviour, restoring their original shape almost completely after deformation." },
  { id: 'solid-4', type: 'mcq', question: "The internal restoring force set up per unit area of a deformed body, which acts to bring it back to its original configuration, is called:", options: ["Young's modulus", "Stress", "Strain", "Elastic limit"], correctIndex: 1, difficulty: "easy", explanation: "Stress is defined as the internal restoring force per unit cross-sectional area that develops within a body when it is deformed." },
  { id: 'solid-5', type: 'mcq', question: "The SI unit of stress is the same as that of:", options: ["Pressure (N/m² or pascal)", "Energy", "Force", "Strain, which is dimensionless"], correctIndex: 0, difficulty: "easy", explanation: "Since stress = force/area, its SI unit is N/m², the same as pressure (the pascal)." },
  { id: 'solid-6', type: 'mcq', question: "The fractional change in configuration (dimension, shape, or volume) of a body, produced under the action of an external deforming force, is called:", options: ["Elastic limit", "Strain", "Modulus of elasticity", "Stress"], correctIndex: 1, difficulty: "easy", explanation: "Strain is precisely defined as the fractional (ratio-based) change in the dimension, shape, or volume of a body due to an applied deforming force." },
  { id: 'solid-7', type: 'mcq', question: "Since strain is defined as the ratio of change in dimension to the original dimension, it is:", options: ["Measured in newtons", "Always greater than 1", "Measured in pascals, exactly like stress", "A dimensionless quantity, having no units"], correctIndex: 3, difficulty: "medium", explanation: "Being a ratio of two quantities with the same dimensions, strain has no units and is dimensionless." },
  { id: 'solid-8', type: 'mcq', question: "Within the elastic limit of a material, the maximum deforming force (or stress) that can be applied such that the body still returns completely to its original shape upon removal of the force is called the:", options: ["Fracture point", "Elastic limit", "Yield point exclusively", "Ultimate tensile strength"], correctIndex: 1, difficulty: "medium", explanation: "The elastic limit marks the maximum stress up to which the material behaves elastically and fully recovers its original shape once the force is removed." },
  { id: 'solid-9', type: 'mcq', question: "If a material is stressed beyond its elastic limit, it will:", options: ["Show no measurable change in its properties", "Always return exactly to its original shape regardless of how much it was stressed", "Retain some permanent deformation even after the deforming force is removed", "Immediately fracture, with no intermediate stage"], correctIndex: 2, difficulty: "medium", explanation: "Beyond the elastic limit, the material enters the plastic region and does not fully recover — some permanent deformation remains after the force is removed." },
  { id: 'solid-10', type: 'mcq', question: "Elastic behaviour of solid materials is explained at the microscopic level in terms of:", options: ["Interatomic and intermolecular forces that resist the displacement of atoms/molecules from their equilibrium positions", "Purely electrical charge interactions with no mechanical basis", "Nuclear forces between protons and neutrons", "Gravitational attraction between individual atoms"], correctIndex: 0, difficulty: "medium", explanation: "At the microscopic level, elasticity arises because interatomic/intermolecular forces resist displacement of atoms from their equilibrium lattice positions and restore them once the external force is removed." },

  // ---------- Types of Stress and Strain ----------
  { id: 'solid-11', type: 'mcq', question: "When a deforming force is applied perpendicular to the cross-sectional area of a body, causing a change in its length, the resulting stress is called:", options: ["Torsional stress", "Longitudinal (tensile or compressive) stress", "Volume (hydraulic) stress", "Shearing stress"], correctIndex: 1, difficulty: "easy", explanation: "A force applied normal to the cross-section, changing the length of the body, produces longitudinal stress, which can be tensile (stretching) or compressive." },
  { id: 'solid-12', type: 'mcq', question: "When a deforming force is applied tangentially (parallel) to the surface of a body, causing a change in its shape without necessarily changing its volume, the resulting stress is called:", options: ["Longitudinal stress", "Hydraulic stress", "Normal stress exclusively", "Shearing (tangential) stress"], correctIndex: 3, difficulty: "easy", explanation: "A force applied tangentially to a surface, producing a change in shape, is defined as shearing (tangential) stress." },
  { id: 'solid-13', type: 'mcq', question: "When a body is subjected to a uniform force acting perpendicular to its entire surface from all directions (e.g. from surrounding fluid pressure), causing a change in its volume without a change in shape, the resulting stress is called:", options: ["Volume (hydraulic) stress", "Shearing stress", "Torsional stress", "Longitudinal stress"], correctIndex: 0, difficulty: "easy", explanation: "Uniform force applied over the entire surface from all directions, changing volume (as when a body is submerged in a fluid), is defined as volume or hydraulic stress." },
  { id: 'solid-14', type: 'mcq', question: "Longitudinal strain, corresponding to longitudinal stress, is defined as the ratio of:", options: ["The change in length to the original length of the body", "The applied force to the cross-sectional area", "The change in volume to the original volume", "The angle of shear to the original length"], correctIndex: 0, difficulty: "medium", explanation: "Longitudinal strain is defined as ΔL/L, the fractional change in length produced by a longitudinal stress." },
  { id: 'solid-15', type: 'mcq', question: "Shearing strain, corresponding to shearing stress, is measured by the:", options: ["Ratio of change in volume to original volume", "Angle of tilt (shear angle) produced in the body due to the applied tangential force", "Change in mass of the body", "Ratio of change in length to original length"], correctIndex: 1, difficulty: "medium", explanation: "Shearing strain is quantified by the angle through which a face of the body is displaced (tilted) relative to its original orientation." },
  { id: 'solid-16', type: 'mcq', question: "Volume strain, corresponding to volume (hydraulic) stress, is defined as the ratio of:", options: ["The shear angle to the applied pressure", "The change in volume to the original volume of the body", "The change in length to the original length", "The applied tangential force to the surface area"], correctIndex: 1, difficulty: "medium", explanation: "Volume strain is defined as ΔV/V, the fractional change in volume produced when a body is subjected to volume stress." },
  { id: 'solid-17', type: 'mcq', question: "Volume (hydraulic) stress is numerically equal in magnitude to the:", options: ["Change in pressure applied to the body", "Change in length per unit original length", "Young's modulus of the material", "Applied tangential force per unit area"], correctIndex: 0, difficulty: "medium", explanation: "When a body is subjected to uniform pressure from all sides, the resulting volume stress is numerically equal to the applied pressure change." },
  { id: 'solid-18', type: 'mcq', question: "Which of the following pairs of stress and its resulting effect is correctly matched?", options: ["Volume stress — causes a change in shape, with no change in volume", "Shearing stress — causes a change in volume, with no change in shape", "Longitudinal stress — causes a change in length", "Shearing stress — causes a change in mass"], correctIndex: 2, difficulty: "medium", explanation: "Longitudinal stress specifically changes a body's length; the other pairings are reversed — shearing stress changes shape (not volume) and volume stress changes volume (not shape)." },
  { id: 'solid-19', type: 'mcq', question: "A wire under tension, stretched by an external pulling force applied along its length, experiences:", options: ["Tensile longitudinal stress", "Shearing stress exclusively", "Volume stress exclusively", "Compressive longitudinal stress"], correctIndex: 0, difficulty: "easy", explanation: "A wire being pulled/stretched along its length experiences tensile longitudinal stress, one of the two types of longitudinal stress." },
  { id: 'solid-20', type: 'mcq', question: "A rod being compressed along its length (pushed inward from both ends) experiences:", options: ["Shearing stress exclusively", "Volume stress exclusively", "Compressive longitudinal stress", "Tensile longitudinal stress"], correctIndex: 2, difficulty: "medium", explanation: "A rod pushed inward along its length, reducing its length, experiences compressive (rather than tensile) longitudinal stress." },

  // ---------- Hooke's Law and the Stress-Strain Curve ----------
  { id: 'solid-21', type: 'mcq', question: "Hooke's law, describing the elastic behaviour of solids within a certain limit, states that:", options: ["Stress is directly proportional to strain, within the elastic limit", "Stress and strain are entirely unrelated quantities", "Stress is inversely proportional to strain", "Stress equals strain exactly, in all cases"], correctIndex: 0, difficulty: "easy", explanation: "Hooke's law states that, within the elastic limit, stress is directly proportional to strain — the foundational relationship of elasticity." },
  { id: 'solid-22', type: 'mcq', question: "The constant of proportionality in Hooke's law, relating stress to strain for a given material, is called the:", options: ["Poisson's ratio", "Elastic limit", "Modulus of elasticity", "Ultimate tensile strength"], correctIndex: 2, difficulty: "medium", explanation: "The proportionality constant in Hooke's law (stress = modulus × strain) is termed the modulus of elasticity of the material." },
  { id: 'solid-23', type: 'mcq', question: "On a typical stress-strain curve for a ductile metal, the initial straight-line portion, where stress is directly proportional to strain, corresponds to the region where:", options: ["The material has already fractured", "Hooke's law is violated", "Hooke's law is obeyed", "Plastic deformation has already begun"], correctIndex: 2, difficulty: "medium", explanation: "The initial linear (straight-line) portion of a stress-strain graph is exactly where stress ∝ strain holds, i.e. where Hooke's law applies." },
  { id: 'solid-24', type: 'mcq', question: "The point on the stress-strain curve up to which the straight-line (Hooke's law) relationship between stress and strain holds is called the:", options: ["Fracture point", "Proportional limit", "Ultimate tensile strength point", "Yield point"], correctIndex: 1, difficulty: "medium", explanation: "The proportional limit is the point up to which the stress-strain graph remains a straight line, i.e. where Hooke's law is valid." },
  { id: 'solid-25', type: 'mcq', question: "Beyond the proportional limit but still within the elastic limit, the stress-strain curve for many materials becomes slightly non-linear, but the material:", options: ["No longer experiences any stress at all", "Never returns to its original dimensions", "Still returns to its original dimensions once the stress is removed", "Immediately fractures"], correctIndex: 2, difficulty: "medium", explanation: "Between the proportional limit and the true elastic limit, the behaviour is no longer strictly linear, but the material still fully recovers its shape once stress is removed." },
  { id: 'solid-26', type: 'mcq', question: "The point on the stress-strain curve beyond which the material begins to undergo significant plastic deformation, with strain increasing rapidly even for a relatively small increase in stress, is called the:", options: ["Fracture point exclusively", "Proportional limit", "Yield point", "Breaking stress exclusively"], correctIndex: 2, difficulty: "medium", explanation: "The yield point marks the onset of significant plastic (permanent) deformation, where strain increases rapidly for only a small additional increase in stress." },
  { id: 'solid-27', type: 'mcq', question: "The maximum stress that a material can withstand before it begins to 'neck' (locally thin out) and eventually fracture is called its:", options: ["Ultimate tensile strength", "Elastic limit", "Yield strength exclusively", "Proportional limit"], correctIndex: 0, difficulty: "medium", explanation: "Ultimate tensile strength is defined as the maximum stress a material can sustain before necking and eventual failure begins." },
  { id: 'solid-28', type: 'mcq', question: "The point on the stress-strain curve at which the material finally breaks/fails completely is called the:", options: ["Elastic limit", "Fracture point", "Yield point", "Proportional limit"], correctIndex: 1, difficulty: "medium", explanation: "The fracture point is where the material physically breaks apart under the applied stress, marking the end of the stress-strain curve." },
  { id: 'solid-29', type: 'mcq', question: "For a typical ductile material, the region of the stress-strain curve between the elastic limit and the fracture point, in which permanent (non-recoverable) deformation occurs, is called the:", options: ["Plastic region", "Hookean region", "Proportional region", "Linear elastic region"], correctIndex: 0, difficulty: "medium", explanation: "Beyond the elastic limit, the material enters the plastic region, where deformation is permanent and not recovered upon removal of stress." },
  { id: 'solid-30', type: 'mcq', question: "A material that can be drawn into thin wires under tensile stress, showing a long plastic region on its stress-strain curve before fracture, is described as:", options: ["Brittle", "Perfectly elastic", "Ductile", "Isotropic exclusively"], correctIndex: 2, difficulty: "medium", explanation: "Ductility is the property of being drawn into wires, correlating with a long plastic region on the stress-strain curve before eventual fracture." },

  // ---------- Young's Modulus ----------
  { id: 'solid-31', type: 'mcq', question: "Young's modulus of a material is defined as the ratio of:", options: ["Lateral strain to longitudinal strain", "Shearing stress to shearing strain", "Longitudinal stress to longitudinal strain, within the elastic limit", "Volume stress to volume strain"], correctIndex: 2, difficulty: "easy", explanation: "Young's modulus specifically relates longitudinal stress to longitudinal strain, Y = (F/A)/(ΔL/L), within the elastic limit." },
  { id: 'solid-32', type: 'mcq', question: "The SI unit of Young's modulus is the same as that of:", options: ["Strain, which is dimensionless", "Stress/pressure (N/m² or pascal)", "Force", "Energy"], correctIndex: 1, difficulty: "easy", explanation: "Since Young's modulus = stress/strain and strain is dimensionless, Y has the same units as stress, i.e. N/m²." },
  { id: 'solid-33', type: 'mcq', question: "A material with a very high value of Young's modulus, such as steel, is:", options: ["Very easily stretched under small applied stress", "Completely non-elastic, showing no restoring force at all", "Very stiff and difficult to stretch or compress", "Always brittle, regardless of other properties"], correctIndex: 2, difficulty: "easy", explanation: "A high Young's modulus means a large stress is required to produce even a small strain, so the material is very stiff and resists elongation/compression." },
  { id: 'solid-34', type: 'mcq', question: "Young's modulus is applicable specifically to solids that undergo:", options: ["A change in volume, with no change in shape or length", "Longitudinal (tensile or compressive) deformation", "No deformation at all under any applied force", "A change in shape, with no change in length"], correctIndex: 1, difficulty: "medium", explanation: "Young's modulus is specifically defined for and applicable to longitudinal deformation, i.e. changes in length under tensile or compressive stress." },
  { id: 'solid-35', type: 'mcq', question: "Comparing typical Young's modulus values, steel generally has a ___ Young's modulus than rubber.", options: ["Undefined, since rubber has no Young's modulus at all", "Much higher", "Lower", "Exactly equal"], correctIndex: 1, difficulty: "medium", explanation: "Steel is far stiffer than rubber for a given stress, so it has a much higher Young's modulus (steel: ~2×10^11 Pa vs rubber: much lower)." },
  { id: 'solid-36', type: 'mcq', question: "For a wire of length L and cross-sectional area A, subjected to a stretching force F that produces an extension ΔL, the Young's modulus is given by the formula:", options: ["Y = FL / ΔL, without the area term", "Y = F/(AL)", "Y = (F × A) / (ΔL × L)", "Y = (F/A) / (ΔL/L) = FL / (A ΔL)"], correctIndex: 3, difficulty: "medium", explanation: "Y is defined as longitudinal stress (F/A) divided by longitudinal strain (ΔL/L), which simplifies algebraically to FL/(AΔL)." },
  { id: 'solid-37', type: 'mcq', question: "For a given applied force and wire cross-section, a wire made of a material with a higher Young's modulus will show:", options: ["A greater extension for the same applied force", "An extension unrelated to the applied force", "A smaller extension for the same applied force", "No measurable extension under any force"], correctIndex: 2, difficulty: "medium", explanation: "Since ΔL = FL/(AY), a higher Young's modulus Y in the denominator results in a smaller extension for the same force, length, and area." },
  { id: 'solid-38', type: 'mcq', question: "The Young's modulus of a wire depends on:", options: ["The diameter/cross-sectional area of the wire", "The length of the wire", "The applied force alone", "The material of the wire, not its specific dimensions"], correctIndex: 3, difficulty: "medium", explanation: "Young's modulus is an intrinsic property of the material itself, independent of the specific length or cross-sectional area of a particular sample." },
  { id: 'solid-39', type: 'mcq', question: "In the design of bridges, buildings, and other structures, materials with a suitably high Young's modulus are preferred mainly because they:", options: ["Are always the cheapest option available", "Deform excessively under normal structural loads", "Resist excessive deformation (elongation/compression) under the loads the structure must bear", "Have no practical relevance to structural engineering"], correctIndex: 2, difficulty: "medium", explanation: "A high Young's modulus ensures structural elements do not stretch or compress excessively under load, essential for the safety and stability of structures." },
  { id: 'solid-40', type: 'mcq', question: "Which of the following materials typically has one of the highest known values of Young's modulus, making it extremely resistant to elastic deformation?", options: ["Cotton wool", "Rubber", "Diamond", "Sponge"], correctIndex: 2, difficulty: "medium", explanation: "Diamond has an exceptionally high Young's modulus, among the highest known for any material, reflecting its extreme stiffness." },

  // ---------- Shear Modulus (Modulus of Rigidity) ----------
  { id: 'solid-41', type: 'mcq', question: "The modulus of rigidity (shear modulus) of a material is defined as the ratio of:", options: ["Volume stress to volume strain", "Shearing stress to shearing strain, within the elastic limit", "Longitudinal stress to longitudinal strain", "Lateral strain to longitudinal strain"], correctIndex: 1, difficulty: "easy", explanation: "Shear modulus (modulus of rigidity), denoted G or η, is defined as shearing stress divided by shearing strain, analogous to Young's modulus." },
  { id: 'solid-42', type: 'mcq', question: "The shear modulus is applicable specifically to deformations that involve:", options: ["A change in volume with no change in shape", "No deformation at all", "A change in the total mass of the body", "A change in shape, with the volume of the body remaining essentially unchanged"], correctIndex: 3, difficulty: "medium", explanation: "Shear modulus describes resistance to shape-changing (shearing) deformation, in which the shape changes but volume remains essentially constant." },
  { id: 'solid-43', type: 'mcq', question: "For most solid materials, the shear modulus (modulus of rigidity) is generally:", options: ["Smaller in magnitude than the Young's modulus of the same material", "Larger in magnitude than the Young's modulus of the same material", "Exactly equal to the Young's modulus for all materials", "Completely unrelated to Young's modulus, and typically much larger"], correctIndex: 0, difficulty: "medium", explanation: "For most common engineering materials, shear modulus is smaller than Young's modulus, since materials generally resist shape-changing deformation less strongly than length-changing deformation." },
  { id: 'solid-44', type: 'mcq', question: "Fluids (liquids and gases), unlike solids, generally:", options: ["Resist shearing deformation strongly, just like solids", "Have a shear modulus identical to their bulk modulus", "Have a very large, well-defined shear modulus", "Have essentially zero shear modulus, since they do not permanently resist a change in shape"], correctIndex: 3, difficulty: "medium", explanation: "Fluids flow freely and offer no permanent resistance to shear stress, so their shear modulus is essentially zero — a defining distinction between solids and fluids." },
  { id: 'solid-45', type: 'mcq', question: "The SI unit of the shear modulus (modulus of rigidity) is:", options: ["Joule (J)", "A dimensionless unit, like strain", "Newton (N)", "Pascal (N/m²)"], correctIndex: 3, difficulty: "easy", explanation: "Since shear modulus = shearing stress (N/m²) divided by shearing strain (dimensionless), its SI unit is the pascal, the same as stress." },
  { id: 'solid-46', type: 'mcq', question: "The angle through which a face of a solid body is tilted, when a tangential (shearing) force is applied to it, is related to shearing strain and is typically measured in:", options: ["Radians", "Newtons", "Joules", "Pascals"], correctIndex: 0, difficulty: "medium", explanation: "Shear strain, being the tangent of the small displacement angle, is expressed in radians rather than in force/energy/pressure units." },
  { id: 'solid-47', type: 'mcq', question: "A material with a large shear modulus is one that:", options: ["Cannot experience any shearing stress at all", "Deforms easily in shape under a small applied tangential (shearing) force", "Has zero resistance to shape change, similar to a fluid", "Strongly resists any change in shape under an applied shearing force"], correctIndex: 3, difficulty: "medium", explanation: "A large shear modulus means a large shearing stress is required to produce even a small shearing strain, so the material strongly resists changes in shape." },
  { id: 'solid-48', type: 'mcq', question: "The concept of shear modulus is particularly relevant to engineering applications such as the design of:", options: ["Shafts and structural components that experience twisting (torsional) forces", "Objects with no material properties at all", "Purely static objects with no applied forces at all", "Devices that only ever experience volume/hydraulic compression"], correctIndex: 0, difficulty: "medium", explanation: "Shafts and other components subjected to twisting/torsional loads primarily experience shearing deformation, making shear modulus a critical design parameter." },

  // ---------- Bulk Modulus and Compressibility ----------
  { id: 'solid-49', type: 'mcq', question: "The bulk modulus of a material is defined as the ratio of:", options: ["Longitudinal stress to longitudinal strain", "Lateral strain to longitudinal strain", "Shearing stress to shearing strain", "Volume (hydraulic) stress to volume strain, within the elastic limit"], correctIndex: 3, difficulty: "easy", explanation: "Bulk modulus, K, specifically relates volume (hydraulic) stress to the resulting volume strain, K = −p/(ΔV/V)." },
  { id: 'solid-50', type: 'mcq', question: "The formula for bulk modulus, K = −p (ΔV/V)⁻¹, includes a negative sign because:", options: ["Pressure is inherently a negative physical quantity", "Volume can be negative for real materials", "Bulk modulus is always a negative number in practice", "An increase in applied pressure always causes a decrease in volume, so pressure and volume-strain have opposite signs, and K itself is kept positive"], correctIndex: 3, difficulty: "medium", explanation: "Since increasing pressure decreases volume (ΔV is negative when p is positive), the negative sign ensures bulk modulus K itself comes out as a positive quantity." },
  { id: 'solid-51', type: 'mcq', question: "Bulk modulus is applicable to which of the following states of matter?", options: ["Only liquids", "Only solids", "Solids, liquids, and gases, since all can undergo a change in volume under pressure", "Only gases"], correctIndex: 2, difficulty: "medium", explanation: "Unlike Young's modulus and shear modulus (which apply only to solids), bulk modulus is meaningful for solids, liquids, and gases, since all can be compressed." },
  { id: 'solid-52', type: 'mcq', question: "Gases generally have a much ___ bulk modulus than liquids and solids, reflecting their much greater compressibility.", options: ["Undefined", "Identical", "Larger", "Smaller"], correctIndex: 3, difficulty: "medium", explanation: "Gases are far more easily compressed than liquids/solids for a given pressure change, meaning they have a much smaller bulk modulus." },
  { id: 'solid-53', type: 'mcq', question: "The compressibility of a material is defined as:", options: ["Directly equal to the bulk modulus K", "The reciprocal of the bulk modulus, i.e. 1/K", "The square of the bulk modulus", "Directly equal to Young's modulus"], correctIndex: 1, difficulty: "medium", explanation: "Compressibility is explicitly defined as the reciprocal of bulk modulus, 1/K — a larger compressibility corresponds to a smaller bulk modulus." },
  { id: 'solid-54', type: 'mcq', question: "Compared to gases, liquids generally have a ___ compressibility.", options: ["Undefined, since liquids cannot be compressed at all", "Much larger", "Exactly equal", "Much smaller"], correctIndex: 3, difficulty: "medium", explanation: "Liquids are far less compressible than gases (they have a much larger bulk modulus), so their compressibility (1/K) is correspondingly much smaller." },
  { id: 'solid-55', type: 'mcq', question: "Solids generally have a higher bulk modulus than liquids, which in turn have a higher bulk modulus than gases, reflecting the general trend that solids are:", options: ["Equally compressible as liquids and gases", "More compressible than liquids and gases", "Completely incompressible under any circumstances", "The least compressible of the three states of matter, under typical conditions"], correctIndex: 3, difficulty: "medium", explanation: "The typical ordering K(solid) > K(liquid) > K(gas) reflects that solids resist volume change the most, i.e. are the least compressible of the three states." },
  { id: 'solid-56', type: 'mcq', question: "The bulk modulus of a material becomes especially relevant in situations involving:", options: ["Situations where no force is applied at all", "Uniform compression or expansion of a body, such as being submerged deep underwater", "Purely tangential forces applied to one face of a body", "Purely one-directional stretching of a thin wire"], correctIndex: 1, difficulty: "medium", explanation: "Bulk modulus specifically describes response to uniform, all-around pressure, which changes only the volume of the body, not its shape or length." },
  { id: 'solid-57', type: 'mcq', question: "The SI unit of bulk modulus, like that of Young's modulus and shear modulus, is:", options: ["Joule per second (W)", "Cubic metre (m³)", "Newton (N)", "Pascal (N/m²)"], correctIndex: 3, difficulty: "easy", explanation: "Since bulk modulus = pressure/volume strain and volume strain is dimensionless, bulk modulus has the same units as pressure/stress." },
  { id: 'solid-58', type: 'mcq', question: "A material with a very high bulk modulus, when subjected to a large increase in surrounding pressure, will show:", options: ["Complete disintegration", "Only a very small decrease in volume", "A large increase in volume", "A very large decrease in volume"], correctIndex: 1, difficulty: "medium", explanation: "A high bulk modulus means a large pressure is required to produce even a small fractional decrease in volume, so the material barely compresses." },

  // ---------- Poisson's Ratio ----------
  { id: 'solid-59', type: 'mcq', question: "When a wire or rod is stretched along its length (producing a longitudinal strain), it typically also undergoes a small contraction in its:", options: ["Mass", "Lateral (perpendicular/transverse) dimension, such as its diameter", "Density, with no change in lateral dimension", "Temperature"], correctIndex: 1, difficulty: "medium", explanation: "Stretching a wire along its length typically causes a corresponding contraction in its perpendicular (lateral) dimensions — the coupled effect that Poisson's ratio quantifies." },
  { id: 'solid-60', type: 'mcq', question: "Poisson's ratio is defined as the ratio of:", options: ["Shearing stress to shearing strain", "Longitudinal strain to lateral strain", "Lateral strain to longitudinal strain, for a body under longitudinal stress", "Volume stress to volume strain"], correctIndex: 2, difficulty: "medium", explanation: "Poisson's ratio (σ) is specifically defined as lateral strain divided by longitudinal strain, quantifying lateral narrowing under longitudinal stretch." },
  { id: 'solid-61', type: 'mcq', question: "Since lateral strain (contraction) and longitudinal strain (elongation) occur in opposite senses when a wire is stretched, Poisson's ratio, when defined with an appropriate sign convention, is generally taken to be:", options: ["A positive quantity for most common materials", "Always a negative quantity for every known material", "Undefined for all solid materials", "Always exactly zero for every material"], correctIndex: 0, difficulty: "medium", explanation: "With the standard sign convention (accounting for the opposite senses of lateral and longitudinal strain), Poisson's ratio comes out positive for most common materials." },
  { id: 'solid-62', type: 'mcq', question: "Poisson's ratio, being the ratio of two strains (both of which are dimensionless), is itself:", options: ["A dimensionless quantity, with no units", "Measured in newtons", "Measured in pascals", "Measured in metres"], correctIndex: 0, difficulty: "medium", explanation: "Since Poisson's ratio is the ratio of two dimensionless strain quantities, it is also dimensionless." },
  { id: 'solid-63', type: 'mcq', question: "The theoretical range within which Poisson's ratio for a real, isotropic material is generally expected to lie is approximately:", options: ["-10 to +10", "Always exactly equal to 1", "Exactly 0 for all materials", "-1 to +0.5"], correctIndex: 3, difficulty: "hard", explanation: "For real, isotropic elastic materials, theoretical constraints (related to requiring positive elastic moduli) restrict Poisson's ratio to the range -1 to +0.5." },
  { id: 'solid-64', type: 'mcq', question: "For most common engineering materials, such as many metals, typical experimental values of Poisson's ratio lie approximately in the range of:", options: ["0.9 to 1.0", "0.2 to 0.4", "Greater than 1", "Exactly 0"], correctIndex: 1, difficulty: "medium", explanation: "Most common metals and engineering materials show experimentally measured Poisson's ratio values in the approximate range of 0.2 to 0.4." },

  // ---------- Elastic Potential Energy ----------
  { id: 'solid-65', type: 'mcq', question: "When a wire is stretched by an external force, work is done against the internal restoring (elastic) forces, and this work is stored in the wire as:", options: ["Elastic potential energy", "Chemical energy", "Kinetic energy exclusively", "Heat energy exclusively"], correctIndex: 0, difficulty: "medium", explanation: "Work done in stretching a wire against its internal restoring forces is stored as elastic potential energy, recoverable when the wire relaxes back." },
  { id: 'solid-66', type: 'mcq', question: "The elastic potential energy stored in a stretched wire, in terms of the applied force F and the resulting extension ΔL (assuming the wire obeys Hooke's law), is given by:", options: ["U = (1/2) F ΔL", "U = F/ΔL", "U = F × ΔL, without any factor of one-half", "U = F × ΔL²"], correctIndex: 0, difficulty: "medium", explanation: "Because the restoring force increases linearly from zero to F as the wire stretches, the work done (and stored elastic PE) is the average force times displacement, U = (1/2)FΔL." },
  { id: 'solid-67', type: 'mcq', question: "The elastic potential energy stored per unit volume of a stretched wire can also be expressed in terms of stress and strain as:", options: ["U/Volume = stress² × strain²", "U/Volume = stress / strain", "U/Volume = (1/2) × stress × strain", "U/Volume = stress × strain, without the factor of one-half"], correctIndex: 2, difficulty: "medium", explanation: "Elastic energy density is given by (1/2) × stress × strain, the exact analogue of (1/2)FΔL expressed per unit volume of the material." },
  { id: 'solid-68', type: 'mcq', question: "Since Young's modulus Y = stress/strain, the elastic potential energy per unit volume of a stretched wire can also be written in terms of Y and strain alone as:", options: ["(1/2) Y × (strain)²", "Y / strain²", "(1/2) Y / strain", "Y × strain, without any squared term"], correctIndex: 0, difficulty: "hard", explanation: "Substituting stress = Y × strain into (1/2)×stress×strain gives energy density = (1/2)Y(strain)², a commonly tested rearranged form." },
  { id: 'solid-69', type: 'mcq', question: "The graphical representation of elastic potential energy stored in a wire, on a stress-strain curve within the Hookean (linear) region, corresponds to:", options: ["The slope of the stress-strain line", "The y-intercept of the stress-strain line", "The area under the stress-strain curve up to the given strain", "The x-intercept of the stress-strain line"], correctIndex: 2, difficulty: "medium", explanation: "Just as work done equals the area under a force-displacement graph, elastic potential energy per unit volume equals the area under the stress-strain curve up to that strain." },
  { id: 'solid-70', type: 'mcq', question: "A material capable of storing a relatively large amount of elastic potential energy per unit volume before reaching its elastic limit is said to have high:", options: ["Compressibility", "Resilience", "Density", "Poisson's ratio"], correctIndex: 1, difficulty: "medium", explanation: "Resilience specifically refers to a material's capacity to absorb and store elastic energy up to its elastic limit without permanent deformation." },
  { id: 'solid-71', type: 'mcq', question: "Springs used in mechanical devices, such as in a wristwatch or a vehicle's suspension system, function by storing and later releasing:", options: ["Chemical energy exclusively", "Nuclear energy", "Purely thermal energy", "Elastic potential energy, as they are deformed and then allowed to return to their original shape"], correctIndex: 3, difficulty: "medium", explanation: "Springs work precisely by storing elastic potential energy when compressed or stretched, then releasing it as they return towards their natural shape." },
  { id: 'solid-72', type: 'mcq', question: "If a wire does not obey Hooke's law over the range of applied stress, the elastic potential energy stored in it can still be determined by:", options: ["Calculating the actual area under the (possibly non-linear) stress-strain curve", "Assuming it is always zero, since Hooke's law does not apply", "Using the simple formula U = (1/2)FΔL regardless of linearity", "It becomes impossible to determine the stored energy in any non-Hookean case"], correctIndex: 0, difficulty: "medium", explanation: "Even with a non-linear stress-strain relationship, stored elastic energy per unit volume equals the area under the actual curve, whatever its shape." },

  // ---------- Applications and Elastomers ----------
  { id: 'solid-73', type: 'mcq', question: "Elastomers, such as rubber, are materials characterised by their ability to undergo very large strains and are distinguished from typical metals mainly because they:", options: ["Have an extremely high Young's modulus, comparable to diamond", "Obey Hooke's law perfectly over their entire range of extension, just like steel", "Do not obey Hooke's law over most of their extension range, showing a markedly non-linear stress-strain curve", "Cannot be stretched at all under any applied force"], correctIndex: 2, difficulty: "medium", explanation: "Rubber and similar elastomers show pronounced non-linear behaviour, unlike the largely linear Hookean region typical of metals — one of their defining characteristics." },
  { id: 'solid-74', type: 'mcq', question: "The phenomenon in which the loading and unloading stress-strain curves of a material like rubber do not coincide, forming a loop, is called:", options: ["Elastic hysteresis", "Necking", "Fracture", "Yielding"], correctIndex: 0, difficulty: "hard", explanation: "Elastic hysteresis describes this loop-forming behaviour, where the unloading curve lies below the loading curve on a stress-strain graph for materials such as rubber." },
  { id: 'solid-75', type: 'mcq', question: "The area enclosed within the hysteresis loop of a material's loading-unloading stress-strain curve represents:", options: ["The material's melting point", "The material's exact Young's modulus", "The total elastic potential energy that is fully recovered", "Energy dissipated (lost, typically as heat) during the loading-unloading cycle"], correctIndex: 3, difficulty: "medium", explanation: "The enclosed hysteresis loop area corresponds to mechanical energy not recovered on unloading, instead dissipated (usually as heat) during the cycle." },
  { id: 'solid-76', type: 'mcq', question: "In structural engineering, beams used to support loads (e.g. in bridges or buildings) are often designed with an 'I-shaped' cross-section mainly to:", options: ["Reduce the overall material strength of the beam", "Eliminate the need for any elastic properties in the material", "Increase the total weight of the beam without any structural benefit", "Provide a high resistance to bending (sagging) while minimising the amount of material used"], correctIndex: 3, difficulty: "medium", explanation: "The I-beam shape concentrates material farther from the central neutral axis, significantly increasing bending resistance for a given amount of material." },
  { id: 'solid-77', type: 'mcq', question: "When a beam sags under a load, it undergoes bending, and the material near the top surface is generally under compressive stress, while the material near the bottom surface is generally under:", options: ["Volume stress exclusively", "Tensile stress", "Shearing stress exclusively", "Zero stress"], correctIndex: 1, difficulty: "medium", explanation: "When a horizontal beam bends downward under load, its upper fibres compress while its lower fibres stretch, putting them under tensile stress." },
  { id: 'solid-78', type: 'mcq', question: "The maximum load a structural member (such as a beam, cable, or column) can safely bear is generally kept well below its ultimate tensile strength by incorporating a:", options: ["Bulk modulus correction exclusively", "Zero safety margin, using the exact breaking stress as the design limit", "Factor of safety, a design margin that accounts for uncertainties and prevents failure", "Poisson's ratio adjustment exclusively"], correctIndex: 2, difficulty: "medium", explanation: "Engineers design structural members to operate well below the ultimate tensile strength by applying a 'factor of safety', providing margin against unexpected loads or material flaws." },
  { id: 'solid-79', type: 'mcq', question: "The choice of an appropriate elastic material for a specific engineering application (e.g. a bridge cable vs. a rubber gasket) primarily depends on matching the material's mechanical properties, such as its Young's modulus and elastic limit, to the:", options: ["Colour of the material alone", "Cost of the material exclusively, with no regard for its mechanical behaviour", "Specific mechanical demands and expected stresses of that particular application", "Material's chemical taste or smell"], correctIndex: 2, difficulty: "medium", explanation: "Sound engineering design requires selecting a material whose elastic properties are appropriate for the specific mechanical demands the application will place on it." },
  { id: 'solid-80', type: 'mcq', question: "The overall study of the mechanical properties of solids — encompassing stress, strain, the various elastic moduli, and elastic potential energy — provides the essential theoretical foundation for:", options: ["Understanding only biological cell structures", "Engineering design and material selection in fields such as construction, mechanical engineering, and materials science", "Understanding only chemical reaction rates", "Understanding only optical phenomena"], correctIndex: 1, difficulty: "medium", explanation: "This chapter's concepts collectively underpin practical engineering decisions — from selecting bridge cables to designing beams and springs — foundational to structural and mechanical engineering." },

];

export default questions;