import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: System of Particles and Rotational Motion
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctIndex (index 0-3), difficulty, explanation }
// Note: correctIndex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Centre of Mass: Concept and Position ----------
  { id: 1, type: 'mcq', question: "The centre of mass of a system of particles is a point at which:", options: ["The entire mass of the system may be considered to be concentrated for analysing translational motion", "All particles of the system must physically be located", "Only the heaviest particle in the system is located", "The system's kinetic energy is always zero"], correctIndex: 0, difficulty: "easy", explanation: "The centre of mass is a mathematical/physical point where the whole mass can be treated as concentrated for describing the translational motion of the system as a whole — it need not contain any actual particle." },
  { id: 2, type: 'mcq', question: "For a system of two particles of masses m1 and m2 located at positions x1 and x2 along the x-axis, the x-coordinate of the centre of mass is given by:", options: ["(x1 + x2)/2", "(m1x2 + m2x1)/(m1 + m2)", "(m1x1 + m2x2)/(m1 + m2)", "m1m2(x1 + x2)"], correctIndex: 2, difficulty: "easy", explanation: "The centre of mass formula is the mass-weighted average of positions, xcm = (m1x1 + m2x2)/(m1 + m2); a simple average (x1+x2)/2 would only work if the masses were equal." },
  { id: 3, type: 'mcq', question: "For a uniform rod of length L, the centre of mass is located at:", options: ["One end of the rod", "The geometric centre of the rod (L/2 from either end)", "A point outside the rod", "A point that depends on which end is labelled 'first'"], correctIndex: 1, difficulty: "easy", explanation: "Because the rod's mass is uniformly distributed, symmetry places the centre of mass exactly at its geometric midpoint, L/2 from either end." },
  { id: 4, type: 'mcq', question: "For a system of particles, if the origin is chosen such that the centre of mass lies exactly at the origin, the sum Σmiri (mass times position vector, summed over all particles) is:", options: ["Equal to the total mass of the system", "Equal to the total momentum of the system", "Always equal to a non-zero constant", "Equal to zero"], correctIndex: 3, difficulty: "medium", explanation: "By definition Rcm = (Σmiri)/M; if Rcm = 0 (origin at the COM), then Σmiri must equal zero." },
  { id: 5, type: 'mcq', question: "For a system consisting of two point masses, the centre of mass always lies:", options: ["Exactly midway between the two masses, regardless of their values", "On the line joining the two masses, closer to the heavier mass", "Outside the line joining the two masses", "At the position of the lighter mass"], correctIndex: 1, difficulty: "medium", explanation: "The COM lies on the line joining the two masses, and since it is a mass-weighted average, it is pulled closer to whichever mass is larger — it's only exactly midway if the masses are equal." },
  { id: 6, type: 'mcq', question: "Two particles of masses 1 kg and 3 kg are placed 4 m apart. The distance of the centre of mass from the 1 kg mass is:", options: ["3 m", "1 m", "2 m", "4 m"], correctIndex: 0, difficulty: "medium", explanation: "Using xcm = m2·d/(m1+m2) measured from the 1 kg mass: (3×4)/(1+3) = 12/4 = 3 m, so the COM sits 3 m from the 1 kg mass (closer to the heavier 3 kg mass, 1 m away)." },
  { id: 7, type: 'mcq', question: "Which of the following statements about the centre of mass of a body is correct?", options: ["The centre of mass must always lie within the physical boundary of the body", "The centre of mass is a fixed physical point that must contain mass", "The centre of mass may lie outside the physical boundary of the body, as in the case of a ring or a horseshoe", "The centre of mass is identical to the centre of gravity under all conditions, including non-uniform gravitational fields"], correctIndex: 2, difficulty: "medium", explanation: "For hollow/curved shapes like a ring or horseshoe, the geometric symmetry places the COM at a point with no actual mass — outside the material of the body itself; COM and centre of gravity only coincide in a uniform gravitational field." },
  { id: 8, type: 'mcq', question: "In the absence of any external force, the centre of mass of a system of particles:", options: ["Always comes to rest immediately", "Accelerates continuously", "Moves with constant velocity (or remains at rest if initially at rest)", "Moves in a circular path"], correctIndex: 2, difficulty: "medium", explanation: "With Fext = M·acm, zero external force means acm = 0, so the COM moves with whatever constant velocity it already had (including staying at rest if it started at rest)." },
  { id: 9, type: 'mcq', question: "A bomb at rest explodes into several fragments under the action of purely internal forces. The centre of mass of all the fragments, immediately after the explosion:", options: ["Moves in the direction of the largest fragment", "Accelerates due to the explosion", "Moves in a random direction", "Continues to remain at rest, since no external force acted on the system"], correctIndex: 3, difficulty: "medium", explanation: "Explosive forces are internal to the bomb-fragments system; with no external force, the COM's motion is unaffected and it stays exactly where it would have been had no explosion occurred." },
  { id: 10, type: 'mcq', question: "For a continuous mass distribution, the position vector of the centre of mass is given by an integral of the form:", options: ["R = (1/M) ∫r dm", "R = M ∫r dm", "R = ∫dm alone, with no position vector involved", "R = ∫r dV, without any mass term"], correctIndex: 0, difficulty: "medium", explanation: "This is the continuous-mass generalisation of the discrete COM formula: sum over all mass elements dm at position r, divided by the total mass M." },

  // ---------- Centre of Mass: Common Systems and Motion of COM ----------
  { id: 11, type: 'mcq', question: "The centre of mass of a uniform circular ring lies at:", options: ["A point on the ring itself", "The geometric centre of the ring, even though no mass is physically located there", "A point outside the ring entirely, away from its centre", "Along the circumference, midway between any two points"], correctIndex: 1, difficulty: "easy", explanation: "By symmetry, a uniform ring's mass distribution balances exactly at its geometric centre, even though no material of the ring is actually located there." },
  { id: 12, type: 'mcq', question: "The centre of mass of a uniform solid sphere lies at:", options: ["A point on the surface of the sphere", "The geometric centre of the sphere", "A point outside the sphere", "Anywhere within the sphere, depending on orientation"], correctIndex: 1, difficulty: "easy", explanation: "A uniform solid sphere has spherical symmetry, so its centre of mass coincides with its geometric centre." },
  { id: 13, type: 'mcq', question: "For a uniform triangular lamina, the centre of mass coincides with the:", options: ["Centroid of the triangle", "Orthocentre of the triangle", "Circumcentre of the triangle", "Any one randomly chosen vertex"], correctIndex: 0, difficulty: "medium", explanation: "For a uniform (constant-density) triangular lamina, the mass balances at the geometric centroid — the intersection point of the medians." },
  { id: 14, type: 'mcq', question: "The total linear momentum of a system of particles is related to the velocity of its centre of mass by the equation:", options: ["P = M/vcm", "P = vcm/M", "P = M + vcm", "P = M vcm"], correctIndex: 3, difficulty: "medium", explanation: "The total momentum of a system equals its total mass times the velocity of its centre of mass, P = M·vcm, treating the whole system like a single particle located at the COM." },
  { id: 15, type: 'mcq', question: "Two skaters, initially at rest and holding hands on frictionless ice, push apart from each other. Considering them as an isolated system with no external horizontal force, the centre of mass of the two-skater system:", options: ["Moves toward the lighter skater", "Remains stationary", "Moves toward the heavier skater", "Oscillates back and forth"], correctIndex: 1, difficulty: "medium", explanation: "The push-off forces are internal to the two-skater system; with zero net external horizontal force and zero initial COM velocity, the COM stays exactly where it started." },
  { id: 16, type: 'mcq', question: "A man walks from one end of a stationary boat (floating on still water, with no friction from water) to the other end. Ignoring water resistance, as the man moves forward, the boat:", options: ["Moves backward, so that the centre of mass of the man-boat system remains stationary", "Remains completely stationary", "Moves forward along with the man", "Sinks completely"], correctIndex: 0, difficulty: "hard", explanation: "With no external horizontal force, the man-boat system's COM must stay fixed; as the man moves one way, the boat must recoil the other way to keep the overall COM stationary." },
  { id: 17, type: 'mcq', question: "The velocity of the centre of mass of a system of particles is defined as:", options: ["The average of the individual velocities, without any mass weighting", "The velocity of the fastest-moving particle in the system", "The velocity of the heaviest particle in the system", "The mass-weighted average of the velocities of all particles in the system"], correctIndex: 3, difficulty: "medium", explanation: "vcm = Σmivi / Σmi — a mass-weighted average, analogous to how the COM position itself is a mass-weighted average of positions." },
  { id: 18, type: 'mcq', question: "For a rigid body, Newton's second law can be applied to the motion of the centre of mass in the same way as for a single particle, i.e.:", options: ["Fext = M acm, where Fext is the net external force and acm is the acceleration of the centre of mass", "Fext = M/acm", "Fext has no relationship to acm for extended bodies", "Fext = acm/M"], correctIndex: 0, difficulty: "medium", explanation: "This is the key result that lets an extended body be treated as a point mass for translational purposes: the net external force equals total mass times COM acceleration, exactly like a single particle." },

  // ---------- Torque and Angular Momentum ----------
  { id: 19, type: 'mcq', question: "The turning effect of a force about a given axis or point, defined as the vector (cross) product of the position vector and the force, is called:", options: ["Linear momentum", "Angular momentum", "Kinetic energy", "Torque (moment of force)"], correctIndex: 3, difficulty: "easy", explanation: "Torque (moment of force) is defined as τ = r × F — the rotational analogue of force, describing its turning effect about a chosen point." },
  { id: 20, type: 'mcq', question: "Torque is mathematically defined as τ = r × F. The magnitude of torque can also be expressed as:", options: ["τ = rF sinθ, where θ is the angle between r and F", "τ = rF cosθ", "τ = rF, regardless of the angle between r and F", "τ = r + F"], correctIndex: 0, difficulty: "easy", explanation: "The magnitude of a cross product is |A||B|sinθ, so τ = rF sinθ, where θ is the angle between the position vector r and the force F." },
  { id: 21, type: 'mcq', question: "The SI unit of torque is the:", options: ["Newton-metre (N m)", "Joule (J)", "Newton (N)", "Watt (W)"], correctIndex: 0, difficulty: "easy", explanation: "Since τ = r × F, its units are (metre)×(newton) = N m, the standard SI unit for torque." },
  { id: 22, type: 'mcq', question: "Although the SI unit of torque (N m) is dimensionally the same as that of energy/work (also N m, i.e. joule), torque is NOT expressed in joules because:", options: ["Torque and work have completely different dimensions", "Torque is always negative, unlike work", "Torque is a vector quantity (involving the direction perpendicular to both r and F), while work is a scalar quantity", "Torque has no defined unit at all"], correctIndex: 2, difficulty: "medium", explanation: "Despite sharing the same dimensional formula, torque is a vector (defined via a cross product with direction perpendicular to r and F) while work/energy is a scalar, so they are kept notationally distinct (N m vs J)." },
  { id: 23, type: 'mcq', question: "The angular momentum of a particle about a given point is defined as the vector product of its position vector and its:", options: ["Angular velocity", "Linear momentum", "Angular acceleration", "Moment of inertia"], correctIndex: 1, difficulty: "easy", explanation: "Angular momentum is defined as L = r × p, the cross product of the position vector and the linear momentum of the particle." },
  { id: 24, type: 'mcq', question: "The relationship between the net external torque acting on a system and its angular momentum is given by:", options: ["τ = L × dt", "τ = L/dt, with no time derivative involved", "τ = ∫L dt", "τ = dL/dt (the rate of change of angular momentum)"], correctIndex: 3, difficulty: "medium", explanation: "Just as force equals the rate of change of linear momentum (F = dp/dt), torque equals the rate of change of angular momentum, τ = dL/dt." },
  { id: 25, type: 'mcq', question: "The relationship τ = dL/dt is the rotational analogue of which linear-motion equation?", options: ["F = ma", "F = dp/dt", "v = u + at", "s = ut + (1/2)at²"], correctIndex: 1, difficulty: "medium", explanation: "τ = dL/dt directly mirrors F = dp/dt in linear motion, with torque replacing force and angular momentum replacing linear momentum." },
  { id: 26, type: 'mcq', question: "According to the right-hand rule used to determine the direction of a torque vector τ = r × F, if the fingers curl from the direction of r towards the direction of F, the thumb points in the direction of:", options: ["The torque vector τ", "The force vector F", "The position vector r", "The velocity vector"], correctIndex: 0, difficulty: "medium", explanation: "For any cross product A × B, the right-hand rule (curling fingers from A to B) gives the thumb's direction as that of the resulting vector — here, the torque τ." },
  { id: 27, type: 'mcq', question: "If the angle between the position vector r and the applied force F is 0° or 180° (i.e. F is directed exactly along or opposite to r), the resulting torque about that point is:", options: ["Maximum", "Equal to rF exactly", "Zero", "Equal to half of rF"], correctIndex: 2, difficulty: "medium", explanation: "Since τ = rF sinθ, and sin(0°) = sin(180°) = 0, the torque is zero when the force acts exactly along or opposite to the position vector." },
  { id: 28, type: 'mcq', question: "For a given force of fixed magnitude, torque about a point is maximised when the angle between the position vector r and the force F is:", options: ["0°", "180°", "90°", "45°"], correctIndex: 2, difficulty: "medium", explanation: "τ = rF sinθ is maximised when sinθ = 1, i.e. when θ = 90°, meaning the force is applied perpendicular to the position vector." },

  // ---------- Equilibrium of Rigid Body ----------
  { id: 29, type: 'mcq', question: "A rigid body is said to be in mechanical equilibrium if both the net external force acting on it and the net external:", options: ["Kinetic energy are zero", "Linear momentum are non-zero", "Potential energy are zero", "Torque acting on it are zero"], correctIndex: 3, difficulty: "easy", explanation: "Full mechanical equilibrium requires both zero net force (translational equilibrium) and zero net torque (rotational equilibrium)." },
  { id: 30, type: 'mcq', question: "If the net force on a rigid body is zero but the net torque is not zero, the body is said to be in:", options: ["Rotational (but not translational) equilibrium — i.e. it may undergo angular acceleration while its centre of mass does not accelerate", "Complete mechanical equilibrium", "Translational (but not rotational) equilibrium", "No motion of any kind"], correctIndex: 0, difficulty: "medium", explanation: "Zero net force means the COM doesn't accelerate (translational equilibrium holds), but a non-zero net torque still produces angular acceleration, so the body is not in rotational equilibrium." },
  { id: 31, type: 'mcq', question: "A pair of equal and opposite forces, acting along two different (parallel) lines of action on a body, is called a:", options: ["Resultant force", "Couple", "Centripetal force pair", "Balanced force system with zero net torque"], correctIndex: 1, difficulty: "medium", explanation: "This specific configuration — equal, opposite, parallel forces with different lines of action — is defined as a couple, and it produces zero net force but a non-zero net torque." },
  { id: 32, type: 'mcq', question: "A couple acting on a rigid body tends to produce:", options: ["Pure translational motion only, with no rotation", "No effect on the body whatsoever", "Pure rotational motion, since the net force is zero but the net torque is not", "A change only in the body's linear momentum, with no torque involved"], correctIndex: 2, difficulty: "medium", explanation: "Since a couple has zero net force but a non-zero net torque, it produces pure rotational effect on the body with no translational acceleration of the COM." },
  { id: 33, type: 'mcq', question: "The 'principle of moments', used in analysing devices such as a simple lever, states that for a body in rotational equilibrium, the sum of clockwise moments about a point equals:", options: ["Zero, always", "The sum of anticlockwise moments about the same point", "Twice the sum of anticlockwise moments", "The net force acting on the body"], correctIndex: 1, difficulty: "easy", explanation: "Rotational equilibrium (zero net torque) means clockwise and anticlockwise moments about any point must exactly balance each other." },
  { id: 34, type: 'mcq', question: "The centre of gravity of a body is the point at which the entire weight of the body may be considered to act; in a uniform gravitational field, this point:", options: ["Is always different from the centre of mass", "Coincides with the centre of mass of the body", "Lies outside the body always", "Depends entirely on the body's velocity"], correctIndex: 1, difficulty: "medium", explanation: "When gravity acts uniformly on every part of a body (as is typically assumed), the centre of gravity coincides exactly with the centre of mass." },

  // ---------- Moment of Inertia: Definition ----------
  { id: 35, type: 'mcq', question: "The rotational analogue of mass in linear motion, representing a body's resistance to change in its rotational motion about a given axis, is called its:", options: ["Moment of inertia", "Angular momentum", "Torque", "Angular velocity"], correctIndex: 0, difficulty: "easy", explanation: "Moment of inertia plays the same role in rotational dynamics (resistance to angular acceleration) that mass plays in linear dynamics (resistance to linear acceleration)." },
  { id: 36, type: 'mcq', question: "For a system of particles, the moment of inertia about a given axis is defined mathematically as:", options: ["I = Σmivi²", "I = Σmi/ri²", "I = Σmi, with no distance term", "I = Σmiri², where ri is the perpendicular distance of the i-th particle from the axis"], correctIndex: 3, difficulty: "easy", explanation: "Moment of inertia is defined as the sum, over all particles, of mass times the square of the perpendicular distance from the axis: I = Σmiri²." },
  { id: 37, type: 'mcq', question: "The moment of inertia of a rigid body about a given axis depends on:", options: ["Only the total mass of the body, with no dependence on shape or axis", "The mass of the body, its shape/mass distribution, and the position of the axis of rotation", "Only the axis chosen, with no dependence on mass", "Only the material the body is made of, regardless of its shape"], correctIndex: 1, difficulty: "medium", explanation: "Since I = Σmiri², it depends jointly on how much mass there is, how that mass is distributed relative to the axis, and which axis is chosen — not on mass or axis alone." },
  { id: 38, type: 'mcq', question: "The moment of inertia of a given rigid body about a specified axis is generally:", options: ["Larger when more mass is distributed farther from that axis", "Independent of how the mass is distributed relative to the axis", "Always the same regardless of which axis is chosen", "Zero for any solid, non-hollow body"], correctIndex: 0, difficulty: "medium", explanation: "Because I = Σmiri² weights mass by the square of its distance from the axis, mass located farther from the axis contributes disproportionately more to I." },
  { id: 39, type: 'mcq', question: "The SI unit of moment of inertia is:", options: ["kg m/s", "kg/m²", "kg m²", "N m"], correctIndex: 2, difficulty: "easy", explanation: "Since I = Σmr², its units are mass × (distance)², i.e. kg m²." },
  { id: 40, type: 'mcq', question: "The 'radius of gyration' (k) of a body about a given axis is defined such that its moment of inertia can be written as:", options: ["I = M/k²", "I = M + k²", "I = Mk²", "I = k²/M"], correctIndex: 2, difficulty: "medium", explanation: "Radius of gyration is defined via I = Mk², where M is the total mass — this lets moment of inertia be expressed compactly in terms of an equivalent single distance k." },
  { id: 41, type: 'mcq', question: "Physically, the radius of gyration represents the distance from the axis at which the entire mass of the body could be concentrated to produce:", options: ["The same torque as the actual body", "The same angular momentum as the actual body", "The same angular velocity as the actual body", "The same moment of inertia as the actual body"], correctIndex: 3, difficulty: "medium", explanation: "By definition (I = Mk²), k is the distance at which all the body's mass, if concentrated as a point, would give the exact same moment of inertia I as the actual, distributed body." },
  { id: 42, type: 'mcq', question: "Moment of inertia plays a role in rotational motion analogous to the role that mass plays in translational motion; specifically, it appears in the rotational kinetic energy formula and in:", options: ["Einstein's mass-energy equivalence equation", "Newton's second law for rotation, τ = Iα", "The law of universal gravitation", "The ideal gas equation"], correctIndex: 1, difficulty: "medium", explanation: "Just as mass appears in F = ma, moment of inertia I appears in the rotational form of Newton's second law, τ = Iα." },

  // ---------- Moment of Inertia: Standard Bodies ----------
  { id: 43, type: 'mcq', question: "The moment of inertia of a uniform circular ring of mass M and radius R, about an axis passing through its centre and perpendicular to its plane, is:", options: ["(1/2)MR²", "MR²", "(2/5)MR²", "(1/4)MR²"], correctIndex: 1, difficulty: "easy", explanation: "All the mass of a ring lies at the same distance R from the central axis, so I = MR² directly, with no reduction factor." },
  { id: 44, type: 'mcq', question: "The moment of inertia of a uniform circular disc of mass M and radius R, about an axis passing through its centre and perpendicular to its plane, is:", options: ["MR²", "(1/2)MR²", "(2/5)MR²", "(2/3)MR²"], correctIndex: 1, difficulty: "easy", explanation: "Unlike a ring, a disc's mass is spread from the centre out to R, giving a smaller effective average r²; integrating over the disc yields I = (1/2)MR²." },
  { id: 45, type: 'mcq', question: "The moment of inertia of a uniform solid sphere of mass M and radius R, about an axis passing through its centre, is:", options: ["(2/5)MR²", "(2/3)MR²", "MR²", "(1/2)MR²"], correctIndex: 0, difficulty: "easy", explanation: "This is a standard result from integrating over a uniform solid sphere: I = (2/5)MR², reflecting that most mass is closer to the centre than R." },
  { id: 46, type: 'mcq', question: "The moment of inertia of a thin, uniform rod of mass M and length L, about an axis passing through its centre and perpendicular to its length, is:", options: ["ML²/3", "ML²", "ML²/2", "ML²/12"], correctIndex: 3, difficulty: "medium", explanation: "Integrating mr² along the rod's length about its central perpendicular axis gives the standard result I = ML²/12." },
  { id: 47, type: 'mcq', question: "The moment of inertia of a thin, uniform rod of mass M and length L, about an axis passing through one end and perpendicular to its length, is:", options: ["ML²/12", "ML²/3", "ML²/2", "ML²"], correctIndex: 1, difficulty: "medium", explanation: "Using the parallel axis theorem on the central value ML²/12, shifting to one end (distance L/2 away) gives ML²/12 + M(L/2)² = ML²/3." },
  { id: 48, type: 'mcq', question: "The moment of inertia of a thin, hollow (spherical shell) sphere of mass M and radius R, about an axis passing through its centre, is:", options: ["(1/2)MR²", "(2/5)MR²", "(2/3)MR²", "MR²"], correctIndex: 2, difficulty: "medium", explanation: "For a hollow spherical shell, all the mass lies at radius R on the surface, giving a larger moment of inertia than a solid sphere: I = (2/3)MR²." },
  { id: 49, type: 'mcq', question: "The moment of inertia of a solid cylinder of mass M and radius R, about its own longitudinal (central) axis, is:", options: ["MR²", "(1/4)MR²", "(1/2)MR²", "(2/5)MR²"], correctIndex: 2, difficulty: "medium", explanation: "A solid cylinder about its own axis behaves like a stack of discs, each contributing (1/2)mr², so the total is I = (1/2)MR², same formula as a disc." },
  { id: 50, type: 'mcq', question: "The moment of inertia of a uniform rectangular lamina of mass M, length l, and breadth b, about an axis through its centre and perpendicular to its plane, is:", options: ["M(l+b)²/12", "Mlb/12", "Mlb²/12", "M(l² + b²)/12"], correctIndex: 3, difficulty: "hard", explanation: "Applying the perpendicular axis theorem to the lamina's two in-plane centroidal moments of inertia (Ml²/12 and Mb²/12) gives the perpendicular-axis result I = M(l² + b²)/12." },
  { id: 51, type: 'mcq', question: "Among a ring, a disc, a solid sphere, and a hollow sphere, all having the same mass M and radius R, which body has the LARGEST moment of inertia about its central axis?", options: ["Solid sphere", "Ring", "Disc", "Hollow sphere"], correctIndex: 1, difficulty: "medium", explanation: "The ring (I = MR²) has all its mass concentrated at maximum distance R from the axis, giving it the highest moment of inertia among these four shapes of equal mass and radius." },
  { id: 52, type: 'mcq', question: "Among a ring, a disc, a solid sphere, and a hollow sphere, all having the same mass M and radius R, which body has the SMALLEST moment of inertia about its central axis?", options: ["Ring", "Solid sphere", "Hollow sphere", "Disc"], correctIndex: 1, difficulty: "medium", explanation: "The solid sphere (I = (2/5)MR² ≈ 0.4MR²) has its mass distributed closest to the axis on average among these shapes, giving it the smallest moment of inertia." },

  // ---------- Parallel and Perpendicular Axis Theorems ----------
  { id: 53, type: 'mcq', question: "The theorem of parallel axes states that the moment of inertia of a body about any axis is equal to its moment of inertia about a parallel axis through its centre of mass, plus:", options: ["Md², where M is the total mass and d is the perpendicular distance between the two axes", "Md, without any squared term", "M/d²", "d² alone, with no mass term"], correctIndex: 0, difficulty: "easy", explanation: "The parallel axis theorem states I = Icm + Md², adding a correction term equal to total mass times the square of the perpendicular distance between the two parallel axes." },
  { id: 54, type: 'mcq', question: "According to the theorem of parallel axes, the moment of inertia of a body about a given axis is always:", options: ["Less than its moment of inertia about a parallel axis through the centre of mass", "Equal to its moment of inertia about the centre-of-mass axis, regardless of distance", "Independent of the distance between the two axes", "Greater than or equal to its moment of inertia about the centre-of-mass axis"], correctIndex: 3, difficulty: "medium", explanation: "Since I = Icm + Md² and Md² ≥ 0, the moment of inertia about any axis is always at least as large as about the parallel centre-of-mass axis, confirming the COM axis gives the minimum I." },
  { id: 55, type: 'mcq', question: "The theorem of perpendicular axes applies specifically to:", options: ["Any three-dimensional solid body, without restriction", "Planar (flat, two-dimensional/laminar) bodies only", "Only spherical bodies", "Only bodies with a circular cross-section"], correctIndex: 1, difficulty: "medium", explanation: "The perpendicular axis theorem (Iz = Ix + Iy) is derived assuming all mass lies in a single plane, so it is valid only for flat, planar (laminar) bodies, not general 3D solids." },
  { id: 56, type: 'mcq', question: "According to the theorem of perpendicular axes, for a planar body, the moment of inertia about an axis perpendicular to its plane (Iz) is equal to the sum of its moments of inertia about two mutually perpendicular axes (Ix and Iy) lying within the plane and intersecting where the perpendicular axis passes, i.e.:", options: ["Iz = Ix + Iy", "Iz = Ix − Iy", "Iz = Ix × Iy", "Iz = (Ix + Iy)/2"], correctIndex: 0, difficulty: "easy", explanation: "This is the statement of the perpendicular axis theorem itself: Iz = Ix + Iy, for a planar lamina with x, y in its plane and z perpendicular through the same point." },
  { id: 57, type: 'mcq', question: "Using the theorem of perpendicular axes, the moment of inertia of a uniform circular disc of mass M and radius R about a diameter (an axis lying in its own plane, through the centre) is:", options: ["(1/2)MR²", "MR²", "(2/5)MR²", "(1/4)MR²"], correctIndex: 3, difficulty: "hard", explanation: "By symmetry Ix = Iy for a disc about any two perpendicular diameters, and Iz = (1/2)MR² about the axis perpendicular to its plane; since Iz = Ix + Iy = 2Ix, each diameter's I = (1/4)MR²." },
  { id: 58, type: 'mcq', question: "The theorem of parallel axes is generally applicable to:", options: ["Planar bodies only, similar to the perpendicular axis theorem", "Any rigid body, regardless of its shape", "Only bodies with a uniform circular cross-section", "Only bodies with zero moment of inertia about their centre of mass"], correctIndex: 1, difficulty: "medium", explanation: "Unlike the perpendicular axis theorem, the parallel axis theorem (I = Icm + Md²) holds for any rigid body of any shape, not just planar ones." },

  // ---------- Rotational Kinetic Energy and Torque-Angular Acceleration ----------
  { id: 59, type: 'mcq', question: "The kinetic energy of a rigid body rotating about a fixed axis with angular velocity ω, and having moment of inertia I about that axis, is given by:", options: ["KE = Iω", "KE = (1/2)Iω", "KE = Iω²", "KE = (1/2)Iω²"], correctIndex: 3, difficulty: "easy", explanation: "Rotational kinetic energy mirrors the linear form (1/2)mv², with moment of inertia replacing mass and angular velocity replacing linear velocity: KE = (1/2)Iω²." },
  { id: 60, type: 'mcq', question: "The rotational analogue of Newton's second law (F = ma) for a rigid body is given by:", options: ["τ = Iα, where α is the angular acceleration", "τ = Iω, where ω is the angular velocity", "τ = I/α", "τ = mα"], correctIndex: 0, difficulty: "easy", explanation: "Just as force produces linear acceleration via F = ma, torque produces angular acceleration via τ = Iα, with I replacing m and α replacing a." },
  { id: 61, type: 'mcq', question: "The instantaneous power delivered by a torque τ acting on a body rotating with angular velocity ω is given by:", options: ["P = τω", "P = τ/ω", "P = τ + ω", "P = τω², with an extra factor of ω"], correctIndex: 0, difficulty: "medium", explanation: "This mirrors the linear power formula P = Fv, with torque replacing force and angular velocity replacing linear velocity: P = τω." },
  { id: 62, type: 'mcq', question: "The relationship between the linear velocity v of a point on a rotating rigid body and the angular velocity ω of the body, where r is the perpendicular distance of that point from the axis of rotation, is given by:", options: ["v = ω/r", "v = ω + r", "v = ωr", "v = ω²r"], correctIndex: 2, difficulty: "easy", explanation: "For rigid-body rotation, every point's linear speed equals the angular velocity times its distance from the axis: v = ωr." },
  { id: 63, type: 'mcq', question: "The relationship between the angular acceleration α of a rotating body and the linear (tangential) acceleration a of a point at distance r from the axis is:", options: ["a = α/r", "a = α + r", "a = αr", "a = α²r"], correctIndex: 2, difficulty: "easy", explanation: "Differentiating v = ωr with respect to time gives the tangential acceleration relation a = αr." },
  { id: 64, type: 'mcq', question: "The work done by a constant torque τ in rotating a rigid body through an angular displacement θ is given by:", options: ["W = τ/θ", "W = τ + θ", "W = τθ², with an extra factor of θ", "W = τθ"], correctIndex: 3, difficulty: "medium", explanation: "This mirrors linear work W = Fs, with torque replacing force and angular displacement replacing linear displacement: W = τθ." },
  { id: 65, type: 'mcq', question: "The work-energy theorem for rotational motion states that the work done by the net external torque on a rigid body equals the change in its:", options: ["Linear kinetic energy exclusively", "Rotational kinetic energy", "Potential energy exclusively", "Angular momentum, expressed in energy units"], correctIndex: 1, difficulty: "medium", explanation: "Just as net work equals the change in translational KE in linear motion, net rotational work equals the change in rotational kinetic energy (1/2)Iω²." },
  { id: 66, type: 'mcq', question: "A flywheel with a large moment of inertia is often used in machines (e.g. engines) mainly because it:", options: ["Helps maintain a steady rotational speed by resisting sudden changes in angular velocity", "Reduces the total mass of the machine significantly", "Eliminates the need for any external torque", "Converts rotational motion entirely into linear motion"], correctIndex: 0, difficulty: "medium", explanation: "A large moment of inertia resists rapid changes in ω for a given torque (since α = τ/I is small), which smooths out fluctuations and keeps rotational speed steady — the flywheel's main practical purpose." },

  // ---------- Conservation of Angular Momentum ----------
  { id: 67, type: 'mcq', question: "The principle of conservation of angular momentum states that, in the absence of any external torque acting on a system, the total angular momentum of the system:", options: ["Continuously increases", "Continuously decreases", "Remains constant", "Becomes exactly zero"], correctIndex: 2, difficulty: "easy", explanation: "With τ = dL/dt, if the net external torque is zero, dL/dt = 0, meaning L is conserved — stays constant over time." },
  { id: 68, type: 'mcq', question: "A figure skater spinning with arms outstretched pulls their arms inward, close to the body. Assuming negligible external torque, the skater's moment of inertia decreases, and consequently their angular velocity:", options: ["Also decreases", "Remains exactly the same", "Increases, since angular momentum (Iω) is conserved", "Becomes zero"], correctIndex: 2, difficulty: "medium", explanation: "Since L = Iω is conserved and I decreases as the arms are pulled in, ω must increase proportionally to keep the product Iω constant — this is why the skater spins faster." },
  { id: 69, type: 'mcq', question: "A diver executing a somersault while in mid-air (in free fall, so gravity provides no net torque about the centre of mass) curls their body into a tucked position to increase their rotational speed. This is a direct application of:", options: ["Newton's third law", "The theorem of parallel axes", "The work-energy theorem", "Conservation of angular momentum, since tucking reduces moment of inertia and increases angular velocity"], correctIndex: 3, difficulty: "medium", explanation: "In free fall, gravity acts through the COM and exerts no torque about it, so angular momentum L = Iω is conserved; tucking reduces I, forcing ω to increase to compensate." },
  { id: 70, type: 'mcq', question: "If the moment of inertia of a rotating system is halved while no external torque acts on it, its angular velocity must:", options: ["Double, so that the product Iω remains constant", "Also be halved", "Remain exactly unchanged", "Become zero"], correctIndex: 0, difficulty: "medium", explanation: "With no external torque, L = Iω stays constant; if I is halved, ω must double to keep the product Iω the same." },
  { id: 71, type: 'mcq', question: "The law of conservation of angular momentum is a direct consequence of the relation τ = dL/dt, since if the net external torque τ is zero, then:", options: ["L must immediately become zero as well", "dL/dt = 0, meaning L remains constant over time", "L must increase without bound", "The relation no longer applies"], correctIndex: 1, difficulty: "medium", explanation: "Setting τ = 0 in τ = dL/dt directly gives dL/dt = 0, i.e. L does not change with time — the mathematical basis for conservation of angular momentum." },
  { id: 72, type: 'mcq', question: "In a system where the net external torque is not zero, the total angular momentum of the system will generally:", options: ["Remain constant, exactly as in the torque-free case", "Change over time, in accordance with τ = dL/dt", "Become undefined", "Have no relationship at all to the applied torque"], correctIndex: 1, difficulty: "medium", explanation: "When τ ≠ 0, dL/dt ≠ 0, so angular momentum changes with time according to how much torque is applied, exactly as τ = dL/dt describes." },

  // ---------- Rolling Motion ----------
  { id: 73, type: 'mcq', question: "For a rigid body undergoing 'pure rolling' without slipping on a surface, the condition relating the linear velocity of the centre of mass (v) and the angular velocity (ω) is:", options: ["v = ωR, where R is the radius of the rolling body", "v = ω/R", "v = ω + R", "v = ωR², with an extra factor of R"], correctIndex: 0, difficulty: "easy", explanation: "Pure (non-slipping) rolling requires the contact point's velocity to be zero, which mathematically translates to the COM velocity satisfying v = ωR." },
  { id: 74, type: 'mcq', question: "The total kinetic energy of a body undergoing pure rolling motion is the sum of its translational kinetic energy and its:", options: ["Potential energy", "Angular momentum, expressed in energy units", "Torque-related energy", "Rotational kinetic energy about the axis through its centre of mass"], correctIndex: 3, difficulty: "easy", explanation: "A rolling body simultaneously translates (COM moves) and rotates (about the COM axis), so its total KE is the sum of translational KE (1/2)Mv² and rotational KE (1/2)Icmω²." },
  { id: 75, type: 'mcq', question: "The total kinetic energy of a rolling body can be expressed in terms of its mass M, velocity v, and the ratio k²/R² (where k is the radius of gyration and R is the radius) as:", options: ["KE = (1/2)Mv²(1 − k²/R²)", "KE = (1/2)Mv²(1 + k²/R²)", "KE = Mv²(k²/R²)", "KE = (1/2)Mv², with no dependence on k²/R² at all"], correctIndex: 1, difficulty: "hard", explanation: "Substituting I = Mk² and ω = v/R into KE = (1/2)Mv² + (1/2)Iω² and simplifying gives KE = (1/2)Mv²(1 + k²/R²), the standard combined rolling-KE formula." },
  { id: 76, type: 'mcq', question: "If a solid sphere, a hollow sphere, a disc, and a ring, all of the same mass and radius, are released from rest and allowed to roll without slipping down the same inclined plane, which of them reaches the bottom FIRST?", options: ["Ring", "Hollow sphere", "Solid sphere", "Disc"], correctIndex: 2, difficulty: "medium", explanation: "The body with the smallest k²/R² has the largest acceleration a = g sinθ/(1+k²/R²); the solid sphere has the smallest k²/R² (=2/5) among these shapes, so it reaches the bottom first." },
  { id: 77, type: 'mcq', question: "The order in which a solid sphere, a disc, a hollow sphere, and a ring (all with the same mass and radius) finish a race rolling down an incline, from fastest to slowest, is generally:", options: ["Ring, hollow sphere, disc, solid sphere", "Disc, ring, solid sphere, hollow sphere", "Solid sphere, disc, hollow sphere, ring", "Hollow sphere, solid sphere, ring, disc"], correctIndex: 2, difficulty: "hard", explanation: "Ranking by increasing k²/R² (2/5 for solid sphere, 1/2 for disc, 2/3 for hollow sphere, 1 for ring) gives decreasing acceleration in exactly that order: solid sphere fastest, ring slowest." },
  { id: 78, type: 'mcq', question: "The reason a solid sphere rolls down an inclined plane faster than a ring of the same mass and radius is that the solid sphere has a:", options: ["Larger moment of inertia, and thus a larger fraction of its kinetic energy goes into rotation", "Moment of inertia identical to the ring", "Larger radius than the ring", "Smaller moment of inertia (smaller k²/R²), so a smaller fraction of its total kinetic energy is 'used up' in rotation, leaving more for translational (linear) motion"], correctIndex: 3, difficulty: "hard", explanation: "The solid sphere's smaller moment of inertia (lower k²/R²) means less of the available gravitational PE has to convert into rotational KE, leaving a larger share to accelerate the COM translationally — hence it moves and finishes faster." },
  { id: 79, type: 'mcq', question: "For a body rolling without slipping down an incline of angle θ, the linear acceleration of its centre of mass is generally given by an expression of the form a = g sinθ / (1 + k²/R²), which shows that a body with a smaller value of k²/R² will have:", options: ["A greater linear acceleration down the incline", "A smaller linear acceleration down the incline", "Exactly the same acceleration as any other rolling body, regardless of k²/R²", "Zero acceleration"], correctIndex: 0, difficulty: "hard", explanation: "In a = g sinθ/(1 + k²/R²), a smaller k²/R² makes the denominator smaller, which directly increases the resulting acceleration a." },
  { id: 80, type: 'mcq', question: "At the point of contact between a rolling body (rolling without slipping) and the surface it rolls on, the instantaneous velocity of that contact point, relative to the surface, is:", options: ["Equal to the linear velocity of the centre of mass", "Equal to twice the linear velocity of the centre of mass", "Directed opposite to the direction of motion", "Zero"], correctIndex: 3, difficulty: "medium", explanation: "'Rolling without slipping' is precisely defined by the contact point having zero instantaneous velocity relative to the surface — the translational velocity v and the rotational velocity ωR at that point exactly cancel." },

];

export default questions;