import type { Question } from "@/lib/questionBank";
// NEET Physics Question Bank
// Chapter: Waves
// 80 PYQ-centric MCQs covering all sub-topics with mixed difficulty (easy/medium/hard)
// Schema: { id, question, options[4], correctindex (index 0-3), difficulty, explanation }
// Note: correctindex follows the fixed 20-value cycle 0,2,1,3,1,0,2,2,3,0,1,1,0,3,1,2,1,0,3,0 (repeated 4x for 80 questions)

const questions: Question[] = [

  // ---------- Wave Motion Basics and Types ----------
  { id: 1, question: "A wave is a disturbance that travels through a medium (or, for certain waves, through vacuum), transporting:", options: ["Energy and momentum, without any net transport of matter", "Matter itself, from one point to another", "Neither energy nor matter, only information", "Only mass, with no energy transfer at all"], correctindex: 0, difficulty: "easy", explanation: "A wave transfers energy and momentum through oscillation of the medium's particles, without any net, permanent displacement of matter." },
  { id: 2, question: "Mechanical waves, such as sound waves and waves on a string, require the presence of a material medium to propagate, since they rely fundamentally on the:", options: ["Presence of a vacuum", "Electromagnetic properties of the medium", "Elastic properties (interactions between particles) of the medium", "Gravitational field of the medium"], correctindex: 2, difficulty: "medium", explanation: "Mechanical waves propagate by transferring disturbances via the medium's elastic properties, which is why they cannot travel through vacuum." },
  { id: 3, question: "In a transverse wave, the individual particles of the medium oscillate:", options: ["Parallel to the direction of wave propagation", "Perpendicular to the direction of wave propagation", "In circular paths around the direction of propagation", "Randomly, with no fixed relationship to the direction of propagation"], correctindex: 1, difficulty: "easy", explanation: "A transverse wave is defined by particle oscillation perpendicular to the direction of wave travel." },
  { id: 4, question: "In a longitudinal wave, the individual particles of the medium oscillate:", options: ["Perpendicular to the direction of wave propagation", "In circular paths", "Randomly", "Parallel to the direction of wave propagation"], correctindex: 3, difficulty: "easy", explanation: "A longitudinal wave is defined by particle oscillation parallel to the direction of wave propagation." },
  { id: 5, question: "Sound waves travelling through air are a classic example of:", options: ["Transverse waves", "Longitudinal waves", "Electromagnetic waves", "Standing waves exclusively, never travelling waves"], correctindex: 1, difficulty: "easy", explanation: "Sound waves propagate through compression and rarefaction of air molecules along the direction of travel, making them longitudinal." },
  { id: 6, question: "Waves on a stretched string, when plucked or disturbed, are a classic example of:", options: ["Transverse waves", "Longitudinal waves", "Waves requiring no medium at all", "Waves that travel only through gases"], correctindex: 0, difficulty: "easy", explanation: "Waves on a string involve particle displacement perpendicular to the direction of wave travel, making them transverse waves." },
  { id: 7, question: "Longitudinal waves are characterised by alternating regions of high particle density/pressure (called compressions) and low particle density/pressure (called):", options: ["Crests", "Troughs", "Rarefactions", "Nodes"], correctindex: 2, difficulty: "medium", explanation: "In a longitudinal wave, regions of minimum particle density/pressure are called rarefactions." },
  { id: 8, question: "Transverse waves are characterised by alternating regions of maximum positive displacement (called crests) and maximum negative displacement (called):", options: ["Compressions", "Rarefactions", "Troughs", "Antinodes exclusively"], correctindex: 2, difficulty: "medium", explanation: "In a transverse wave, points of maximum negative displacement are called troughs." },
  { id: 9, question: "Unlike mechanical waves, electromagnetic waves (such as light) are unique in that they:", options: ["Cannot travel through any medium whatsoever, including vacuum", "Require a material medium to propagate, just like sound", "Are always longitudinal in nature", "Can propagate through a vacuum, since they do not rely on the oscillation of material particles"], correctindex: 3, difficulty: "medium", explanation: "Electromagnetic waves consist of oscillating electric and magnetic fields and do not require a material medium." },
  { id: 10, question: "Water waves on the surface of a pond, upon closer physical examination, actually involve a combination of both transverse and longitudinal particle motion, following approximately:", options: ["Elliptical or circular paths for individual water particles", "Perfectly straight, purely transverse paths", "Perfectly straight, purely longitudinal paths", "No motion of the water particles at all"], correctindex: 0, difficulty: "medium", explanation: "Water waves involve surface particles moving in roughly circular or elliptical paths, combining transverse and longitudinal motion." },

  // ---------- The Wave Equation and Parameters ----------
  { id: 11, question: "A one-dimensional, sinusoidal, progressive (travelling) wave moving in the positive x-direction can be mathematically represented by the general equation:", options: ["y = A sin(kx + ωt)", "y = A sin(ωt − kx)", "y = A sin(ω + k)", "y = A(ωt)(kx)"], correctindex: 1, difficulty: "medium", explanation: "This is the standard equation for a sinusoidal wave travelling in the positive x-direction." },
  { id: 12, question: "In the wave equation y = A sin(ωt − kx), the parameter k, called the wave number, is related to the wavelength λ by the formula:", options: ["k = λ", "k = 2π/λ", "k = λ/2π", "k = 2πλ"], correctindex: 1, difficulty: "medium", explanation: "The wave number is defined as k = 2π/λ, relating spatial periodicity to the wave equation's phase term." },
  { id: 13, question: "The wavelength (λ) of a wave is defined as the:", options: ["Distance between two consecutive points on the wave that are in the same phase (e.g. two successive crests)", "Time taken for one complete oscillation of a single particle", "Maximum displacement of the wave from its mean position", "Speed at which the wave travels"], correctindex: 0, difficulty: "easy", explanation: "Wavelength is the spatial distance over which the wave pattern repeats, i.e. between two consecutive points in identical phase." },
  { id: 14, question: "The relationship between the speed (v) of a wave, its frequency (f), and its wavelength (λ) is given by the fundamental wave equation:", options: ["v = f/λ", "v = f − λ", "v = f + λ", "v = fλ"], correctindex: 3, difficulty: "easy", explanation: "This is the fundamental relationship connecting wave speed, frequency, and wavelength, v = fλ." },
  { id: 15, question: "According to the equation v = fλ, if the frequency of a wave is doubled while its speed remains constant (e.g. as it stays in the same medium), the wavelength must:", options: ["Also double", "Become half of its original value", "Remain exactly unchanged", "Become four times its original value"], correctindex: 1, difficulty: "medium", explanation: "Since v = fλ, if v is constant and f doubles, λ must be halved to keep the product unchanged." },
  { id: 16, question: "The time period (T) of a wave, related to its angular frequency ω, is given by:", options: ["T = 2π/ω", "T = ω/2π", "T = 2πω", "T = ω²/2π"], correctindex: 0, difficulty: "medium", explanation: "This is the standard relation between time period and angular frequency, T = 2π/ω." },
  { id: 17, question: "The wave speed (v) can also be expressed in terms of the angular frequency (ω) and the wave number (k) as:", options: ["v = ωk", "v = k/ω", "v = ω/k", "v = ω + k"], correctindex: 2, difficulty: "medium", explanation: "Since v = fλ = (ω/2π)(2π/k) = ω/k, wave speed can be expressed as ω/k." },
  { id: 18, question: "For a transverse wave described by y(x,t) = A sin(ωt − kx), the wave is said to travel in the positive x-direction because, as time t increases, points of constant phase (e.g. a particular crest) shift toward:", options: ["Negative x values", "Neither positive nor negative x, remaining fixed", "Positive x values", "Both positive and negative x values simultaneously"], correctindex: 2, difficulty: "medium", explanation: "Maintaining constant phase (ωt − kx = constant) as t increases requires x to also increase, so the wave moves in the +x direction." },
  { id: 19, question: "For a transverse wave described by y(x,t) = A sin(ωt + kx), instead of (ωt − kx), the wave travels in the:", options: ["Positive x-direction, exactly as with the minus sign", "Direction perpendicular to the x-axis", "Direction unrelated to the sign convention used", "Negative x-direction"], correctindex: 3, difficulty: "medium", explanation: "With y = A sin(ωt + kx), maintaining constant phase as t increases requires x to decrease, so the wave travels in the −x direction." },
  { id: 20, question: "The amplitude of a wave, denoted A in the wave equation, represents the:", options: ["Maximum displacement of a particle of the medium from its equilibrium (undisturbed) position", "Distance travelled by the wave in one complete time period", "Speed at which the wave propagates through the medium", "Number of complete oscillations per unit time"], correctindex: 0, difficulty: "easy", explanation: "Amplitude is the maximum displacement any particle of the medium reaches from its equilibrium position." },

  // ---------- Speed of Waves: Strings and Sound ----------
  { id: 21, question: "The speed of a transverse wave travelling along a stretched string is given by the formula:", options: ["v = √(T/μ)", "v = √(μ/T)", "v = T/μ", "v = Tμ"], correctindex: 0, difficulty: "easy", explanation: "This is the standard formula for wave speed on a stretched string, where T is tension and μ is linear mass density." },
  { id: 22, question: "In the formula v = √(T/μ) for the speed of a wave on a string, the symbol μ represents the string's:", options: ["Total mass", "Total length", "Mass per unit length (linear mass density)", "Young's modulus"], correctindex: 2, difficulty: "medium", explanation: "μ denotes the linear mass density of the string, mass divided by length." },
  { id: 23, question: "According to the string wave speed formula, v = √(T/μ), increasing the tension in the string, while keeping its mass per unit length constant, will cause the wave speed to:", options: ["Decrease", "Increase", "Remain exactly unchanged", "Become undefined"], correctindex: 1, difficulty: "medium", explanation: "Since v ∝ √T, increasing tension increases the speed of transverse waves on the string." },
  { id: 24, question: "According to the string wave speed formula, using a thicker (heavier per unit length) string, while keeping the tension constant, will cause the wave speed to:", options: ["Increase", "Remain exactly unchanged", "Become undefined", "Decrease"], correctindex: 3, difficulty: "medium", explanation: "Since v ∝ 1/√μ, a thicker string (larger mass per unit length) results in a slower wave speed." },
  { id: 25, question: "The speed of sound (a longitudinal wave) travelling through a solid medium is generally given by a formula involving the:", options: ["Density of the solid alone, with no elastic modulus involved", "Elastic (Young's) modulus of the solid and its density", "Colour of the solid", "Electrical conductivity of the solid"], correctindex: 1, difficulty: "medium", explanation: "Speed of sound in a solid depends on Young's modulus and density, v = √(Y/ρ)." },
  { id: 26, question: "The speed of sound travelling through a liquid is generally given by a formula involving the liquid's:", options: ["Bulk modulus and its density, v = √(B/ρ)", "Viscosity alone", "Surface tension alone", "Colour alone"], correctindex: 0, difficulty: "medium", explanation: "Since liquids resist compression, speed of sound in a liquid is v = √(B/ρ), where B is the bulk modulus." },
  { id: 27, question: "For sound travelling through a gas, Newton initially proposed a formula for the speed of sound based on isothermal (constant temperature) compressions and rarefactions, but this formula was later corrected by Laplace, who instead assumed the compressions and rarefactions occur:", options: ["At exactly constant volume", "At exactly constant pressure", "Adiabatically, i.e. rapidly enough that no heat exchange occurs", "At exactly constant density"], correctindex: 2, difficulty: "medium", explanation: "Laplace recognised that sound compressions/rarefactions occur too rapidly for heat exchange, meaning the process is adiabatic." },
  { id: 28, question: "The Laplace-corrected formula for the speed of sound in a gas is given by:", options: ["v = √(P/ρ)", "v = √(γ/ρ)", "v = √(γP/ρ)", "v = γP/ρ, without any square root"], correctindex: 2, difficulty: "medium", explanation: "This is the Laplace-corrected (adiabatic) formula, v = √(γP/ρ)." },
  { id: 29, question: "The speed of sound in a gas, according to the Laplace formula, is directly proportional to the square root of the gas's absolute temperature, meaning that as temperature increases, the speed of sound:", options: ["Decreases", "Remains exactly unchanged", "Becomes zero", "Increases"], correctindex: 3, difficulty: "medium", explanation: "Since v = √(γRT/M), speed of sound is directly proportional to √T, increasing with rising temperature." },
  { id: 30, question: "At a given temperature, the speed of sound in a gas is generally found to be essentially independent of the gas's:", options: ["Pressure, provided the temperature remains constant", "Absolute temperature", "Molar mass", "Specific heat ratio"], correctindex: 0, difficulty: "medium", explanation: "Since v = √(γRT/M) and P/ρ is independent of pressure at fixed T, speed of sound is essentially independent of pressure at constant temperature." },

  // ---------- Superposition and Interference ----------
  { id: 31, question: "The principle of superposition states that when two or more waves overlap at a point in a medium, the resultant displacement at that point is:", options: ["The product of the individual displacements due to each wave", "The algebraic (vector) sum of the individual displacements due to each wave", "Always equal to zero, regardless of the individual wave displacements", "Equal to only the larger of the two individual displacements"], correctindex: 1, difficulty: "medium", explanation: "The principle of superposition states net displacement equals the sum (with sign) of the individual displacements each wave would produce alone." },
  { id: 32, question: "When two waves meet such that their crests (or troughs) coincide, reinforcing each other and producing a resultant wave of larger amplitude, this is called:", options: ["Destructive interference", "Constructive interference", "Diffraction", "Refraction"], correctindex: 1, difficulty: "medium", explanation: "Constructive interference occurs when overlapping waves are in phase, resulting in a larger combined amplitude." },
  { id: 33, question: "When two waves meet such that the crest of one coincides with the trough of the other, partially or fully cancelling each other and producing a resultant wave of reduced (or zero) amplitude, this is called:", options: ["Destructive interference", "Constructive interference", "Diffraction", "Polarisation"], correctindex: 0, difficulty: "easy", explanation: "Destructive interference occurs when overlapping waves are out of phase, resulting in partial or complete cancellation." },
  { id: 34, question: "For two waves of equal amplitude to produce complete destructive interference (resulting in exactly zero resultant amplitude at a point), they must meet at that point with a phase difference of exactly:", options: ["0 radians (i.e. exactly in phase)", "π/2 radians (90°)", "2π radians (a full cycle, effectively in phase)", "π radians (180°), i.e. exactly out of phase"], correctindex: 3, difficulty: "medium", explanation: "Complete destructive interference of equal-amplitude waves requires a phase difference of exactly π radians (180°)." },
  { id: 35, question: "For two waves of equal amplitude to produce maximum constructive interference (resulting in a resultant amplitude equal to twice each individual amplitude), they must meet at that point with a phase difference of exactly:", options: ["π radians (180°)", "0 radians (i.e. exactly in phase, or an integer multiple of 2π)", "π/2 radians (90°)", "3π/2 radians (270°)"], correctindex: 1, difficulty: "medium", explanation: "Maximum constructive interference requires the waves to be exactly in phase (0, or an integer multiple of 2π)." },
  { id: 36, question: "The phenomenon of interference, resulting from the superposition of two or more coherent waves, provides direct evidence for the:", options: ["Wave nature of the phenomenon exhibiting interference (e.g. sound, light)", "Particle nature exclusively, with no wave-like behaviour involved", "Complete absence of any energy in the interfering waves", "Fact that waves cannot overlap under any circumstances"], correctindex: 0, difficulty: "medium", explanation: "The characteristic patterns of interference are a hallmark of wave behaviour and provide strong evidence for wave nature." },

  // ---------- Standing Waves: General and in Strings ----------
  { id: 37, question: "When two identical waves of the same amplitude and frequency travel in exactly opposite directions through the same medium and superpose, the resulting wave pattern is called a:", options: ["Travelling (progressive) wave", "Shock wave", "Standing (stationary) wave", "Sound wave exclusively"], correctindex: 2, difficulty: "medium", explanation: "A standing wave is formed by the superposition of two identical waves travelling in opposite directions." },
  { id: 38, question: "In a standing wave, points that remain permanently at rest (zero displacement at all times) are called:", options: ["Antinodes", "Crests", "Nodes", "Troughs"], correctindex: 2, difficulty: "medium", explanation: "Nodes are the fixed points where destructive interference is always complete, giving zero displacement." },
  { id: 39, question: "In a standing wave, points that oscillate with the maximum possible amplitude are called:", options: ["Nodes", "Troughs exclusively", "Crests exclusively", "Antinodes"], correctindex: 3, difficulty: "medium", explanation: "Antinodes are the points where constructive interference is always maximal, giving the largest oscillation amplitude." },
  { id: 40, question: "In a standing wave pattern, the distance between two consecutive nodes (or equivalently, between two consecutive antinodes) is:", options: ["Half the wavelength (λ/2)", "One full wavelength (λ)", "A quarter of the wavelength (λ/4)", "Twice the wavelength (2λ)"], correctindex: 0, difficulty: "medium", explanation: "The spacing between adjacent nodes (or adjacent antinodes) is always exactly half the wavelength." },
  { id: 41, question: "Unlike a travelling wave, a standing wave does not transport net energy from one point to another, since the wave pattern:", options: ["Moves continuously in one fixed direction, without changing shape", "Remains fixed in its overall spatial pattern, oscillating in place rather than propagating", "Has an amplitude that continuously increases without limit", "Contains no nodes or antinodes at all"], correctindex: 1, difficulty: "medium", explanation: "A standing wave's spatial pattern remains fixed, with each point oscillating in place, so there is no net energy transport." },
  { id: 42, question: "For a string of length L, fixed rigidly at both ends, the boundary conditions require that a node must exist at:", options: ["The centre of the string only", "Each of the two fixed ends of the string", "No specific location; nodes can form anywhere", "One end only, with the other end free to move"], correctindex: 1, difficulty: "medium", explanation: "Since the string is rigidly fixed at both ends, those points cannot move, so both ends must be nodes." },
  { id: 43, question: "For a string fixed at both ends, the simplest possible standing wave pattern (the fundamental mode, or first harmonic) consists of:", options: ["A single antinode at the centre, with nodes at the two fixed ends", "Two antinodes and three nodes", "No antinodes at all", "Nodes only, with no antinodes anywhere"], correctindex: 0, difficulty: "medium", explanation: "The fundamental mode has one antinode at the centre, flanked by nodes at the two fixed ends." },
  { id: 44, question: "For a string of length L, fixed at both ends, the wavelength of the fundamental mode (first harmonic) is related to the string's length by:", options: ["λ = L/4", "λ = L", "λ = 4L", "λ = 2L"], correctindex: 3, difficulty: "medium", explanation: "Since the fundamental mode fits exactly half a wavelength between the fixed-end nodes, λ = 2L." },
  { id: 45, question: "The fundamental frequency of vibration of a string of length L, fixed at both ends, with wave speed v on the string, is given by the formula:", options: ["f = v/(4L)", "f = v/(2L)", "f = 2v/L", "f = vL/2"], correctindex: 1, difficulty: "medium", explanation: "Using v = fλ with λ = 2L gives f = v/(2L), the fundamental frequency of a string fixed at both ends." },
  { id: 46, question: "For a string fixed at both ends, the set of possible higher-frequency standing wave modes (overtones), in addition to the fundamental, occur at frequencies that are:", options: ["Integer multiples of the fundamental frequency (i.e. 2f, 3f, 4f, and so on)", "Only odd-integer multiples of the fundamental frequency", "Fractional (non-integer) multiples of the fundamental frequency", "Completely unrelated to the fundamental frequency"], correctindex: 0, difficulty: "medium", explanation: "A string fixed at both ends supports all integer harmonics (f, 2f, 3f, ...), a defining characteristic of this boundary condition." },
  { id: 47, question: "The general formula for the possible frequencies (harmonics) of a string of length L, fixed at both ends, with wave speed v, is given by:", options: ["fn = nv/(4L), for n = 1, 2, 3, ...", "fn = v/(2nL), for n = 1, 2, 3, ...", "fn = n²v/(2L), for n = 1, 2, 3, ...", "fn = nv/(2L), for n = 1, 2, 3, ..."], correctindex: 3, difficulty: "hard", explanation: "This general formula, fn = nv/(2L), gives all allowed harmonic frequencies, with n=1 corresponding to the fundamental." },
  { id: 48, question: "Musical instruments such as the guitar and violin produce sound using vibrating strings fixed at both ends, and the pitch (perceived frequency) of the note produced can be altered by changing the string's tension, length, or:", options: ["Colour", "Mass per unit length (thickness/density of the string)", "Temperature of the room alone", "Distance from the listener"], correctindex: 1, difficulty: "medium", explanation: "String frequency depends on length, tension, and mass per unit length (via v = √(T/μ) and f = v/2L)." },

  // ---------- Standing Waves in Air Columns ----------
  { id: 49, question: "A pipe that is open at both ends, used to produce standing sound waves within an enclosed air column, requires that an antinode of displacement forms at:", options: ["Neither end of the pipe", "Each of the two open ends of the pipe", "The exact centre of the pipe only", "Only one of the two open ends"], correctindex: 1, difficulty: "medium", explanation: "At an open end, air molecules are free to move, corresponding to a displacement antinode at each open end." },
  { id: 50, question: "A pipe that is closed at one end and open at the other, used to produce standing sound waves within an enclosed air column, requires a node of displacement at the closed end and a(n) ___ at the open end.", options: ["Node", "Antinode", "Point of zero pressure variation", "Point unrelated to displacement entirely"], correctindex: 1, difficulty: "medium", explanation: "At the closed end, air cannot move (a node); at the open end, it is free to move (an antinode)." },
  { id: 51, question: "For an open pipe (open at both ends) of length L, the fundamental mode of vibration has a wavelength related to the pipe's length by:", options: ["λ = 2L", "λ = L", "λ = 4L", "λ = L/2"], correctindex: 0, difficulty: "medium", explanation: "With antinodes at both open ends, the fundamental mode fits half a wavelength in the pipe, giving λ = 2L." },
  { id: 52, question: "The fundamental frequency of an open pipe (open at both ends) of length L, with sound speed v, is given by:", options: ["f = v/(4L)", "f = v/L", "f = v/(2L)", "f = 4v/L"], correctindex: 2, difficulty: "medium", explanation: "Using v = fλ with λ = 2L gives f = v/(2L)." },
  { id: 53, question: "For an open pipe (open at both ends), the possible harmonic frequencies include:", options: ["Only odd-numbered harmonics (f, 3f, 5f, ...)", "Only even-numbered harmonics (2f, 4f, 6f, ...)", "All integer harmonics (f, 2f, 3f, 4f, ...)", "No harmonics beyond the fundamental frequency"], correctindex: 2, difficulty: "medium", explanation: "An open pipe supports the full set of integer harmonics, since both boundary conditions are symmetric (antinodes at both ends)." },
  { id: 54, question: "For a closed pipe (closed at one end, open at the other) of length L, the fundamental mode of vibration has a wavelength related to the pipe's length by:", options: ["λ = 2L", "λ = L", "λ = L/2", "λ = 4L"], correctindex: 3, difficulty: "medium", explanation: "With a node at the closed end and antinode at the open end, the fundamental fits a quarter wavelength, giving λ = 4L." },
  { id: 55, question: "The fundamental frequency of a closed pipe (closed at one end) of length L, with sound speed v, is given by:", options: ["f = v/(2L)", "f = v/(4L)", "f = 2v/L", "f = 4v/L"], correctindex: 1, difficulty: "medium", explanation: "Using v = fλ with λ = 4L gives f = v/(4L), lower than an open pipe of the same length." },
  { id: 56, question: "For a closed pipe (closed at one end, open at the other), the possible harmonic frequencies include only:", options: ["Odd-numbered harmonics of the fundamental frequency (f, 3f, 5f, ...)", "Even-numbered harmonics of the fundamental frequency (2f, 4f, 6f, ...)", "All integer harmonics, just as with an open pipe", "No harmonics beyond the fundamental at all"], correctindex: 0, difficulty: "medium", explanation: "The asymmetric boundary conditions of a closed pipe permit only odd-numbered harmonics." },
  { id: 57, question: "For pipes of the same length L, a closed pipe has a fundamental frequency that is, compared to an open pipe's fundamental frequency:", options: ["Exactly twice as high", "Exactly the same", "Exactly half as low", "Exactly four times as high"], correctindex: 2, difficulty: "medium", explanation: "Comparing f = v/(4L) to f = v/(2L) shows the closed pipe's fundamental is exactly half that of the equivalent open pipe." },
  { id: 58, question: "A resonance tube experiment, commonly used to determine the speed of sound in air, works by adjusting the length of an air column (typically closed at one end, e.g. by a water surface) until the air column resonates with a tuning fork of known frequency, producing a noticeably:", options: ["Silent, undetectable response", "Steady decrease in observed sound intensity", "Loud, amplified sound, indicating that a standing wave/resonance condition has been achieved", "Change only in the tuning fork's own frequency, with the air column unaffected"], correctindex: 2, difficulty: "medium", explanation: "When the air column length matches a resonant condition, constructive reinforcement occurs, producing a noticeably louder sound signaling resonance." },

  // ---------- Beats ----------
  { id: 59, question: "When two sound waves of slightly different frequencies are superposed, the resulting phenomenon of periodic variation in the loudness (intensity) of the combined sound is called:", options: ["Resonance", "The Doppler effect", "Interference, generally", "Beats"], correctindex: 3, difficulty: "easy", explanation: "Beats refer specifically to periodic rising and falling of loudness from two sound waves of slightly different frequencies." },
  { id: 60, question: "The beat frequency, i.e. the number of times per second that the loudness of the combined sound rises to a maximum, is given by the:", options: ["Absolute difference between the frequencies of the two individual waves", "Sum of the frequencies of the two individual waves", "Product of the frequencies of the two individual waves", "Average of the frequencies of the two individual waves"], correctindex: 0, difficulty: "easy", explanation: "Beat frequency is calculated as |f1 − f2|, the absolute difference between the two component frequencies." },
  { id: 61, question: "For beats to be clearly perceptible to the human ear as distinct, periodic variations in loudness, the difference between the two component frequencies must generally be:", options: ["Very large, at least several thousand hertz", "Relatively small, typically no more than about 10 hertz or so", "Exactly zero", "Completely unrelated to perceptibility"], correctindex: 1, difficulty: "medium", explanation: "For beats to be heard as distinct loudness variations, the frequency difference must be relatively small, typically less than about 10 Hz." },
  { id: 62, question: "The phenomenon of beats arises due to the periodic constructive and destructive interference between the two component waves, as their phase relationship continuously shifts because of their:", options: ["Identical frequencies", "Slightly different frequencies", "Identical amplitudes, with no relation to frequency at all", "Completely random, unrelated phases at all times"], correctindex: 1, difficulty: "medium", explanation: "Because the frequencies differ slightly, the relative phase continuously drifts, causing alternating constructive and destructive interference." },
  { id: 63, question: "Musicians commonly use the phenomenon of beats as a practical technique to:", options: ["Tune two musical instruments (or two strings) to the exact same frequency, by adjusting until the beat frequency approaches zero", "Increase the volume of a musical performance", "Change the pitch of a note permanently", "Eliminate all sound from an instrument"], correctindex: 0, difficulty: "easy", explanation: "Musicians use the audible beating effect as a tuning aid, adjusting until the beats slow down and disappear, indicating matched frequencies." },
  { id: 64, question: "If two tuning forks, one of known frequency 256 Hz and another of unknown frequency, produce 4 beats per second when sounded together, the unknown frequency must be:", options: ["Exactly 256 Hz", "Exactly 4 Hz", "Exactly 1024 Hz", "Either 252 Hz or 260 Hz"], correctindex: 3, difficulty: "hard", explanation: "Since beat frequency equals the absolute difference between frequencies, the unknown frequency must be 256 − 4 = 252 Hz or 256 + 4 = 260 Hz." },
  { id: 65, question: "The beat phenomenon can be mathematically shown to arise from adding two sinusoidal waves of nearly equal frequency, which produces a resultant wave whose amplitude itself:", options: ["Remains perfectly constant over time", "Varies periodically over time, at a rate related to the frequency difference", "Increases without limit over time", "Is completely unrelated to the individual wave frequencies"], correctindex: 1, difficulty: "medium", explanation: "Superposing two close-frequency waves produces a resultant wave whose amplitude itself oscillates slowly, perceived as beats." },
  { id: 66, question: "Beats can occur for any type of wave phenomenon exhibiting interference, including sound waves, but the term is most commonly and classically associated in physics with the superposition of two:", options: ["Electromagnetic waves of identical frequency exclusively", "Sound waves (or other mechanical waves) of slightly different frequencies", "Static, non-oscillating disturbances", "Standing waves exclusively, never travelling waves"], correctindex: 1, difficulty: "medium", explanation: "Beats are most classically studied in the context of two sound waves of slightly different frequencies." },

  // ---------- The Doppler Effect ----------
  { id: 67, question: "The Doppler effect refers to the apparent change in the observed frequency (or pitch, for sound) of a wave, as perceived by an observer, whenever there is relative:", options: ["Temperature difference between the source and the medium", "Motion between the wave source and the observer", "Difference in wave amplitude between the source and observer", "Difference in the medium's density at the source versus the observer"], correctindex: 1, difficulty: "easy", explanation: "The Doppler effect describes the apparent frequency shift due to relative motion between the wave source and the observer." },
  { id: 68, question: "When a sound source moves towards a stationary observer, the observer perceives the sound's frequency (pitch) to be:", options: ["Lower than the source's actual emitted frequency", "Higher than the source's actual emitted frequency", "Exactly identical to the source's actual emitted frequency, with no change", "Completely random and unpredictable"], correctindex: 1, difficulty: "medium", explanation: "As a source approaches, wavelength effectively compresses, increasing the observed frequency (a rising pitch)." },
  { id: 69, question: "When a sound source moves away from a stationary observer, the observer perceives the sound's frequency (pitch) to be:", options: ["Lower than the source's actual emitted frequency", "Higher than the source's actual emitted frequency", "Exactly identical to the source's actual emitted frequency, with no change", "Completely random and unpredictable"], correctindex: 0, difficulty: "medium", explanation: "As a source recedes, wavelength effectively stretches, decreasing the observed frequency (a falling pitch)." },
  { id: 70, question: "The formula for the apparent frequency f' heard by a stationary observer, when a sound source of actual frequency f moves towards the observer with speed vs (with v being the speed of sound), is given by:", options: ["f' = f(v − vs)/v", "f' = f(v + vs)/v", "f' = f × v/vs", "f' = f × v/(v − vs)"], correctindex: 3, difficulty: "medium", explanation: "This is the standard Doppler formula for a source approaching; since (v − vs) < v, f' is greater than f." },
  { id: 71, question: "The formula for the apparent frequency f' heard by a stationary observer, when a sound source of actual frequency f moves away from the observer with speed vs, is given by:", options: ["f' = f × v/(v − vs)", "f' = f × v/(v + vs)", "f' = f(v − vs)/v", "f' = f(v + vs)/v"], correctindex: 1, difficulty: "medium", explanation: "This is the standard Doppler formula for a receding source; since (v + vs) > v, f' is less than f." },
  { id: 72, question: "When an observer moves towards a stationary sound source, the observer perceives the sound's frequency to be:", options: ["Lower than the source's actual frequency", "Higher than the source's actual frequency", "Exactly identical to the source's actual frequency", "Completely random and unpredictable"], correctindex: 1, difficulty: "medium", explanation: "An observer moving toward a source encounters wave crests more frequently, resulting in a perceived increase in frequency." },
  { id: 73, question: "The formula for the apparent frequency f' heard by an observer moving towards a stationary sound source of actual frequency f, with observer speed vo (and v being the speed of sound), is given by:", options: ["f' = f(v + vo)/v", "f' = f(v − vo)/v", "f' = f × v/(v + vo)", "f' = f × v/(v − vo)"], correctindex: 0, difficulty: "medium", explanation: "This is the standard formula for an approaching observer; since (v + vo) > v, f' is greater than f." },
  { id: 74, question: "When an observer moves away from a stationary sound source, the observer perceives the sound's frequency to be:", options: ["Higher than the source's actual frequency", "Exactly identical to the source's actual frequency", "Completely random and unpredictable", "Lower than the source's actual frequency"], correctindex: 3, difficulty: "medium", explanation: "An observer moving away encounters wave crests less frequently, resulting in a perceived decrease in frequency." },
  { id: 75, question: "The formula for the apparent frequency f' heard by an observer moving away from a stationary sound source of actual frequency f, with observer speed vo, is given by:", options: ["f' = f(v + vo)/v", "f' = f(v − vo)/v", "f' = f × v/(v + vo)", "f' = f × v/(v − vo)"], correctindex: 1, difficulty: "medium", explanation: "This is the standard formula for a receding observer; since (v − vo) < v, f' is less than f." },
  { id: 76, question: "A key distinction in the Doppler effect for sound is that the mathematical formulas differ depending on whether it is the source or the observer that is moving, because sound waves propagate relative to a definite:", options: ["Medium (e.g. air), which provides a fixed reference frame relevant to the wave's actual propagation", "Observer, regardless of any medium", "Source, regardless of any medium", "Vacuum, with no medium involved at all"], correctindex: 0, difficulty: "medium", explanation: "Because sound relies on a physical medium, the medium establishes a preferred reference frame, causing the formulas to differ based on what's moving." },
  { id: 77, question: "When both the sound source and the observer are simultaneously in motion (relative to the medium), the general Doppler effect formula for the apparent frequency f' combines the individual source and observer terms into a single expression:", options: ["f' = f × vs/vo, considering only the ratio of speeds", "f' = f, with no combined dependence on either speed", "f' = f × (v ± vo)/(v ∓ vs), with signs chosen according to the specific directions of motion of source and observer", "f' = f + vs + vo, added directly with no proportional relationship"], correctindex: 2, difficulty: "hard", explanation: "The general Doppler formula combines both effects into a single ratio, with signs determined by the directions of motion." },
  { id: 78, question: "The Doppler effect is not limited to sound waves and mechanical waves; it is also observed for electromagnetic waves such as light, providing important applications in astronomy, such as detecting the:", options: ["Exact chemical composition of distant stars, with no relation to their motion", "Precise mass of distant celestial objects", "Motion of distant galaxies (e.g. redshift, indicating galaxies moving away from Earth)", "Age of the universe directly, with no reference to wavelength shifts"], correctindex: 2, difficulty: "medium", explanation: "The Doppler effect for light, observed as redshift/blueshift, is a key astronomical tool for determining relative motion of galaxies." },
  { id: 79, question: "Doppler radar, a practical technology used in applications such as weather forecasting (detecting storm movement) and speed detection by traffic police, works by measuring the:", options: ["Colour of the radar signal reflected from a moving object", "Total energy of the radar signal, with no reference to frequency shift", "Frequency shift of a reflected radio wave signal, due to the relative motion of the target object", "Absolute loudness of the returning signal"], correctindex: 2, difficulty: "medium", explanation: "Doppler radar measures the frequency shift of a reflected radio signal to determine a moving object's speed and direction." },
  { id: 80, question: "Overall, the study of wave motion in this chapter — covering wave types, wave speed, superposition, standing waves, beats, and the Doppler effect — provides a foundational framework applicable to a wide range of physical phenomena, including:", options: ["Only visible light, with no application to sound", "Only quantum mechanical particles, with no classical wave applications", "Only static, non-propagating disturbances", "Sound, musical instruments, medical ultrasound, astronomical observations, and numerous other wave-based technologies and natural phenomena"], correctindex: 3, difficulty: "medium", explanation: "This chapter's concepts collectively underpin a huge range of real-world phenomena and technologies, from acoustics to medical imaging to astrophysics." },

];

export default queestions;